### ISSUE TITLE
Callback error on start

### ISSUE THREAD

**Issue by fraincs** [doczjs/docz#1000]
## Callback error on start

**Describe the bug**

*Upon starting docz dev an error pops, it goest away but is still showing in the console*

**To Reproduce**

1. Start a fresh docz 2.0rc
2. Once localhost starts you get the error

```shell
Uncaught TypeError: callback is not a function
    at flushFirstCallback (scheduler.development.js:107)
    at flushWork (scheduler.development.js:219)
    at MessagePort../node_modules/scheduler/cjs/scheduler.development.js.channel.port1.onmessage (scheduler.development.js:611)
```

**Comment by patricksevat** [comment]
Hi @fraincs , just ran into this as well.
According to https://github.com/facebook/react/issues/15647 the fix is to add 
`"scheduler": "0.14.0"` as a dependency. This solved the issue for me. Could you verify? If so, I'll shoot in a PR

**Comment by will-stone** [comment]
@patricksevat That solved this issue for me.

**Comment by patricksevat** [comment]
Thx for letting me know @will-stone, I'll leave the implementation of this fix to @pedronauck as the current dev setup of docz v2 errors in my local set-up (probably some windows issue)

**Comment by xthilakx** [comment]
I ran into the same error when trying to use React hooks. I'm still on `docz@0.13.7`, and adding `scheduler@0.15.0` helped workaround this issue.

**Comment by xuanxuan321** [comment]
@patricksevat That solved this issue for me too.

**Comment by brauliodiez** [comment]
Just tried and had to apply same fix, since this is a showstopper, meanwhile is needed to launch the project I think it should be added to the getting started guide.

**Comment by rakannimer** [comment]
Should be fixed by : https://github.com/pedronauck/docz/commit/84918d8ac4fd11b2f69b065c786ca81217ce8d68

Will update here when the next version is release.

**Comment by rakannimer** [comment]
Released as version 2.0.0-rc.5 
Please let me know if it fixes this issue for you 👍

**Comment by rakannimer** [comment]
Closing this as resolved, feel free to re-open it if the issue happens again.

**Comment by dreyks** [comment]
hmm... started a new project with docz and suddenly (yay) after I've added `astroturf` package i started getting this error. removing the package did not help.
I'm currently using `docz@2.0.0-rc.40`, here're the relevant parts of package.json and yarn.lock

<details>
<summary>
package.json
</summary>

```json
{
  "devDependencies": {
    "astroturf": "^0.9.17",
    "docz": "^2.0.0-rc.40",
    "prop-types": "^15.7.2",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
}
```
</details>

<details>
<summary>
yarn.lock (irrelevant parts omited)
</summary>

```
docz@2.0.0-rc.40, docz@^2.0.0-rc.40:
  version "2.0.0-rc.40"
...
  dependencies:
...
    scheduler "^0.15.0"
...

ink@^2.3.0:
  version "2.3.0"
...
  dependencies:
...
    scheduler "^0.13.2"
...

react-dom@^16.9.0:
  version "16.9.0"
...
  dependencies:
...
    scheduler "^0.15.0"

react-reconciler@^0.20.0:
  version "0.20.4"
...
  dependencies:
...
    scheduler "^0.13.6"

scheduler@^0.13.2, scheduler@^0.13.6:
  version "0.13.6"
...
  
scheduler@^0.15.0:
  version "0.15.0"
...
```
</details>

<details>
<summary>yarn why scheduler</summary>

```console
$ yarn why scheduler
yarn why v1.17.3
[1/4] 🤔  Why do we have the module "scheduler"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "scheduler@0.13.6"
info Has been hoisted to "scheduler"
info Reasons this module exists
   - Hoisted from "docz#gatsby#gatsby-cli#ink#scheduler"
   - Hoisted from "docz#gatsby#gatsby-cli#ink#react-reconciler#scheduler"
info Disk size without dependencies: "128KB"
info Disk size with unique dependencies: "212KB"
info Disk size with transitive dependencies: "236KB"
info Number of shared dependencies: 3
=> Found "docz#scheduler@0.15.0"
info This module exists because "docz" depends on it.
info Disk size without dependencies: "212KB"
info Disk size with unique dependencies: "296KB"
info Disk size with transitive dependencies: "320KB"
info Number of shared dependencies: 3
=> Found "react-dom#scheduler@0.15.0"
info This module exists because "react-dom" depends on it.
info Disk size without dependencies: "212KB"
info Disk size with unique dependencies: "296KB"
info Disk size with transitive dependencies: "320KB"
info Number of shared dependencies: 3
```
</details>

**Comment by mrfelton** [comment]
Same issue. Pinning schedular to `0.15.0` resolved foe me too.
