### ISSUE TITLE
Your current PostCSS version is 6.0.23, but autoprefixer uses 7.0.17

### ISSUE THREAD

**Issue by MehdiMahmoudi** [doczjs/docz#1001]
## Bug Report

I systematically get this error after running `yarn docz dev`, and right after Gatsby bootstrapping finished.

I'm using docz 2.0.0-rc.1 tried with both React/React DOM 16.9.0 and 16.8.6

**Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but autoprefixer uses 7.0.17. Perhaps this is the source of the error below.**

Happens on a fresh install of a react app with `create-react-app`.

**Environment**
macOS Mojave
Node v10.16.0

Thanks!

**Comment by bilobom** [comment]
same issue here

**Comment by bonashen** [comment]
```bash
$ npm ls postcss
```

+-- **babel-plugin-react-css-modules**@5.2.6
| +-- postcss@7.0.18  deduped
| +-- postcss-modules@1.4.1
| | +-- css-modules-loader-core@1.1.0
| | | +-- postcss@6.0.1
| | | +-- postcss-modules-extract-imports@1.1.0
| | | | `-- postcss@6.0.23
| | | `-- **postcss-modules-scope@1.1.0**
| | |   `-- **postcss@6.0.23**
| | `-- postcss@7.0.18  deduped
| +-- postcss-modules-extract-imports@1.2.1
| | `-- postcss@6.0.23
| +-- postcss-modules-local-by-default@1.2.0
| | `-- postcss@6.0.23
| +-- postcss-modules-parser@1.1.1
| | `-- postcss@5.2.18
| +-- postcss-modules-scope@1.1.0
| | `-- postcss@6.0.23
| `-- postcss-modules-values@1.3.0
|   `-- postcss@6.0.23

**Comment by emilianoarlettaz** [comment]
Hi, the same issue here:
MacOS 10.13.6
Node v10.16.2

Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.23, but autoprefixer uses 7.0.23.

**Comment by nazarimohamad** [comment]
Look at the [the answer](https://stackoverflow.com/questions/59013313/autofixer-uses-a-different-postcss-version-than-my-current-version-and-it-is-cau/59364288#59364288). You should update your PostCSS by installing `gatsby-plugin-postcss` and add that in plugin. after that in `postcss.config.js` add these lines
```
const postcssPresetEnv = require(`postcss-preset-env`)

module.exports = () => ({
  plugins: [
    postcssPresetEnv({
      stage: 0,
    }),
  ],
})
```

**Comment by nazarimohamad** [comment]
look at [the answer](https://stackoverflow.com/questions/59013313/autofixer-uses-a-different-postcss-version-than-my-current-version-and-it-is-cau/59364288#59364288). install the `gatsby-plugin-postcss` and add the plugin. then in `postcss.config.js` type 
```
const postcssPresetEnv = require(`postcss-preset-env`)

module.exports = () => ({
  plugins: [
    postcssPresetEnv({
      stage: 0,
    }),
  ],
})
```

**Comment by p0o** [comment]
> look at [the answer](https://stackoverflow.com/questions/59013313/autofixer-uses-a-different-postcss-version-than-my-current-version-and-it-is-cau/59364288#59364288). install the `gatsby-plugin-postcss` and add the plugin. then in `postcss.config.js` type
> 
> ```
> const postcssPresetEnv = require(`postcss-preset-env`)
> 
> module.exports = () => ({
>   plugins: [
>     postcssPresetEnv({
>       stage: 0,
>     }),
>   ],
> })
> ```

This worked for me! But it's weird, according to docs we should be able to import normal CSS files without postCSS plugin (as used in starter_default template) but with this error it's not possible.

**Comment by jpcmf** [comment]
@nazarimohamad I got this issue in my project using webpack, so basically i've install the `postcss-preset-env` and then update my `postcss.config.js`.

from:

```
module.exports = {
  plugins: {
    'rucksack-css': {},
    lost: {},
    autoprefixer: {},
    cssnano: {},
  },
};
```
to:
```
const postcssPresetEnv = require(`postcss-preset-env`);

module.exports = () => ({
  plugins: [
    postcssPresetEnv({
      stage: 0,
    }),
  ],
});
```

It's working. Hope it helps anybody :)

**Comment by kahboom** [comment]
Thanks @jpcmf that fixed it for me 👍

**Comment by shadahmedshahadot** [comment]
I am facing the same type of problem. anyone can help me?


40% building 1/2 modules 1 active ...nfo\hospital\src\assets\style.cssUnknown error from PostCSS plugin. Your current PostCSS version is 7.0.35, but autoprefixer uses 6.0.23. Perhaps this is the source of the error below.
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 error                      12:20:27 PM

 error  in ./src/assets/style.css

Syntax Error: BrowserslistError: Unknown browser query `dead`
    at Array.reduce (<anonymous>)
    at new Promise (<anonymous>)


 @ ./src/assets/style.css 4:14-193 14:3-18:5 15:22-201
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js



+-- @vue/cli-service@4.5.9
| +-- @intervolga/optimize-cssnano-plugin@1.0.6
| | +-- cssnano-preset-default@4.0.7
| | | +-- css-declaration-sorter@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- cssnano-util-raw-cache@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss@7.0.35
| | | +-- postcss-calc@7.0.5
| | | | `-- postcss@7.0.35
| | | +-- postcss-colormin@4.0.3
| | | | `-- postcss@7.0.35
| | | +-- postcss-convert-values@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-discard-comments@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-discard-duplicates@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-discard-empty@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-discard-overridden@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-merge-longhand@4.0.11
| | | | +-- postcss@7.0.35
| | | | `-- stylehacks@4.0.3
| | | |   `-- postcss@7.0.35
| | | +-- postcss-merge-rules@4.0.3
| | | | `-- postcss@7.0.35
| | | +-- postcss-minify-font-values@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-minify-gradients@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-minify-params@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-minify-selectors@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-charset@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-display-values@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-positions@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-repeat-style@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-string@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-timing-functions@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-unicode@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-url@4.0.1
| | | | `-- postcss@7.0.35
| | | +-- postcss-normalize-whitespace@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-ordered-values@4.1.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-reduce-initial@4.0.3
| | | | `-- postcss@7.0.35
| | | +-- postcss-reduce-transforms@4.0.2
| | | | `-- postcss@7.0.35
| | | +-- postcss-svgo@4.0.2
| | | | `-- postcss@7.0.35
| | | `-- postcss-unique-selectors@4.0.1
| | |   `-- postcss@7.0.35
| | `-- postcss@7.0.35
| +-- @vue/component-compiler-utils@3.2.0
| | `-- postcss@7.0.35
| +-- autoprefixer@9.8.6
| | `-- postcss@7.0.35
| +-- css-loader@3.6.0
| | +-- icss-utils@4.1.1
| | | `-- postcss@7.0.35
| | +-- postcss@7.0.35
| | +-- postcss-modules-extract-imports@2.0.0
| | | `-- postcss@7.0.35
| | +-- postcss-modules-local-by-default@3.0.3
| | | `-- postcss@7.0.35
| | +-- postcss-modules-scope@2.2.0
| | | `-- postcss@7.0.35
| | `-- postcss-modules-values@3.0.0
| |   `-- postcss@7.0.35
| +-- cssnano@4.1.10
| | `-- postcss@7.0.35
| `-- postcss-loader@3.0.0
|   `-- postcss@7.0.35  deduped
+-- @vue/compiler-sfc@3.0.4
| +-- postcss@7.0.35
| `-- postcss-modules@3.2.2
|   `-- postcss@7.0.35
+-- postcss-cssnext@3.1.0
| +-- autoprefixer@7.2.6
| | `-- postcss@6.0.23
| +-- pixrem@4.0.1
| | `-- postcss@6.0.23
| +-- pleeease-filters@4.0.0
| | `-- postcss@6.0.23
| +-- postcss@6.0.23
| +-- postcss-apply@0.8.0
| | `-- postcss@6.0.23
| +-- postcss-attribute-case-insensitive@2.0.0
| | `-- postcss@6.0.23
| +-- postcss-calc@6.0.2
| | `-- postcss@7.0.35
| +-- postcss-color-function@4.1.0
| | `-- postcss@6.0.23
| +-- postcss-color-gray@4.1.0
| | `-- postcss@6.0.23
| +-- postcss-color-hex-alpha@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-color-hsl@2.0.0
| | `-- postcss@6.0.23
| +-- postcss-color-hwb@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-color-rebeccapurple@3.1.0
| | `-- postcss@6.0.23
| +-- postcss-color-rgb@2.0.0
| | `-- postcss@6.0.23
| +-- postcss-color-rgba-fallback@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-custom-media@6.0.0
| | `-- postcss@6.0.23
| +-- postcss-custom-properties@6.3.1
| | `-- postcss@6.0.23
| +-- postcss-custom-selectors@4.0.1
| | `-- postcss@6.0.23
| +-- postcss-font-family-system-ui@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-font-variant@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-image-set-polyfill@0.3.5
| | `-- postcss@6.0.23
| +-- postcss-initial@2.0.0
| | `-- postcss@6.0.23
| +-- postcss-media-minmax@3.0.0
| | `-- postcss@6.0.23
| +-- postcss-nesting@4.2.1
| | `-- postcss@6.0.23
| +-- postcss-pseudo-class-any-link@4.0.0
| | `-- postcss@6.0.23
| +-- postcss-pseudoelements@5.0.0
| | `-- postcss@6.0.23
| +-- postcss-replace-overflow-wrap@2.0.0
| | `-- postcss@6.0.23
| +-- postcss-selector-matches@3.0.1
| | `-- postcss@6.0.23
| `-- postcss-selector-not@3.0.1
|   `-- postcss@6.0.23
`-- tailwindcss@2.0.2
  +-- @fullhuman/postcss-purgecss@3.1.3
  | `-- purgecss@3.1.3
  |   `-- postcss@8.2.1  deduped
  +-- postcss-functions@3.0.0
  | `-- postcss@6.0.23
  `-- postcss-js@3.0.3
    `-- postcss@8.2.1

**Comment by weijiyang** [comment]
npm install postcss     can fix it
