### ISSUE TITLE
remove linter

### ISSUE THREAD

**Issue by jeremy-coleman** [doczjs/docz#1008]
Updated, likely caused by react hmr 

Project isn't using ESLint or any rules related to hooks.
![image](https://user-images.githubusercontent.com/25135855/63072024-ba165e00-beef-11e9-9ef6-ab4691f4cef6.png)
possibly the simplest setup imaginable. the file on the left is the only file in the directory.
![image](https://user-images.githubusercontent.com/25135855/63072207-8daf1180-bef0-11e9-9871-1268d683d7a6.png)

**Comment by mAAdhaTTah** [comment]
That isn't a linter error. That's a runtime error.

**Comment by jeremy-coleman** [comment]
Idk how thats possible, no hooks are used

**Comment by zicodeng** [comment]
Try `yarn why react` see if you have multiple versions of it?

**Comment by jeremy-coleman** [comment]
I got the same error in another project, the cause , where the cause was @hot-loader/react-dom

**Comment by jesperorb** [comment]
@jeremy-coleman
Could you try the latest RC and check it this error still exists? `docz©next`

I had the same problem in v.1.2 and you can temporarily fix that after installing dependencies by running:
```bash
npm dedupe
```
