### ISSUE TITLE
Creating Docz entries from other data sources?

### ISSUE THREAD

**Issue by rsexton404** [doczjs/docz#1011]
## Question

I'd like my Docz site to pull in pages from Google Docs (using the [gatsby-source-google-docs](https://www.gatsbyjs.org/packages/gatsby-source-google-docs/) plugin) _as well as_ MDX files. When creating nodes and creating pages for the Google Docs content, **how would I also add "entries" for Docz** so that I can render these new pages using the base layout component from Docz?

Any information pointing me in the right direction would be greatly appreciated!

**Comment by colbyfayock** [comment]
@rsexton404 did you ever figure this out? trying to get something working myself

**Comment by rsexton404** [comment]
@colbyfayock I never did get an answer to this and didn’t have the time to dig into Docz’s data structures which were kind of on obscured by the way Gatsby’s theme system puts a lot of code that you might want to build on top of in node_modules. We just ended up building our own props table component that used gatsby-transformer-react-docgen nodes directly. Then we used React Live for our live code examples. Ended up being easier and more customizable than Docz. Hope that helps! I’d be happy to chat more about it sometime!

**Comment by colbyfayock** [comment]
ah okay. not quite the same but i got Netlify CMS working simply because it commits the files into git 🤷‍♂ https://github.com/colbyfayock/gatsby-starter-docz-netlifycms

but would love to get a data source for a more advanced cms at some point. thanks for the reply
