### ISSUE TITLE
Allow setting custom npm registry on docz dev

### ISSUE THREAD

**Issue by hijiangtao** [doczjs/docz#1012]
Currently, if I want to import a package named "XXX" from private node module registry (which couldn't be found in npmjs.org), the docz would report an error with:

```
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/XXX: Not found".
```

However, there may exists some situations like this, since some packages are not suitable for open. Is there some way that I can specify the npm registry when I develop or bundle docz project?

Some facility like this may be good for me:

```
docz dev --npm-registry=https://PRIVATE-REGISTRY.org/
```

Thanks.

**Comment by hijiangtao** [comment]
Currently, I can prevent this error by set npm registry using `npm config set registry` command globally.

However, it may not meet all situations, because packages that developers used in their projects may not come from the same registry, a customized property that can passed in to the npm commands would be nice.

**Comment by rakannimer** [comment]
Could you please try running : 

```sh
yarn config set registry https://PRIVATE-REGISTRY.org/
```

before `docz dev` and let me know if it works ?

**Comment by rakannimer** [comment]
Hey @hijiangtao,

More recent docz release candidates don't need to re-install your dependencies so you shouldn't face this problem. 

Can you try updating and see if it still happens ?

**Comment by hijiangtao** [comment]
@rakannimer That's great, I use the latest docz with `next` tag and it works for me now!

**Comment by hijiangtao** [comment]
The issue can be closed since problem is solved in latest docz. : -)
