### ISSUE TITLE
How do I access the current theme's property in a custom mdx component?

### ISSUE THREAD

**Issue by godmar** [doczjs/docz#1038]
## Question

**Description**
I would like to use docz for its support for MDX. I have written my own highlighting component like [here](https://mdxjs.com/guides/syntax-highlighting#build-a-codeblock-component). What I would like is for the component to enter "dark mode" when the user selects dark mode.

How do I access the currently active theme/mode from within a custom MDX component?
I am not using a custom theme yet, just what comes builtin with a standard install of docz@next (which is 2.0.5-rc.5)

Thanks.

**Comment by godmar** [comment]
ping

**Comment by rakannimer** [comment]
Hey @godmar,

You can access the colorMode (dark|light) by using the `useColorMode` hook from 'theme-ui`

For example : 

```jsx
// src/MyComponent.jsx

import { useColorMode } from 'theme-ui'

const MyComponent = () => {
	const [colorMode] = useColorMode();
	return <div>You are using {colorMode} color mode</div>
}

```
