### ISSUE TITLE
How to access an MDX component's children as markdown?

### ISSUE THREAD

**Issue by godmar** [doczjs/docz#1039]
## Question

**Description**
I'd like to build a custom MDX component I'd like to use like this:
```
import SpecialBox from 'mycomponents';
Inside an .mdx file
<SpecialBox>
Markdown content here. I'd like to be able to use [links](tourls)
</SpecialBox>

Is there an example of how to do that?  I'd like to set an enclosing container (maybe a styled div), but then use the same component that renders docz's markdown to render the children.

Thanks.

**Comment by rakannimer** [comment]
Hey @godmar,

Thanks for reporting this issue,

Inside the mdx file, the block : 

```jsx
<SpecialBox>
Markdown content here. I'd like to be able to use [links](tourls)
</SpecialBox>
```

is parsed as JSX so it won't render `SpecialBox`'s children as markdown.

You could alter the behavior of SpecialBox to parse and render markdown but I'm not sure that's what you want.

**Comment by godmar** [comment]
Thanks for the reply. I've been using a string literal:
```
<SpecialBox>
{`
Markdown content here.
`}
```
could you share a pointer how I would then process it in a way that uses MDX builtin parser/renderer?

**Comment by godmar** [comment]
Ok, just in case someone else finds this.  The answer is to leave an empty line before and after the content, like so:

```jsx
<SpecialBox>

Markdown content here

</SpecialBox>
```

I discovered this from the [carbon theme documentation](https://github.com/carbon-design-system/gatsby-theme-carbon/blob/master/packages/example/src/pages/components/PageDescription.mdx)....

**Comment by rakannimer** [comment]
Awesome ! Thanks for reporting back with the answer 👍
