### ISSUE TITLE
Starter example with docz v2

### ISSUE THREAD

**Issue by trondhindenes** [doczjs/docz#1044]
It would be good to have a starter example for Gatsby with docz v2. I'm trying to implement it from scratch and cannot get it to work.

**Comment by rakannimer** [comment]
Hey @trondhindenes, 

Thanks for reporting this issue.

You can see the example of integrating Gatsby with Docz v2 [here](https://github.com/doczjs/docz/tree/master/examples/gatsby). 

And you can try it on your machine with : 

```sh
npx create-docz-app my-docz-gatsby-app --example gatsby
```

Hope that helps !
