### ISSUE TITLE
Document/Example for how to use full text search

### ISSUE THREAD

**Issue by trondhindenes** [doczjs/docz#1045]
There's very little info on how to plug in search into docz (not talking about the light-weight filter menu, but actual full-text search). It would be good if this was either described in a starter template or in documentation. We're building a large doc site, and rich search is an absolute requirement.

**Comment by rakannimer** [comment]
That's a cool feature request, right now it's not possible to get full-text search out of the box. 

You'd need to do some additional work, and it's not yet documented how to go about doing that. 

I'm open to adding full text search out of the box ( behind some config flag ) or adding documentation explaining how to override `gatsby-theme-docz` and add full text search with something like https://community.algolia.com/docsearch/ 

Right now, I'm focusing on squashing v2 bugs but would be happy to merge in a PR for either of these options.

**Comment by rakannimer** [comment]
Not stale.

**Comment by grzesuav** [comment]
also interested  in this feature

**Comment by rakannimer** [comment]
We've added an example of using full-text search with Algolia here : https://github.com/doczjs/docz/tree/master/examples/with-algolia-search

Make sure to read the README for a detailed tutorial :+1:

**Comment by trondhindenes** [comment]
awesome, thanks!
