### ISSUE TITLE
Make docz build work without needing docz dev first

### ISSUE THREAD

**Issue by hilquias-kil** [doczjs/docz#1049]
## Bug Report

When trying to run `docz build`, this error occurs:

```shell
cd: no such file or directory: .docz
```

**To Reproduce**

1. Run `docz build` before running `docz dev` after `npm install`, I believe that this error occurs because the .docz folder is created by `docz dev`.

**Environment**

* OS: OSX 10.14.6
* Node/npm version: Node 10.16.3/npm 6.9.0

**Comment by shmidt-i** [comment]
Were you able to go through the docz build till the end? After I build, I have `Uncaught Error: Minified React error #321;` which turns out to be invalid hooks call order error - https://reactjs.org/docs/error-decoder.html/?invariant=321.

**Comment by shmidt-i** [comment]
Seems to be a problem during rehydration, tracked it down to @mdx-js's useMDXcomponents hook:
`var contextComponents = React.useContext(MDXContext);` <- this line shoots for some reason

**Comment by shmidt-i** [comment]
My problem already got fixed in #1050 ! 😉

**Comment by pedronauck** [comment]
Can we close here @shmidt-i?

**Comment by rakannimer** [comment]
`docz build` doesn't require you to call `docz dev` first anymore. 

If this issue is not resolved please re-open it or add a new one.
