### ISSUE TITLE
Playground lost syntax highlighting

### ISSUE THREAD

**Issue by shmidt-i** [doczjs/docz#1055]
## Bug Report

Playground now doesn't do syntax highlighting

**To Reproduce**

1. Create a page with playground
2. Code is not highlighted

**Expected behavior**

Code should be highlighted

**Environment**
docz@2.0.0-rc.21

**Additional context/Screenshots**

- docz@2.0.0-rc.9:

![Untitled](https://user-images.githubusercontent.com/5012901/64078291-25767300-ccd9-11e9-8a7f-25bc94269522.png)

- docz@2.0.0-rc.21:

<img width="546" alt="Screen Shot 2019-09-01 at 16 52 37" src="https://user-images.githubusercontent.com/5012901/64078293-2d361780-ccd9-11e9-80e8-12feefdc8034.png">

**Comment by rakannimer** [comment]
Should be fixed in `docz@2.0.0-rc.22` 

Please feel free to re-open if it's not 👍
