### ISSUE TITLE
Theme styles and config settings missing from production build

### ISSUE THREAD

**Issue by mrfelton** [doczjs/docz#1056]
## Bug Report

Various theme styles are missing after doing a production build. Everything looks correct in dev mode, but then various styles and settings are missing after doing a production build.

See https://github.com/LN-Zap/zap-tutorials

For example, blockquote styles, link colours, paragraph margins, code highlighting etc.

Also, `config.title` doesn't render correctly in the Logo component yet it works fine in dev mode (in our repo we have had to hard code the title into our shadowed Logo component since reading from config doesn't work.

**Expected behavior**

Prod build should look exactly like dev build.

**Environment**

* OS: Mac
* Node/npm version: 12

**Comment by rakannimer** [comment]
Hey, 

Thanks for reporting this issue and providing a repo to be able to easily reproduce it. 

I released a new version 2.0.0-rc.25 

I tried it on your repo and it seemed to work, could you confirm it does ? 

Cheers !

**Comment by mrfelton** [comment]
Hi,

Thanks - these issues are indeed now resolved :)
