### ISSUE TITLE
Cannot use images in mdx

### ISSUE THREAD

**Issue by rumblefrog** [doczjs/docz#1057]
## Bug Report

When attempting to use images, I'm greeted with 

`TypeError: Property value expected type of string but got null`

**Directory Structure**

```
├── doczrc.js
├── public
│   ├── image.png
├── src
│   └── readme.mdx
```

**readme.mdx content**

```
![](/public/image.png)
```

**To Reproduce**

1. Create an mdx  file and link to an image in the public directory

```shell
UNHANDLED REJECTION Property value expected type of string but got null



  TypeError: Property value expected type of string but got null

  - utils.js:164 Object.validate
    [.docz]/[@babel]/types/lib/definitions/utils.js:164:13

  - validate.js:22 validateField
    [.docz]/[@babel]/types/lib/validators/validate.js:22:9

  - validate.js:16 validate
    [.docz]/[@babel]/types/lib/validators/validate.js:16:3

  - builder.js:46 builder
    [.docz]/[@babel]/types/lib/builders/builder.js:46:27

  - index.js:335 Object.StringLiteral
    [.docz]/[@babel]/types/lib/builders/generated/index.js:335:31

  - index.js:95 imageToJsx
    [.docz]/[remark-docz]/dist/index.js:95:123

  - index.js:102
    [.docz]/[remark-docz]/dist/index.js:102:18

  - index.js:27 overload
    [.docz]/[unist-util-visit]/index.js:27:12

  - index.js:34 one
    [.docz]/[unist-util-visit-parents]/index.js:34:25

  - index.js:57 all
    [.docz]/[unist-util-visit-parents]/index.js:57:16

  - index.js:42 one
    [.docz]/[unist-util-visit-parents]/index.js:42:28

  - index.js:57 all
    [.docz]/[unist-util-visit-parents]/index.js:57:16

  - index.js:42 one
    [.docz]/[unist-util-visit-parents]/index.js:42:28

  - index.js:26 visitParents
    [.docz]/[unist-util-visit-parents]/index.js:26:3

  - index.js:22 visit
    [.docz]/[unist-util-visit]/index.js:22:3

  - index.js:99
    [.docz]/[remark-docz]/dist/index.js:99:3
```

**Expected behavior**

Development server spins up without any problem and displays the image

**Environment**

* OS: Windows 10 Pro 1903.18965.1005
* Node/yarn version: Node 12.4.0 | Yarn 1.17.3

**Comment by rakannimer** [comment]
Hey @rumblefrog,

Adding images is supported out of the box but you have to use either a relative path to the image or a url.

In your example : 

```diff
- ![](/public/image.png)
+ ![](../public/image.png)
```

You can find a complete example here: https://github.com/doczjs/docz/tree/master/examples/images

Closing this, please feel free to re-open if the issue persists

**Comment by rumblefrog** [comment]
So what is this documentation referring to? https://github.com/doczjs/docz-website/blame/4cd751756a56fbfb2efe040603731c6f71ad73ae/src/docs/documentation/references/project-configuration.mdx#L119-L139

**Comment by rakannimer** [comment]
Not sure honestly, probably v1 specific. Are you on docz v1?

**Comment by rumblefrog** [comment]
No, I'm v2. But, I thought the doc was updated for the newest version, it's even on the production site: https://www.docz.site/docs/project-configuration

**Comment by rakannimer** [comment]
Hmm you're right, I'll make sure the docs are updated before the official v2 is released 👍

**Comment by rumblefrog** [comment]
Would this behavior be restored in v2, or is it eradicated?

**Comment by rumblefrog** [comment]
Using a relative path is still failing. 

I also tried putting the image and the mdx in the same directory, and referencing the image `![](image.png)` and I still get the same error.

**Comment by rumblefrog** [comment]
Apparently that error is caused by empty brackets

```diff
- ![](image.png)
+ ![some string](image.png)
```

**Comment by rakannimer** [comment]
Oh nice ! Didn't think about that 👍 

Thanks for reporting back with the solution.

It would be nice to add a warning about in the docs. Maybe we'll add a FAQ with v2.

**Comment by tuantvk** [comment]
i use `![some string](image.png)`
But, how to show image center ?

**Comment by rumblefrog** [comment]
@tuantvk 

With HTML and not markdown. Please google the question next time and not use an issue unrelated to it.
