### ISSUE TITLE
docz 1.3.0 has no github listing

### ISSUE THREAD

**Issue by StoneCypher** [doczjs/docz#1066]
Published by a package maintainer so I suspect it's just a glitch, but, docz 1.3.0 published with no readme and no github link

![image](https://user-images.githubusercontent.com/77482/64136982-13b0d080-cdaa-11e9-9859-efc74ddc4db4.png)

**Comment by rakannimer** [comment]
Hey @StoneCypher,

Thanks for reporting this, will update it and report back here 👍

**Comment by rakannimer** [comment]
Released 1.3.1 with updated docs and repository link to npm : https://www.npmjs.com/package/docz/v/1.3.1

**Comment by StoneCypher** [comment]
Possibly intentional, but you released 1.3.1 with v2's readme

**Comment by rakannimer** [comment]
Yep, intentionally, to encourage people who see it to use v2 😄
