### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by csywweb** [doczjs/docz#1067]
## Bug Report

**i have a bug as same  as #964 **

**Environment**

* OS: [ OSX 10.13.4]
* Node/npm version: [e.g. Node 8.11.0/npm 5]
* docz: [@2.0.0-rc.21]

**Additional context/Screenshots**
![avatar](https://user-images.githubusercontent.com/13011363/61555872-f86e4980-aa25-11e9-8aa6-3d6e6c457b35.png)

**Comment by rakannimer** [comment]
Hey @csywweb,

Thanks for reporting this. 

Could you please provide the markdown files you have in your project and their relative path in your filesystem ? 

You might need to set the route as / to your markdown file to tell docz to serve it as the root url.

Example here : https://github.com/doczjs/docz/blob/master/examples/basic/src/index.mdx

**Comment by csywweb** [comment]
Hi @rakannimer, 
awesome man, thanks,
