### ISSUE TITLE
onCreateBabelConfig function does not work.

### ISSUE THREAD

**Issue by nikitpatel24** [doczjs/docz#1077]
## Bug Report

*A clear and concise description of what the bug is.*
cannot set babel plugin using onCreateBabelConfig  function within gatsby-node.js

**To Reproduce**

create a gatsby-node.js file in the project root folder.

export the function
`exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name: '@babel/plugin-proposal-decorators',
    options: {
      legacy: true
    },
  });
};`

This setting is ignored,

**Expected behavior**

This setting should have been used.
In the .docz folder, there is a file called gatsby-node.js which is generated.
but only onCreateWebpackConfig function is described there.
If I directly used the above described onCreateBabelConfig function inside this file and then 
built the project, it seems to be working.

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 12]

**Comment by hvsy** [comment]
you can do it by doczrc.js

just like this:

```javascript
import { createPlugin } from "docz-core";

const myPlugin = () =>
  createPlugin({
    onCreateBabelConfig({ actions }) {
      actions.setBabelPlugin({
        name: "@babel/plugin-proposal-decorators",
        options: { legacy: true }
      });
    }
  });

export default {
  plugins: [myPlugin()]
};
```

**Comment by nikitpatel24** [comment]
Tried the above code, could not get it to work. Got the following  errror
<img width="1057" alt="Screen Shot 2019-09-05 at 09 53 51" src="https://user-images.githubusercontent.com/17763984/64322619-3538d480-cfc3-11e9-8969-40804971cb1d.png">

**Comment by rakannimer** [comment]
Hey @nikitpatel24 

@hvsy's code (thanks 👏) works for me.

Check out an example with @babel/plugin-proposal-decorators here : https://github.com/doczjs/docz-issue-1031

**Comment by nikitpatel24** [comment]
Indeed it works in the mentioned repo...thanks for your help.
