### ISSUE TITLE
Component Props not rendering on V2

### ISSUE THREAD

**Issue by jsplopes** [doczjs/docz#1079]
## Bug Report

The bug [#825](https://github.com/doczjs/docz/issues/825) reported on previous version is now appening on version 2.0.0-rc.28.

Regards,
Júlio

**Comment by rakannimer** [comment]
Hey @jsplopes 

Could you provide an example component that's failing and the mdx file that's importing it ? 

It will help us reproduce your problem and hopefully fix it.

**Comment by jsplopes** [comment]
Hey @rakannimer 
I'm currently using the repo that contains the gatsby [example](https://github.com/doczjs/docz/tree/master/examples/gatsby) provided by docz.
I tried to clean up node_modules and .docz but the properties still not rendering.

I made some debug and the issue is the same as i mentioned previously on bug #825 when get the filename
![image](https://user-images.githubusercontent.com/35458912/64328465-631f1880-cfc5-11e9-898d-4c1e015705df.png)
the path is showing windows slash for path separator and the docz stateProps is unix.

**Comment by rakannimer** [comment]
Ok, thanks for reporting this. 

I'm going to use @fi3ework's fix here : https://github.com/fi3ework/docz/commit/69c9cf9aeb1e458209b37469aa871fdbf8a86b09 

will ping you here when it's published

**Comment by rakannimer** [comment]
Ok, thanks for reporting this. 

@fi3ework's fix here : https://github.com/fi3ework/docz/commit/69c9cf9aeb1e458209b37469aa871fdbf8a86b09 
is supposed to fix the filename path to make it platform-agnostic 

Could you check which version of `babel-plugin-export-metadata` is being used in your node_modules

Unfortunately I can't debug more as I don't have a Windows machine. 

Also, could you try running : 

```
npx create-docz-app tmp-docz-test && cd tmp-docz-test && yarn dev
```

And let me know if it works as expected ?

**Comment by jsplopes** [comment]
Hi @rakannimer,
After executing the command

<pre>npx create-docz-app tmp-docz-test && cd tmp-docz-test && yarn dev</pre>

the issue remains :(.

The version of **babel-plugin-export-metadata** is  **2.0.0-rc.1**

**Comment by dreyks** [comment]
having the same issue on Mac with docz@2.0.0-rc.40 and babel-plugin-export-metadata@2.0.0-rc.1

**Comment by rakannimer** [comment]
Hey @dreyks,

Are you also using Windows ?

**Comment by dreyks** [comment]
nope. MacOS

**Comment by dreyks** [comment]
I'm not sure I have the same issue though. It's just Props is not working for me. I'll try to debug this today

**Comment by rakannimer** [comment]
Oh sorry missed that in your previous comment ! 

Do these commands also fail ?

Development :

```sh
npx create-docz-app tmp-docz-test && cd tmp-docz-test && yarn dev
```


Building : 

```sh
npx create-docz-app tmp-docz-test && cd tmp-docz-test && yarn docz build && yarn docz serve
```

**Comment by rakannimer** [comment]
Ok, if you can, make sure to provide the component where `Props` is failing and the mdx file using it.

**Comment by dreyks** [comment]
btw
```
npx create-docz-app tmp-docz-test && cd tmp-docz-test && yarn dev
```

gives me 

```
Downloading files for example basic. This might take a moment.


Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: e.destroy is not a function
    at e.forEach.e (/Users/dreyk/.npm/_npx/67694/lib/node_modules/create-docz-app/dist/index.js:2:35630)
```

**Comment by rakannimer** [comment]
Could you try again now ? You might have an older version of `create-docz-app` cached on your system that depends on the `dev` branch being defined (it was missing for around 1 minute)

**Comment by dreyks** [comment]
ok i figured this (the original issue) out. I have my components wrapped inside React.forwardRef, so obviously docz can't find its props

the `npx` works again too

**Comment by jesperorb** [comment]
https://github.com/fi3ework/docz/commit/69c9cf9aeb1e458209b37469aa871fdbf8a86b09 did fix the babel-plugin but there still seems to be something fishy in the `docz-core` which I am trying to solve here: https://github.com/doczjs/docz/pull/1151

**Comment by jesperorb** [comment]
@jsplopes Could you try with the latest rc `2.0.0-rc.54` and see if it fixes the issue?

**Comment by haohello** [comment]
I'm also having the same issue.  As in my case, the component is actually wrapped in a factory method, not sure if this is the reason why it cannot be rendered. So here is the code just in case any of you could shed some light on this.

Here is the factory method
```typescript
const createBox = (config: RenderComponentHookConfig<HTMLElement, BoxProps>) => {

  const {
    displayName = 'Box',
    className = 'ui-box',
    shorthandPropName = 'children',
    defaultProps,
    handledProps = [],
    /* eslint-disable react/forbid-foreign-prop-types */
    propTypes = {
      ...commonPropTypes.createCommon(),
    },
    contextMap = {},
    render
  } = config 

  const Box: CustomComponentType<HTMLElement, BoxProps> = 
    React.forwardRef((props: BoxProps, ref: React.Ref<HTMLElement>) => {
     // code to create the box below
    )
  }) as CustomComponentType<HTMLElement, BoxProps>
  Box.propTypes = propTypes
  Box.defaultProps = defaultProps
  Box.create = createShorthandFactory({ Component: Box })
  
  return Box
}
```
And here is the code to call the factory method to create the box component
```typescript
const config = {
  displayName: 'Container',
  className: 'ui-container',
  props: {}, 
  propTypes: {
    ...commonPropTypes.createCommon(),
    fluid: PropTypes.bool
  },
  defaultProps: {
    fluid: false
  },
  contextMap: []
} as RenderComponentHookConfig<HTMLElement, BoxProps>

const Container = createBox(config) as CustomComponentType<HTMLElement, ContainerProps>
```

**Comment by mateussales98** [comment]
Alguém pode ajudar?

C:\>npx create-docz-app docz-teste

Creating a new Docz app in C:\Users\mateus.sales\Documents\folder\tmp-docz-test.

Downloading files for example basic. This might take a moment.


Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: e.destroy is not a function
    at C:\Users\mateus.sales\AppData\Local\npm-cache\_npx\f6e6de91721365f0\node_modules\create-docz-app\dist\index.js:2:35630
    at Array.forEach (<anonymous>)
    at C:\Users\mateus.sales\AppData\Local\npm-cache\_npx\f6e6de91721365f0\node_modules\create-docz-app\dist\index.js:2:35573
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
