### ISSUE TITLE
border-radius broken in Playground

### ISSUE THREAD

**Issue by toyjhlee** [doczjs/docz#1080]
## Bug Report

I'm not good at speaking English.

**Describe the bug**

border-radius broken in Playground

**To Reproduce**

1. Create .mdx
2. Input playground tag
3. Run docz build && docz serve

**Expected behavior**

hope smooth border-radius

**Environment**

* OS: [Ubuntu 18.04.2 LTS]
* Node/npm version: [10.16.3/6.9.0]
* Browser : [Chrome 75.0.3770.100]
* Docz: [2.0.0-rc.35]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![playground-bordor-broken](https://user-images.githubusercontent.com/366932/64308315-c44de880-cfd3-11e9-8e88-87454ef91ef3.png)

**Comment by jesperorb** [comment]
Added in [v2.0.0-rc.53](https://github.com/doczjs/docz/releases/tag/v2.0.0-rc.53)
