### ISSUE TITLE
1.3.1 Seems broken

### ISSUE THREAD

**Issue by FredyC** [doczjs/docz#1082]
## Bug Report

We haven't changed anything lately but got an automatic upgrade to 1.3.1 from 1.2.0 and suddenly the website is crashing with the error.

> Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings

**To Reproduce**

https://mobx-react.js.org

Ref: https://github.com/mobxjs/mobx-react-lite/issues/219

**Comment by rakannimer** [comment]
Hey @FredyC 

Thanks for reporting this, working on it now. 

Is that the repo you use : https://github.com/mobxjs/mobx-react-docz ?

**Comment by FredyC** [comment]
@rakannimer Yes, that's correct.

**Comment by rakannimer** [comment]
Ok, very sorry for that ! 

It should be fixed with 1.3.2 I was able to run `docz dev` and `docz build` locally.

And I opened a PR to fix it to 1.3.2 : https://github.com/mobxjs/mobx-react-docz/pull/40
