### ISSUE TITLE
v2: how to add languages for syntax highlighting

### ISSUE THREAD

**Issue by olivoil** [doczjs/docz#1087]
## Question

I need to add syntax highlighting for a language not included by default in `prism-react-renderer`. The language in question is supported by `prismjs`.

I saw `react-prism-renderer` accepts a `Prism` prop to the `Highlight` component, but I'm not sure how to do it from docz.

How would you recommend doing it?

**Comment by rakannimer** [comment]
Hey @olivoil

Setting custom languages is not yet supported out of the box, but it's easy to add by passing a `language` prop to `LiveProvider` through the docz `Playground` component [here](https://github.com/doczjs/docz/blob/master/core/docz-components/src/components/Playground/index.tsx).

It's a very reasonable feature request so I'll add support for it later today and ping you here when it's published !

Cheers

**Comment by rakannimer** [comment]
Hey @olivoil 

I added support to set a custom language in the Playground component, you can now pass a prop (`language`) to the Playground component to set the language but I'm not sure that's what you're looking for.


I'm afraid if the language you want to use is not in this list : https://github.com/FormidableLabs/prism-react-renderer/blob/master/src/vendor/prism/includeLangs.js

then you won't be able to get syntax highlighting out of the box. 

What you can do is to bypass docz and create a component that reads your code as a string and displays it with the correct syntax highlighting :

In your JSX : 
```jsx
const CodeDisplay = (children) =>  {
	// use an alternative to React Live to get syntax highlighting like https://www.npmjs.com/package/react-syntax-highlighter
	return <pre>{children}</pre>
}
```

In your MDX : 

```mdx
import { Playground } from 'props'
import CodeDisplay from 'path/to/CodeDisplay'
<Playground>
<CodeDisplay language="my-language">
{`
print("hello world")
print("hello again")
`}
</CodeDisplay>
</Playground>
```

**Comment by olivoil** [comment]
Thanks, I'll give it a try!

Do you think there could be an easier way to add syntax highlighting for languages not in includeLangs.js? Maybe leveraging something like babel-plugin-prismjs or setting a costum Prism object in doczrs.js and passing it down to the Highlight component?

**Comment by olivoil** [comment]
The workaround I found at the moment is to do this:

```jsx
import { default as Prism } from 'prism-react-renderer/prism'
(typeof global !== 'undefined' ? global : window).Prism = Prism;
require('prismjs/components/prism-myLanguage');
```

**Comment by pavanpodila** [comment]
Does this work for syntax highlighting in fenced code blocks ? Is there a simpler approach to add language support for other languages, simply for rendering using Prism ?

**Comment by rakannimer** [comment]
I stumbled upon another version to do this using `gatsby-remark-vscode`. 

Please check out this example of using it with docz : https://github.com/doczjs/docz/tree/master/examples/with-gatsby-remark-vscode

Read more about everything you can do with gatsby-remark-vscode here : https://github.com/andrewbranch/gatsby-remark-vscode 

And about supported languages and adding more languages here : https://github.com/andrewbranch/gatsby-remark-vscode#languages

It should give you much more power and flexibility than the default Prism.
