### ISSUE TITLE
V1 doc is missing full section on creating a theme

### ISSUE THREAD

**Issue by fraincs** [doczjs/docz#1090]
This pages gives a 404

https://docz-v1.surge.sh/docs/creating-themes

**Comment by marcelorl-geru** [comment]
Not really sure what happens, but if you navigate manually to creating-themes page it actually works haha.

https://docz-v1.surge.sh -> "Documentation" (Header) -> "Creating Themes" (Sidebar)

If you refresh the page, then you will get the same 404 you reported. Something to be investigated for sure.

**Comment by jesperorb** [comment]
The website is a separate repo 🤓 Opened an issue and a PR(https://github.com/doczjs/docz-website/pull/76) for this issue there instead
