### ISSUE TITLE
How to modify font-size in V2 version?

### ISSUE THREAD

**Issue by csywweb** [doczjs/docz#1092]
## How to modify font-size in V2 version?

I tried this method, but I couldn't.

https://github.com/doczjs/docz/issues/555

**Comment by rakannimer** [comment]
Hey @csywweb 

You can use GatsbyJS theme shadowing to modify the font size and other styles.

Styles are defined in [`src/theme/styles.js`](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/theme/styles.js).

To override them, create a file `src/gatsby-theme-docz/theme/styles.js` and inside it change the values you'd like to override. 

For example : 

```js
// src/gatsby-theme-docz/theme/styles.js

import styles from 'gatsby-theme-docz/src/theme/styles`

styles.root.fontSize = 1 // or whatever you'd like

export default styles
```

Going to close this issue, please feel free to re-open it if this doesn't help or doesn't work.
