### ISSUE TITLE
Is it possible to use the UI of docz v1 with docz v2？

### ISSUE THREAD

**Issue by csywweb** [doczjs/docz#1093]
## Could I use ths UI of v1 version？

I want to use the UI of version 1 and Doc V1,  

could you give me some suggestion.

**Comment by rakannimer** [comment]
Hello csywweb, 

You could do that by using Gatsby's component shadowing, unfortunately this is not well documented yet

Will update here after we document better how to do it.

**Comment by csywweb** [comment]
@rakannimer looking forward to your updates  :)
