### ISSUE TITLE
How to make container take it's full width? 

### ISSUE THREAD

**Issue by ronaklalwaniii** [doczjs/docz#1098]
Hello, How to make the main container take its full width? I tried changing its width to 100% from the theme config but it wouldn't work. This is my theme config:
` themeConfig: {
    colors: {
      primary: "#7367f0",
      text: "#626262",
      link: "#7367f0",
      header: {
        bg: "#7367f0",
        text: "#FFFFFF"
      },
      sidebar: {
        navLinkActive: "#7367f0"
      }
    },
    fonts: {
      body: "Montserrat",
      heading: "Montserrat",
      monospace: "Montserrat"
    },
    styles: {
      p: {
        fontSize: 15
      },
      Container: {
        maxWidth: "100%"
      }
    }
  }`

Am doing something wrong?

**Comment by jesperorb** [comment]
@ronaklalwaniii 

No it seems that `docz` is ignoring that property in `themeConfig` and not setting a custom width in the `<Layout>`-component of the theme. This needs to be fixed in `docz`.

**Comment by jesperorb** [comment]
This should be fixes in `v2.0.0-rc.54`, so try updating and your example code should work.
