### ISSUE TITLE
when overriding theme, use background color for content

### ISSUE THREAD

**Issue by jstacoder** [doczjs/docz#1100]
## Bug Report

**Describe the bug**

when overriding the theme, it no longer uses the themes 'background color'

**To Reproduce**

create default site
override theme
set colors.background

**Expected behavior**

pages background color should be w/e was set in the theme

**Environment**

* OS: [e.g. OSX 10.13.4, Windows 10]
* Node/npm version: [e.g. Node 8/npm 5]

**Comment by rakannimer** [comment]
Thanks @jstacoder for reporting and fixing this ! Released as 2.0.0-rc.40 👍
