### ISSUE TITLE
Can't add other gatsby plugin from custom gatsby-config

### ISSUE THREAD

**Issue by rakannimer** [doczjs/docz#1108]
Issue first reported in #994

Desribed by @rahulrmetocean : https://github.com/doczjs/docz/issues/994#issuecomment-526688887

gatsby-config in `.docz` merge with custom config makes it override the plugins field array instead of merging them.

**Comment by dreyks** [comment]
doh. thought i was going crazy until i looked into the sources to find that `merge` there :D

any immediate workarounds available?
