### ISSUE TITLE
V2: Bring back full screen mode for Playground ⤢

### ISSUE THREAD

**Issue by Dangoo** [doczjs/docz#1111]
Hey @rakannimer,

The `docz-theme-default`featured a very useful full screen mode for the component demo:

![](https://camo.githubusercontent.com/11cef66f5b42f785d0cefc0c97fc9752fcff25e8/68747470733a2f2f63646e2d7374642e64707263646e2e6e65742f66696c65732f6163635f3634393635312f785a74357a72)

I think we should bring it back, what do you think?

PS: All-in-all I really liked the compact appearance of the Playground with line numbers, resize handle etc.

**Comment by rakannimer** [comment]
Yep bringing it back would be cool, though I'm not sure yet how much work it would take.

> All-in-all I really liked the compact appearance of the Playground with line numbers, resize handle etc.

I agree that the playground looked neater.  In v1 react-ace was used as the code editor in v2 react-live is used as the code editor and previewer.

We can start by checking if there are easy wins to get without switching the react-live editor.

If it's too limiting, we can check if we should revert it back to using react-ace.
