### ISSUE TITLE
V2: Menu icon in mobile view gets covered by other absolute components ☰

### ISSUE THREAD

**Issue by Dangoo** [doczjs/docz#1112]
The three bar menu icon (☰) in mobile view of `gatsby-theme-docz` has an initial `z-index` value and thus can be covered easily/accidentally by any other following absolute/fixed positioned sibling.

![menu](https://user-images.githubusercontent.com/1252204/64865062-c994de00-d638-11e9-8a38-9faec87e4de8.png)

This can be guarded by using an (arbitrary) higher index - even though any developer could choose a higher value of course.
Alternatively, moving the button out of the main container (e.g. to the header) can bring it into another stacking context so it can never be overlaid by children of main.

What do you think?

**Comment by rakannimer** [comment]
Moving the button out seems like the way to go IMO.

Could you send me an email at {myfirstname}{mylastname} at gmail so I can add you to the docz asana board to discuss more easily ?
