### ISSUE TITLE
Flow type example doesn't work

### ISSUE THREAD

**Issue by jakubmatena** [doczjs/docz#1113]
## Bug Report

Babel loader returns "syntax error" for flow type definition.

**To Reproduce**

1. Just clone from here: https://github.com/doczjs/docz/tree/master/examples/flow
2. Run 'yarn' to install fresh not cached dependencies
3. Run 'yarn dev' to run development server

```shell
 error  in ../src/components/Button.jsx
⠀
Syntax Error: SyntaxError: /Users/jakubmatena/projects/Personal/flow/src/components/Button.jsx: Unexpected token, expected ";" (61:5)

  59 | `
  60 | 
> 61 | type ButtonProps = {
     |      ^
  62 |   scale: 'small' | 'normal' | 'big',
  63 |   kind: 'primary' | 'secondary' | 'cancel' | 'dark' | 'gray',
  64 |   outline: boolean,


 @ ../src/components/Button.mdx 24:0-34 131:8-14 154:14-20 162:9-15 185:14-20 193:9-15 201:22-28 209:22-28 233:14-20 241:9-15 249:22-28 257:22-28 265:22-28 273:22-28 297:14-20 305:9-15 314:22-28 323:22-28 332:22-28 341:22-28
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ../node_modules/event-source-polyfill/src/eventsource.js ../node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
```

**Expected behavior**

*It will open Docz's documentation index page without any errors.*

**Environment**

* OS: OSX 10.14.6
* Node/npm version: Node 10/npm 6.9

**Comment by jesperorb** [comment]
@jakubmatena 
I tried to reproduce this error with:
```bash
npx create-docz-app docz-app-flow --example flow
cd docz-app-flow
yarn dev
```

But for me I am only getting the expected behavior, that the page loads without error. Could you try again if and see if the error still exists?

---
OS: OSX 10.14.1
Node: 10.16.2 / Yarn 1.17.3

**Comment by esturcke** [comment]
I seem to be running into a similar issue in my project. My `.babelrc`:

```
{
  "presets": ["@babel/preset-flow", "@babel/preset-react", "@babel/preset-env"]
}
```

Running `yarn docz dev` fails with:

```
warn "export 'Resizable' was not found in 're-resizable'

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

/Users/esturcke/ui/src/app/components/Checkbox/index.js: Unexpected token, expected ";" (8:5)

   6 | const block = bem("checkbox")
   7 |
>  8 | type Props = {
     |      ^
   9 |   /** Checkbox value */
  10 |   checked?: boolean | "partial",
  11 |   /** Wrap long labels */

File: ../src/app/components/Checkbox/index.js:8:5

failed Building development bundle - 6.935s
```

I WAS however able to run the flow type example without issue, so something else in my project might be breaking. Unfortunately this is a non-public project and I'm not sure what to try next to get a minimal reproduction case.

**Comment by esturcke** [comment]
Creating `gatsby-node.js` in the project root with the following fixed my issue:

```js
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPreset({
    name: `@babel/preset-flow`,
  })
}
```

**Comment by rakannimer** [comment]
> Creating gatsby-node.js in the project root with the following fixed my issue:
```
 exports.onCreateBabelConfig = ({ actions }) => {
   actions.setBabelPreset({
     name: `@babel/preset-flow`,
   })
 }
```

Thanks @esturcke for the solution this is indeed the way to do it, we need to tell babel to remove flow types to turn the code to plain JS.

Closing this, please feel free to re-open if the issue persists !
