### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by BTARPAR** [doczjs/docz#1118]
## Bug Report

**Describe the bug**
Not able to generate build. Trying to deploy documentaiton live  
*A clear and concise description of what the bug is.*

**To Reproduce**

1. docz build

```shell
FOR BUGS: Insert debug trace
 ERROR #95312 

"window" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  21 |  // to operate correctly into non-standard environments
  22 |  // @see https://github.com/webpack-contrib/style-loader/issues/177
> 23 |  return window && document && document.all && !window.atob;
     | ^
  24 | });
  25 | 
  26 | var getTarget = function (target, parent) {


  WebpackError: ReferenceError: window is not defined
  
  - addStyles.js:23 
    node_modules/style-loader/lib/addStyles.js:23:1
  
  - addStyles.js:12 
    node_modules/style-loader/lib/addStyles.js:12:1
  
  - addStyles.js:80 ./node_modules/style-loader/lib/addStyles.js.module.exports
    node_modules/style-loader/lib/addStyles.js:80:1
  
  - buttons.scss?d045:16 Object.../src/components/Button/buttons.scss
    src/components/Button/buttons.scss?d045:16:82
  
  - index.js:1 Module.../src/components/Button/index.js
    src/components/Button/index.js:1:1
  

⠋ Building static HTML for pages
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**
 sucessful build
*A clear and concise description of what you expected to happen..*

**Environment**

* OS: [e.g. OSX 10.13.4]
* Node/npm version: [e.g. Node v10.15.3/npm 6.4.1]

**Comment by rakannimer** [comment]
This looks like one of your dependencies is expecting window to be there. However Gatsby renders your app using node to generate the markup and you can't expect window to be defined at all times. 

More info [here](https://www.gatsbyjs.org/docs/debugging-html-builds/).

**Comment by jesperorb** [comment]
@BTARPAR Can you supply us with some more information about your project? Do you have a link to your project?

Looks like you are using `sass`, are you using some custom webpack config for it or are you running `create-react-app`?

**Comment by BTARPAR** [comment]
@jesperorb  Yes I am using sass and for sass, I am using webpack loaders
{
      test: /\.(scss|css)$/,
      use: [
        'style-loader',
        {
          loader: 'css-loader',
          options: {
            modules: {
              mode: 'local',
              localIdentName: 'my-app__[local]'
            }
          }
        },
        'sass-loader'
      ]
    }

**Comment by deammer** [comment]
I'm running into a similar problem. Here's a barebones repo with instructions on how to reproduce the error. Adding `style-loader` (in order to compile .scss files) seems to be the problem.

https://github.com/deammer/docz-test

**Comment by jesperorb** [comment]
Thank you @deammer 🙂 
Try installing [`isomorphic-style-loader`](https://github.com/kriasoft/isomorphic-style-loader)
```bash
yarn add isomorphic-style-loader --dev
```

And exchanging `style-loader` to `isomorphic-style-loader` in `gastby-node.js`:
```js
exports.onCreateWebpackConfig = ({ actions }) => {
  const extraConfig = {
    module: {
      rules: [
        {
          test: /\.(scss)$/,
          use: ['isomorphic-style-loader', "css-loader", "sass-loader"]
        }
      ]
    }
  };

  actions.setWebpackConfig(extraConfig);
};
```

Not ideal but seems to work.

**Comment by BTARPAR** [comment]
I replaced all my style-loader in webpack , and gatsby-node.js but still giving me the same error

**Comment by jesperorb** [comment]
Did you try removing `.docz`-folder after you installed the new package and replaces your webpack config?

That package worked in @deammer repo so I thought it would work for you. You can try if this works (i haven't tried it):

Install [gatsby-plugin-sass](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/)
```
yarn add node-sass gatsby-plugin-sass
```

Create a `gatsby-config.js` in your root with the following:
```js
module.exports = {
 plugins: [`gatsby-plugin-sass`]
}
```

And remove your your rules for `scss` in your webpack config.

**Comment by BTARPAR** [comment]
@jesperorb  I've tried the way you mentioned in the previous comment. But I am getting GRAPHQL ERROR
![Screen Shot 2019-10-07 at 12 07 15 PM](https://user-images.githubusercontent.com/18237494/66341038-4b57ee80-e8fb-11e9-8e08-729cc94bb2cb.png)

Same error on the when I do docz dev

**Comment by jesperorb** [comment]
@BTARPAR Check this issue and see if any solutions in the issue helps: https://github.com/doczjs/docz/issues/1007

**Comment by deammer** [comment]
@jesperorb thank you for your help! I didn't like the `isomorphic-style-loader` because it required extra code to work properly. Using `gatsby-plugin-sass` worked best.

**Comment by BTARPAR** [comment]
@jesperorb  I've tried to follow that issue but still, no luck  getting the same error with the 404 page

**Comment by BTARPAR** [comment]
![Screen Shot 2019-10-08 at 10 18 02 AM](https://user-images.githubusercontent.com/18237494/66417864-c7167180-e9b5-11e9-90e4-6795dd0f1edf.png)


Is this success build?

**Comment by BTARPAR** [comment]
I was able to do `docz dev ` "docz": "^2.0.0-rc.42" but when I upgrade it to "docz": "^2.0.0-rc.53", I am not able to `docz dev` and also got GRAPHQL ERROR

**Comment by rakannimer** [comment]
Hey @BTARPAR 

Does `"docz": "^2.0.0-rc.52"` work ?

Also can you copy the output of the command below  

```sh
rm -rf node_modules yarn.lock .docz && yarn add docz@next && yarn docz dev
```

**Comment by BTARPAR** [comment]
I've checked 42,44 to 53 with below command non of them worked. (I'll try one more time with your command)
`rm -rf node_modules yarn.lock .docz &&  yarn docz dev`

**Comment by BTARPAR** [comment]
@rakannimer I've tried your command with `"docz": "^2.0.0-rc.52"` but did not work have the same error GRAPHQL (https://github.com/doczjs/docz/issues/1118#issuecomment-539160355)

**Comment by rakannimer** [comment]
> can you copy the output here of the command below

```
rm -rf node_modules yarn.lock .docz && yarn add docz@next && yarn docz dev
```

I think we need more information to be able to properly help instead of guessing.

Could you provide a repository with a minimal reproduction of your problem and we can continue working from there ?

**Comment by BTARPAR** [comment]
@rakannimer sure, I'll do that this weekend and let you know

**Comment by BTARPAR** [comment]
@rakannimer @jesperorb here is a repo, where u was able to reproduce the error
https://github.com/BTARPAR/DOCZ

**Comment by rakannimer** [comment]
@BTARPAR can you please check https://github.com/BTARPAR/DOCZ/pull/1

It fixes the GraphQL error you referenced. After that the build fails because of some directories you did not include in the demo like `config`.

**Comment by BTARPAR** [comment]
@rakannimer updated the repo you can find the missing file now

**Comment by rakannimer** [comment]
Your repo is working correctly on my side after removing `gatsby-theme-docz` 1.2.0

What's the error you're getting ?

**Comment by BTARPAR** [comment]
Ii am getting the error mentioned on the top

**Comment by rakannimer** [comment]
Did you try the PR I referenced : BTARPAR/DOCZ#1 ?

**Comment by BTARPAR** [comment]
`docz dev `this worked for me as well try to do `docz build`

**Comment by rakannimer** [comment]
I tried @jesperorb's solution of replacing style-loader with isomorphic-style-loader and building using it works. 

1. Merge https://github.com/BTARPAR/DOCZ/pull/2
2. pull from master
3. rm -rf .docz && yarn docz build

**Comment by BTARPAR** [comment]
Yes, it worked for me as well let me see how it goes on my main project. Since this project works with docz I'll try to move my old stuff here and see how it goes. Wish me luck @rakannimer

**Comment by rakannimer** [comment]
Hey @BTARPAR  

Did you get the chance to confirm docz works with your codebase ?

**Comment by BTARPAR** [comment]
Good News latest version worked guys. It still has the issue but that definitely looks like on my side but build worked and dev also worked. I am closing this issue for now. If anything come up I'll let you know guys. 
Thank You @rakannimer @jesperorb  for this

**Comment by tquiroga** [comment]
Same error, I have components using `window`, I cannot import them because of the SSR done by gatsby, I've tried their workaround in the documentation, nothing has worked so far.

**Comment by wilkerlucio** [comment]
I'm also in a situation like this, I want to use `cytoscape-dagre` and having an import error:

```
   8 | 	else
   9 | 		root["cytoscapeDagre"] = factory(root["dagre"]);
> 10 | })(window, function(__WEBPACK_EXTERNAL_MODULE__4__) {
     |  ^
  11 | return /******/ (function(modules) { // webpackBootstrap
  12 | /******/ 	// The module cache
  13 | /******/ 	var installedModules = {};


  WebpackError: ReferenceError: window is not defined

  - cytoscape-dagre.js:10
    node_modules/cytoscape-dagre/cytoscape-dagre.js:10:2
```

**Comment by yes1am** [comment]
> I'm also in a situation like this, I want to use `cytoscape-dagre` and having an import error:
> 
> ```
>    8 | 	else
>    9 | 		root["cytoscapeDagre"] = factory(root["dagre"]);
> > 10 | })(window, function(__WEBPACK_EXTERNAL_MODULE__4__) {
>      |  ^
>   11 | return /******/ (function(modules) { // webpackBootstrap
>   12 | /******/ 	// The module cache
>   13 | /******/ 	var installedModules = {};
> 
> 
>   WebpackError: ReferenceError: window is not defined
> 
>   - cytoscape-dagre.js:10
>     node_modules/cytoscape-dagre/cytoscape-dagre.js:10:2
> ```

in my case: https://www.gatsbyjs.com/docs/debugging-html-builds/#fixing-third-party-modules works.

**Comment by nitin-** [comment]
Working Solution after spending 3 hours 

 "dependencies": {
    "docz": "^2.3.1",
    "gatsby-plugin-sass": "^3.2.0",
    ........
  },

// gatsby-config.js
module.exports = {
    // To fix the SCSS Errors 
    plugins: [`gatsby-plugin-sass`],
    // This has impressed me a lot
    flags:{
        DEV_SSR:false
    }
   }
