### ISSUE TITLE
Trying to implement Docz on a project with native-base 

### ISSUE THREAD

**Issue by ecalvi** [doczjs/docz#1120]
## Question
Hey, guys. I'm trying to document my React-Native project using Docz. Thing is my project is using Native-Base.

**Description**
When I try to build, I keep getting this error:
```
./node_modules/native-base-shoutem-theme/src/StyleProvider.js 10:19
Module parse failed: Unexpected token (10:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class StyleProvider extends React.Component {
>   static propTypes = {
|     children: PropTypes.element.isRequired,
|     style: PropTypes.object,
```
This is my doczrc.js file:
```
import { reactNative } from 'docz-plugin-react-native';

export default {
  title: 'Recarga Styleguide',
  plugins: [reactNative()],
  native: true,
  src: './app/components/ui/' // <== where the components are located inside the project
};

```
I've been researching and it seems to be quite a common error with Native-Base.
I found this solution in stackoverflow:
[https://stackoverflow.com/questions/56586865/expo-for-web-failed-to-compile-because-of-native-base-module](Expo for Web failed to compile because of native base module)

I suspect this solution might work for me, thing is: I don't think my project is using expo. I think I would like to try some setting on my babel.config or metro.config file, but I'm not sure how it would work.

Could you help me?
Thanks!

**Comment by rakannimer** [comment]
Hey @ecalvi 

Unfortunately my experience with native-base is very limited. 

Any chance you can provide an example repo that I ( or someone ) could look into ?

**Comment by rakannimer** [comment]
Also, which docz version are you using ?

**Comment by leggomuhgreggo** [comment]
@ecalvi docz no longer uses that plugin for native. It was moved to a default config option like:

```
// doczrc.js

import pkg from "./package.json";
export default {
  title: pkg.name,
  native: true,
  ...
};
```

Even with this setting, I had some issues with the v2 rc branches which I fixed by adding an alias the gatsby webpack hook docz kindly exposes, like this:

```
// gatsby-node.js
const path = require("path");

const ROOT = "../";

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      alias: {
        "react-native": path.resolve(ROOT, "node_modules/react-native-web"),
        ...
      },
      ...
    }
  });
};
```

Hope that helps!

**Comment by ecalvi** [comment]
Hey, guys! Thank you all for your help. I can't share the code because it's a company project.
But I will try to share more code than I did.
Regarding version, @rakannimer (thanks for the btw): I tried v2 but it forced me to install yarn and for what I've read it didn't seem to be too stable yet, so I got back to v1.

But I keep getting that same error:
```
./node_modules/native-base-shoutem-theme/src/StyleProvider.js 10:19
Module parse failed: Unexpected token (10:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export default class StyleProvider extends React.Component {
>   static propTypes = {
|     children: PropTypes.element.isRequired,
|     style: PropTypes.object,
```
I always end up there. No matter which path I travel.
Again, I think its Native Base related. I'm starting to hate Native Base but it's in the project nonetheless, so I'll have to cope for now. :-p

I had to freeze the documentation task for the moment, but I will get back to this in the next few days because I would really like to use Docz in my project, I think it's a very cool tool.

Thanks for all the help!

**Comment by ecalvi** [comment]
I keep hitting that same wall no matter what I do. :___(

I'm adding here my webpack config file:
```
module.exports = {
  presets: ['module:metro-react-native-babel-preset', 'module:react-native-dotenv'],
  plugins: [
    [
      'transform-rename-import',
      {
        replacements: [
          { original: 'react-native-vector-icons/Ionicons', replacement: '../../../../../app/components/icon' }
        ]
      }
    ],
    [
      'jsx-property-alias',
      {
        properties: {
          testID: 'accessibilityLabel'
        }
      }
    ],
    ['transform-inline-environment-variables']
  ],
  env: {
    production: {
      plugins: ['transform-remove-console']
    }
  }
};
```

I tried adding `'module:native-base-shoutem-theme'` into `presets` to try the solution mentioned here [Expo for Web failed to compile because of native base module](https://stackoverflow.com/questions/56586865/expo-for-web-failed-to-compile-because-of-native-base-module) and I got a different crash:
```Error: Cannot find module 'react-docgen/dist/babylon'```

That, I'm seeing, seems to be related to Docs ([727](https://github.com/pedronauck/docz/issues/727), [822](https://github.com/pedronauck/docz/issues/822)) but it is an earlier crash, so I'm assuming it's not a good idea to go that way.

The crash appears after I run= the `docz dev`, the original crash appears later during the compilation.

I'm not sure what to try next, because I don't have a clue of what could be causing this error.
