### ISSUE TITLE
v2: how to change favicon?

### ISSUE THREAD

**Issue by crusoexia** [doczjs/docz#1121]
## V2: How to change favicon

**Description**
There is no documentation about this, tried a few v1's method but doesn't work. Do I need to use gatsby plugin to change the favicon?

**Comment by rakannimer** [comment]
You're right this needs to be better documented.

I think you can use react-helmet along with gatsby-plugin-react-helmet to modify your favicon or other metadata. 

[How do I add react-helmet](https://www.gatsbyjs.org/docs/add-page-metadata/) ?

Once you've added react-helmet you can shadow the src/wrapper.js to add metadata

so you would create a file : `src/gatsby-theme-docz/wrapper.js` and inside it : 

```js
import * as React from 'react'
import { Helmet } from 'react-helmet'

const Wrapper = ({ children }) => <React.Fragment>
	<Helmet>
		<meta charSet="utf-8" />
		<title>My Title</title>
		<link rel="icon" 
      		type="image/png" 
		    href="http://example.com/myicon.png"
		>
	</Helmet>
	{children}
</React.Fragment>
export default Wrapper

```

**Comment by crusoexia** [comment]
@rakannimer thanks, it works
