### ISSUE TITLE
Trying to import Material-UI Button into .mdx file

### ISSUE THREAD

**Issue by jmschmidt** [doczjs/docz#1123]
I am trying to import Material-UI's button component into button.mdx and it fails to compile due to a missing dependency. Loading the Material-UI button into the React app works as expected though. I believe there is some kind of dependency conflict .

button.mdx
```
---
name: Button
menu: Atoms
---
import Button from '@material-ui/core/Button';

<Button variant="contained">
    Default
</Button>
```
This is the error returned during compile:
```
These dependencies were not found:
⠀
* dom-helpers/addClass in ../node_modules/react-transition-group/esm/CSSTransition.js
* dom-helpers/removeClass in ../node_modules/react-transition-group/esm/CSSTransition.js
```

App was created using create-react-app.
Docz Version: ^2.0.0-rc.41

**Comment by truecolintracy** [comment]
This looks to be a duplicate issue that has a conversation going on here: #1102

**Comment by jmschmidt** [comment]
I was able to get this working using this [solution](https://github.com/react-bootstrap/dom-helpers/issues/51#issuecomment-531002422) from @barbalex.
I updated my package.json to include:
`"resolutions": {
    "react-transition-group": "4.0.0"
  }`
