### ISSUE TITLE
Migrate bug

### ISSUE THREAD

**Issue by fidoChou** [doczjs/docz#1140]
When I migrate docz from 0.13.7 to the next version. here are some problems:

*  My propject used `docz-plugin-css`, I meet  the similar [issues/999](https://github.com/doczjs/docz/issues/999) what I lacked is the plugin 
`gatsby-plugin-mdx`. 

* Then I removed the `docz-plugin-css`, the eslint disabled me bundle the file, I got the info: 

![image](https://user-images.githubusercontent.com/11592539/65867713-8319e000-e3a9-11e9-8986-91c8ecbad3b1.png)

It's my own package lib dist. so I add `.eslintignore` in the project root which is invalid.

But I found in the node_modules/gatsby/dist/utils/webpack.config.js
line 314, It telled me my program.directory is `.docz`? Sure It can't not read my `.eslntrc`?

![image](https://user-images.githubusercontent.com/11592539/65868732-6d0d1f00-e3ab-11e9-8cc9-16361aadc42e.png)

gatsby maked sad :(

Or is there any config file  can be provided ?

**Environment**

- docz version: [2.0.0-rc.48]
- OS: [OSX 110.14.6]
- Node/npm version: [Node v10.16.3 / yarn 1.17.3]

**Comment by rakannimer** [comment]
Hey @fidoChou 

Thanks for reporting this issue.

Any chance you can provide a small repro repository with the problem ?

**Comment by fidoChou** [comment]
> Hey @fidoChou
> 
> Thanks for reporting this issue.
> 
> Any chance you can provide a small repro repository with the problem ?

Just install the plugin `docz-plugin-css`, you will reshow the case, As for the second eslint problem, I will do more check about the code.

**Comment by jesperorb** [comment]
> > Hey @fidoChou
> > Thanks for reporting this issue.
> > Any chance you can provide a small repro repository with the problem ?
> 
> Just install the plugin `docz-plugin-css`, you will reshow the case, As for the second eslint problem, I will do more check about the code.

`docs-plugin-css` is not needed / does not work any more for `v2`. This is not well documented, we are sorry about that. But we have written about it here and will try to make it more clear in the documentation:
[Migration Guide](https://github.com/doczjs/docz/blob/master/MIGRATION_GUIDE.md#css-preprocessors-managed-by-gatsby)

**Comment by fidoChou** [comment]
I read the migration said the `docz-theme-default` is decrepted but not `docz-plugin-css`. You just give me a good guide. I will try to make a repo to show the eslint error.

> > > Hey @fidoChou
> > > Thanks for reporting this issue.
> > > Any chance you can provide a small repro repository with the problem ?
> > 
> > 
> > Just install the plugin `docz-plugin-css`, you will reshow the case, As for the second eslint problem, I will do more check about the code.
> 
> `docs-plugin-css` is not needed / does not work any more for `v2`. This is not well documented, we are sorry about that. But we have written about it here and will try to make it more clear in the documentation:
> [Migration Guide](https://github.com/doczjs/docz/blob/master/MIGRATION_GUIDE.md#css-preprocessors-managed-by-gatsby)

I read the migration said the `docz-theme-default` is decrepted but not `docz-plugin-css`. You just give me a good guide. I will try to make a repo to show the eslint error.

**Comment by fidoChou** [comment]
I have invited you  two to join a private repo.   Thanks for your time.

**Comment by fidoChou** [comment]
![image](https://user-images.githubusercontent.com/11592539/66315597-abc14d00-e948-11e9-8c23-4be4879e46e3.png)
Hi,  guys, just read the gatsby source code, I have fix the eslint error  with  `gatsby-config.js`. Anyway the doc is really not nice for developer :(

**Comment by fidoChou** [comment]
BTW, I think the root path  is default belong to the project instead of `.doz` ?

**Comment by jesperorb** [comment]
Glad you fixed it, sorry that the docz are missing some config, we are working on improving them.
