### ISSUE TITLE
Props work in dev, but not in production build

### ISSUE THREAD

**Issue by brandonarbini** [doczjs/docz#1147]
## Bug Report

When building in dev mode the props are being parsed properly and showing up in docs. When doing a production build the props are missing completely.

**To Reproduce**

I can't share the code and I could try and reproduce in another project, but first I'd like to ask if you can think of a reason this would happen for me to investigate first.

**Environment**

- docz version: 2.0.0-rc.52
- OS: OSX 10.14.5
- Node/npm version: Node 12.8.0/NPM 6.11.3

**Comment by brandonarbini** [comment]
To be clear, this has been the case for the last 10 releases or so, I just haven't reported it yet. It's still present in rc52. I've tried a number of things (like building dev first and others), but nothing has fixed the production build. I'd love some direction for further research.

**Comment by rakannimer** [comment]
Hey @brandonarbini,

Would love to help but I'm not sure what the issue is without having a repro.

I tried : 

```sh
cd /tmp && npx create-docz-app issue-1147 && cd issue-1147 && yarn && yarn build && yarn serve
```

Then opened : http://localhost:9000/src-components-alert

and Props table showed up correctly.

Are you using typescript ? Can you share the example mdx and js/ts file ?

**Comment by brandonarbini** [comment]
Thanks for taking a look for me. I've narrowed it down a little bit.

1. Yes, I am using typescript.
2. I tried the command you pasted above and it worked.
3. I tried the command with `-e typescript` and it worked.
4. I tried using `yarn docz build && yarn docz serve` on my project and it worked!
5. Then I tried it in CI (Bitbucket Pipelines) and it didn't work. :(

So, I'm going to keep working on figuring out why it works locally, but not in CI.

**Comment by jesperorb** [comment]
@brandonarbini What differs from your local environment from CI? CI running Linux/Windows and a different version of npm/yarn?

**Comment by brandonarbini** [comment]
Hi @jesperorb. I'm running Mac OS locally and Linux in CI. The versions of `npm` and `yarn` should match. I'm not sure of any other meaningful differences. I haven't had a chance to return to this for a little bit as I'm currently building locally and uploading to S3. Once I get some more time I'll try and tackle this again. In the meantime, any tips to get me going in the right direction would be appreciated. Thanks!

**Comment by jesperorb** [comment]
I am a bit clueless to why it shouldn't work. We have recently merged a PR that will adress the handling generating the props (https://github.com/doczjs/docz/pull/1151). It has not been released yet but will be soon. This may help with this issue but no promises. I have no concrete tips sadly, I will try running the build on my machine with Linux and report back but I don't see that the OS difference between Mac and Linux should be a problem. Is the CI running exactly the same commands as your local environment?
