### ISSUE TITLE
Crash when importing `index.tsx` from `index.mdx`

### ISSUE THREAD

**Issue by Kerumen** [doczjs/docz#1164]
## Bug Report

**Describe the bug**

When importing a component from a `index.tsx` file in a `index.mdx` at the same location, it crashes with:

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**To Reproduce**

1. `$ npx create-docz-app docz-app-typescript --example typescript`
2. Create a random exported component in the file `src/index.tsx` (either named export or default export)
2. Change `src/index.mdx` to

```mdx
import Component from './'
// or
import { Component } from './'

<Component />
```

4. Run `npm run docz dev`
5. See error in browser

**Expected behavior**

It should render the component without any error.

PS: it works fine with javascript files, the error occurs for TS only.

**Environment**

- docz version: v2.0.0-rc.53
- OS: OSX 10.14.6
- Node/npm version: Node v10 / npm v6

**Additional context/Screenshots**

<img width="1001" alt="Screenshot 2019-10-07 at 14 53 49" src="https://user-images.githubusercontent.com/5436545/66313414-9df0d500-e912-11e9-8213-082982845d5b.png">

**Comment by selbekk** [comment]
Hi! Sounds like you’ve imported your component as a default export, while it’s only available as a named export. 

If you change the import to read `import { Component } from ‘./‘`, you should be good 👌

**Comment by Kerumen** [comment]
@selbekk Both doesn't work. I'll add this in the issue.

**Comment by selbekk** [comment]
Hm, interesting. Looks like `.mdx` "takes presedence" over `.tsx`. This is probably due to the fact that Docz specifies the markdown plugin before the typescript plugin. If you specify the full `./index.tsx`, it works though :)
