### ISSUE TITLE
mdx parser throws on empty line in JSX block

### ISSUE THREAD

**Issue by samjt** [doczjs/docz#1165]
## Bug Report

**Describe the bug**

React Native projects fail to compile, throwing an unexpected token error or a JSX mismatch error. Other react-native projects also do not compile.

**To Reproduce**

1. create-docz-app my-docz-app --template react-native && cd my-docz-app
2. yarn dev
5. See error in terminal

```shell
 error  in ../src/components/Alert.mdx
⠀
Syntax Error: SyntaxError: unknown: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (31:9)

  29 |   <Alert><Text>{message}</Text></Alert>
  30 | )
> 31 | `}</code></pre>
     |          ^
  32 | <p>{`  }}`}</p>
  33 | </Playground>
  34 |     </MDXLayout>/Users/sam/Documents/myapp/src/components/Alert.mdx: unknown: Adjacent JSX elements must be wrapped in an enclosing tag. Did you want a JSX fragment <>...</>? (31:9)

  29 |   <Alert><Text>{message}</Text></Alert>
  30 | )
> 31 | `}</code></pre>
     |          ^
  32 | <p>{`  }}`}</p>
  33 | </Playground>
  34 |     </MDXLayout>
```

**Expected behavior**

The template at least should compile without modifications.

**Environment**

- docz version: 2.0.0-rc.53
- OS: OS X 10.14.6
- Node/npm version: node v10.14.2 / npm 6.11.1

**Comment by samjt** [comment]
After some digging, it’s an issue with gatsby-plugin-mdx, which in turn is relying on @mdx/react I think.

**Comment by rakannimer** [comment]
Also opened an issue to track this in `gatsby-plugin-mdx` https://github.com/gatsbyjs/gatsby/issues/17947 

But as you said this looks like a mdx issue.

**Comment by samjt** [comment]
This is still an issue and should be open

**Comment by rakannimer** [comment]
You're right, we can track its progress here : https://github.com/mdx-js/mdx/issues/767
