### ISSUE TITLE
Page Routing/URL issue on the Documenation

### ISSUE THREAD

**Issue by impressivewebs** [doczjs/docz#1166]
The following link appears to be broken:

https://www.docz.site/docs/migration-guide

But when I visit the same link from within the documentation, it works fine. It seems to have something to do with how the URLs are resolved client-side.

This seems to happen with any documentation link.

**Comment by jesperorb** [comment]
@impressivewebs Thank you for bringing this to our attention. We will get around to fixing it as fast as possible.

**Comment by AdrianoCahete** [comment]
Same as you go to Introduction and click on "Let's get started!". The link sends to a broken URL, even with the correct URL.

**Comment by rakannimer** [comment]
There was a small issue in docz-website that should be fixed now :

https://www.docz.site/docs/migration-guide
and
https://www.docz.site/docs/getting-started

work as expected.

**Comment by CaitlinWeb** [comment]
@rakannimer @jesperorb Issue seems to have come back. Going to https://www.docz.site/docs/migration-guide results in "Not found" page. 

For anyone else who encounters this, you can see the migration guide here as well: https://github.com/doczjs/docz/blob/master/MIGRATION_GUIDE.md

**Comment by rakannimer** [comment]
Thanks @CaitlinWeb for reporting this. It should be fixed (again 😅) now : https://www.docz.site/docs/migration-guide
