### ISSUE TITLE
How to cancel default menu when I use menu config

### ISSUE THREAD

**Issue by jyjin** [doczjs/docz#1171]
<img width="358" alt="docz" src="https://user-images.githubusercontent.com/8912548/66704780-dac52d80-ed51-11e9-8e6f-98a17d195253.png">

My project have many mdx files. And I want to use sort menu by config, but it always produce duplicated menu, one of config, one of default.

How to cancel the default menu produce?

doc config:

```

import menu from './src/menu'

export default {
    title: 'fntd组件库',
    dest: '/doc-dist',
    files: './src/mdx/*.mdx',
    menu
}
```

menu js:
```
module.exports = [
  {
    name: '快速入门',
    route: '/home'
  },
  {
    name: '组件库',
    menu: [
      {
        name: 'Button 按钮',
        route: '/button',
      },
      {
        name: 'Icon 图标',
        route: '/icon',
      },
      {
        name: 'Typography 排版',
        route: '/typography',
      },
    ]
  }
]
```

mdxs:

<img width="323" alt="b" src="https://user-images.githubusercontent.com/8912548/66704910-f977f400-ed52-11e9-856c-cfc6b8e8acd8.png">

**Comment by sanshuiwang** [comment]
https://www.docz.site/docs/project-configuration

Build pipeline

**Comment by jakemmarsh** [comment]
@sanshuiwang using the `menu` setting in build pipeline does not disable the default menu, as this issue is reporting.

Same as #694

**Comment by sanshuiwang** [comment]
> @sanshuiwang using the `menu` setting in build pipeline does not disable the default menu, as this issue is reporting.
> 
> Same as #694

Great!
