### ISSUE TITLE
Statically rendered documentation

### ISSUE THREAD

**Issue by pepibumur** [doczjs/docz#1172]
## Awesome, do you have an idea? 😍
I'm using Docz for [Tuist's documentation](https://docs.tuist.io) and I'm very happy with how easy and flexible it's creating a documentation website with Docz. Congrats everyone involved in this project because it's insanely valuable.

There's one little thing that I wish Docz had and that I'm a bit surprised it hasn't been built yet into Docz. Since the generate website loads dynamically with React, the documentation website can't be indexed by search engines like Google.

Is there any plan to add this feature? If so, is there any estimates? I'd be happy to contribute to the project if anyone could provide me with some guidance on where to start from.

**Comment by rakannimer** [comment]
Hey @pepibumur ! 

Happy to hear that docz is helpful to you ! 

docz v2 is completely built with Gatsby so it generates a static website that can be indexed by any search engine !

Have you tried updating to v2 with : 

```
yarn add docz@next 
```

**Comment by pepibumur** [comment]
> docz v2 is completely built with Gatsby so it generates a static website that can be indexed by any search engine !

Wow! That's fantastic. I tried a while ago but I ran into some issues with the migration and I gave up. I'll try again and let you know.

Feel free to close this issue because this has already been worked on.

**Comment by rakannimer** [comment]
> Feel free to close this issue because this has already been worked on.

Will do ! Please feel free to open new issues with any problem you encounter while migrating !
