### ISSUE TITLE
Shadowing and extending the Playground component

### ISSUE THREAD

**Issue by deammer** [doczjs/docz#1174]
## Question

I would like to extend the `Playground` component to add some markup around it. [According to Gatsby's docs](https://www.gatsbyjs.org/blog/2019-07-02-extending-components/), it should be possible to do so.

So my question is: is this supported with Docz? And if so, what's the correct syntax?

Here's an [example repository](https://github.com/deammer/docz-test) where I attempt to add a `<div>` wrapper around the `Playground`.

**Comment by rakannimer** [comment]
Hey 

Thanks for reporting this issue.

You're shadowing the Playground component correctly but the playground used in the markdown is from `docz` not from `gatsby-theme-docz` (the theme you're shadowing).

You could create a CustomPlayground component that wraps Playground with a div and exports it and use it instead of the one `docz` provides

```jsx
// Playground.js
import { Playground } from 'docz'

export default (props) => {
	return <div>
		<Playground {...props}/>
	</div>
}

```


Would that work ?

**Comment by deammer** [comment]
Thanks for the quick reply, @rakannimer! You're right, I was doing it wrong. For reference, here's how to make it work:

1. extend the component:

   ```jsx
   import React from 'react'
   import { Playground } from 'docz'

   export default props => {
     return (
       <div style={{ background: 'rebeccapurple', padding: 12 }}>
         <Playground {...props} />
       </div>
     )
   }
   ```

2. import the component using a relative path:

   ```js
   import CustomPlayground from '../path/to/component';
   ```

3. wrap your markup as you normally would:

   ```jsx
   <CustomPlayground>
     <button type="button">Click me</button>
   </CustomPlayground>
   ```

**Comment by deammer** [comment]
Bonus: if you're not thrilled at the prospect of importing from a relative path, use webpack's `@alias` feature! For instance, add a `gatsby-node.js` file to your root directory:

```js
// gatsby-node.js
const path = require('path')

exports.onCreateWebpackConfig = ({ actions }) => {
  const extraConfig = {
    resolve: {
      alias: {
        '@playground': path.resolve(__dirname, '../src/custom/Playground')
      }
    }
  }

  actions.setWebpackConfig(extraConfig)
}
```

Now, assuming that your custom `Playground` component is the default export of a file named `src/custom/Playground/index.js`, you should be able to import it directly:

```js
// documentation.mdx
import Playground from '@playground`;
```

(make sure to restart the Docz server to reload the webpack configuration)

**Comment by deammer** [comment]
@rakannimer it looks like this stopped working. How would recommend extending the `Playground` component?

What I'm looking for:

```jsx
import React from 'react'
import { Playground } from 'docz'

export default props => {
  return (
    <div style={{ background: 'rebeccapurple', padding: 12 }}>
      <Playground {...props} />
    </div>
  )
}
```

**Comment by rakannimer** [comment]
Hey @deammer 

I'm not sure what the problem you're facing is. 

I added two examples, one that shows a shadowed playground and the other an extended one with the example code you provided. 

Can you please check them ?

- shadowed playground : https://github.com/doczjs/docz/tree/master/examples/shadowed-playground
- extended playground : https://github.com/doczjs/docz/tree/master/examples/wrapped-playground

**Comment by deammer** [comment]
@rakannimer thank you for the examples, they helped me debug my problem!

My problem was that I was trying to extend the `Playground` component while shadowing it at the same time. I had a `Playground.jsx` file in `src/gatsby-theme-docz/components/`, which was causing an infinite referential loop.

The solution was to move that file somewhere else (`src/components`, for instance).
