### ISSUE TITLE
Customize meta description

### ISSUE THREAD

**Issue by pepibumur** [doczjs/docz#1177]
### Need

I'd like to leverage the shadowing of the [wrapper](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/wrapper.js) component to add a meta description to the generated pages using the description that is included in the page frontmatter:

```md
---
description: just a description
---
Page content
```
### Proposal
Support passing the page frontmatter to the wrapper component so that developers can use frontmatter's metadata from the component.

**Comment by rakannimer** [comment]
Hey @pepibumur 

This sounds like a reasonable need and solution.

I think we would have to pass down the `entry` object prop to the `Wrapper` component here : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/base/Layout.js#L16 and that would allow you to map the description from frontmatter to a meta description.

**Comment by pepibumur** [comment]
I think we can close this @rakannimer. Since now the properties are passed down, I can use Helmet to set the meta headers.
