### ISSUE TITLE
How to point the doczrc.js src to components in dependency package in a monorepo?

### ISSUE THREAD

**Issue by dragonza** [doczjs/docz#1179]
## Question
How can I config docz to use components from other packages in monorepo?

**Description**
I am using a monorepo which has a package containing all the components. In the monorepo,  I have another package which wants to document these components. I am using gatsby with docz v2.0.0-rc.55.

So far using relative path to point to the components package (like this `../components-package/src/component`) in the monorepo worked but that would be an anti-pattern to do so. I would prefer docz could reach into the `node_modules` which has components package as dependency.  Below is what I want
```
export default {
  menu: [
    { name: 'Docs home', route: 'docs/' },
  ],
  src: 'components-package/src/components', // components-package exists in the node_modules here
  files: '**/*.{mdx}',
}
```

However, when I navigate to `http://localhost:8000/docs/`, I got an error

![image](https://user-images.githubusercontent.com/10185439/66870067-825e7d80-ef55-11e9-8bbe-9ff3339c3d11.png)

and GraphQL error like `Cannot query field "allDoczEntries" on type "Query". Did you mean "allDoczDb"?`
I am wondering if this is possible to do with docz. 
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by rakannimer** [comment]
I think the `filterComponents` and `docgenConfig.searchPath` flags in [`doczrc.js`](https://github.com/doczjs/docz/blob/master/examples/monorepo-separate-docs/packages/docs/doczrc.js) would help for your use case. 

Check out this monorepo example of a `docs` package used to document other peer packages : https://github.com/doczjs/docz/tree/master/examples/monorepo-separate-docs

**Comment by dragonza** [comment]
I got it! Thank you very much
