### ISSUE TITLE
Failed to load config "react-app" to extend from.

### ISSUE THREAD

**Issue by csywweb** [doczjs/docz#1180]
## Bug Report

**npm run docz:dev webpack error**

```
Generating development JavaScript bundle failed

Failed to load config "react-app" to extend from.
Referenced from: BaseConfig

File: .cache/app.js
```

**To Reproduce**

https://github.com/csywweb/docz-webpack-error

1. yarn
2.npm run docz:dev

**Environment**

- docz version: [2.0.0-rc.53]
- OS: [OSX 10.14.6]
- Node/npm version: [Node 8.16.1/npm 5]

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/3185567/66886373-ae3b3b00-f009-11e9-853e-05f6c41cd596.png)

**Comment by csywweb** [comment]
seem like  it's missing eslint-config-react-app
but
![image](https://user-images.githubusercontent.com/3185567/66898766-61b52700-f02c-11e9-8367-cc2c00c4cdc3.png)

**Comment by enric-jorda** [comment]
You should upgrade your eslint version

**Comment by kremuwa** [comment]
It's the newest version at this time. I'm facing the same problem.
