### ISSUE TITLE
Gatsby Theme - Should the component reside next to the mdx file?

### ISSUE THREAD

**Issue by vinayg-cp** [doczjs/docz#1183]
## Question

**Description**
In a gatsby monorepo, 
I am trying to use docz as a separate package. 
But the props is not working as expected, if I am trying to import component from other package folder.
It seems to pick up props only when I try to place it next to the .mdx story.

It works in following scenario: 
docs-gatsby-project
|_ src/
   |_components/
     |_ Button.jsx
     |_ Button.mdx -> Where Button.mdx imports Button.jsx 

But does not work in this case: 
- docs-gatsby-project
  |_ src/
    |_ components/
      |_ Circle.mdx -> Where Circle.mdx imports theme/src/components/Circle
- theme/
  |_ src/
    |_components/
     |_Circle.jsx

Is it really necessary that the Component and Documentation should be on same level?

**Comment by selbekk** [comment]
Try setting the `docgenConfig.searchPath` prop of the `.doczrc` file to `..` or something:

```
docgenConfig: {
  searchPath: '../packages',
},
```

It's not documented, but worked for me!
