### ISSUE TITLE
SVG rendering issue "InvalidCharacterError: Failed to execute 'createElement' on 'Document'"

### ISSUE THREAD

**Issue by Tombre** [doczjs/docz#1184]
## Bug Report

**Describe the bug** 

When importing svg elements into docz MDX files, rendering those svgs returns an error like so:
```
InvalidCharacterError: Failed to execute 'createElement' on 'Document': The tag name provided ('data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyMCAyMCI+PHBhdGggZD0iTTE2LjE3MiA5bC02LjA3MS02LjA3MSAxLjQxNC0xLjQxNEwyMCAxMGwtLjcwNy43MDctNy43NzggNy43NzgtMS40MTQtMS40MTRMMTYuMTcyIDExSDBWOXoiLz48L3N2Zz4=') is not a valid name.
```

_Just a note: I am unsure if it's my setup is wrong, but from reading other issues here I assuming you can import SVG's into considering svgr is included in the core?_

**To Reproduce**

I have built a small sandbox to reproduce the issue:
https://github.com/Tombre/docz-svg-rendering

run `yarn docz:dev`

**Expected behavior**

Importing an svg into the mdx file should render it like a regular react component.

**Environment**

Docz Version: ^2.0.0-rc.57
Node: v10.16.3
NVM: 6.9.0

**Additional context/Screenshots**

Here is a screen shot of the result
![Screen Shot 2019-10-18 at 8 54 53 am](https://user-images.githubusercontent.com/3880871/67057884-f6329d00-f184-11e9-9124-50694de0c965.png)

**Comment by juanpablocs** [comment]
you should use a gatsby plugin

```
npm add gatsby-plugin-react-svg
```

create file `gatsby-config.js`

add

```js
module.exports = {
    plugins: ['gatsby-plugin-react-svg']
}
```

This worked for me.

**Comment by rakannimer** [comment]
Thanks @juanpablocs for providing the solution ! 

@Tombre, I opened a PR (https://github.com/Tombre/docz-svg-rendering/pull/1) to your repro and tried it and it's working as expected 👍

**Comment by Tombre** [comment]
This solved it thanks!
