### ISSUE TITLE
Service not listening on 0.0.0.0

### ISSUE THREAD

**Issue by MaluNoPeleke** [doczjs/docz#1185]
Service is starting, only problem is that is not listening on 0.0.0.0 so I cannot connect from outside the container.
Additional note, I've tried using -e DOCZ_HOST=0.0.0.0 but didn't worked

docz 2 RC57

**Comment by rakannimer** [comment]
Hey @MaluNoPeleke 

Since `docz` uses Gatsby, you can change the host to 0.0.0.0 by adding the `host` flag to docz dev : 

```sh
yarn docz dev --host=0.0.0.0
``` 

or in your package.json : 

```json
{
	"scripts": {
		"dev": "docz dev --host=0.0.0.0"
	}
}
```
