### ISSUE TITLE
Include components in index.js files as well

### ISSUE THREAD

**Issue by esturcke** [doczjs/docz#1212]
This is somewhere between a bug and a feature request. The default `filterComponents` does not include components specified in `index.js` files (e.g. `components/Button/index.js`). Would it be possible to extend the default regex to something like:

```js
files => files.filter(filepath => /\/[A-Z]\w*(\/index)?\.js$/.test(filepath)),
```

Without this I was running into `<Props>` returning nothing. It took me a while reading through code to even find that option. 😁 

If not, perhaps it can be highlighted in the docs? Thanks!

**Comment by selbekk** [comment]
Ran into the same issue. +1 on including it, or at least documenting this behavior 😘

**Comment by rakannimer** [comment]
Hey @esturcke 

Thanks for reporting this. 

You're right this not being documented can lead to a very frustrating experience when you want lower case files or just `index` to be included. 

Would you be open to submitting a PR to slightly loosen the regex to accept `index.(js|jsx|ts|tsx)` ? 

It might be better to avoid having `docz` users think about this unless they really need to.

What do you think ?

**Comment by esturcke** [comment]
Sure, I can put one together.
