### ISSUE TITLE
Errors are thrown when importing another mdx file in your mdx page

### ISSUE THREAD

**Issue by jzarzeckis** [doczjs/docz#1219]
## Bug Report

**Describe the bug**

When `mdx` content is being converted to a React component, it's wrapped in the [Layout](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/base/Layout.js) components. This is fine for pages, where page context is required, but turns out it happens for imported md content too, and therefore when trying to embed another mdx file in existing content, it tries to build the whole layout inside the imported mdx component

**To Reproduce**
1. `npx create-docz-app docz-app-basic`
2. Change src/index.mdx to

```mdx
import Readme from '../README.md'
### Some mdx content

<Readme />
```

4. Run `npm run docz dev`
5. See error in browser

```shell
TypeError: Cannot read property 'frontmatter' of undefined
findEntry
node_modules/gatsby-theme-docz/src/base/Layout.js:29
  26 | 
  27 | const findEntry = (db, ctx) => {
  28 |   console.log(db)
> 29 |   const isIndex = ctx.frontmatter.route === '/'
  30 |   const eqIndex = propEq('value.route', '/')
  31 |   if (!ctx.entry && isIndex) return db.entries.find(eqIndex)
  32 |   const filepath = get('entry.filepath', ctx)
```

**Expected behavior**

README.md content embedded within the "Getting Started" page

**Environment**

- docz version: 2.0.0-rc.66
- OS: macOS Mojave 10.14.6
- Nodeversion: v12.11.1

**Additional context/Screenshots**
When I try to avoid these errors, and provide the missing props as `<Readme pageContext={{frontmatter: {route: '123'}, entry: {filepath:'README.md'}}} />` etc to the component, then it does render README, however it also builds the whole layout within the embedded component, and thus left nav is repeated:

![image](https://user-images.githubusercontent.com/919350/67858350-ab6c3a00-fb21-11e9-8b0a-4833a3784ffa.png)

**Comment by MaximeHeckel** [comment]
This solution unlocked my team. Is this going to be permanent? we would like to avoid having this kind of "code" showing up in NPM or Github for our repos

**Comment by rakannimer** [comment]
> we would like to avoid having this kind of "code" showing up in NPM or Github for our repos

Yeah I agree, I don't really like this solution either ! Going to keep this issue open while we figure out a better solution 👍

**Comment by heynext** [comment]
any updates here?

**Comment by chrisrzhou** [comment]
It would be ideal if source content in other markdown files does not require the magical `export default ({ children }) => children` clause.  Is this something that is specific to `mdx` and not `docz`?
