### ISSUE TITLE
2.0 Release Roadmap?

### ISSUE THREAD

**Issue by drewlustro** [doczjs/docz#1222]
## 2.0 Roadmap

👋 Hello Pedro & maintainers,

First off, thank you for your work! We leverage Docz 1.x at our org for a design system.

I want to know if there is any official roadmap for 2.0's release.

So far, these are my observations:

- **mid 2018** @pedronauck creates docz
- **late 2018** docz gains immense momentum
- **early 2019** docz enjoys massive community support, but Pedro is overwhelmed by bundler issues (and generally the sheer number of issues)
- **mid 2019** Pedro announces plan for 2.0 / integration with Gatsby
  - @pedronauck promotes some new maintainers and stops personally contributing to the project
- **late 2019** maintainers have been marching towards 2.0, but progress is relatively slow

Given these observations, I've considered switching to Storybook. However, it would be a lot of work that I prefer to avoid.

**I would love to stay on Docz and plan for the future, but this is difficult because of the the lack of a 2.0 release roadmap.** There seems to be a new burst of "release candidates" every few weeks. These spark hope, but the fact that we're up to 60+ candidates deep is not confidence-inspiring. These builds do not appear close to production ready. Often, a release candidate will be generated for fixing one bug or addressing one issue. 

Anyhow, just looking for guidance as we'd like to continue using and supporting Docz at my workplace.

**Comment by selbekk** [comment]
AFAIK the core team is pretty close to a release - there isn't a lot of stuff left on the 2.0 roadmap (found here: https://github.com/doczjs/docz/projects/1) before a 2.0 can be released.

**Comment by rakannimer** [comment]
Hey @drewlustro 

Your "timeline" is correct. Below is a response to the rest.

> late 2019 maintainers have been marching towards 2.0, but progress is relatively slow

The switch from docz v1 to v2 is a big one and we wanted to make sure that `docz` was stable and well-tested before releasing the official 2.0 version.

We're one issue away from it and it should be released in about a week's time.

> Given these observations, I've considered switching to Storybook

You know your project better and should do whatever makes you more comfortable !

> there seems to be a new burst of "release candidates" every few weeks.

As you can see in [releases](https://github.com/doczjs/docz/releases) the rc releases have been quite regular, most of them fixing issues reported here or adding features that users have requested.

> These spark hope, but the fact that we're up to 60+ candidates deep is not confidence-inspiring.

Not sure what you mean here, should we ship less frequently ?

We wanted to make sure that fixes and features were shipped as frequently as possible to our v2 users.

> These builds do not appear close to production ready. Often, a release candidate will be generated for fixing one bug or addressing one issue.

Again, I'm not sure what you mean here, we're trying to ship features and fixes as soon as we can, do you recommend that we wait until we have a given amount of features/issues to release a new version ? It seems unfair to users who could be blocked.

> Anyhow, just looking for guidance as we'd like to continue using and supporting Docz at my workplace.

Not sure I can provide much guidance regarding your specific use-case.

But if you decide to try to migrate to v2 and face any issues we'd be happy to help !

**Comment by drewlustro** [comment]
@rakannimer – Top class for the detailed response. I am very grateful, thank you.

I didn't know the team was so close to `2.0`! It would be really cool if there was a pull request with a checklist of outstanding tasks/bugs. That would not only help others (like myself) contribute on 2.0, but it would assist planning.

Thanks again for your effort <3

---

> The switch from docz v1 to v2 is a big one and we wanted to make sure that docz was stable and well-tested before releasing the official 2.0 version.

🙏 

> We're one issue away from it and it should be released in about a week's time.

❤️ 

> Again, I'm not sure what you mean here, we're trying to ship features and fixes as soon as we can, do you recommend that we wait until we have a given amount of features/issues to release a new version ? It seems unfair to users who could be blocked.

Fair point. I think ultimately, all I wanted was a roadmap or trackable issue for 2.0's progress.

> Not sure what you mean here, should we ship less frequently ?

That's pretty much  my feedback. Commit/merge into master, sure, but create release candidates for batches of fixes.
