### ISSUE TITLE
Globals not working in DocZ 2.0

### ISSUE THREAD

**Issue by MaximeHeckel** [doczjs/docz#1226]
## Bug Report
I'm trying to update from DocZ 1.3.2 to 2.0.0-rc.67 but I'm having the following issue:
I used to set "Globals"   in my mdx files through an import statement
`import '../globals.js';`

where `global.js` would be a function returning the following structure 
```
{
FOO: false,
BAR: false,
}
```

and these globals would be used by components to be rendered in the docs.
This is working without any issues in 1.3.2 but in 2.0.0.rc67 I'm getting
```
  18:9  error  'FOO' is not defined   no-undef
  35:5  error  'BAR' is not defined  no-undef
```

**To Reproduce**

1. create-docz-app my-docz-app && cd my-docz-app
2. Change the following files:

```js
// src/globals.js
const globals = {
  FOO: false,
  BAR: false,
}

module.exports = globals;
```

```js
// SomeComponent

import React from 'react';

const SomeComponent = () => {

  if (FOO) {
     console.log('FOO')
  }

  if(BAR) {
    console.log('BAR')
  }

  return <div>Test</div>
}

```

```mdx
### Some mdx content
import '../globals.js'

<SomeComponent />
```

4. Run npm run docz dev
5. See error in the terminal (the doc is not rendering so no web UI available)

**Expected behavior**

I'd expect this to work and have these globals defined and my components using these globals rendering

**Environment**

- docz version: [e.g. 2.0.0-rc.67 or 1.3.2]
- OS: macOS Catalina 10.15
- Node/npm version: Node v12.12.0 / Yarn 1.12.3 / NPM 6.11.3

cc @stefcameron

**Comment by stefcameron** [comment]
Thanks for filing this, @MaximeHeckel ! To put a little more context around these globals, they are globals we use in our code and which are defined at build time in our Webpack configurations to enable various forms of tree shaking, like when you use `process.env.NODE_ENV` in your code and then use the Webpack [Define](https://webpack.js.org/plugins/define-plugin/) plugin to give that a value of `true` or `false`.

Since there's no provided/documented way to define these globals in Docz 1.3.2 (I spent time scouring the 1.3.2 source too), what we're describing here is basically a workaround we found in order to be able to build using Docz where our MDX files reference our source code (which is the whole point!).

IMO, the `doczrc.js` file should formally allow defining globals and pass those to the underlying rollup build using https://www.npmjs.com/package/@rollup/plugin-replace

Not being able to define globals in some way is a showstopper for our project.

**Comment by MaximeHeckel** [comment]
I even tried to add a `onCreateWebpackConfig` in `gatsby-nodes.js`  and use DefinePlugin there as well but it looks like my custom gatsby-node does not end in the resulting `.docz` build folder

```
const { DefinePlugin } = require('webpack');

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    plugins: [new DefinePlugin(OUR_ENVIRONMENT_VARIABLES)]
  });
};
```

**Comment by rakannimer** [comment]
Hey @MaximeHeckel & @stefcameron 

Thanks for reporting this issue.

It's possible to add global environment variables like you would to a regular GatsbyJS app, by either using `gatsby-node.js` or by pointing to a `dotenv` file from `gatsby-config.js`

I added an example showing both here : https://github.com/doczjs/docz/tree/master/examples/with-env-variables 

In particular : 

- Usage : https://github.com/doczjs/docz/blob/master/examples/with-env-variables/src/components/Alert.jsx
- Defining from dotenv file : https://github.com/doczjs/docz/blob/master/examples/with-env-variables/.env.development & https://github.com/doczjs/docz/blob/master/examples/with-env-variables/gatsby-config.js
- Defining by modifying the webpack config : https://github.com/doczjs/docz/blob/master/examples/with-env-variables/gatsby-node.js

**Comment by MaximeHeckel** [comment]
Thank you @rakannimer I'll check that out and report back

**Comment by MaximeHeckel** [comment]
@rakannimer where exactly should the gatsby-node.js live?
I'm trying to define it at the root of my repo, but when I look at the resulting `.docz` build, I do not see my config within it.
Shall it live at the root? within the custom theme definition?

**Comment by MaximeHeckel** [comment]
Ah never mind got it to work! I see that it;'s put in a `gatsby-node.custom.js`

**Comment by MaximeHeckel** [comment]
@rakannimer I used the
> Defining by modifying the webpack config : https://github.com/doczjs/docz/blob/master/examples/with-env-variables/gatsby-node.js

solution and it worked. Thank you so much!

**Comment by stefcameron** [comment]
@rakannimer Ditto! Thank you for your quick response and sample code. That really helped unblock us on Docz. 🎉

**Comment by stefcameron** [comment]
@rakannimer I'm sure we aren't the first ones to come across this. It might help others to point this out in the Docz docs. 😄

**Comment by rakannimer** [comment]
Awesome ! Happy to hear it helped ! 

I'll make sure to add this to the docs 👍
