### ISSUE TITLE
add baseComponents fail, Cannot read property 'border' of undefined

### ISSUE THREAD

**Issue by LilyZhou36** [doczjs/docz#1227]
## Bug Report

After adding <ComponentsProvider components={baseComponents}> to get default theme from gatsby-theme-docz, it will display two errors. Errors as following:

```
TypeError: Cannot read property 'border' of undefined
borderRight
node_modules/gatsby-theme-docz/src/components/Sidebar/styles.js:31
  28 | zIndex: 1,
  29 | minWidth: 0,
  30 | maxHeight: '100vh',
> 31 | borderRight: t => `1px solid ${t.colors.border}`,

Error: [useColorMode] requires the ThemeProvider component
▶ 18 stack frames were collapsed.
(anonymous function)
  37 |  *
  38 |  * Let's warn if we find service workers in development.
  39 |  */
> 40 | if (`serviceWorker` in navigator) {

```
**To Reproduce**
To reproduce get the same error as mine, clone this themesDir example
https://github.com/doczjs/docz/tree/master/examples/with-themes-dir
Add a index.js under theme/gatsby-theme-docz/ folder, index.js content:
```
import React from 'react'
import { theme, useConfig, ComponentsProvider } from 'docz'
import { ThemeProvider } from 'emotion-theming'
import baseComponents from 'gatsby-theme-docz/src/components'

const componentsMap = {
  ...baseComponents
}

const Theme = ({ children }) => {
  const config = useConfig()
  return (
    <ThemeProvider theme={config}>
      <ComponentsProvider components={baseComponents}>
        {children}
      </ComponentsProvider>
    </ThemeProvider>
  )
}

const themeConfig = {
  colors: {
    primary: 'tomato',
    secondary: 'khaki',
    gray: 'lightslategray',
  },
}

export default theme(themeConfig)(Theme)
```

yarn, then yarn dev, you'll get error message.

Or you can clone from my sandbox
https://github.com/LilyZhou36/Docz-Sandobx
Please notify me if there's no error on your side

**Expected behavior**

Add default theme without any error

**Environment**

- docz version: next
- OS: OSX 10.13.6

![Screen Shot 2019-11-04 at 1 08 45 PM](https://user-images.githubusercontent.com/37810691/68147039-3628ac80-ff07-11e9-9b78-71fe786e9e35.png)
![Screen Shot 2019-11-04 at 1 08 52 PM](https://user-images.githubusercontent.com/37810691/68147040-3628ac80-ff07-11e9-8202-574f9e7b86ea.png)

**Comment by rakannimer** [comment]
Hey @LilyZhou36 

Your code looks correct, the problem seems to be that you're importing `ThemeProvider` from `emotion-theming` instead of `theme-ui`. 

Could you give https://github.com/LilyZhou36/Docz-Sandobx/pull/1 a try ?

**Comment by LilyZhou36** [comment]
> Hey @LilyZhou36
> 
> Your code looks correct, the problem seems to be that you're importing `ThemeProvider` from `emotion-theming` instead of `theme-ui`.
> 
> Could you give [LilyZhou36/Docz-Sandobx#1](https://github.com/LilyZhou36/Docz-Sandobx/pull/1) a try ?

Thanks a lot! That works perfectly. One more thing, I copied ThemeProvider from emotion-theming from https://www.docz.site/docs/gatsby-theme. I don't know if import from emotion-theming makes more sense there. Thanks!

**Comment by rakannimer** [comment]
>  One more thing, I copied ThemeProvider from emotion-theming from docz.site/docs/gatsby-theme.

Thanks for pointing that out ! Looks like a bug in the docs. I'll make sure to get it fixed 👍

**Comment by LilyZhou36** [comment]
@rakannimer 
Hi, I am so sorry to mention this issue again.
It seems like that the fix from last time only works partly.
If we do 'yarn docz dev', from getting page, we click its component -> Alert, the component page won't load. It will show as:
![Screen Shot 2019-11-11 at 3 26 02 PM](https://user-images.githubusercontent.com/37810691/68618726-fb3eef80-0497-11ea-983b-af23e68dba4d.png)

Thank you!

**Comment by garretteklof** [comment]
What was the resolution here? I'm having trouble creating my own theme with the examples given in the docs. I'm getting the same errors as above as well as bizarre behavior like the main container turning slate blue (#6363CE, to be exact) - I have tried multiple alternatives, like shadowing `gatsby-theme-docz/theme/index.js` directly to no avail. Only thing that seems to work  is not shadowing `gatsby-theme-docz/index.js` but overriding themeConfig in `doczrc.js` - though this is not the level of control I'm looking for. Thanks for any help in advance.

**Comment by nejcm** [comment]
There is a bug in the docs.  You need to pass `config.themeConfig` to `ThemeProvider`.
Hope this helps.

**Comment by chrystal-lyu** [comment]
> There is a bug in the docs. You need to pass `config.themeConfig` to `ThemeProvider`.
> Hope this helps.

Hi do you mean to change `config` inside `<ThemeProvider theme={config}>`  into `config.themeConfig` as follows?
```
import React from "react";
import { theme, useConfig, ComponentsProvider } from "docz";
import { ThemeProvider } from "theme-ui";
import baseComponents from "gatsby-theme-docz/src/components";

const Theme = ({ children }) => {
  const config = useConfig();
  return (
    <ThemeProvider theme={config.themeConfig}>
      <ComponentsProvider components={baseComponents}>
        {children}
      </ComponentsProvider>
    </ThemeProvider>
  );
};

const themeConfig = {
  colors: {
    primary: "tomato",
    secondary: "khaki",
    gray: "lightslategray"
  }
};

export default theme(themeConfig)(Theme);
```

Unfortunately I'm still getting the error:
`Error: [useColorMode] requires the ThemeProvider component`

How did you fix it?

**Comment by nejcm** [comment]
Hey @chrystal-lyu. Yes. You need to shadow this [index.js](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/index.js) file and you can see how it is done there. 

Regarding the useColorMode. I also had that error if I had the `theme-ui` dep. installed. Just remove it from your package.json as it is already a part of `docz` package. I did no investigate why this happens but I suspect `docz` uses a different version which is not compatible.

Hope it helps.

**Comment by chrystal-lyu** [comment]
@nejcm Thanks for sharing your solution! Unfortunately I still could not get it work after several attempts (both installing `"theme-ui": "^0.2.38"` or remove it). My  current shadowing `index.js` file which lives under my project's `src/gatsby-theme-docz` looks like this:
```
import React from 'react'
import { theme, useConfig, ComponentsProvider } from 'docz'
import { Styled, ThemeProvider } from 'theme-ui'
import baseComponents from "gatsby-theme-docz/src/components"

const Theme = ({ children }) => {
  const config = useConfig()
  return (
    <ThemeProvider theme={config.themeConfig}>
      <ComponentsProvider components={baseComponents}>
        <Styled.root>{children}</Styled.root>
      </ComponentsProvider>
    </ThemeProvider>
  )
}

const themeConfig = {
  colors: {
    primary: "tomato",
    secondary: "khaki",
    gray: "lightslategray"
  }
};

export default theme(themeConfig)(Theme)
```

And my `doczrc.js` file looks something like this:

```
export default {
  title: 'some project',
  description: 'some description',
  indexHtml: 'public/index.html',
  propsParser: false,
  ignore: ['README.md', '**/blog/**'],
  public: './public',
  themeConfig: {
    colors: {
      primary: '#3742fa',
    },
    initialColorMode: 'light',
  },
  menu: ["intro", "general"]
}
```
`Error: [useColorMode] requires the ThemeProvider component` still shows up.
Removing `themeConfig` inside `doczrc.js` doesn't help either.
Is it something I did wrong in my `doczrc.js` file?

**Comment by nejcm** [comment]
@chrystal-lyu Don't forget to uninstall it with your package manager to remove it.

My stack trace was showing that the error was happening in the `Header` component.

**Comment by nejcm** [comment]
@chrystal-lyu  I will publish my theme in the next day or two. Will paste the link here and you can take a look at it.

**Comment by chrystal-lyu** [comment]
@nejcm thank you for pointing out the correct way of uninstalling packages! It is now working after I did `yarn remove theme-ui`.  Turned out it was actually due to inconsistent `theme-ui` versions like you mentioned. Thanks again!

**Comment by nejcm** [comment]
This is my extended theme: [link](https://github.com/nejcm/docz-theme-extended). 
Good luck with yours.
