### ISSUE TITLE
Most Docz builds throw a 'gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?'

### ISSUE THREAD

**Issue by TaylorKrusen** [doczjs/docz#1229]
## Bug Report

**Describe the bug**
All Docz builds that I can find throw the following error:
`warn The gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?`
The doczEntries and doczDb nodes generate successfully, but mdx (or md) nodes do not. 

I have the same issue on the [Docz Getting Started guide](https://www.docz.site/docs/getting-started) and the [Docz tutorial on Gatsby](https://www.gatsbyjs.org/tutorial/writing-documentation-with-docz/).

**To Reproduce**

1. mkdir docz-test-app && cd docz-test-app
2. `yarn add docz@next react react-dom`
3. Add scripts to 'package.json' (build wouldn't trigger for me without this step):
```
"scripts": {
    "docz:dev": "docz dev",
    "docz:build": "docz build"
  }
```
4. Create a 'test.mdx' file and paste some content:
```
---
name: Hello world
route: /
---

# Hello world

Hello, I'm a mdx file!
```
5. Run `yarn docz dev` to start server
6. Site may successfully build, but nodes are not created
7. View error in build log
8. Navigate to http://localhost:3000/___graphql and query for 'allMdx' or 'mdx' data
9. (Optional) Create a '/src/pages' directory and place your .mdx files inside. 
  9a. (Optional) Create a 'gatsby-config.js' in the root directory and tell Gatsby where the source filesystem is:
``` 
{
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
}
```

**Expected behavior**

The Docz build should generate Docz-specific nodes *and* Gatsby nodes that contain data about mdx and md files. Without the frontmatter unique to each mdx (or md) file, you can't apply business logic elsewhere in your application.

**Environment**

- docz version: 2.0.0-rc.69
- OS: OSX 10.14.6
- Node/npm version: Node 12.1.0 / npm 6.9.0
- React: 16.11.0
- React-dom: 16.11.0

**Additional context/Screenshots**

FYI, this is similar to [this issue](https://github.com/gatsbyjs/gatsby/issues/15594). However, setting the `gatsby-source-filesystem` in `gatsby-config.js` has no impact.

**Comment by rakannimer** [comment]
Hey @TaylorKrusen 

Thanks for reporting this issue and for the detailed repro steps.

I was able to successfully reproduce it here : https://github.com/rakannimer/docz-issue-1229.

Out of curiosity, would you mind sharing what you're looking to do with the Gatsby nodes ?

**Comment by rakannimer** [comment]
Could you give `2.0.0-rc.71` a try ?

**Comment by TaylorKrusen** [comment]
Thanks, Rakan!! 

I'm creating documentation from some tools that are automatically generating (somewhat messy) markdown. Rather than trying to get the generator to spit out well-made mdx files, I'm trying to create data components so I can query for the specific markdown data I need then feed it into a different mdx file. 

TBH, I'm not sure whether this is the right approach, but I'll be sure to revisit with an update later this week. It's been a challenging use case!
