### ISSUE TITLE
Can't find variable: acornJsxMap in doc dev

### ISSUE THREAD

**Issue by ycjcl868** [doczjs/docz#1234]
## Bug Report

**Describe the bug**

![image](https://user-images.githubusercontent.com/13595509/68367604-041a8300-0171-11ea-9ca0-8e06dfedfe24.png)

**Comment by rakannimer** [comment]
Hey @ycjcl868 

Could you please provide more information like how to reproduce the issue you're getting ? It's hard to help with the amount of information you provided.

**Comment by ycjcl868** [comment]
reproduce in the mobile device container, not easy to reproduce.
It's ok in build mode, but error in dev.
