### ISSUE TITLE
Left navigation menu order

### ISSUE THREAD

**Issue by gfazioli** [doczjs/docz#1236]
## is there a way to order the left menu?

**Version**
The latest `v2.0.0-rc.70`

**Description**

I tried with

```
---
name: Changelog
route: /changelog
order: 10000
---
```
but it seems not working

**Comment by rakannimer** [comment]
Hey @gfazioli 

Thanks for reporting this issue.

Unfortunately, `order` property support was removed in version 1 but I think we should support it again as it can be very useful. 

To do that we'll probably need to do some changes to `core/docz/src/hooks/useMenus.ts` 

Let's use this issue to track progress on it. 

Meanwhile, you could shadow the Sidebar component (https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Sidebar/index.js) and add your own sorting to the menus from useMenus before rendering them.
