### ISSUE TITLE
eslintrc in project doesn't apply to docz project.

### ISSUE THREAD

**Issue by theo-mesnil** [doczjs/docz#1237]
Hello :)

I have an issue with gatsby and eslint.
I have an eslintrc in my repo directory but when i do an docz dev i have an eslint from gatsby, why ?

![Capture d’écran 2019-11-07 à 17 12 51](https://user-images.githubusercontent.com/50322149/68406448-2668cc80-0182-11ea-9df4-6fd053c08c64.png)

And on my file, this line is disable for eslint.

Thanks.

**Comment by rakannimer** [comment]
Hey @theo-mesnil,

Could you share a repro repo or failing that :

- the offending line in MarkdownEditor/index.js
- your package.json

**Comment by feychenie** [comment]
Hello guys, I don't know if this is related or not, but according to the gatsby docs (https://www.gatsbyjs.org/docs/eslint/#how-to-use-eslint), putting an empty .eslintrc at the root of the project should disable eslint completely, but it doesn't seem to be the case in docz.

**Comment by ejuo** [comment]
@feychenie, yes, faced the same problem .eslintrc in root folder doesn't  depend on .eslintrc in .docz folder.
Temporarily, you can use .eslintignore file for disable eslint.

**Comment by rakannimer** [comment]
@ejuo do you think this can be solved by copying `.eslintrc` to `.docz` folder ?

**Comment by ejuo** [comment]
@rakannimer I think yes.

**Comment by rakannimer** [comment]
Ok then, this should be relatively easy to solve, let's consider this as a docz bug.

**Comment by Dangoo** [comment]
Hey @theo-mesnil ,

since @rakannimer fixed that in #1254 and it was released in stable release v2.1.0 I consider this issue done. Please feel free to comment in case we missed something.
