### ISSUE TITLE
Custom document properties in useMenus() hook

### ISSUE THREAD

**Issue by NicolaiF** [doczjs/docz#1238]
At the start of every mdx-document, one has the ability to write custom properties for the chosen page. This is useful, but these properties, are only accessible through the useCurrentDoc() hook (as I can see). 

The feature request is to have these accessible through the useMenus() hook as well, so when implementing a menu for your site, one can customize how each `MenuItem` should appear based on these custom properties.

**Comment by rakannimer** [comment]
Hey @NicolaiF,

Thanks for reporting this, I agree with you it would be a useful feature to have.

To enable it we'll need to delete the `entryAsMenu` function here : https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useMenus.ts#L12-L16

And remove the array mapping here : https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useMenus.ts#L19 and here : https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useMenus.ts#L29

And last, probably fix a type "error" here : https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useMenus.ts#L141

Would you like to give a PR a shot ? 

If not, no problem I can get to it later 👍

**Comment by NicolaiF** [comment]
I will try it over the weekend, thanks for showing me the necessary steps needed!

**Comment by rakannimer** [comment]
Awesome ! Feel free to join the docz slack workspace if you have any questions : https://join.slack.com/t/docz-workspace/shared_invite/enQtNzc4ODc2ODA3NzUxLWI0ZmYwY2NhNjhkNDFjN2UzYzlmMDcwZjQyZGY4MWQ1NmQwZDVlZDE4MmE3N2I4MWRjZTAxZjY4ODk4NGMzZjg
