### ISSUE TITLE
Component not importing correctly into mdx file

### ISSUE THREAD

**Issue by tylerthehaas** [doczjs/docz#1243]
## Bug Report

**rc 72 reports an error that imported component is undefined**

using release candidate 72 my imported component is undefined however using release candidate 58 everything works fine.

**To Reproduce**

https://github.com/tylerthehaas/prism-ui-monorepo

1. install rc.72
2. go to `Thing` component
3. you'll see component undefined error
4. install rc.58
5. everything will work

```mdx
### Some mdx content

<IDontExist />
```

4. Run npm run docz dev
5. See error in browser

![image](https://user-images.githubusercontent.com/11150235/68563686-8de57d00-040b-11ea-8cca-ab19cb666508.png)

**Expected behavior**

should be able to find imported component

**Environment**

- docz version: [2.0.0-rc.72]
- OS: OSX 10.14.4
- Node/npm version: node 12.8.1 yarn 1.19.1

**Comment by rakannimer** [comment]
Hey @tylerthehaas 

Thanks for reporting this issue and providing a repro. 

The problem seems to be that you have the docz-theme-default as a dependency. 

Removing it solves the problem for me. 

I'll make sure to add this step to the migration guide.

**Comment by tylerthehaas** [comment]
Works for me as well! Thanks!

**Comment by rakannimer** [comment]
Thanks for the suggestion ! I think it was added though here : https://github.com/doczjs/docz/blob/master/MIGRATION_GUIDE.md#docz-theme-default-removed

Do you think we should make it more explicit ?

**Comment by MaluNoPeleke** [comment]
The documentation about that is not properly linked anymore on the main website https://www.docz.site/docs/getting-started-> https://www.docz.site/docs/migration-guide and on https://www.docz.site/docs/document-settings -> https://www.docz.site/docz/creating-your-themes#using-documents-settings

**Comment by tylerthehaas** [comment]
no I think thats pretty clear just didn't see that section of the docs since I was setting up a new project instead of migrating.
