### ISSUE TITLE
Base path for docz in an existing Gatsby Site

### ISSUE THREAD

**Issue by XpitifulApples3** [doczjs/docz#1248]
I have a landing page with an existing gatsby project, i want to add the docz routes in the `/docs` path prefix.
I am using the `gatsby-theme-docz@next` package.
I tried using the base property but the docs are still served in `/`.
The only way i found is adding the route prefix in every .mdx file, but this is repetitive and prone to error.
Is there a way to add a global pathPrefix to all the docs?

**Comment by apdrsn** [comment]
I'm experiencing the same thing.
To add to that, I also experience that sometimes reloading when updating code, causes the `/docs`page to hijack my frontpage.

- I'm also using `/docs/` as my `base` option.
- welcome.mdx has `route` option set to `docs/`
- `pages/index.js`is a pure gatsby index – which sometimes is being hijacked.

**Comment by callil** [comment]
I'm experiencing this exact thing. If I directly navigate to the sub-page it works, but `/` is broken.
