### ISSUE TITLE
Importing component for playground under different folder

### ISSUE THREAD

**Issue by moopmonster** [doczjs/docz#1253]
## Question
I'm currently trying to import a component from my react project to use with Playground. 

My project directory structure is as below: 
<pre>
/root/
   |__ /react/
          |__src/
               |__Components/
               |__etc/
   |__ /docz/
          |__src/
               |__GettingStarted/
               |__Testing/
               |__Components/
</pre>
When I try to import the component in docz mdx file, it gives "Module not found: Can't resolve '../../../react/src/Components/blah' in 'c:\path\to\docz\src\Components'. 

I've tried the below variants : 
<pre>
import { Playground } from 'docz' 
import {blah} from './react/src/Components/blah'
import {blah} from '../../react/src/Components/blah'
import {blah} from '../../../react/src/Components/blah'
import {blah} from '../../../../react/src/Components/blah'
</pre>
but to no avail. Can't help but feel as though  I'm missing something. Is it possible to have such a structure and if yes, what additional doczrc.js settings would I need? 

Would setting the `src` key in doczrc.js work, and is it possible to set multiple sources here, so as not to add the entire root directory which also has other folders that are unrelated? Thank you.

**Comment by moopmonster** [comment]
The imports can be found after I set `typescript=true` in `doczrc.js`, however, I am now getting the error message 
<pre>
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
</pre>
I will upgrade to docz v2 to see if it helps.

**Comment by rakannimer** [comment]
Hey @moopmonster 

If you could upgrade to v2 and report back if this is happening it would be great. 

Usually for these kinds of monorepos we recommend using Lerna and/or yarn workspaces to be able to easily access different modules. 

Take a look at the following examples in case they're helpful :
 
- https://github.com/doczjs/docz/tree/master/examples/monorepo-package
- https://github.com/doczjs/docz/tree/master/examples/monorepo-separate-docs
- https://github.com/doczjs/docz/tree/master/examples/monorepo

**Comment by moopmonster** [comment]
Hi @rakannimer , 

I've tried V2 and followed closely the example of monorepo-separate-docs. I was able to get a sample working with the folder hierarchy I wanted using yarn. Thanks muchly for the pointers!

However, similar to #1239, I encountered some `mdx-scopes-dir` error when I tried to use gatsby-node.js to do: 
`import Alert from 'Alert'`
instead of 
`import Alert from 'newtest/src/components/Alert.tsx'`
in docs/src/components/Alert.mdx 

The error is : 
<pre>
ERROR #98123  WEBPACK 
Generating SSR bundle failed
Can't resolve 'Alert.tsx' in 'D:\docz_issue_1253\docs\.docz\.cache\caches\gatsby-plugin-mdx\mdx-s copes-dir'
File: .cache\caches\gatsby-plugin-mdx\mdx-scopes-dir\5e27e31a5864ef4a447c4445011422d9.js
</pre>

It can be reproduce here : https://github.com/moopmonster/docz_issue_1253 

I'm afraid my lack of understanding of how docz works, and how I should define the other components folder relative to the doczjs is causing me much headache in getting things working. 

Another issue is <Props of={Alert} /> does not show the props in docz. I must be missing something  because it worked just fine in the monorepo-separate-docs example. 

Thank you.

**Comment by rakannimer** [comment]
I looked at the repo and found two problems that were causing it to fail : 

gatsby-node is copied to and used in .docz directory so you need to add an extra `..` before the path.

https://github.com/moopmonster/docz_issue_1253/pull/1/commits/349cb15834951eacd93b3689945ecae2a17d94bd

 
ts props parser fails when there is no tsconfig.json file at the root of the docs directory I added one and pointed it to the right place and it created the props table as expected : 

https://github.com/moopmonster/docz_issue_1253/pull/1/commits/b59c87d72d81d92eb9655d7fdc5fd07ae854c4a6

Docs should make this clearer, I'll start by updating the examples 👍 

If you try merging this PR https://github.com/moopmonster/docz_issue_1253/pull/1 it should work as expected.

**Comment by moopmonster** [comment]
Hi! Thanks for your speedy response. 

I'm still playing around with the `gatsby-node.js` settings and found that  : 

1) `path.resolve(__dirname, "../../newtest"),` 
does not work with 
`import Alert from 'src/components/Alert'` in Alert.mdx, 

but :

2) `path.resolve(__dirname, "../../newtest/src"),` 
works : 
`import Alert from 'components/Alert'` 

and then the solution you've provided : 

3) `path.resolve(__dirname, "../../newtest/src/components"),` 
works with 
`import Alert from 'Alert'` 

Is there anything extra I need to do to get 1) working?

**Comment by rakannimer** [comment]
> path.resolve(__dirname, "../../newtest"),
> does not work with
> import Alert from 'src/components/Alert' in Alert.mdx,

Yep, this is weird, if you rename the directory to anything other than `src` it works as expected 🤔 

I'm not sure why this happens !

**Comment by kkor** [comment]
I was having problems with similar symptoms and I was 100% sure the import url is correct. What fixed it: deleting the .docs/.cache folder.
