### ISSUE TITLE
How do I make a multilingual MDX Blog?

### ISSUE THREAD

**Issue by ysfzrn** [doczjs/docz#1255]
## Question

**Description**
I want to add multi language support for my docs. Have any practice way for do this ? 
I suppose, best example for gatsby is this https://github.com/gatsbyjs/gatsby/tree/master/examples/using-i18n.

Should I implement like this project for docz ?

**Comment by rakannimer** [comment]
Hey @ysfzrn 

I would probably go with creating different markdown files for each. 

Or alternatively you could write a component that takes in a prop with the language and use any i18n solution you want.

So you'd have something like : 

```jsx
// pageone.en.mdx

---
name: Page One
route: /en/page-one
---

<PageOne language="en" />
```
and another language

```jsx
// pageone.tr.mdx
---
name: Birinci Sayfa
route: /tr/birinci-sayfa
---

<PageOne language="tr" />
```

I haven't written any multi-lingual sites with docz so I'm not sure this is the best solution. Let us know if you find something that works well for you 👍

**Comment by ysfzrn** [comment]
You are right @rakannimer . 
I have overwritten Sidebar and Header component via gatsby-theme-docz and I have created different markdown files like you said. Thanks for your feedback.
