### ISSUE TITLE
Webpack dev server version is higher than react-scripts

### ISSUE THREAD

**Issue by ronaklalwaniii** [doczjs/docz#1256]
## Bug Report

After installing the latest v2.0.0-rc.74, I am getting the following error in my terminal:
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.
```
How to fix this? I am not able to run my react project after upgrading to the latest version.
You can check the attached screenshot.

Regards

![docz-bug](https://user-images.githubusercontent.com/44769573/68848015-97b1fd80-06f5-11ea-84a9-42c0bd2d2e4a.PNG)

**Comment by rakannimer** [comment]
Hey @ronaklalwaniii 

I tried reproducing with a fresh install but I couldn't. 

Could you try uninstalling `docz-theme-default` and trying again ?
