### ISSUE TITLE
How to add the title to the top of the sidebar?

### ISSUE THREAD

**Issue by MaluNoPeleke** [doczjs/docz#1260]
## How to add the title to the top of the sidebar?

**Description**
I would like to add the title and/or a logo/image to the top of the sidebar (above the search) but I don't know how to do it.

**Comment by gfazioli** [comment]
You should add in your `devDependencies` the `"gatsby-theme-docz": "^2.0.0-rc.75",` and run `yarn` again. Then you have to create `src/gatsby-theme-docz/components/Logo/index.js` and also `src/gatsby-theme-docz/components/Logo/styles.js`

```jsx
// src/gatsby-theme-docz/components/Logo/index.js
import { jsx, Flex } from 'theme-ui'
import { Link, useConfig } from 'docz'

import * as styles from './styles'

export const Logo = () => {
  const config = useConfig()
  return (
    <div>
      <Flex aligmItems="center" sx={styles.logo} data-testid="logo">
        <Link to="/" sx={styles.link}>
          {config.title}
        </Link>
      </Flex>
      <p sx={styles.description}>{config.description}</p>
    </div>
  )
}
```
```js
// src/gatsby-theme-docz/components/Logo/styles.js
export const logo = {
  letterSpacing: '-0.02em',
  fontWeight: 600,
  fontSize: 4,
}

export const link = {
  fontWeight: 600,
  color: 'header.text',
  textDecoration: 'none',
  ':hover': {
    color: 'primary',
  },
}


export const description = {
  fontWeight: 100,
  color: "#888",
  margin: 0,
  fontSize: "12px"
}
```

**Comment by MaluNoPeleke** [comment]
I did that already but that shows the logo in the header but if I scroll down it is not visible anymore.
That's why I wanted to move the title to the top of the sidebar while a logo could be still visible in the header.
Similar to the [lightning design system](https://www.lightningdesignsystem.com/):
![image](https://user-images.githubusercontent.com/1446541/68950867-508f3f80-07bd-11ea-831f-9ac43517f901.png)

**Comment by gfazioli** [comment]
you could try by adding `src/gatsby-theme-docz/wrapper.js`

```jsx
// src/gatsby-theme-docz/wrapper.js
import "./styles/global.css"
import * as React from 'react'

const Wrapper = ({ children }) => <React.Fragment>{children}</React.Fragment>
export default Wrapper
```

along with a `src/gatsby-theme-docz/styles/global.css`

```css
html body main [data-testid='header'] {
  position: fixed;
  width: 100vw;
  z-index: 999;
}

html body main [data-testid='header']+div {
  padding-top: 70px;
}
```

**Comment by MaluNoPeleke** [comment]
Thanks, that doesn't look nice in the mobile view and also makes it hard to scroll in the sidebar for long pages/sidebar contents:

![image](https://user-images.githubusercontent.com/1446541/68953716-c9dd6100-07c2-11ea-9be9-f70726a01172.png)

![image](https://user-images.githubusercontent.com/1446541/68953739-d5308c80-07c2-11ea-83f0-4f71b749f5aa.png)

**Comment by gfazioli** [comment]
yep, obviously you should add some `@media` alignment there

**Comment by MaluNoPeleke** [comment]
Thanks for the suggestion but this solution just makes the header sticky instead of including the title at the top of the sidebar.

**Comment by rakannimer** [comment]
Hey !

As @gfazioli suggested usually to place your own logo, you would need to shadow the logo component.

But to get something like the lightning design system site you referenced you would need to shadow the Sidebar (to position the logo inside it) and the Header to remove it. 

You can find an example of doing that here : https://github.com/doczjs/docz/tree/master/examples/logo-in-sidebar

**Comment by MaluNoPeleke** [comment]
Great, thanks a lot, works as expected!

Another question related to the documentation of design systems: Is it easily possible to add tabs for pages (as requested in #625)?
If yes, how to?

**Comment by rakannimer** [comment]
Hmmm, I can't think of an "easy" way to do this. 

But since MDX supports all JSX I guess you could build this on your site with a library to help with tabs. Maybe something like [react-tabs](https://github.com/reactjs/react-tabs) ? 

This could be a nice feature to add to docz if we can think of a nice API for it.

**Comment by rakannimer** [comment]
I think this issue should be closed as the main subject has been resolved. 

Feel free to open another if you face another problem 👍
