### ISSUE TITLE
Search SVG icon is not visible on FireFox

### ISSUE THREAD

**Issue by gfazioli** [doczjs/docz#1262]
## Bug Report

**Describe the bug**

The search SVG icon is not visible on FireFox

**Expected behaviour**

![image](https://user-images.githubusercontent.com/432181/68953827-03ae6780-07c3-11ea-83c4-e655179449ec.png)

**Environment**

- docz version: [v2.0.0-rc.75]
- gatsby-theme-docz: [v2.0.0-rc.75]
- OS: [OSX 10.15.1 ]
- FireFox [70.0.1 (64 bit)]

**Additional context/Screenshots**

Current behaviour on FireFox

![image](https://user-images.githubusercontent.com/432181/68954006-67d12b80-07c3-11ea-86c7-c8b734438b6a.png)

**Suggested Fix**

The issue seems on the `display: flex` for the `data-testid="nav-search"`
With `display: inline-flex` it works fine

**Comment by rakannimer** [comment]
Thanks @gfazioli for catching this and suggesting a fix ! 

I pushed a fix to master and it will be included with the next release 👍
