### ISSUE TITLE
Problems when using with NX monorepo

### ISSUE THREAD

**Issue by stramel** [doczjs/docz#1264]
## Bug Report

**Describe the bug**

Failing to compile with just a basic library generated.

**To Reproduce**

Please try to build a small repo with a repro of your problem and provide a link to it.

Doing that allows more people to quickly help you.

If you can't provide a repo then provide clear steps describing how to reproduce the issue.

1. `yarn create nx-workspace`
2. Enter a workspace name
3. Select empty workspace
5. `npm i -g @nrwl/cli`
6. `yarn add -D @nrwl/react`
7. `nx g @nrwl/react:lib test`
8. `nx g @nrwl/react:component --project=test button`
9. Add the following mdx next to the button component file

```mdx
---
name: Button
route: /
---

import { Playground, Props } from 'docz'
import { Button } from './'

# Button

<Props of={Button} />

## Basic usage

<Playground>
  <Button>Click me</Button>
  <Button kind="secondary">Click me</Button>
</Playground>
```

10. `yarn add -D docz@next` 
11. Run `npm run docz dev`
12. See the errors in the console

```shell
Building app
warn Configuring yargs through package.json is deprecated and will be removed in the next major release,

 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-emotion" plugin declared in "/Users/michael/Projects/coolfire/coolfire/node_modules/gatsby-theme-docz/gatsby-config.js".

Tried looking for an installed package in the following paths:
 - /Users/michael/Projects/coolfire/coolfire/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/coolfire/coolfire/node_modules/gatsby/dist/bootstrap/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/coolfire/coolfire/node_modules/gatsby/dist/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/coolfire/coolfire/node_modules/gatsby/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/coolfire/coolfire/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/coolfire/node_modules/gatsby-plugin-emotion
 - /Users/michael/Projects/node_modules/gatsby-plugin-emotion
 - /Users/michael/node_modules/gatsby-plugin-emotion
 - /Users/node_modules/gatsby-plugin-emotion
 - /node_modules/gatsby-plugin-emotion

not finished open and validate gatsby-configs - 0.567s
```

after installing `gatsby-plugin-emotion` the error comes from it trying to compile my `README.md` file.

```shell
Building app
warn Configuring yargs through package.json is deprecated and will be removed in the next major release,
success open and validate gatsby-configs - 0.565s
success load plugins - 0.325s
success onPreInit - 0.003s
success initialize cache - 0.008s
success copy gatsby files - 0.036s
success onPreBootstrap - 0.030s

 ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Expected corresponding JSX closing tag for <img> (9:102)
```

Followed by a bunch of these errors

```shell
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'theme-ui' in '/Users/michael/Projects/coolfire/coolfire/node_modules/gatsby-theme-docz/src'

File: ../node_modules/gatsby-theme-docz/src/index.js
```

**Expected behavior**

It should spin up the local docz environment

**Environment**

- docz version: `2.0.0-rc.75`
- OS: `OSX 10.15.1`
- Node/npm version: `12.13.0`/`6.12.0`
- Yarn version: `1.19.1`

**Comment by stramel** [comment]
Not sure who to ping here, @rakannimer can you point me in the right direction or give me some help. Would love to use this in my project.

**Comment by stramel** [comment]
Finally got it to work. However, it was still attempting to parse my `README.md` file despite setting `files` to `**/*.mdx` and `src` to a folder that doesn't contain that file.

Also, found that I *had* to have an `index.ts` file inside my component folder.

**Comment by rakannimer** [comment]
Sorry I couldn't help because I couldn't recreate your setup due to a bad connection, it would stop midway.

If you update to next tag, your readme will be ignored by using src

```
yarn add docz@next
```

You can also use the ignore array to tell docz not to include your readme if you don't want to update but it will still attempt to parse it.

**Comment by alchi126** [comment]
Hi @stramel, could you provide some pointers on how were you able to resolve? Running into very similar issues trying to use gatsby-theme-docz in a Rush monorepo. All signs indicate that webpack has trouble resolving sub-dependencies, despite providing paths to find root level node_modules.

**Comment by stramel** [comment]
@alchi126 We're using `^2.3.0-alpha.3` version of Docz. Here are my files:

```js
// /doczrc.js
export default {
  typescript: true,
  ignore: ['**/README.md'],
}
```

```js
// /gatsby-config.js
module.exports = {
  plugins: ['gatsby-plugin-svgr'],
}
```

```js
// /gatsby-node.js
const TSPathsPlugin = require('tsconfig-paths-webpack-plugin')

exports.onCreateWebpackConfig = ({ actions }) => {
  actions.setWebpackConfig({
    resolve: {
      plugins: [new TSPathsPlugin({ configFile: '../tsconfig.json' })],
    },
  })
}
```

I did install `yarn add -D gatsby-plugin-emotion gatsby-plugin-svgr tsconfig-paths-webpack-plugin`.

Mostly, it just took time of debugging and trying different things.
