### ISSUE TITLE
How to style inline code from backticks

### ISSUE THREAD

**Issue by DannyAziz** [doczjs/docz#1265]
## Question

I have some code that is inline a paragraph, using backticks (``) it is wrapped with <code></code> however I can't change the styling

**Comment by rakannimer** [comment]
Hey,

What kind of styling are you looking to do inside the code container ? 

If you want to override the react-prism-renderer prism-ui theme you can shadow files in this folder : https://github.com/doczjs/docz/tree/master/core/gatsby-theme-docz/src/theme/prism

You can also shadow the `Code` component that is used when backticks are provided in your markdown here : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Code/index.js

**Comment by haohello** [comment]
I also came across this issue,  the inline code within the back tick simply doesn't work.  Say for example,  github markdown would automatically style the inline code, but there is no such styling in the docz. 

The `Col` lets you specify column widths across 5 breakpoint sizes (xs, sm, md, large, and xl). 
For every breakpoint, you can specify the amount of columns to span, 
or set the prop to `<Col lg={true} />` for auto layout widths.

Simply want to have the functionality like [this specification](https://github.com/mdx-js/specification/issues/7).

**Comment by DannyAziz** [comment]
@rakannimer Showing the `Code` component allows me to make changes to code blocks that I insert in my markdown using `<code></code` 

But it does nothing for backticks provided in the markdown

**Comment by DannyAziz** [comment]
I found a method, follow this in the docs: https://www.docz.site/docs/gatsby-theme#theme-ui-integrated

I added this to my `doczrc.js`:
```
  themeConfig: {
    styles: {
      inlineCode: {
        bg: COLOR
      }
    }
  }
```

but it required me to go through the `gatsby-theme-docz` repo to work out that the key I was looking for was `inlineCode` and not `code`

**Comment by DannyAziz** [comment]
I've come up with a workaround

Unfortunately creating my own theme like the docs says to do (https://www.docz.site/docs/gatsby-theme#theme-ui-integrated) didn't work for me

But I was able to shadow `theme/modes` and add a new object for `inlineCode` like so:
```
import * as colors from 'gatsby-theme-docz/src/theme/colors'
import prismDark from 'gatsby-theme-docz/src/theme/prism/dark'
import prismLight from 'gatsby-theme-docz/src/theme/prism/light'

export const light = {
    ...colors,
    primary: colors.blue,
    text: colors.grayDark,
    muted: colors.gray,
    link: colors.blue,
    background: colors.white,
    border: colors.grayLight,
    sidebar: {
        bg: colors.white,
        navGroup: colors.grayDark,
        navLink: colors.grayDark,
        navLinkActive: colors.blue,
        tocLink: colors.gray,
        tocLinkActive: colors.grayExtraDark,
    },
    header: {
        bg: colors.grayExtraLight,
        text: colors.grayDark,
        border: colors.grayLight,
        button: {
        bg: colors.blue,
        color: colors.white,
        },
    },
    props: {
        bg: colors.grayUltraLight,
        text: colors.grayDark,
        highlight: colors.blue,
        defaultValue: colors.gray,
        descriptionText: colors.grayDark,
        descriptionBg: colors.white,
    },
    playground: {
        bg: colors.white,
        border: colors.grayLight,
    },
    blockquote: {
        bg: colors.grayExtraLight,
        border: colors.grayLight,
        color: colors.gray,
    },
    prism: {
        ...prismLight,
    },
    inlineCode: {
        bg: 'black',
        color: 'white'
    }
}

export const dark = {
    ...colors,
    primary: colors.skyBlue,
    text: colors.grayExtraLight,
    muted: colors.gray,
    link: colors.skyBlue,
    background: colors.grayExtraDark,
    border: colors.grayDark,
    sidebar: {
        bg: colors.grayExtraDark,
        navGroup: colors.gray,
        navLink: colors.grayLight,
        navLinkActive: colors.skyBlue,
        tocLink: colors.gray,
        tocLinkActive: colors.grayLight,
    },
    header: {
        bg: colors.dark,
        text: colors.grayLight,
        border: colors.grayDark,
        button: {
        bg: colors.skyBlue,
        color: colors.white,
        },
    },
    props: {
        bg: colors.dark,
        text: colors.gray,
        highlight: colors.skyBlue,
        defaultValue: colors.grayDark,
        descriptionText: colors.gray,
        descriptionBg: colors.grayExtraDark,
    },
    playground: {
        bg: colors.dark,
        border: colors.grayDark,
    },
    blockquote: {
        bg: colors.grayDark,
        border: colors.gray,
        color: colors.gray,
    },
    prism: {
        ...prismDark,
    },
    inlineCode: {
        bg: 'white',
        color: 'black'
    }
}
```

and then in my `doczrc.js`, I did the following:
```
  themeConfig: {
    styles: {
      inlineCode: {
        bg: 'inlineCode.bg',
        color: 'inlineCode.color'
      }
    }
  }
```

**Comment by MaluNoPeleke** [comment]
By default using a tickmark changes the style correctly to code but doesn't use a grey background color.
This should be fixed.
