### ISSUE TITLE
How to resolve the baseUrl which is configured in jsconfig/tsconfig file?

### ISSUE THREAD

**Issue by haohello** [doczjs/docz#1266]
## Question
Not able to resolve the absolute import as per the baseUrl configured in the jsconfig/tsconfig.

**Description**

Since all my components are imported with the absolute path as per the baseUrl configured in the tsconfig.json, and this will result in a bunch of errors of not being able to resolve those related files.

So any ideas how this would be resolved?

**Comment by haohello** [comment]
Sorry to get back here again. After digging more with the gatsby doc and the information in the docz repo, I finally found [this link to help me resolve the issue ](https://github.com/doczjs/docz/tree/master/examples/webpack-alias)(which requires adding a gatsby-node.js in the project root and a onCreateWebpackConfig method inside ).

**Comment by rakannimer** [comment]
Hey @haohello 

Thank you for reporting the issue and looking for the solution in the examples.

I will add a page to the docz site explaining this and will close this issue when I do 👍

**Comment by rakannimer** [comment]
Added here : https://www.docz.site/docs/customizing-webpack-config 

Please feel free to re-open if the issue re-occurs.
