### ISSUE TITLE
Props component doesnt work with Typescript when tsconfig is missing

### ISSUE THREAD

**Issue by tylerthehaas** [doczjs/docz#1267]
## Bug Report

**Prop component doesn't display table when used with typescript**

If I have typescript set to true in doczrc.js then the table doesn't appear but does if set to false and importing from jsx file.

**To Reproduce**

https://github.com/tylerthehaas/prism-ui-monorepo

**Expected behavior**

should display table of my props.

**Environment**

- docz version: 2.0.0-rc.72
- OS: OSX 10.14.4
- Node/npm version: node 12.8.1/npm 6.9.0

**Comment by rakannimer** [comment]
Hey @tylerthehaas 

Is this still occurring, looking at your repo it looks like you were able to get it to work for the Thing component. 

Is there something else that is not working ?

**Comment by tylerthehaas** [comment]
nope. This works. I ended up using the cli command to generate the typescript example inside my monorepo. As far as I could tell the only thing different that changed is the example from docz/example has a tsconfig that I didn't have because I was using a monorepo approach and my tsconfig was in a directory outside of where docz was looking. If this is the reason it wasn't working before maybe we could add a way in the config to tell docz where the tsconfig file is located or at least add some documentation to let users know that there has to be a tsconfig in the root directory of their docz project.
