### ISSUE TITLE
Body doesn't turn into dark when dark mode is selected

### ISSUE THREAD

**Issue by smakosh** [doczjs/docz#1268]
## Bug Report

Body doesn't turn black when it's turned on

**To Reproduce**

https://github.com/smakosh/unnamed-website

**Expected behavior**

This shouldn't happen, background has to be dark

<img width="1675" alt="Screen Shot 2019-11-17 at 19 17 02" src="https://user-images.githubusercontent.com/20082141/69011839-19f92680-096f-11ea-975d-fff8b0cedfac.png">

**Environment**

- docz version: `2.0.0-rc.68`
- OS: macOS Catalina
- Node/npm version: `12.13.0`

**Comment by rakannimer** [comment]
Hey @smakosh 

Could try updating to the latest docz version : 

```
yarn add docz@next
```

**Comment by smakosh** [comment]
Nope the issue is still occurring
> docz version: `2.0.0-rc.75`

**Comment by rakannimer** [comment]
Hey @smakosh 

Which browser are you seeing this behavior in ? 

Looks like it's working as expected on chrome, firefox and brave on my end when I open https://unnamed.smakosh.com/buttons#disabled .

<img width="1412" alt="unnamed-website dark mode example" src="https://user-images.githubusercontent.com/1270909/69130548-5d5fac00-0ab9-11ea-9626-ef8d5d5de249.png">

**Comment by smakosh** [comment]
I'm on Chrome, macBook Pro 15"
You can see the white box on the screenshot you took

**Comment by rakannimer** [comment]
Ok so you're talking about the additional line of whitespace to the Playground NOT the issue you referenced at first 👍

**Comment by smakosh** [comment]
Oh I see, thanks @rakannimer!
