### ISSUE TITLE
React is not defined - when using Fragment JSX syntax(<>) inside Playground with `typescript: true`

### ISSUE THREAD

**Issue by aibolik** [doczjs/docz#1270]
## Bug Report

**Describe the bug**

I get error `React is not defined` when using Fragment JSX syntax(`<></>`) inside `Playground` component and with `typescript: true` in `doczrc.js`.

**To Reproduce**

[Here](https://github.com/aibolik/docz-v2-react-fragment-issue-repro) is a reproduction with docz basic example. [This file](https://raw.githubusercontent.com/aibolik/docz-v2-react-fragment-issue-repro/master/src/components/Alert.mdx)

or steps:

1. create-docz-app my-docz-app && cd my-docz-app
2. add `typescript: true` in `doczrc.js`
3. in `Alert.mdx` wrap `Alert` component inside `Playground` with React Fragment using JSX syntax:

```mdx
<Playground>
  <>
    <Alert>Some message</Alert>
  </>
</Playground>
```

4. Run npm run docz dev
5. See error in browser

```shell
ReferenceError: React is not defined
```

**Expected behavior**

Component renders without errors in React Fragment with JSX syntax.

**Environment**

- docz version: [e.g. 2.0.0-rc.75]
- OS: [e.g. OSX 10.14.16]
- Node/npm version: 10.16.3/6.9.0

**Additional context/Screenshots**

It works if I use `React.Fragment` and works if `typescript` options is not set to `true`. TypeScript should already come with the support for JSX fragment syntax starting from `2.6.2`, according to [docs here](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#typescript). Maybe it is related to how `Playground` parses the code. 🤷‍♂ 

Here is a screenshot from browser error:

![image](https://user-images.githubusercontent.com/7687108/69226529-96168880-0b80-11ea-98e9-6160f318d207.png)

**Comment by techniq** [comment]
I'm seeing this as well, and switched to using `React.Fragment` for now.

**Comment by rakannimer** [comment]
Thanks for reporting ! 

This looks related to Gatsby, I opened an issue for it here : https://github.com/gatsbyjs/gatsby/issues/20030

**Comment by aibolik** [comment]
Hey, should it still stay active until the related issue in Gatsby not resolved?

**Comment by rogeliorv** [comment]
Still happening in August 2020

**Comment by yokiijay** [comment]
Still happening in March 2021
![image](https://user-images.githubusercontent.com/24253244/112274902-fa3be600-8cb9-11eb-983a-6dbdbc5c2282.png)
