### ISSUE TITLE
Getting Started: Could not locate an example named "basic"

### ISSUE THREAD

**Issue by giulianok** [doczjs/docz#1274]
## Bug Report

I tried creating an app with `create-docz-app`.

### Reproduce

Run `npx create-docz-app my-docz-app`

```shell
npx: installed 1 in 2.324s
Could not locate an example named "basic". Please check your spelling and try again.
```

**Environment**

- docz version: "latest"
- OS: OSX 10.14.5
- Node/npm version: v10.13.0 / 6.4.1

**Comment by rakannimer** [comment]
Hey @giulianok 

Could you try again ? I'm not sure why it wasn't finding the git repo and can't reproduce it anymore.

**Comment by LPink777** [comment]
I have the same problem
