### ISSUE TITLE
Enumerated types should not be converted to lowercase

### ISSUE THREAD

**Issue by angular-moon** [doczjs/docz#1278]
## Bug Report
Enumerated types should not be converted to lowercase
**Describe the bug**

export interface AlertProps {
  /**
   * Set this to change alert kind
   * @default info
   */
  kind: "INFO" | "POSITIVE";
}

<Props> display  "info" | "positive"

**Comment by rakannimer** [comment]
Hey @angular-moon 

Thanks for reporting this issue.

It should be fixed by [this commit](https://github.com/doczjs/docz/commit/8f7b9491cf1572f59388b47ad8f94158a65dd3ab) 

I'll release a new version later today and ping back here 👍

**Comment by Dangoo** [comment]
Hey @angular-moon,

as @rakannimer mentioned it was fixed and released in [v2.1.0](https://github.com/doczjs/docz/releases/tag/v2.1.0).
I'll close this issue for now. Please feel free to comment in case we missed something.
