### ISSUE TITLE
Crawl .md file by default

### ISSUE THREAD

**Issue by theo-mesnil** [doczjs/docz#1279]
## Bug Report

**Describe the bug**

When i start a `docz dev --src src`, the outside src are crawled. And this file (readme.md, contributing.md and changelog.md) are not an `.mdx` file.

**To Reproduce**

My files : 
<img width="331" alt="Capture d’écran 2019-11-26 à 14 48 15" src="https://user-images.githubusercontent.com/50322149/69639478-dbddc000-105c-11ea-8e47-029e2548ed7a.png">

My configuration :
```js
export default {
  title: 'Welcome UI',
  description: 'Design system of @wttj with react, styled-components and styled-system',
  dest: '/docs',
  menu: ['Getting Started', 'Theming', 'Components', 'Fields'],
  port: 3020,
  // https://github.com/pedronauck/docz/issues/777#issuecomment-489947783
  filterComponents: files => files.filter(filepath => /w*.(js|jsx|ts|tsx)$/.test(filepath))
}
```

**Environment**

- docz version: 2.0.0
- OS: OSX 10.15.1

Thanks :)

![Capture d’écran 2019-11-26 à 14 58 03](https://user-images.githubusercontent.com/50322149/69639636-2b23f080-105d-11ea-9929-c578caf7f624.png)

**Comment by theo-mesnil** [comment]
I don't know why i put `src: /src` but docz crawl all my project files instead...

**Comment by rakannimer** [comment]
Hey @theo-mesnil 

Could you try using the `ignore` field in your `doczrc.js` ?

```js
export default {
  // ...
  ignore: ["readme.md", "contributing.md", "changelog.md"]
  // ...
}

```

**Comment by theo-mesnil** [comment]
Hi @rakannimer :)

It's the same, it's like `ignore` only ignore on menu items

**Comment by rakannimer** [comment]
Hmm ok I was able to reproduce. 

We'll need a way to tell `gatsby-plugin-mdx` to not parse these files. 

The simplest way I can think of is to allow the user to change [the extensions](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#extensions) provided to the plugin. 

If docz were to parse only files that have an `mdx` extension, your problem would be solved right ?

**Comment by theo-mesnil** [comment]
@rakannimer yes :)

**Comment by theo-mesnil** [comment]
On the docz configuration > `files`  

> Glob pattern used to find your files. By default, Docz finds all files inside the source folder that have a .mdx extension.

https://www.docz.site/docs/project-configuration

**Comment by rakannimer** [comment]
Hey,

Starting from 2.2.0-alpha.0 docz won't crawl or parse anything outside `src`.

So in your case, you can add `src: "src"` and everything else will be ignored ( so the error and warning should disappear )

Please try it out with : `yarn add docz@next` when you can and let us know.

**Comment by theo-mesnil** [comment]
Thanks ! It works 🥳
