### ISSUE TITLE
Open external links in a new tab

### ISSUE THREAD

**Issue by MaluNoPeleke** [doczjs/docz#1283]
External links in markdown should automatically open in a new tab.

**Comment by selbekk** [comment]
Strong disagree.

**Comment by selbekk** [comment]
I disagree that this should be the default behavior.

However, if you want this behavior, you can implement it yourself quite easily.

Pass in your own implementation of the `a` component to Docz via the `<ComponentsProvider />` component, and implement something like this:

```js
const MarkdownLink = (props) => 
  href.startsWith('http://') || href.startsWith('https://') 
  ? <a {...props} target="_blank" rel="noreferrer nofollow" /> 
  : <a {...props} />;
```

**Comment by rakannimer** [comment]
Heyo !

I added an example to demonstrate one way to do it based on @selbekk's suggestion (thanks !)

You can check it here : https://github.com/doczjs/docz/tree/master/examples/with-custom-links

Closing this issue, but feel free to re-open or comment here if you face an issue 👍
