### ISSUE TITLE
Broken Build if I use 

### ISSUE THREAD

**Issue by joaaoeu** [doczjs/docz#1286]
## Bug Report

Hello! Can someone help me, please? 😄 I can't get why this is happening...

I'm getting this warns in the terminal after run ***docz dev*** or ***docz build***:

```shell
warn "export 'hasOwnProperty' (imported as 'XXXX') was not found in './some-path'
warn "export 'hasOwnProperty' (imported as 'YYYY') was not found in './some-path'
```

Everything works fine in **development**, but after build, in prod the links in sidebar don't work and the components don't render correctly...

I notice that this occurs when I have some component in the Docz with imports like **import * as XXXX** (in the component or in an imported file).

```javascript
// ./components/SomeComponent/index.js
import { XXXX, YYYY } from '../../somepath'
// ... component code
```

```javascript
// ./somepath/index.js
import * as XXXX from './xxxx';
import * as YYYY from './yyyy';

export { XXXX, YYYY }
```

```javascript
// ./somepath/xxxx.js
export const A = 'something'
export const B = 'something else'
```

```javascript
// ./somepath/yyyy.js
export const C = 'something else else'
export const D = 'something else else else'
```

**To Reproduce**

I reproduce a very basic example of this issue in this [repository](https://github.com/joaaoeu/docz-app-basic-error-reproduce) that I create from [docz basic example](https://github.com/doczjs/docz/tree/master/examples/basic).

Just run ***yarn*** to install dependencies, ***yarn dev*** to run dev and ***yarn build*** then ***yarn serve*** to run prod.

**Expected behavior**

I don't know why this **warn** is happening, but the build should work (like in development)!

**Environment**

**- docz version:** 2.1.1
**- OS:** macOS Catalina 10.15.1
**- Node/npm version:** Node 10.16.0/npm 6.11.3

**Additional context/Screenshots**
- **Console after run *yarn dev***
![console-after-run-yarn-dev](https://user-images.githubusercontent.com/6677405/69825220-6877b200-1206-11ea-9a7b-d47fd1956fa7.png)

- **Browser console in *dev***
![browser-console-in-dev](https://user-images.githubusercontent.com/6677405/69825217-67df1b80-1206-11ea-987e-3e5a7f5e0d49.png)

- **Console after run *yarn build***
![console-after-run-yarn-build](https://user-images.githubusercontent.com/6677405/69825219-6877b200-1206-11ea-90f3-0cac2fdee309.png)

- **Browser console in *prod (yarn serve)***
![browser-console-in-prod](https://user-images.githubusercontent.com/6677405/69825218-6877b200-1206-11ea-9792-aa39651656e4.png)

**Comment by rakannimer** [comment]
Closing this in favor of #1287
