### ISSUE TITLE
Adding custom components to the theme

### ISSUE THREAD

**Issue by wcastand** [doczjs/docz#1288]
## Bug Report

I'm trying to add custom components to the docz theme using the shadowing system of gatsby.

```
// ./src/gatsby-theme-docz/components/index.js
import * as baseComponents from "../../../node_modules/gatsby-theme-docz/src/components";
import * as customComponents from "../customs";
console.log(baseComponents);
export default {
  ...customComponents,
  ...baseComponents
};
```

The issue is as soon as i start adding these file, i loose all docz theme styling component because baseComponents becomes the custom ones (so no more menu, etc)

i tried to use `gatsby-theme-docz/src/components` but same result, that's why i tried to directly target the docz theme in node_module but gatsby seems to shadow all of it anyway.

Is there a way to add custom components without loosing docz theme?

**Comment by rakannimer** [comment]
Hey,

If you want to change `components/index.js` you need to export the files as they were before. You can see a full example [here](https://github.com/doczjs/docz/blob/master/examples/with-custom-links/src/gatsby-theme-docz/components/index.js). The example adds a custom link component to be used when rendering your MDX. 

For your case it would look something like this : 

```js
import * as headings from 'gatsby-theme-docz/src/components/Headings'
import { Code } from 'gatsby-theme-docz/src/components/Code'
import { Layout } from 'gatsby-theme-docz/src/components/Layout'
import { Playground } from 'gatsby-theme-docz/src/components/Playground'
import { Pre } from 'gatsby-theme-docz/src/components/Pre'
import { Props } from 'gatsby-theme-docz/src/components/Props'
import * as customComponents from "../customs";



export default {
  ...headings,
  ...customComponents,
  code: Code,
  playground: Playground,
  pre: Pre,
  layout: Layout,
  props: Props,
}
```

**Comment by wcastand** [comment]
Great ! thank, worked better when you doing it right ahah

Thank for the help. :) sorry i couldn't find the good example.
Maybe the name could more generic like `custom-components`.
