### ISSUE TITLE
Support Component Story Format (CSF)

### ISSUE THREAD

**Issue by bmcmahen** [doczjs/docz#1289]
I'm wondering how hard it would be to leverage support for [Component Story Format (CSF](https://storybook.js.org/docs/formats/component-story-format/)). If you're unfamiliar, CSF looks like this:

```jsx
export default {
  title: 'Button',
  component: Button
}

export const basicButton = () => <Button />;
```

I'm currently prototyping my components using Storybook but documenting my design system using Docz (because of the flexibility markdown offers). I'm having to copy examples from Storybook to Docz. Ideally I could reuse stories within my docz markdown documentation:

```jsx
import * as stories from './Button.stories';

<Playground>
  {stories.basicButton()}
</Playground>
```

This currently will render the button, but it won't render the proper source code. Ideally it could render the story inline.

**Comment by rakannimer** [comment]
Hey @bmcmahen 

Thanks for raising this issue. 

I'm not sure this is storybook specific. It's similar to when a user would want to show the contents of any component inside the playground e.g. 

```jsx
// BasicButton.js

export const BasicButton = () => {
	return (
		<button>
			Button
		</button>
	)
}
```

and then in your markdown you'd write something like this : 

```jsx
<Playground>
	<BasicButton />
	{/*
		And the user would see <button> Button </button> in the interface
	*/}
</Playground>
```

I can definitely see why this feature would be useful but I can't think of a straight-forward way to do this at the moment. 

Let's keep this issue open and see if we can come up with a way to do it 👍

**Comment by bmcmahen** [comment]
Thanks @rakannimer. I'm happy to help if you can think of some strategies which might work.

For what it's worth, storybook docspage does support this feature, as you can see [here](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs). But it's not super elegant, imo.

**Comment by bugzpodder** [comment]
I just came here for a similar need and found this:
https://github.com/uber/react-view

**Comment by rakannimer** [comment]
That's a cool library ! Thanks @bugzpodder for sharing, we'll see if we can maybe integrate it in docz.

Though, I'm not sure we'd be able to solve @bmcmahen use-case with it right ?
