### ISSUE TITLE
Typescript decorators not working with v2 (was working with v1)

### ISSUE THREAD

**Issue by xaviergonz** [doczjs/docz#1294]
## Bug Report

Typescript decorators not working with v2 (they were working out of the box with v1). They are properly enabled in tsconfig.json

```
 ERROR #98123  WEBPACK      

Generating SSR bundle failed

xxx.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (22:1):
```

I suspect the babel config might be missing 
```
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
```

**To Reproduce**

Create a typescript docz project, add a decorator to any of the ts files, run `yarn docz dev`

**Expected behavior**

Decorators should work when using typescript (at least when the experimentalDecorators flag is set in tsconfig.json

**Environment**

- docz version: latest v2
- OS: Windows 10
- Node/npm version: Node 13.x

**Comment by xaviergonz** [comment]
PS: for anybody looking into this issue:  it can be kind of fixed by creating a gatsby-node.js file in the root with:
```
exports.onCreateBabelConfig = ({ actions }) => {
  actions.setBabelPlugin({
    name: `@babel/plugin-proposal-decorators`,
    options: { legacy: true },
  })
}
```
plus a `yarn add --dev @babel/plugin-proposal-decorators`

**Comment by rakannimer** [comment]
Hey !

Thanks for providing the fix, docz v2 uses babel to transpile typescript code so I think this is necessary. I'll add an example to avoid confusion for others. 

Is this solution causing other issues or unexpected behavior in your setup ?

**Comment by xaviergonz** [comment]
Nope, seems to work like a charm 👍
