### ISSUE TITLE
How to create a reusable theme?

### ISSUE THREAD

**Issue by drinchev** [doczjs/docz#1297]
## Question

**Description**

Based on the docs 

> Now, if you want to create your own theme, just create a file located at src/gatsby-theme-docz/index.js

was wondering is there a way to create a custom theme that one can package and reuse?

**Comment by rakannimer** [comment]
Hey @drinchev,

To create a theme you would create a folder in src called gatsby-theme-docz and inside it you would shadow any or all files located in the theme src directory : https://github.com/doczjs/docz/tree/master/core/gatsby-theme-docz/src

To package the theme you could put it in a repository and then clone it in the right place under `src/gatsby-theme-docz`. Or just download it from anywhere. And it would work without any additional steps

Here are some examples where different components and files from the theme are shadowed : 

- Remove header and position logo in sidebar :  https://github.com/doczjs/docz/tree/master/examples/logo-in-sidebar
- Wrap Playground component with a styled div : https://github.com/doczjs/docz/tree/master/examples/shadowed-playground
- Make all links open in new tab : https://github.com/doczjs/docz/tree/master/examples/with-custom-links
- Add favicon and page metadata to wrapper : https://github.com/doczjs/docz/tree/master/examples/with-favicon-and-metadata

Does that answer your question ?

**Comment by drinchev** [comment]
Thanks for the fast response and the great job on Docz.

I guess that's the answer I was looking for, however asking people to clone a theme and put it in `src` doesn't sound optimal :( 

Was hoping more there would be a way to be able to set a package which implements the shadowing. 

So a user can install `npm install docz-theme-bar` which after being set somewhere in `doczrc.js` will be used as the shadowing root.

Anyway thanks for the answer.

**Comment by rakannimer** [comment]
> So a user can install npm install docz-theme-bar which after being set somewhere in doczrc.js will be used as the shadowing root.

That's a valid concern ! 

I think it should be possible to do that with docz by adding a theme to the plugins list in gatsby-config.js and doing the shadowing inside it 🤔 

Let's keep this open while I see if I can setup a demo.

**Comment by rakannimer** [comment]
Hello again,

I added an example showing how to create, share and consume custom docz themes without cloning and putting them in your repo. 

Checkout the README and code : https://github.com/doczjs/docz/tree/master/examples/with-custom-docz-theme#using-and-creating-a-custom-docz-theme-example

Please let me know if anything isn't clear or can be made better 👍 !

**Comment by drinchev** [comment]
Oh that's great! Thanks for that example and the support.
