### ISSUE TITLE
Allow multiple src entry points to read from node_modules and src

### ISSUE THREAD

**Issue by Okazari** [doczjs/docz#1298]
## I'd like to build docs from my "node_modules"

Hey guys ! I'm trying a new approach for my current work.

I'm using a multi-project design-system running on docz with a lot of shared design references and components.
But i also want to run a docz for my projects. I had the idea that i could run docz on my project files + gather the docs (.mdx etc..) from my design-system from my node_modules.

On my first attemps it did not work. After a small search on docz codebase i found this line :
https://github.com/doczjs/docz/blob/e6b1521c82e99cb01b390402f566e956a61f21f5/core/gatsby-theme-docz/gatsby-config.js#L53

In order to use both files from my `node_modules` and my `src` i did the following.

```js
export default {
  src: "./node_modules/../",
  files: ["src/**/*.{md,mdx}", "node_modules/nv-design-system/**/*.{md,mdx}"]
};
```

But... This really seems like a hack.
Do you see another way to do this ?

If not, do you think we could try to work on a support of multiple `config.src` or an option allowing to search files into `node_modules` ? (instead of `config.src.indexOf('node_modules'`)

Thanks in advance :) !

**Comment by rakannimer** [comment]
Hello @Okazari 

> But... This really seems like a hack.
> Do you see another way to do this ?

Nice find, we added this specifically for cases like yours 😄 

Adding support for multiple src in config.src is on the roadmap. Let's use this issue to track it 👍
