### ISSUE TITLE
Sidebar Menu is updated in rapidly after hot reload

### ISSUE THREAD

**Issue by theparthy** [doczjs/docz#1299]
## Bug Report

**Describe the bug**
The Sidebar is updated rapidly, after hot reload.
When left alone for a while,  the browser tab gets slugish. 
The links are not Clickable. 
After a full reload everything is fine.

**To Reproduce** 

[Repo](https://github.com/theparthy/docz-sidebar-issue)

0. `git clone git@github.com:theparthy/docz-sidebar-issue.git`
1. Run npm run docz dev
2. got to ```src/elements/Spinner/index.mdx``` 
3. remove or add Component in Playground
4. After hot reload look at sidebar in Elements tab in DevTools. (Screenshot Below)

**Expected behavior**
Only one update of Sidebar 

**Environment**
- docz version: [2.1.1]
- OS: [OSX 10.14.6]
- Node/npm version: [v12.3.1]
- Other libraries used
```
    "reakit": "^1.0.0-beta.13",
    "styled-components": "^4.4.1",
    "styled-icons": "^9.0.1",
    "styled-is": "^1.3.0",
    "styled-system": "^5.1.4"
```

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/3232200/70045999-6bd3ba80-15c5-11ea-9029-74ca12b6c9f8.png)

**Comment by rakannimer** [comment]
Hey @theparthy 

Thanks for catching and reporting that bug, it's an annoying one ! 

The fix will be released with `2.2.0`. 

Meanwhile you can use `2.2.0-alpha.7` (`yarn add docz@next`) to use the patched code right away 👍

**Comment by theparthy** [comment]
Hey @rakannimer 

thanks for the quick response and fix.
2.2.0-alpha.7 fixes the issue.

**Comment by rakannimer** [comment]
Awesome ! You're welcome !

Going to close this, feel free to re-open or comment here if it re-occurs 👍
