### ISSUE TITLE
Docz v2 `docz dev` crashes with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

### ISSUE THREAD

**Issue by wldcordeiro** [doczjs/docz#1301]
## Bug Report

When I run `docz dev` it takes forever and a day then crashes out with a memory leak.

**To Reproduce**

A reproduction repo isn't really doable as this is coming from a large monorepo and might be an issue of Docz trying to parse too much stuff in my sources. Providing the relevant config files.

```js
// doczrc.js
module.exports = {
  base: '/citadel',
  description: 'The home for Execute projects.',
  typescript: true,
  menu: [
    {
      name: 'General Information',
      route: '/',
      menu: [
        'Introduction',
        'Contributor Guide',
        'Maintainer Guide',
        'Supporting Legacy Packages',
        'Citadel Combined Changelog',
      ],
    },
    {
      name: 'Agile Dialogs',
      route: 'agile-dialogs',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'API Client',
      route: 'api-client',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Breadcrumbs',
      route: 'breadcrumbs',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Calendar',
      route: 'calendar',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Config',
      route: 'config',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'I18N',
      route: 'i18n',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Iteration Header',
      route: 'iteration-header',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Notification Hub',
      route: 'notification-hub',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Rich Text Editor',
      route: 'rich-text-editor',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Subscribe Button',
      route: 'subscribe-button',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Summary Container',
      route: 'summary-container',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Team Core',
      route: 'team-core',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Team Header',
      route: 'team-header',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Team Settings',
      route: 'team-settings',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'Update Stream',
      route: 'update-stream',
      menu: ['Guide', 'Changelog'],
    },
    {
      name: 'User Header',
      route: 'user-header',
      menu: ['Guide', 'Changelog'],
    },
  ],
  title: 'Execute Citadel',
  themeConfig: {
    colors: { primary: '#fd0e35' },
  },
};
```

```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({ actions }) => {
  const path = require('path');
  const root = path.resolve(__dirname, '..'); // we're in the .docz/ execution
  const DOCS_ROOT = path.resolve(root, 'docs');
  actions.setWebpackConfig({
    resolve: {
      alias: {
        '@components': `${DOCS_ROOT}/components`,
        '@images': `${DOCS_ROOT}/images`,
        '@splitsoftware/splitio': path.resolve(
          root,
          'node_modules/@splitsoftware/splitio/lib/umd.js'
        ),
      },
    },
    module: { rules: [{ test: /\.css|html$/, use: 'raw-loader' }] },
  });
};
```

My docs are either in the `DOCS_ROOT` for general purpose docs pertaining to the whole monorepo and the rest are in `packages/*/docs`

**Expected behavior**

That the dev server would start up and not crash and that the entire extra effort of using Gatsby for v2 would result in a less slow start up instead of slower.

**Environment**

- docz version: 2.1.1
- OS: OSX 10.14.6
- Node/npm version: Node 12.x & Yarn 1.x.

**Comment by rakannimer** [comment]
Hello @wldcordeiro,

Please provide the output of docz dev before it runs out of memory, to help us know where the bottleneck you're facing is.

In parallel, could you try updating to the `next` tag : 

```sh
yarn add docz@next
```

Then in your `doczrc.js` add :

```
src: "packages" // or DOCS_ROOT
```

I know you have the rest in another package, I'm just trying to see if limiting the amount of parsed files helps or if it's from something else.

If you're still getting slow build after doing the above, try setting `propsParser` to false and see if it helps.

If it does than we'll make `src` accept an array and you will be able to do : 

```
src: [DOCS_ROOT, "packages"]
```

> the entire extra effort of using Gatsby for v2 would result in a less slow start up instead of slower.

The "entire extra effort" was made for many reasons not for : "a less slow start up".

Anyway, we're very happy to take PRs if you have suggestions on how we can make it faster 👍

**Comment by rakannimer** [comment]
I ran into a similar issue that I fixed by setting an array of regex using the `files` config flag. 

For example : 
```js
// doczrc.js
{
  files: ['./DOCS_ROOT/**/*.mdx', './packages/*/README.md', './README.md'],
}
```

**Comment by wldcordeiro** [comment]
I'll give that a try and report back.

**Comment by dpvitt** [comment]
Hi @rakannimer, I've got the same issue here on `docz 2.2.0`, `node 12.*`, `lerna 3.*`. We've got a large monorepo with 5-6 UI apps and 5-6 API apps. The only difference is that we're running it on `lerna` rather than `yarn` and `yarn workspaces`. We also define our packages separately in lerna, we don't have a packages directory. 

```
"packages": [ "z_ui", "y_ui", "x_ui", ... ]
```

I tried setting the file config option as you mentioned above for 2 of our UI apps, so we don't look through everything `files: ['../x_ui/**/*.mdx', '../y_ui/**/*.mdx']`. I also tried setting `propsParser: false` in `doczrc.js`, however I'm still getting the memory issue.

**Comment by dpvitt** [comment]
So after looking into this further, my issue was with the amount of files being parsed, but not because of the amount of apps in the monorepo. The problem is with the glob posted above:

```
'../x_ui/**/*.mdx',
```

The above meant it was searching through all `node_modules` and symlinked folders. The fix was easy, change the above to:

```
'../x_ui/src/**/*.mdx',
```

Key being that the files I actually want to parse are in `src`, this avoids looking through all of the node_modules and symlinked files.
