### ISSUE TITLE
yarn create docz-app my-docz-app could not be located

### ISSUE THREAD

**Issue by Persepolis1** [doczjs/docz#1302]
## Bug Report

**Describe the bug**

I cannot seem to install the library with yarn create docz-app my-docz-app
I get the following error: 
"Could not locate an example named "styled-components". Please check your spelling and try again."

```
➜ yarn create docz-app docz-app-styled-docz --example styled-components

yarn create v1.19.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Installed "create-docz-app@0.1.4" with binaries:
      - create-docz-app
[############################################################################################] 151/151Could not locate an example named "styled-components". Please check your spelling and try again.
error Command failed.
Exit code: 1
Command: /usr/local/bin/create-docz-app
Arguments: docz-app-styled-docz --example styled-components
Directory: /Users/persepolis1/docz
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**To Reproduce**

run `yarn create docz-app my-docz-app --example styled-components` to create the project.

**Expected behavior**

It should scaffold a basic docz project with the styled-components example.

**Environment**

- docz version: latest, using the command
- OS: macOS 10.14.6 (Mojave)
- Node/npm version: Node v13.2.0 and yarn v1.19.2

**Comment by kumarharsh** [comment]
+1 None of the examples work. Even the simplest example mentioned on the website doesn't work (https://www.docz.site/docs/getting-started).

```shell
npx create-docz-app my-docz-app
```

```shell
npx: installed 1 in 0.672s
Could not locate an example named "basic". Please check your spelling and try again.
```

**Comment by rakannimer** [comment]
This is very weird I can't reproduce it, maybe a network issue ?
