### ISSUE TITLE
Modify component props, the page is not updated

### ISSUE THREAD

**Issue by Cavendichun** [doczjs/docz#1303]
## Bug Report

**Describe the bug**

I use the example project https://github.com/doczjs/docz/tree/master/examples/basic for testing. When I modify the component's props, the page will not be updated. I have to use yarn dev again to display normally

**Expected behavior**

I hope the page can be displayed correctly when I modify the component's props,  without having to yarn dev again

**Environment**

- docz version: [latest]
- OS: [Windows 10]
- Node/npm version: [node v10.16.0, npm 6.9.0]

**Comment by rakannimer** [comment]
Hello @Cavendichun 

Which component's props are you changing that are not triggering a reload ? In the Alert page for example ? Sorry I couldn't reproduce, it's reloading when I change a mdx or js file as expected.

**Comment by Cavendichun** [comment]
Hello @rakannimer 

I just changed the component's propTypes, such as changing kind to kind1, or required to non-required. The page won't change when I save it. But there is no problem on v1.2.0 version.

![image](https://user-images.githubusercontent.com/31662444/70345611-6b724280-1897-11ea-8bdf-e8aac5d887eb.png)

**Comment by rakannimer** [comment]
I also tried changing kind to kind1 required to non-required and changing the default props, it made the page reload and it worked as expected.

I'm not sure why and how this is happening in your setup.
