### ISSUE TITLE
TypeScript interfaces converted to lowercase by <Props/>.

### ISSUE THREAD

**Issue by rlmcneary2** [doczjs/docz#1308]
If a TypeScript interface property type is defined as another interface the name of the property interface is lowercased in the generated `<Props />` documentation.

```
import {BackgroundLayout, CircleLayout} from "mapboxgl";

export interface LayerProps {
  layout?: BackgroundLayout | CircleLayout;
}
```
becomes:
> layout: Backgroundlayout | circlelayout

Note "circlelayout" above.

**Expected behavior**
> layout: BackgroundLayout | CircleLayout

- docz version: 2.2.0-alpha8
- OS: linux
- Node/npm version: node 12.13.1

**To Reproduce**
clone https://github.com/rlmcneary2/remapgl.git
checkout gh-pages and `yarn install`
`yarn docz:dev`

**Comment by rakannimer** [comment]
Thanks @rlmcneary2 for reporting this. It's fixed in `docz@2.3.0-alpha.9` (yarn add docz@next) and will be released with `docz@2.3.0`
