### ISSUE TITLE
Can't start docz on Windows when providing files and src to config

### ISSUE THREAD

**Issue by stramel** [doczjs/docz#1310]
## Bug Report

**Describe the bug**
Can't start Docz

```sh
ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allDoczEntries" on type "Query". Did you mean "allDoczDb"?

File: ..\node_modules\gatsby-theme-docz\lib\createPagesStatefully.js:28:10
```

**To Reproduce**

I'm not sure how to reproduce this. It has been running fine on my Mac at work and this is the first time I tried it on my Windows machine.

I'm running this in an NX monorepo with TypeScript.

My config looks like:

```js
// doczrc.js
export default {
  files: '**/*.mdx',
  src: './libs/',
  typescript: true,
  title: 'Coolfire Web'
};
```

**Expected behavior**

I would expect this to start on Windows

**Environment**

- docz version: 2.1.1
- OS: Windows 10
- Node/npm version: Node 12.13.0 / npm 6.12.0

**Additional context/Screenshots**

Seems similar to #1007 

**UPDATE:**

Removing `files` and `src` allowed it to spin up but now my `README.md` file is back in. This feels very misleading since the documentation says that the `README.md` is ignored by default.

![image](https://user-images.githubusercontent.com/855184/70453918-328cc600-1a6f-11ea-8d53-4362fc0f464b.png)

**Comment by stramel** [comment]
I haven't checked but I believe this is still valid. I will update to the latest on Monday

**Comment by heynext** [comment]
I get this error with `files: "docs/**/*.{mdx}"` in `doczrc.js` too. It takes me lot of time to figure it out. 😶😶😶

**Comment by febugcoder** [comment]
@rakannimer I have same error, Is there anything new?
thanks a lot

**Comment by heynext** [comment]
so any other ways to ignore `README.md`?

**Comment by limarc** [comment]
@heynext, this is due to the picomatch release [version 2.2.1](https://github.com/micromatch/picomatch/blob/master/CHANGELOG.md#221-2020-01-04) and fix this issue [#49](https://github.com/micromatch/picomatch/issues/49). Just remove braces (`{}`).

```
files: "docs/**/*.mdx"
```

**Comment by dsumer** [comment]
are there any news on this? sadly for me it doesn't even work to configure the files property as @limarc described, which makes this some sort of blocker for me, because developers on windows machines can't work with our docz setup

**Comment by stramel** [comment]
Not stale

**Comment by wumiangithub** [comment]
i am  on  mac  is  same  problem

**Comment by BigSnowDay** [comment]
add config  `files:'./components/**/*.{md,markdown,mdx}'` to `doczrc.js` can fix it for me.

**Comment by sarvasvarora** [comment]
I have `files: './docs/**/*.{md,markdown,mdx}'` in my `doczrc.ts` file, but the `README.md` file is being included in the edocs still. Is there any fix?

Moreover, I also have the base config set like `base: '/contents/'`, however, the docs still get exposed on `/`. Seems like some of the config properties are not working properly (??)

I'm on MacOS and using `docz` 2.4.0 and `gatsby-theme-docz` 2.4.0
