### ISSUE TITLE
gatsby-theme-docz exhibits "flash of color" issue when switching dark/light mode

### ISSUE THREAD

**Issue by Yihwan** [doczjs/docz#1311]
## Bug Report
When `initialColorConfig` is set to `light` (default), switching to dark mode using `gatsby-theme-docz` will cause the "light mode" to initially flicker on any page render. Not sure if this is a docz, gatsby, or theme-ui issue, so I may just post this everywhere. 😅 

### To Reproduce 
Set up a repo with [instructions from Gatsby site](https://www.gatsbyjs.org/tutorial/writing-documentation-with-docz/). You also need to `npm i docz@next` which isn't mentioned. Run `gatsby develop` and toggle the color mode using the icon to view the site in "dark mode." 

Now navigate to a different page, and you should see the light mode flicker before the dark theme is applied. Switching `initialColorConfig` to `dark` will cause the dark theme to flicker when switching to light mode. 

Sample repo: https://github.com/Yihwan/gatsby-docz-flicker-issue

Though not necessary to reproduce the bug, you may also want to pull in the `src` folder of `gatsby-theme-docz` into your `src/gatsby-theme-docs` dir to debug further. This has already been done in the sample repo.

NB: Since `useColorConfig` utilizes localStorage, you may have to clear site application data as needed or use incognito.

### Debugging so far 
Best I can tell, this has to do with the site not picking up on the selected `theme-ui-color-mode` in localStorage on first render. Instead, for some reason the `initialColorConfig` selection is rendered first. 

This seems to be a known issue with theme-ui because I found at least a [passing reference](https://theme-ui.com/color-modes#gatsby-plugin) to the issue in the docs. Not sure how this will git in with `gatsby-theme-docz` though. 

Thank you in advance!!!

**Comment by Yihwan** [comment]
@rakannimer any chance we might be able to pull in `gatsby-plugin-theme-ui` to fix this issue? https://github.com/system-ui/theme-ui/issues/510

happy to help / open a pr depending on your initial thoughts on approach

**Comment by rakannimer** [comment]
Hey @Yihwan 

Sorry for the late reply ! I didn't mean to ignore the issue I went through it and I was able to reproduce but I wasn't able to solve it in the time I had allocated.

If you think `gatsby-plugin-theme-ui` can help then I'd be happy to bring it in !

I'd be happy to review any PR and if you'd like to chat more please join our [slack workspace](https://join.slack.com/t/docz-workspace/shared_invite/enQtNzc4ODc2ODA3NzUxLWI0ZmYwY2NhNjhkNDFjN2UzYzlmMDcwZjQyZGY4MWQ1NmQwZDVlZDE4MmE3N2I4MWRjZTAxZjY4ODk4NGMzZjg) where I or another team member can help ! 

Cheers !

**Comment by PaulieScanlon** [comment]
Hey @yaodingyd and @Yihwan i'm also experiencing this issue. Did implementing `gatsby-plugin-theme-ui` solve this?

**Comment by Yihwan** [comment]
hey @PaulieScanlon i can't say i've had time to make much progress. @rakannimer it seems like support for this should be included automatically (https://github.com/system-ui/theme-ui/issues/510#issuecomment-570314042) but i haven't had a chance to make it work yet

**Comment by kpratik2015** [comment]
I can provide some insight. In order to change the flash color here's what I did:
`
// gatsby-theme-docz -> theme -> index.js
export default merge(typography, {
  initialColorMode: 'default',
  .
  .
  .
  colors: {
    background: '#000', // this changes the color of flash. Default seems to be #ee99ff
    modes: {
      dark: modes.dark,
      light: modes.light
    }
  }
`

**Comment by rakannimer** [comment]
I tried adding the theme-ui gatsby plugin (theme-ui-gatsby-plugin) on a docz site, it stopped the flicker issue but also broke switching between dark and light mode. 

I setup an example repo showing it if someone would like to dig deeper in this : https://github.com/rakannimer/docz-gatsby-flicker-issue

**Comment by goldcaddy77** [comment]
Has anybody figured out a solution to this?

**Comment by kpratik2015** [comment]
I solved it few weeks back and I can't recall all the steps but see if this helps. This just a workaround though.

File:  gatsby-theme-docz/components/Header/index.js
```javascript
const {
    value: isDarkModeEnabled,
    enable: enableDarkMode,
    disable: disableDarkMode
  } = useDarkMode();

useEffect(() => {
    if (isDarkModeEnabled) {
      setColorMode('dark');
    } else {
      setColorMode('light');
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
```

File:  gatsby-theme-docz/index.js
```javascript
import useDarkMode from 'use-dark-mode';

const Theme = ({ children }) => {
  const config = useConfig();
  const { value: isDarkModeEnabled } = useDarkMode();
  const colorMode = isDarkModeEnabled ? 'dark' : 'light';
  return (
    <ThemeProvider
      theme={{
        ...config.themeConfig,
        colors: {
          ...config.themeConfig.colors,
          background: config.themeConfig.colors.modes[colorMode].background
        }
      }}
      components={components}
    >
      // ...
    </ThemeProvider>
  );
};

export default theme(defaultTheme)(Theme);
```

**Comment by igoroctaviano** [comment]
Gosh, they are not going to fix this? o.o

**Comment by edmundojr** [comment]
This issue still happens in the latest version.

**Comment by mortoni** [comment]
Hey guys, I am still facing this issue, any solution?

**Comment by suhrudh** [comment]
has anyone found a work around or at least a way to remove the dark mode toggle option?
