### ISSUE TITLE
Typescript docs example is broken

### ISSUE THREAD

**Issue by rafarovina** [doczjs/docz#1318]
## Bug Report

I tried to start the [typescript](https://github.com/doczjs/docz/tree/master/examples/typescript) example project, but when I run I have the following error:

```
ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (19:21)

File: ../src/components/Button.tsx:19:21


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (4:7)

File: ../src/components/Alert.tsx:4:7
```

To reproduce, just follow the instructions on the doc:
```
yarn create docz-app docz-app-typescript --example typescript
cd my-docz-app
yarn
yarn dev
```

I tried to create `.doczrc.js` as per [docs](https://www.docz.site/docs/usage-with-typescript). I still got the same error.

Not sure it's related, but I noticed that `.docz/gatsby-config.js` has `typescript: false`.

```
const config = {
  ...
  plugins: [
    {
      resolve: 'gatsby-theme-docz',
      options: {
        typescript: false,
        ts: false,
        ...
```

**Environment**

- docz version: 2.2.0
- OS: OSX 10.15.2
- `npm -v`: 6.13.1
- `yarn -v`: 1.19.1
- `node -v`: v12.13.0

**Comment by rakannimer** [comment]
Thanks for catching and reporting this @rafarovina in the upcoming version you will no longer need to set typescript:true in your doczrc config.

I updates the example it should work now. 

If you want to fix your project just add a doczrc.js file in the root directory with contents : 

```js
export default {
	typescript: true
}
```

or use the next docz version with : yarn add docz@next 👍

**Comment by rafarovina** [comment]
@rakannimer thanks for the extremely quick response! It works fine now

I can't believe I had a leading  `.`  on my `doczrc.js` file name 😱
