### ISSUE TITLE
<Details> Element for Props Component

### ISSUE THREAD

**Issue by Dangoo** [doczjs/docz#1322]
I'd like to propose to use the HTML `<details>` element for each entry in the list view of the `Props` component in `gatsby-theme-docz`.
This would bring a standardized as well as accessible markup structure which could even be extended by the use a `<dl>` for the whole props list.

## Example
```html
<dl class="prop-list">
  <dt class="prop-list__label">id</dt>
  <dd class="prop-list__description">
    <details>
      <summary class="prop-list__summary">string</summary>
      <p>The id global attribute defines an identifier (ID) which must be unique in the whole document. Its purpose is to identify the element when linking (using a fragment identifier), scripting, or styling (with CSS).</p>
    </details>
  </dd>
  <dt class="prop-list__label">class</dt>
  <dd class="prop-list__description">
    <details>
      <summary class="prop-list__summary">string</summary>
      <p>A space-separated list of the classes of the element.</p>
    </details>
  </dd>
</dl>
```

See this pen for 👉[demo](https://codepen.io/daniel_gooss/details/oNggWRZ)

## Small print
- [Browser support](https://caniuse.com/#feat=details) includes all modern browsers except IE Edge
- Support for IE Edge (and older) could be added through a polyfill
- Degrades gracefully: Not supporting browsers will treat `<details` and `summary` elements as `div` so the content will be visible (and will have an appearance like the opened version)
- Safari seems to have an issue with updating the `open` state (repaint occurs only after blur) when using pseudo element for caret

I'd like to implement that as soon as I find some spare time and I'm always open to feedback :)

**Comment by lkuechler** [comment]
In my opinion a polyfill for Edge would be to much. Without one the list is just displayed as opened and does not prevent the usage of it.
The polyfill would just be additional code to be maintained which hopefully will be unused within a few updates of Edge.

**Comment by Dangoo** [comment]
Hi there,
little status update before christmas:

The desktop view turned out quite good whereas the mobile view comes with some challenges.
Tricky is the part where on mobile the arrow is not next to the label but next to the prop type since this is how details works.
Would you mind if we would keep it like that for now or does it have big impact on usability?
I also tried using a label for `<details>` but that seems not to be supported…

#### Desktop
<img width="735" alt="desktop" src="https://user-images.githubusercontent.com/1252204/71353296-dfd80180-2578-11ea-9cbd-3558a26ef645.png">

#### Mobile
<img width="455" alt="mobile" src="https://user-images.githubusercontent.com/1252204/71353306-e6ff0f80-2578-11ea-924d-6731b96195f6.png">

Merry Christmas to you all! 🎁
