### ISSUE TITLE
need a prop to set default visibility of props descriptions version 2+

### ISSUE THREAD

**Issue by gogoyqj** [doczjs/docz#1323]
## Question

seems a props form Props component is needed to control default visibility of props‘s descriptions

![image](https://user-images.githubusercontent.com/1776278/70881082-684d2400-2006-11ea-812a-2051aad8afbb.png)

seems that `isToggle` means to do it but actually not

```tsx
<Props isToggle of={ComponentXX} />
```

https://github.com/doczjs/docz/blob/320f5c4ad8be1835cbc8498cee1dcb41afee0c85/core/docz/src/components/Props.tsx#L161

**Comment by rakannimer** [comment]
Hey @gogoyqj 

Thanks for reporting this issue. You're right it looks like isToggle is not being used in v2. 

To fix it we would need to 

1. Add isToggle argument in Props definition : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L68
2. Pass isToggle down to Prop https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L74
3. Add isToggle argument in Prop definition : https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L23
4. Initialize `showing` state to isToggle https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Props/index.js#L24

PRs are very welcome if someone would like to take a shot at it. 

If not I'll try to get to it as soon as possible 👍

**Comment by gogoyqj** [comment]
@rakannimer i'd like to fix it and then make a pr today
