### ISSUE TITLE
No way to add line breaks

### ISSUE THREAD

**Issue by baldarian** [doczjs/docz#1324]
Is there a way to add line breaks in pages?

I've tried adding `&nbsp;`, `\` and lot more but it was useless.

**Comment by rakannimer** [comment]
Hey @baldarian 

You can add a line break in markdown files in two ways : 

1. Use a `<br />` tag
2. Add two consecutive line breaks

Is that what you mean ?

**Comment by baldarian** [comment]
Yeah, `<br />` did the thing.
Thank you!
