### ISSUE TITLE
`gatsby-theme-docz`: allow overriding root path passed to `gatsby-source-filesystem` plugin

### ISSUE THREAD

**Issue by gmatroskin** [doczjs/docz#1329]
We use `docz` to generate internal documentation for our product's react components.  We co-locate our `mdx` files with our components, but separate `docz` into a subfolder with its own `package.json` file, so that we don't "pollute" all of our application builds with `gatsby` packages (fetching the gatsby dependencies considerably slows down our CI builds).  We were doing this successfully with version `2.1.1` by setting the `src` folder in `docsrc` to `..`, and using a custom webpack config to make module resolution look in two separate locations.

However, commit https://github.com/doczjs/docz/commit/e6b1521 by @rakannimer in version `2.2` of `gatsby-theme-docz` broke things for us because it started including all of our non-documentation javascript into the gatsby build, which a) significantly slows things down, and b) breaks our build by trying to do SSR on certain client-side only packages (e.g. `Highcharts`). We'd like to be able to either override the root back to the value it had in `2.1.1`, or have some other way of excluding files/folders from the gatsby build.

**Comment by rakannimer** [comment]
Hey there,

While this change was made following a user request, I failed to consider that it would break existing workflows. 

I replaced `src` with a new flag `gatsbyRoot` in gatsby-theme-docz. This should fix your use-case.

The fix will be released with 2.3.0, but you can try it out now with : `yarn add docz@next`

**Comment by gmatroskin** [comment]
Thank you so much for the fast fix @rakannimer!  Pulled down latest version, works perfectly with the new config.
