### ISSUE TITLE
`docz` package.json should pin version of internal deps, such as `gatsby-theme-docz`

### ISSUE THREAD

**Issue by gmatroskin** [doczjs/docz#1330]
## Bug Report

When `docz` `v2.2` was released, it broke our build (#1329).  Unfortunately, pinning the version of `docz` to `2.1.1` was not sufficient to fix the problem, because the `docz` `package.json` does `"gatsby-theme-docz": "^2.1.0"`, which still pulls in the breaking version.

The problem could be avoidable if versions of `docz` and `gatsby-theme-docz` were always "lock step".

**Comment by rakannimer** [comment]
Hey @gmatroskin 

Sorry your build was broken. 

A lock-file would have also avoided that problem in your build.

But your suggestion is definitely noted, we will pin internal dependencies versions 👍

**Comment by gmatroskin** [comment]
Thank you @rakannimer!  We actually did have a lock file that saved us for a bit, but things broke when we pulled in another package & regenerated.  Appreciate all the work you are doing!
