### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by baldarian** [doczjs/docz#1331]
Build fails when there's a component wrapped in `memo`.

Here's a screenshot.
![Untitled](https://user-images.githubusercontent.com/40735399/70986745-ee856b00-20d7-11ea-8a11-84889ba8f5ae.png)

Is this related to Gatsby or Docz ?

**Comment by rakannimer** [comment]
Hello,

Which version of docz are you using ?

**Comment by baldarian** [comment]
Hey.

I'm using `2.3.0-alpha.2` .

**Comment by rakannimer** [comment]
@baldarian thanks for reporting this, it looks like a docz issue 👍 

@axe312ger it looks like `pascal-case` throws when undefined is provided to it here https://github.com/doczjs/docz/commit/9d5b129#diff-5cc2196461930cb24939fb44764d656bR126 

https://github.com/blakeembrey/change-case/blob/master/packages/no-case/src/index.ts#L27

We'll need to cast the component name to a string when it is not fetched properly.

**Comment by baldarian** [comment]
@rakannimer Thank you for a quick response.
