### ISSUE TITLE
How to copy a code?

### ISSUE THREAD

**Issue by baldarian** [doczjs/docz#1333]
Hey! I have a section of helper functions where I demonstrate the usage of the helpers by putting a code inside 3 brackets like this. 

\```js
code
\```

The problem is that I'm not able to copy the text because of `user-select: none`. Furthermore, I'd expect to see a button that would automatically copy the code for me.

What do you think?

**Comment by alexandre-lelain** [comment]
Hello,

If you want a customized [Code](https://github.com/doczjs/docz/tree/master/core/gatsby-theme-docz/src/components/Code)  component, I think you can override it in your `src/gatsby-theme-docz` folder and add your copy button there.

More about shadowing can be read here: https://www.docz.site/docs/component-shadowing

Hope it helps.
