### ISSUE TITLE
Multiple folders support

### ISSUE THREAD

**Issue by simonepizzamiglio** [doczjs/docz#1334]
## Question

**Description**

Hi,
I'm facing a problem very similar to this [one](https://github.com/doczjs/docz/issues/864).

I'm trying to implement docz in my react-native project, this is how my root folder is structured
```
|- android
|- ios
|- docs
|- src
```

I don't want docz to parse `android` and `ios` folders otherwise it will run into errors.

[This discussion ](https://github.com/doczjs/docz/issues/864) says I should specify the folders `docs` and `src` in the `files` config.

This is my doczrc.js but it still parses `android` and `ios` folders.
```
{
	title: 'React Native',
	files: '{src,docs}/**/*.{md,markdown,mdx}',
	src: './',
};

```

**Comment by treshugart** [comment]
I've ran into this exact issue. Anything in `src` is still parsed even if you are more specific with `files`. The docs don't really explain the distinction. It would seem that only having a `files` option should suffice? Thanks!
