### ISSUE TITLE
Upgrade to emotion v11

### ISSUE THREAD

**Issue by stramel** [doczjs/docz#1335]
Emotion has started to release some `next` builds for v11.

This includes TypeScript support for theming and fixes using hooks in the styled components. 

I currently need v11 for my app but docz can't run it because docz is using v10.

I'm not sure what the timeline for v11 release looks like but it would be cool to work on getting it into a release so people (primarily myself) can start using it with Docz.

**Comment by stramel** [comment]
Still pending the v11 release

**Comment by stramel** [comment]
Still pending the v11 release

**Comment by stramel** [comment]
Still pending

**Comment by stramel** [comment]
Still pending... 😒

**Comment by gillesdemey** [comment]
We're also quite keen on getting emotion 11 support, since it has [officially](https://github.com/emotion-js/emotion/pull/1600) been released ✌️

**Comment by pgrekovich** [comment]
@gillesdemey @pedronauck when it will be in release?

**Comment by stramel** [comment]
@pgrekovich I was waiting for an upstream PR to be merged. I'll work on getting that update in now that it has been merged.

**Comment by stramel** [comment]
I think we should wait for this one too just to clean up our dependency tree a bit. https://github.com/rebassjs/rebass/pull/1051

**Comment by stramel** [comment]
I have reached out to @jxnblk directly. If the issue is not resolved in the near future then we will either proceed without it or run on a forked version.
