### ISSUE TITLE
Optimize the toggle of the prop description

### ISSUE THREAD

**Issue by zhaoyao91** [doczjs/docz#1336]
Currently the description toggle is too far and too small to be triggered easily. 

There could be some optimization, such as 
- make the whole item clickable
- provide hover tooltip
- move the toggle from right to the left

![image](https://user-images.githubusercontent.com/3808838/71305265-1e9c7900-240c-11ea-8fc6-5f21051a9aa1.png)

**Comment by Dangoo** [comment]
Hi @zhaoyao91,
