### ISSUE TITLE
"Page not found" for new pages without the restart of dev-build

### ISSUE THREAD

**Issue by lttb** [doczjs/docz#1338]
## Bug Report

**Describe the bug**

There is a gatsby 404 error for new pages without restart of dev-build.

The page after creation is visible in the sidebar:

![image](https://user-images.githubusercontent.com/11135392/71553809-b14da100-2a26-11ea-9f0e-0fb5746d3fbd.png)

But it's not accessible by the link and the route:

![image](https://user-images.githubusercontent.com/11135392/71553818-c75b6180-2a26-11ea-9585-e07d3ed5d199.png)

It's required to restart the build to make the new page work.

**To Reproduce**

1. `yarn create docz-app docz-app-basic --example basic`
2. `yarn dev`
4. open the site
3. create `src/hello.mdx`
4. try to visit the new page, see 404 gatsby error

**Expected behavior**

It's expected that the new page will be available on fly.

**Environment**

- docz version: [latest, 2.2.0]
- OS: [OSX 10.14.6]
- Node/yarn version: [node 10.16.3/yarn 1.19.1]

**Comment by ShinyLeee** [comment]
Facing the same issue，do you find any workaround?

**Comment by twf-nikhila** [comment]
Facing same problem, the only way I figured out is terminating npm and building it again.

**Comment by kayosouza** [comment]
Same thing here, pages are not created on the .docz folder when the new build is generated.

**Comment by lttb** [comment]
it seems that an issue was caused by this fix: https://github.com/doczjs/docz/commit/dad228fff5cbe4c9f989d96a16f8f3c598b98bea#diff-10b0f76ede3ea173b8dda2af33c892a9

that fix stops `completely re-creating all pages on every file change`, but it also looks like that it stops creating new pages too

in example, `exports.createPages = require('./lib/createPagesStatefully')` works fine

so, in general, we should make efficient incremented updates for already created pages, but also still create new pages too

**Comment by rakannimer** [comment]
Hey @lttb,

I think you accurately described the problem and the solution. 
We need to replace createPagesStatefully back with createPagr

**Comment by rakannimer** [comment]
Hey @lttb,

I think you accurately described the problem and the solution. 
We need to replace createPagesStatefully back with createPagr

**Comment by jeffsjs** [comment]
Any precision of the solution?

**Comment by smeevil** [comment]
This is still an issue, any outlook on a solution?
