### ISSUE TITLE
Hide html native prop for typescript

### ISSUE THREAD

**Issue by gaoljie** [doczjs/docz#1341]
I am using styled components with typescript to write component,

this is the code
```js
import styled from "styled-components";
import Box, { BoxProps } from "../box";
import theme from "../theme";
import React from "react";

export interface CircleProps extends BoxProps {
  width?: string;
  color?: string;
  half?: boolean;
}

const Circle = styled.div<CircleProps>`
  width: ${props => props.width || "2px"};
  height: ${props => props.width || "2px"};
  display: inline-block;
  border: 1px solid ${props => props.color || theme.primary};
  background-color: ${props =>
    props.half ? "white" : props.color || theme.primary};
  border-radius: 50%;
`;

export default Circle;

```

and this is the documentation
```
---
name: Circle
---

import Circle from './index.tsx'
import { Props } from 'docz'

### Box Props
<Props of={Circle} />

```

It prints out print out all the HTML props, is there any way to filter the props? 
![image](https://user-images.githubusercontent.com/10665889/71760401-fbdd7c00-2e71-11ea-8375-e7906083ad0c.png)

for styleguidist, it has filter function for the props
https://github.com/styleguidist/react-docgen-typescript

**Comment by papeloto** [comment]
Also, having the option to remove the undefined prop will be nice since all of them are optional (not marked as required).

**Comment by rubencustodio** [comment]
This is still an issue, can we reopen?

**Comment by subhojit-cn** [comment]
I face the same issue. If props are optional then showing undefined. Please if anyone has an answer to resolve this that will be very helpful.
