### ISSUE TITLE
Props Component / Yarn Workspaces

### ISSUE THREAD

**Issue by PaulieScanlon** [doczjs/docz#1343]
## Is it possible to source components from another project in my yarn workspaces

I have the following x2 yarn workspaces

- MyProject
  -  src
    -  components
       -  some-component.js

- Demo
  - .docz
  - components
    -  some-file.mdx

Inside `some-file.mdx` i am able to import `some-component` and it renders using the `<Playground>` component but i see no prop table if i use `<Props of={SomeComponent} />`

I've see in the [Project Configuration](https://www.docz.site/docs/project-configuration) that it's possible to change the `src` in `doczrc.js` but i can't seem to get it working

I've tested the directory path is correct

`const directoryPath = path.join( process.cwd(), "../MyProject/src/components")`

 and i am able to see that all my "component" files are found when i log the `directoryPath` but i still see no prop table.

Any ideas?

**Comment by PaulieScanlon** [comment]
Ah ha! i think i've got it!

`const directoryPath = path.join( process.cwd(), "../MyProject/src/components")`

It's not `src` that i needed in `doczrc.js` but  ...

```js
export default {
  ...
  docgenConfig: {
    searchPath: directoryPath,
  },
}
```

The example from the monorepo helped me out 👉 doczrc.js](https://github.com/doczjs/docz/blob/master/examples/monorepo-separate-docs/packages/docs/doczrc.js)

**Comment by eddysims** [comment]
@PaulieScanlon I am having the issue where `<Props />` is not working. When I tried your solution, my console continues to run with this happening over and over again

```
success onPreExtractQueries - 0.005s
success extract queries from components - 0.053s
success write out requires - 0.014s
success onPreExtractQueries - 0.020s
success extract queries from components - 0.018s
success write out requires - 0.002s
```

did you happen to come across this issue as well?
