### ISSUE TITLE
.doczrc.js not ignoring README.md file

### ISSUE THREAD

**Issue by callil** [doczjs/docz#1345]
The README.md file is still showing up in my docs even though it's ignored in a .doczrc.js file as follows:

```
export default {
  title: 'Documentation',
  base: '/docs',
  ignore: [
    '**/blog/**',
    'readme.md',
    'changelog.md',
    'code_of_conduct.md',
    'contributing.md',
    'license.md'
  ],
  files: '**/*.{md,mdx}',
  menu: ['Getting Started', 'Components']
}
```

When I remove `md` from the files object the README.md file is correctly ignored. I'm using docz@next and gatsby-themedocz@next.

**To Reproduce**
Current repo where this happens: [https://github.com/callil/uniswap-io/tree/gatsby-docs](https://github.com/callil/uniswap-io/tree/gatsby-docs)

**Comment by callil** [comment]
ignore is case sensitive. defined `README.md` not `readme.md to resolve.

**Comment by 9oelM** [comment]
FYI rebooting with yarn dev is needed after changing `ignore` too..
