### ISSUE TITLE
How Good is the SEO of the documentation?

### ISSUE THREAD

**Issue by twf-nikhila** [doczjs/docz#1348]
## Question

**Description**

Hello,

I'm really loving this project. Looking forward to moving our documentation from Wordpress to docz, just wondering how is the SEO of the document generated?

Can anyone share some insights on it?

Thank you in advance.

**Comment by rakannimer** [comment]
Hey @twf-nikhila 

Happy to hear that !

docz is powered by Gatsby and generates fast static sites that search engines should love. For the rest, you can do everything you could in a wordpress site so it shouldn't be a problem !

If you'd like to customize your meta tags and/or keywords, check out how you can customize page metadata with react-helmet-async and the doc prop that docz injects to your wrapper here : https://www.docz.site/docs/add-favicon-and-metadata

I'm going to close this issue feel free to comment here or open a new one if there's anything not clear or not working as expected and I'll re-open 👍.

**Comment by twf-nikhila** [comment]
That's great, Thank you for helping
