### ISSUE TITLE
Playground Content is empty when Playground Component is nested in another Element

### ISSUE THREAD

**Issue by dsumer** [doczjs/docz#1351]
## Bug Report

**Describe the bug**

If the Playground Component is nested in any other element (see the Screenshot below) it is being rendered with an empty content. As soon as the Playground component is on the root level, everything works fine.

**To Reproduce**

Steps describing how to reproduce the issue:

1. create-docz-app my-docz-app && cd my-docz-app
2. Change src/index.mdx to

```mdx
### Some mdx content

<div>
  <Playground>
    <span>asd</span>
  </Playground>
</div>
```

4. Run npm run docz dev
5. See empty Playground

**Expected behavior**

Playground Content shouldn't be empty when it is nested in any elements.

**Environment**

- docz version: 2.2.0
- OS: Ubuntu
- Node/npm version: node 10 / npm 6

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/4418879/72077020-d7acef80-32f6-11ea-9abf-cae73313e95e.png)

**Comment by nlopin** [comment]
Same thing if `Playground` is surrounded by other JSX components:

```
<Header>Playground</Header>
<Playground>
    <Icons.Gear/>
</Playground>
<Header>Next header</Header>
```

But it works when you put empty lines above and below the Playground:
```
<Header>Playground</Header>

<Playground>
    <Icons.Gear/>
</Playground>

<Header>Next header</Header>
```

**Comment by rakannimer** [comment]
It looks like `rehype-docz` is not adding the right props to Playground when it is not in the top-level.

https://github.com/doczjs/docz/blob/master/core/rehype-docz/src/index.ts
