### ISSUE TITLE
Plugin development broken?

### ISSUE THREAD

**Issue by StevenLangbroek** [doczjs/docz#1361]
## Bug Report

**Describe the bug**

I'm trying to use plugins, but can't seem to get it to resolve a local path.

**To Reproduce**

1. create a file (e.g., `config/plugin.js`)
2. create a basic plugin that operates on `modifyFiles`:

```js
import { createPlugin } from 'docz-core';

const filesPlugin = createPlugin({
  modifyFiles: files => {
    console.log('Hello from plugin');
    return files.filter(file => {
		return file.indexOf('whatever') !== -1;
	});
  }
});

export default filesPlugin;
```

3. try to reference it from config like so:

```js
export default {
  plugins: ['./config/plugin'],
  // also tried:
  // - importing the plugin and putting the reference there
  // - creating the plugin inline
  // - using object notation with { resolve: './config/plugin' }
  // - using `path.resolve`
}
```

Result is either a warning saying `Module not found: ./config/plugin`, or simply no effect. Plugin is *never* run.

```shell
FOR BUGS: Insert debug trace
```

**Expected behavior**

Be able to use plugin

**Environment**

- docz version: 2.2.0
- OS: OS X
- Node/npm version: Node 12 LTS

**Comment by rakannimer** [comment]
Hey @StevenLangbroek, 

Thanks for reporting this. I was able to reproduce the error. But when creating the plugin inline it worked : 

```js
// doczrc.js
import { createPlugin } from 'docz-core'

const filesPlugin = createPlugin({
  modifyFiles: files => {
    console.log('Hello from plugin')
    return files.filter(file => {
      return file.indexOf('README') !== -1
    })
  },
})

export default {
  plugins: [filesPlugin],
}
```

Could you please confirm that this also doesn't work on your setup while we investigate the rest of the failing cases ?

**Comment by StevenLangbroek** [comment]
Sorry, you're right, that works.

**Comment by pedronauck** [comment]
I assume that this issue is closed 🙌
