### ISSUE TITLE
using the src or files property throws "Error: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by sag1v** [doczjs/docz#1367]
I am migrating to Docz v2. Actually it was so hard to migrate i just removed Docz and started all over by following the documentations.

Everything seems to work fine so far except 2 properties in the `doczrc.js` file: The `src` and the `files` properties.

When i try to use only the `src` for example:
```
...
src: './src',
...
```

And running  `yarn docz:dev`  I get an error in console:
> Error: ENOENT: no such file or directory, open 'C:\Users\<path_to_my_lib>\node_modules\gatsby\src\internal-plugins\dev-404-page\gatsby-node.js'

When i remove it and run  `yarn docz:dev`  again, it works as expected.

I tried deleting `.docz` , `node_modules` , `yarn.lock` and installing again, or using the @next version of Docz, no luck.

This happens when i use either `src` or `files` properties (together or just one of them), I need this properties because i want Docz to ignore the `.md` files on my root folder, files like `CODE_OF_CONDUCT.md` or even `README.md`.

<strike>It also seems that the `ignore` property is not working, as this was supposed to bypass those files by default.</strike>
OK, seems like `ignore` is case sensitive and the default file names are in lower case while my files were upper case. (reference #1345  ) 

**Stack trace on bottom**

I don't have a way to reproduce it because as i said i was in the middle of migration / re-installing docz from scratch.

**Environment**

- docz version: 2.2.0 || 2.3.0-alpha.6
- OS: Windows 7
- Node/yarn/npm version: Node v10.14.2/ yarn v1.6.0/ npm v6.4.1 

I'm working with Yarn though.

---
**stack Trace with the error**

```
UNHANDLED REJECTION ENOENT: no such file or directory, open 'C:\Users\path_to_my_lib\node_modules\gatsby\src\internal-plugins\dev-404-page\gatsby-node.js'



  Error: ENOENT: no such file or directory, open 'C:\Users\path_to_my_lib\node_modules\gatsby\src\internal-plugins\dev-404-page\gatsby-node.js'

  - api-runner-node.js:357 Promise.catch.err
    [my_lib_name]/[gatsby]/src/utils/api-runner-node.js:357:27

  - From previous event:

  - api-runner-node.js:338 Promise.mapSeries.plugin
    [my_lib_name]/[gatsby]/src/utils/api-runner-node.js:338:14

  - api-runner-node.js:214 done
    [my_lib_name]/[gatsby]/src/utils/api-runner-node.js:214:11

  - gatsby-node.js:24 FSWatcher.chokidar.watch.on.on
    [my_lib_name]/[gatsby]/src/internal-plugins/dev-404-page/gatsby-node.js:24:26

  - From previous event:

  - api-runner-node.js:330 resolve
    [my_lib_name]/[gatsby]/src/utils/api-runner-node.js:330:13

  - From previous event:

  - api-runner-node.js:246 apiRunnerNode
    [my_lib_name]/[gatsby]/src/utils/api-runner-node.js:246:3

  - index.js:495 module.exports
    [my_lib_name]/[gatsby]/src/bootstrap/index.js:495:9


not finished createPagesStatefully - 0.155s
```

**Comment by ParamagicDev** [comment]
So I ran into a similar problem when creating my docz site. I forget exactly what was happening, but when changing the value of `src` it totally messed with docz. My solution to avoid the root README.md was to have the follow `doczrc.js`:

```javascript
export default {
  // above code omitted
  files: "./src/**/*.{md,markdown,mdx}",
}
```

[Link to my doczrc.js](https://github.com/ParamagicDev/ma-protocol-rewrite/blob/master/doczrc.js)

Let me know if the above fix works for you.

**Comment by sag1v** [comment]
The ignore property worked for me, as i mentioned i used upper case file names instead of lower case.

**Comment by ParamagicDev** [comment]
Gotcha, so the ignore / src / files properties aren't the issues.

Do you have a repo you could link to? See if I could recreate the issue?

**Comment by sag1v** [comment]
>Also, have you tried running gatsby clean or deleting your .cache directory?

I did delete the `.cache` directory and it didn't help at that time.

>Do you have a repo you could link to? See if I could recreate the issue?

This is the repo: [react-elastic-carousel](https://github.com/sag1v/react-elastic-carousel)
But i already migrated to the new docz (with gatsby)

**Comment by jesperorb** [comment]
Closing this as it sounds like your issue is resolved. But you say and I can reopen if there is still an issue with these properties.
