### ISSUE TITLE
css file returned as html

### ISSUE THREAD

**Issue by abdullahtariq1171** [doczjs/docz#1369]
## Bug Report

**Describe the bug**

CSS file returns as HTML mimetype. (added through react-helmet; see repo ) 

I have also added bootstrap from CDN which works fine, the issue is only with local CSS file.

**To Reproduce**

https://github.com/abdullahtariq1171/my-docz-app/
Simply run `yarn && yarn dev`

**Expected behavior**

It should return the file as CSS

**Environment**

- docz version: ^2.3.0-alpha.6
- OS: macos Catalina 10.15.2 (19C57)
- Node/npm version: node v10.16.3 /yarn 1.21.1

**Additional context/Screenshots**

![Console logs](https://monosnap.com/image/IsOBGy9yXrRQv9o7LwoDInWxixRr2x)

![Network request](https://monosnap.com/image/wozfkj5gyrs8vJV0FGE0mv3H3FlABb)

**Comment by alexandre-lelain** [comment]
Hello,

From what I understand, `Docz` doesn't take into account single css files when not imported as modules in some react components.

However, if you still want to add global style with css, what you can do is to create a `gatsby-browser.js` file at the root of your project and import your css file in it:
```js
// gatsby-browser.js
import "../src/global.css"
```

> Note: the path begins by `../` because the file will be loaded from the `.docz/` folder during compilation.

**Comment by arecvlohe** [comment]
I have tried several variations of trying to serve up my file that provides global styles. It also includes tailwindcss directives. Although, the main issue is that it's never injected into the head of the app. I am not using react-helmet in my app. It works locally when I use `wrapper.js` component, but when what I am doing never works for a build.

**Comment by andregamma** [comment]
Hey @arecvlohe I've been trying to use tailwindcss with docz, but I am having several problems. It's been 4 months, have you managed to make it work?

**Comment by hamfz** [comment]
I am not sure if this is still a problem with gatsby, but the issue of an imported CSS file not being resolved in production (`docz:build` and `docz:serve`) is still present.

I got around this by using component shadowing to override some of the core components and import my stylesheets there through a `Styles` component

**Comment by arecvlohe** [comment]
> Hey @arecvlohe I've been trying to use tailwindcss with docz, but I am having several problems. It's been 4 months, have you managed to make it work?

No, I've moved on.
