### ISSUE TITLE
How can I disable the --open browser?

### ISSUE THREAD

**Issue by hbrls** [doczjs/docz#1374]
## Question

**Description**
 
The `--open` is a cli option of gatsby. How can I disable it?

`docz dev --open=false` takes no effect.

`docz-config.js openBrowser: false` takes no effect.

**Comment by rakannimer** [comment]
Hey @hbrls,

Thanks for reporting this, it should be fixed in `2.3.0-alpha.11`, you can try it now with `docz@next` or in `2.3.0` when it is released 👍
