### ISSUE TITLE
Make results of <Props> iterable

### ISSUE THREAD

**Issue by droganov** [doczjs/docz#1375]
Branched from https://github.com/doczjs/docz/pull/1371#issuecomment-579845270

I suggest to change `<Props>` so it would accept function child and that child could be used to manipulate rendered rows.

```jsx
<Props of={UiComponent}>
  {renderedProps => children.filter(propRow => propRow.componentName === 'UiComponent')}
</Props>
```

We also need to inject metadata (component name and path) as a static members, to make that manipulate meaningful

```javascript
({ of, children }) => {
  const result = Object.entries(of).map(renderPropAndInjectMetadata);
  return typeof children === 'function' ? children(result) : result; 
}
```

**Comment by droganov** [comment]
@mickaelzhang 

> What you are describing is possible right now by shadowing the <Props /> component already btw

Could you post an example? I traced Props output, and I can see rows are wrapped, and I can't manipulate them.

**Comment by mickaelzhang** [comment]
Could you add a use case example? When would you need to filter this way?

> Could you post an example? I traced Props output, and I can see rows are wrapped, and I can't manipulate them.

You must shadow the component (meaning that you need to create a `gatsby-theme-docz/components/Props/index.js` file) in your project. And then probably do something similar to this:

```js
import { Props as DoczProps } from 'docz'

export const Props = ({ props, ...others }) => {
  const displayedProps = props.filter(propRow => propRow.componentName === 'UiComponent'))

  return <DoczProps props={displayedProps} {...others} />
}
```

> We also need to inject metadata (component name and path) as a static members, to make that manipulate meaningful

I have no idea for the injection of meta data as I don't know the project enough but filtering by component use sounds like a valid case. @rakannimer might have an idea about this part.




What you want to do currently, if I understand correctly, is to not change the rendered element (you still want the Table from `docz`) but only filter the row right?

As of how would we do it, I think that `children` might not be the best candidate? `children` is deeply linked to the rendered element which will make it confusing for developers.

Another way would be:
```js
<Props of={Component} filter={propRow => propRow.componentName === 'UiComponent')}/>
```

**Comment by droganov** [comment]
@mickaelzhang the use case — I want split props into groups for every component in my UI lib.

It looks I can do that with the HOC, I will try to do so and post update.

as for injecting, I think it could be something like this:

```
const row = <div>ya-da</div>
;
return Object.assign(row, someProps);
```

**Comment by mickaelzhang** [comment]
@droganov Correct me if I'm wrong but if you must split into group all your component in your UI lib, then you case is similar to mine? Then shadowing the Props component of the docz theme is probably better for you

With the solution that you propose you would need to filter everytime you use `<Props />`, with the shadowing you would just filter it once

**Comment by droganov** [comment]
Yes, basically what I want is inserting a component name.

Will try it in a day or so.

**Comment by mickaelzhang** [comment]
Any new on this @droganov?

**Comment by droganov** [comment]
@mickaelzhang I'm sorry, I could'n do it fast.
Will try next week, travelling ATM

**Comment by mickaelzhang** [comment]
I'll close this issue for now @droganov, the current solution in place in `docz` should work for you

Feel free to reopen a PR later if needed :)
