### ISSUE TITLE
Cannot read property 'getElementsByTagName' of null while navigating

### ISSUE THREAD

**Issue by tianhaoz95** [doczjs/docz#1376]
## Bug Report

**Describe the bug**

Error `Cannot read property 'getElementsByTagName' of null` was thrown while navigating from one page to another with sidebar when the site is deployed on GitHub Pages. As a result, the page is blank. However, after a refresh on the URL, the content will show up.

**To Reproduce**

The site source code: https://github.com/tianhaoz95/iwfp/tree/master/iwfphome
Deploy script to GitHub Pages:
https://github.com/tianhaoz95/iwfp/blob/c6912c29e6c350cb70983f17bc22deaf2346e737/.github/workflows/release_docs.yml#L61-L90

**Expected behavior**

It should navigate to the page and show its content.

**Environment**

- docz version: latest
- OS: GitHub should be hosting it in some Linux docker
- Node/npm version: Node v12.14.1/NPM 6.13.4

**Additional context/Screenshots**
<img width="1259" alt="Screen Shot 2020-02-01 at 7 34 36 PM" src="https://user-images.githubusercontent.com/16887772/73602505-e79ca580-4529-11ea-8e65-92d1be7f0069.png">

**Comment by donglinkai** [comment]
I got same issue

**Comment by 0ctothorp** [comment]
I get the same error, but on local and when trying to use `ThemeProvider` from `theme-ui` in my doc page:
```jsx
<Playground>
  <ThemeProvider theme={preset}>
    <MyComponent />
  </ThemeProvider>
</Playground>
```
After refresh I get: `TypeError: Cannot read property 'plain' of undefined`.

**Comment by BestDingSheng** [comment]
I got same issue

**Comment by nanxiaobei** [comment]
I got same issue

**Comment by jcowman2** [comment]
Not stale, I have the same issue.
