### ISSUE TITLE
How to locate MDX files in other package

### ISSUE THREAD

**Issue by floriangosse** [doczjs/docz#1377]
We have a monorepo for our design-system where we store the MDX documentation files next to our implementation code. One part of our design-system is a CSS-only package that has some documentation in it as well.

Right now I have the problem that the components inside of our React package can't resolve `@emotion/core` which isn't a dependency. I assume that this problem occurs because of some transformations made by docz.

```
ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve '@emotion/core' in '/Users/floriangosse/code/design-system/packages/design-system-react/src/components'

File: ../../packages/design-system-react/src/components/Button.js
```

The packages are structured in this way:
```
.
├── docs
│   ├── doczrc.js
│   ├── gatsby-config.js
│   ├── gatsby-node.js
│   └── package.json
├── packages
│   ├── design-system
│   └── design-system-react
├── lerna.json
└── package.json
```

**Comment by rakannimer** [comment]
In order for docz to render your code, it needs to be able to use your dependencies. 

When you install it in a separate package outside of the packages in the workspace it won't be able to use them.

You have 3 choices here : 

- Tell webpack in docz to look for dependencies in two folders `/docs/node_modules` and `/docs/node_modules` (Not recommended)

```js
// gatsby-node.js
const path = require('path')

exports.onCreateWebpackConfig = args => {
  args.actions.setWebpackConfig({
    resolve: {
      // Note the '..' in the path because the docz gatsby project lives in the `.docz` directory
      modules: [path.resolve(__dirname, '../../node_modules'), 'node_modules']
    },
  })
}
```

- Put docs in packages directory : https://github.com/doczjs/docz/tree/master/examples/monorepo-separate-docs

- Put docz at root of your workspace : https://github.com/doczjs/docz/tree/master/examples/monorepo

**Comment by floriangosse** [comment]
I came up with a solution.

I switched from using only `docz` to `gatsby` and `gatsby-theme-docz`. I think that was the key point for my solution because it seemed that `docz` had problems with looking up the correct folders.

Even your first solution (@rakannimer) didn't work for me. 

This is how my working configuration looks now.

```js
// gatsby-config.js
module.exports = {
    plugins: [
        'gatsby-theme-docz'
    ]
};
```

```js
// gatsby-node.js
const path = require('path');

exports.onCreateWebpackConfig = ({ actions }) => {
    actions.setWebpackConfig({
        resolve: {
            modules: [
                'node_modules',
                path.resolve(__dirname, 'node_modules')
            ]
        }
    });
};
```

```js
// docz.js
module.exports = {
	// This workaround is required because of https://github.com/doczjs/docz/blob/84bdae414b41c1673cbb7ba0827379c1b3e9d5e0/core/gatsby-theme-docz/gatsby-config.js#L54
    src: './node_modules/../',
    files: [
        'pages/**/*{md,mdx}',
        'node_modules/@truffls/design-system/src/**/*{md,mdx}',
        'node_modules/@truffls/design-system-react/src/**/*{md,mdx}'
    ],
	// ...
};
```
