### ISSUE TITLE
Docz with TSX and React JS

### ISSUE THREAD

**Issue by yehbrian** [doczjs/docz#1379]
Hey everyone. i'm trying to use docz and have my props display. Currently its working with all my JS components. However, i just added my first TSX component which means in my doczrc.js i added   typescript: true into the file. This made my TSX File display correctly along with the props. However, all my other JS components don't display the correct Props anymore. I'm assuming this is because the props are in different places between a JS component and a TSX component and once i do typescript: true, it searches for the props in the interface of a typescript file (which isn't in the normal react JS components). Is it possible to have both TSX and react JS components in the same Docz environemnt? and if so, does anyone know how to set it up? Thanks!

**Comment by rakannimer** [comment]
Hey @yehbrian, thanks for reporting this. 

Support for both TSX and JSX React components at the same time is not currently possible. However we're planning on updating react-docgen to the latest version that supports both TSX and JSX parsing. 

Will keep this in mind when we update to make sure your use-case will be solved 👍 

Happy to help if someone would like to submit a PR.
