### ISSUE TITLE
docz serve not reading supplied port

### ISSUE THREAD

**Issue by tylerthehaas** [doczjs/docz#1380]
## Bug Report

port is not read from configuration files or env vars when running `docz serve`

add DOCZ_PORT to .env and run `docz serve` 

or 

run `docz serve --port 7000`

**Expected behavior**

expect to run on supplied port

**Environment**

- docz version: 2.2.0
- OS: OSX 10.14.2
- Node/npm version: Node 12.8.1/6.13.1

**Comment by rakannimer** [comment]
Thanks @tylerthehaas for reporting this. It's fixed in docz@2.3.0-alpha.10 (yarn add docz@next) and will be released with docz@2.3.0
