### ISSUE TITLE
Cannot create as TypeComposer the following value: Date

### ISSUE THREAD

**Issue by mcntsh** [doczjs/docz#1385]
## Bug Report

I get an error building the schema when integrating docz into an existing project.

![Screenshot 2020-02-10 at 14 09 07](https://user-images.githubusercontent.com/1314484/74152794-5acfa700-4c0f-11ea-9e5d-0948346dcf71.png)

**Expected behavior**

Dev server goes up

**Environment**

- docz version: [e.g. 2.0.0-rc.x or 1.3.2]
- OS: [e.g. OSX 10.13.4, Windows 10]
- Node/npm version: [e.g. Node 8/npm 5]

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by alexandre-lelain** [comment]
Hello,

Are you using `lerna` ? You might have duplicated instances of `graphql`. It seems some people had the same problem on some Gatsby issues.

Removing the `node_modules` & the `.lock` file, and making a fresh `install` seemed to work for them. I also had to follow those steps to integrate `Docz` in an existing project.

I still don't know why the `.lock` file was causing version mismatch... 🤔 

Anyway, I hope that helps :)

**Comment by mihai-ro** [comment]
I am facing this same error; removing `node_modules` and the `.lock` file, and freshly installing it did not fix it 😞 
I do have other dependencies in the app (`aws-appsync` and `aws-amplify`) that have `graphql` as a dependency and they indeed reference a different version than the one `gatsby` uses. So I tried forcing resolutions on all three of them, but this still did not fix it.

Any suggestions or updates on this topic?

**Comment by mcntsh** [comment]
I do have Lerna. I had to update GraphQL and did a fresh install which seemed to do the trick. Thanks for the help!
