### ISSUE TITLE
remark-docz prevents markdown from rendering as React components children

### ISSUE THREAD

**Issue by homearanya** [doczjs/docz#1386]
In some instances one needs to render markdown as React Components children. 

At the moment, you can do this by leaving a blank line between the React component tag and the markdown content. For example:

```
<Notice type={"tip"} title={"Side note"}>

does this `really` work?

</Notice>
```

However, due to the remark-docz plugin this is not possible when using gatsby-theme-docz. Is there anyway you can change gatsby-theme-docz options so that you can opt-out remark-docz. At the moment, this is not possible due to the way gatsby-config.js is coded. 

Otherwise, can you suggest any workaround?

Many thanks

**Comment by rakannimer** [comment]
Hey @homearanya, are you sure that the problem comes from remark-docz ? I was able to reproduce it with just gatsby and mdx. 

In terms of workarounds I'm not sure what I can recommend other than leaving a blank line 🤔 .

**Comment by homearanya** [comment]
When I comment out remark-docz on gatsby-theme-docz's gatsby-config, it works with the blank line. With remark-docz it doesn't. 

Somebody else experienced the same issue a while back: https://github.com/mdx-js/mdx/issues/628#issuecomment-529551009

**Comment by rakannimer** [comment]
Oh that's weird then, I'm not able to reproduce 🤷‍♂ 

You've commented out require('remark-docz') in `node_modules/gatsby-theme-docz/gatsby-config.js` and were able to get "really" to be rendered as markdown using something like this : 
`<div>does this `really` work?</div>`

We can add a flag to the config if someone would like to submit a PR, I'm just curious about what I'm missing in the repro.

**Comment by homearanya** [comment]
Yes, that's right. I commented out require('remark-docz') in `node_modules/gatsby-theme-docz/gatsby-config.js` and I was able to render markdown as children

```
---
name: Getting Started
route: /
---

import Box from "../src/components/box"

# Getting Started

## Hello world

Type here the most beautiful getting started that you ever saw!

<Box>

does this `really` work?

</Box>
```
rendered as

```
...
<div>
   <p class="css-1ftn47p">
        does this
        <code class="css-ueqitl">really</code> 
        work?
   </p>
</div>
...
```
If I don't comment out "render-docz" I get:
```
<div>work? really does this</div>
```

This is the test repo: https://github.com/homearanya/tester-docz

**Comment by 0phoff** [comment]
Getting the same issue, I cannot nest markdown inside of react components with docz.  
```md
<Component>

this component has _markdown_ styled `text` inside.

</Component>
```

The above does not handle the inner markdown properly, like I'm used to with MDX.  
It just outputs the raw text as a node, instead of properly parsing the markdown and returning:
```html
<p>this component has <em>markdown</em> style <pre>text</pre> inside.</p>
```
