### ISSUE TITLE
Shadowing the MainContainer does not reflect in the browser

### ISSUE THREAD

**Issue by ParamagicDev** [doczjs/docz#1387]
## Bug Report

**Describe the bug**

Shadowing the MainContainer component is not being reflected in the browser

**To Reproduce**

Right now, the following file is located at `./src/gatsby-theme-docz/components/MainContainer/index.js`

```javascript
/** @jsx jsx */
import { jsx } from 'theme-ui'
import React from 'react'
import Title from "../../../components/title.js"
import { MainContainer as OriginalMainContainer } from 'gatsby-theme-docz/src/components/MainContainer/index.js'

export const MainContainer = props => {
  return (
    <div>
      <Title title={document.title} />
      <OriginalMainContainer {...props} />
    </div>
  )
}
```

However, when I refresh my browser, the change does not appear. I have tried refreshing `node_modules`, rebuilding my docker container, and removing the `.cache/` directory with no luck.

My repo with the commit trying to use the shadowed component:
[https://github.com/ParamagicDev/ma-protocol-rewrite/tree/c5d0aa3d17d289172a52553ac81317d60699da34](https://github.com/ParamagicDev/ma-protocol-rewrite/tree/c5d0aa3d17d289172a52553ac81317d60699da34)

I have noticed this error message everytime I refresh as well.

` [Violation] 'setTimeout' handler took 273ms app.js:66`

There are no errors on the gatsby terminal however.

**Expected behavior**

I expected the Title to be inserted however it does not get inserted and the component does not get shadowed. I have no issues shadowing the `wrapper.js` component.

**Environment**

- docz version: 2.2
- OS: Debian-stretch-slim (via Docker)
- Node version: Node 12.14.0

**Comment by mickaelzhang** [comment]
Hello @ParamagicDev!
I was the one that created the `MainContainer` component, I'll look into and see if I can reproduce the error when I have a bit of time

**Comment by ParamagicDev** [comment]
Awesome, let me know if there is any way I can help you reproduce the problem at all. I'd be more than willing to help in any way I can.

**Comment by ParamagicDev** [comment]
I just checked via Tags and the MainContainer does not exist in version 2.2. It only exists in 2.3.0-Alpha. Ill try upgrading to 2.3.0 if the main container shadowing works.

**Comment by mickaelzhang** [comment]
Hello @ParamagicDev! I didn't had time yet to dig into it, sorry 🙏
Thank's for the additional info though, I'll let you know when I will

**Comment by mickaelzhang** [comment]
@ParamagicDev I had a bit of time to investigate the issue. I did my test on both my company's project and on the dev environment of docz, the issue seems to come from using the `MainContainer` component of `docz` in your own. 

This issue is present for all component that we can shadow, I can't pinpoint why it does that as I don't know the in and out of docz. Maybe @rakannimer might have an idea?

What I would recommend, for now at least as a quick solution, would be to not use docz's `MainContainer` as it doesn't to much (a max width and margin auto).

**Comment by ParamagicDev** [comment]
Yea right now I have a pretty hacky work around. Basically I wanted to use the MainContainer to add both Pagination and the Title without having to set both within every `.mdx` file.

As of right now my workaround is to add in my Title and PageNav components into the `./src/gatsby-theme-docz/wrapper.js` file and then in the `./gatsby-browser.js` run a query selector on the PageNav and Title components and insert them into the MainContainer component using the `onRouteUpdate` lifecycle method provided by Gatsby. The one issue I've run into is it requires manually refreshing of pages to have everything render correctly on the page when developing.

[./src/gatsby-theme-docz/wrapper.js](https://github.com/ParamagicDev/ma-protocol-rewrite/blob/d90b75a814fbae8bd4a352c432e065d172fd0bcf/src/gatsby-theme-docz/wrapper.js)
[./gatsby-browser.js](https://github.com/ParamagicDev/ma-protocol-rewrite/blob/d90b75a814fbae8bd4a352c432e065d172fd0bcf/gatsby-browser.js)

[Full repo of my latest commit](https://github.com/ParamagicDev/ma-protocol-rewrite/tree/d90b75a814fbae8bd4a352c432e065d172fd0bcf)

I'm fairly new to React so I'm thinking of using the [useEffect](https://reactjs.org/docs/hooks-reference.html#useeffect) hook provided by React in the `wrapper.js` file to automatically place the PageNav and the Title into the proper spot inside the MainContainer every time the wrapper renders rather than onRouteUpdate.

**Comment by mickaelzhang** [comment]
Hello @ParamagicDev! Any news on this? Let me know if you found a solution! :)

**Comment by ParamagicDev** [comment]
I did not find a solution. I even tried just using a plain div and it still didn't shadow properly. I don't know enough about docz to begin troubleshooting it either.

**Comment by mickaelzhang** [comment]
I cloned your repo and looked a bit, it comes from the version of `gatsby-theme-docz`, you need to upgrade it, `MainContainer` doesn't exist in the version that is currently installed on your project! :)

**Comment by ParamagicDev** [comment]
Oh wow! Thank you @mickaelzhang  so much! I'll close this issue in that case.
