### ISSUE TITLE
How to use in a non-lerna monorepo ?

### ISSUE THREAD

**Issue by Thebigbignooby** [doczjs/docz#1393]
I have a monorepo which is not a lerna repo.

I want to use Docz for all my `README.md` files as well as my `deep/nested/components/Component/Component.mdx` files

Project looks something like this
```
.
├── folder-to-ignore
├── database
├── ci
├── doc
│   ├── apples.md
│   ├── bananas.md
├── docz-website
│   ├── .docz
│   ├── doczrc.js
│   └── package.json
├── ...other-folders
├── services
│   ├── service_1
│   └── service_2
│   └── frontends
│       └── tomato
│       │   └── README.md
│       └── potato
│       │   └── README.md
│       └── src
│       │   └── components
│       │       └── Button
│       │           └── Button.js
│       │           └── Button.mdx
│       └── package.json
│       └── README.md
└── README.md
```

I have followed the documentation, but somehow things still don't work.
I have looked at the monorepo examples, but they don't fit this usecase.

My main question is, how do I get this to work with my folder structure ?

sub questions are:
- what is the `doczrc` `src` config for me ? 
    - the project root ?
    - or the *components* folder as stated on the docz website ?
- how do I ignore `folder-to-ignore` ?

**Comment by mgallagher** [comment]
Similar situation here, and not sure how to handle it.

Setting `src` to be `../` would allow Docz to find all your md/mdx files, but Gatsby will still parse all `.md`, `.js`, files in `folder-to-ignore`, `ci`, etc., which in our case slows things down considerably and produces lots of errors. You might have better luck though.

The `files` and `ignore` settings don't really help our situation either. Changing the `files` setting to only include the directories we DO want does _not_ change what files get parsed during the build, and `ignore` is filtered based on the results of the `files` glob pattern.

Some related issues:
#1334
#1329

It seems like the best way to do this right now would be to add an exclusions for those directories at the webpack level.

**Comment by treshugart** [comment]
I've been having the same issue. I was able to work around it by explicitly ignoring the files I don't want parsed instead of specifying the source.

The problem here is you have to specify each one individually, but you can use `glob` (I used `fast-glob`) to work around that:

```js
const glob = require('fast-glob')

export default {
  files: 'docs/**/*.{md,mdx}',
  ignore: [...glob.sync('{other,dirs}/**/*.{md,mdx}'), 'README.md'],
}
```

It really feels like you should be able to specify only `files` and have it work in the same way, but hopefully this helps someone.

**Comment by treshugart** [comment]
Ok, the above seemed to work with a warm cache, but failed on initial builds. I actually couldn't get consistent results from the build. However, I did find a solution that works by creating a plugin and forcing the `files` option:

```js
// doczrc.js

import glob from 'fast-glob'
import path from 'path'
import tmp from 'tmp'
import { createPlugin } from 'docz-core'

const work = () => {
  // I'm not sure how we can maintain state on the Docz plugin (`this` is
  // `undefined`) so we have to do it in scope.
  let files
  return createPlugin({
    setConfig(config) {
      // Docz doesn't allow you to specify multiple sources and we don't want
      // it to parse everything, so we must tell it to parse nothing,
      // initially, and then supply it specific files via modifyFiles.
      const dir = tmp.dirSync()

      // Doing this allows us to reuse the existing configuration option and
      // provide expected behavior.
      files = config.files

      return {
        ...config,
        src: dir.name,
      }
    },
    modifyFiles() {
      // Docz operates in the .docz/ folder, so we have to resolve our actual
      // root path to glob from there. Just using ".." messes up resolution
      // inside of Gatsby.
      const root = path.resolve('..')
      return glob.sync(path.join(root, files))
    },
  })
}

export default {
  files: '{your,dirs}/**/*.{md,mdx}',
  plugins: [work()],
}
```

**Comment by kilianc** [comment]
I actually found the problem:

```
files: ['README.md', '**/*.test.mdx']
```

if `README.md` is missing there is no output.
