### ISSUE TITLE
How to customize components of the theme?

### ISSUE THREAD

**Issue by superhos** [doczjs/docz#1394]
I used the `gatsby-theme-docz` as below.
````javascript
// gatsby-config.js
module.exports = {
  plugins: ['gatsby-theme-docz'],
}
````
I don't have any source code for this theme in my project.
But the document told me 
> Components shadowing is one of the best things included in the new Gatsby theme feature, with it is possible to replace theme files just by creating your own file following a file naming convention.
Example: If you're using our gatsby-theme-docz which has a Header component located at src/components/Header/index.js you can override the component by creating src/gatsby-theme-docz/components/Header/index.js. Cool right?

Is that mean I need to download the theme's source code to my project and rewrite the target component if I want to customize components of this theme?

**Comment by mickaelzhang** [comment]
Hello @superhos,

You don't need to download the source code, but you must know the structure of docz's theme to shadow a component.

There is an example where we shadow the playground here:
https://github.com/doczjs/docz/tree/master/examples/shadowed-playground

The documentation of gatsby is also quite detailed if you need more info:
https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/

Hope it helps, let me know if you have any questions! :)

**Comment by superhos** [comment]
> Hello @superhos,
> 
> You don't need to download the source code, but you must know the structure of docz's theme to shadow a component.
> 
> There is an example where we shadow the playground here:
> https://github.com/doczjs/docz/tree/master/examples/shadowed-playground
> 
> The documentation of gatsby is also quite detailed if you need more info:
> https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/
> 
> Hope it helps, let me know if you have any questions! :)

It seems to solve my problem
Thanks a lot!
