### ISSUE TITLE
Package exports for #longpath# do not define a '.' subpath

### ISSUE THREAD

**Issue by stolinski** [doczjs/docz#1398]
## Bug Report

**Describe the bug**

Adding Docz to an existing TSDX project. First time running `docz:dev` gives 
```
Generating SSR bundle failed

[BABEL] /Users/scotttolinski/Sites/fresh-forms/.docz/.cache/develop-static-entry.js: Package exports for '/Users/scotttolinski/Sites/fresh-forms/node_modules/@babel/preset-env/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath

File: .cache/develop-static-entry.js

```

**To Reproduce**

clone https://github.com/leveluptuts/fresh

re-install docz or try to run `docz:dev`

**Expected behavior**

A build to happen.

**Environment**

- docz version: 2.2.0
- OS: 10.13.4
- Node/npm version: Node 13.1

**Comment by stolinski** [comment]
Bummer. This is still a problem and the reason I don't use Docz currently.

**Comment by jesperorb** [comment]
Seems like an issue with our version of Babel and running node `13`, can you try if you get the same problem with node `12` or earlier?
https://github.com/babel/babel/pull/11006

We will look into updating `babel` to a later version if that is the problem.
