### ISSUE TITLE
gatsby-node file not be used in running time.

### ISSUE THREAD

**Issue by superhos** [doczjs/docz#1401]
## Relevant information
I used docz for building my own website. 
And I found webpack's config in gatsby-node.js is not working. Config file as below.

````javascript
// gatsby-node.js
const path = require('path')
const I18nMergePlugin = require('./webpack/plugins/i18n-merge-plugin')

exports.onCreateWebpackConfig = ({
  actions,
  plugins
}) => {
  actions.setWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, '../src'), path.resolve(__dirname, '../components'),  'node_modules'],
      alias: {
        'cpin': path.resolve(__dirname, '../components')
      }
    },
    plugins: [
      ...plugins,
      new I18nMergePlugin({
        output: './components/locale/_comp'
      })
    ]
  })
}
````
Couldn't use the alias and the plugin not fired.
And I have tried to add some code like this: `process.exit(1)` on the top of the `gatsby-node`. Still not Influence.

Any idea about this issue?
Thanks.

**Comment by ParamagicDev** [comment]
Probably a stupid question, but is the file simply named `gatsby-node` or is it `gatsby-node.js`?

**Comment by superhos** [comment]
> Probably a stupid question, but it's worth asking, is the file simply named `gatsby-node` or is it `gatsby-node.js`?
> 
> To do what you're trying to do, Gatsby reads from `gatsby-node.js`

Actually, the file name is correct. `gatsby-config.js` can be called but `gatsby-node.js` not.
It seems more like the issue for gatsby. I will found the answer in gatsby.
