### ISSUE TITLE
Playground does not accept function as child

### ISSUE THREAD

**Issue by otakustay** [doczjs/docz#1402]
## Bug Report

**Describe the bug**

I have a simple `.mdx` including a `Playground` component with a function child, copied from [official documentation](https://www.docz.site/docs/built-in-components)

```mdx
---
name: Hello world
route: /
---

# Hello world

Hello, I'm a mdx file!

## Button

<Playground>
  {() => {
    const [counter, setCounter] = React.useState(0)
    return (
      <>
        <button onClick={() => setCounter(counter => counter+1)}>
          Increase
        </button>
        <p>{counter}</p>
      </>
    )
  }}
</Playground>
```

When I run `docz dev`, there is no playground content in browser and I got an error message:

```text
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
```

**To Reproduce**

Follow the steps described above

**Expected behavior**

It should render a button and a counter value as epxected

**Environment**

- docz version: 2.2.0
- OS: macOS 10.15.3
- Node/npm version: node 13.7.0

**Additional context/Screenshots**

From the [source code of Playground](https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useComponents.tsx#L37) it seems function child ability is removed

I'm trying to use docz to create a documentation of a set of react hooks, invoking hooks inside `Playground` is an important feature to his

**Comment by alexandre-lelain** [comment]
Hello,

The [source code of Playground](https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useComponents.tsx#L37) component is correct. 

Unless I am mistaken, in React:

```jsx
<button>click me</button>
```

is equivalent to:

```jsx
{() => {
  return <button>click me</button>
}}
```

In both case you return an **instance** of a component. That said, the `Playground` component from Docz enables you to write functional components inside, and so use hooks.

I was able to make the sample from the [documentation](https://www.docz.site/docs/built-in-components) work with `docz@2.2.0` without any extra step. You can find the `package.json` & `hello-world.mdx` files in the following gist: 

https://gist.github.com/alexandre-lelain/2eb6642ccb4fc4786b13d0d8092f3710

Once those files downloaded, if you run `yarn install && yarn start`, you should be able to see the result working correctly in your broswer.

If that helps, I sometimes have to remove the `.docz` folder entirely to make some features work. I still don't know why, but maybe it can help on your side.

I hope it helps!

**Comment by otakustay** [comment]
@alexandre-lelain Thanks for help, it seems I missed `import {Playground} from 'docz'` in mdx file.
