### ISSUE TITLE
docgenConfig.propFilter is ignored

### ISSUE THREAD

**Issue by tripphamm** [doczjs/docz#1403]
## Bug Report

I'm passing a custom `docgenConfig.propFilter` to my `docz.config.js`, but it is not being run.

Culprit seems to be [here](https://github.com/doczjs/docz/blob/87eea505e3a9aef78c53b6bdcdc39d596d37bb7c/core/docz-core/src/utils/docgen/typescript.ts#L170) in the TypeScript docgen parser module.

It's short, so I'll copy it here for convenience:
```ts
propFilter(prop: any): any {
  if (prop.parent == null) return true
  const propFilter = config.docgenConfig.propFilter
  const val = propFilter && _.isFunction(propFilter) && propFilter(prop)
  return !prop.parent.fileName.includes('node_modules') || Boolean(val)
}
```

This code ignores the custom `propFilter` if `prop.parent == null`, but I would like to have my custom `propFilter` always run so that I can decide how to treat `prop.parent == null`.

Also, in the return statement, my custom `propFilter` result could also be ignored. It seems to say that if the prop's parent is not a node_modules file, then it should always be included regardless of my `propFilter` result.

## Suggestion

Provide a "default" propFilter, but allow the user to completely override it if they want.

```js
function defaultPropFilter(prop) {
  if (prop.parent == null) return true;
  return !prop.parent.fileName.includes('node_modules');
}

 propFilter(prop: any): any {
    const customPropFilter = config.docgenConfig.propFilter;
    const propFilter =_isFunction(customPropFilter) ? customPropFilter : defaultPropFilter;
    return Boolean(propFilter(prop));
  }
```

**Environment**

- docz version: 2.2.0
- OS: OSX 10.15.3
- Node/npm version: Node 12.14.1 / NPM 6.13.4

**Comment by pedronauck** [comment]
Hi @tripphamm, that's a pretty nice suggestion, would you make some pull request in order to change it?

**Comment by tripphamm** [comment]
Yeah, I'll put a PR together 👍
