### ISSUE TITLE
How to use external package on creating playground?

### ISSUE THREAD

**Issue by sayjeyhi** [doczjs/docz#1405]
## Question

**We need to use external package on creating playground?**
*actually I have a monorepo and I want to use some packages in another package without getting stick with `../` , but I got unresolved error message at .cache folder*

**Comment by pedronauck** [comment]
Can you please show us the error most specifically dude? 🙏

**Comment by sayjeyhi** [comment]
for example see this `mdx` file which try to load some component in Playground: 
https://raw.githubusercontent.com/snappmarket/frontend-toolbox/develop/packages/ui/packages/Alert/index.mdx
in this part:
```javascript
---
name: Alert
route: /ui/alert
menu: Ui
---

import { useState } from 'react';
import { Playground, Props } from 'docz';
import { Alert, Button, Row, Col } from '..';
```
I do not want to load `Alert`, `Button` and etc from `..` and want to use package namespace `@snappmarket/ui` . This made our example more readable and re-usable.

In this example we have easy config, If we see advanced usages like importing monorepo another package dependency ([here](https://raw.githubusercontent.com/snappmarket/frontend-toolbox/develop/packages/ui/packages/ConfirmDialog/index.mdx)) it could be more complex.

**Comment by pedronauck** [comment]
You can create somes aliases for webpack config using Gatsby Hooks as explained here:
https://www.docz.site/docs/powered-by-gatsby
