### ISSUE TITLE
Nested menus

### ISSUE THREAD

**Issue by odalysadam** [doczjs/docz#1407]
Ok, so it's 2020 now, every issue I've read is closed, but I couldn't get anything to work.

I tried something like this in my doczrc.js:

```
menu: [
  'Getting Started',
  { name: 'Components', menu: [
    { name: 'Atoms', menu: ['Button']}, 
    'Molecules', 
    'Organisms'
  ]}, 
]
```

In my button.mdx I've tried these and a bunch more:

`name: Button`
`menu: Components/Atoms/Button`
`menu: Button`
`menu: Molecules`

None of it works. It always creates a new menu entry "x > Button".

Since there is no Button entry under Atoms, I'm guessing nesting still doesn't go that far? So what's the state on this feature? Seems a little odd that this is not fixed/implemented by now or what am I doing wrong?

**Comment by alexandre-lelain** [comment]
Hello,

Unfortunately, I don't think you can have nested [nav-group](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/NavGroup/index.js) menus at the moment. It seems you can only have one nested level.

Please let me know if that didn't answer your problem or if I'm wrong.

**Comment by joscha** [comment]
Is there an easy way to replace the nav component of docz with my own in order to support more than two levels?

**Comment by Fruitseller** [comment]
@joscha maybe https://www.docz.site/docs/component-shadowing can help you?

**Comment by joscha** [comment]
Thanks, will check it out!

**Comment by coopbri** [comment]
I would love this feature -- it's the only thing holding me back from docz at the moment.
@joscha, have you figured out any solutions for this? I would be willing to contribute.

**Comment by joscha** [comment]
We went to Gatsby directly to solve it.

**Comment by coopbri** [comment]
Thanks for letting me know! I will look around.
