### ISSUE TITLE
Css-modules not working

### ISSUE THREAD

**Issue by pfodox** [doczjs/docz#1408]
## Bug Report

I created simple Button.tsx and styles.css, and tried to use styles in Button.tsx, but classes not generating.

**To Reproduce**

I created small repo: https://github.com/pfodox/docz-css-modules-bug

1) Run npm install
2) Run npm run docz:dev
3) In browser you will see button without styles

**Expected behavior**

Button with green text

**Environment**

- docz version: [e.g. 2.2.0]
- OS: [e.g. OSX 10.14.6]
- Node/npm version: [e.g. Node 12.13.1/npm 6.13.6]

**Additional context/Screenshots**

<img width="331" alt="Screenshot 2020-03-03 at 22 11 18" src="https://user-images.githubusercontent.com/16138325/75810605-f0d49880-5d9b-11ea-9fd0-0b57120aecf5.png">

**Comment by ioso** [comment]
文件解决了吗我的也有这个问题

**Comment by seanhealy** [comment]
We had a similar issue. It had to do with docz v2 requiring `file.module.css` we fixed it with the following in our `doczrc.js` file.

```js
import { createPlugin } from "docz-core";

const projectPlugin = () =>
  createPlugin({
    onCreateWebpackConfig: ({ rules, getConfig }) => {
      // Activate CSS modules, referenced from:
      // https://github.com/gatsbyjs/gatsby/issues/16129
      const config = getConfig();

      const cssRule = {
        ...rules.cssModules(),
        test: rules.css().test
      };

      config.module.rules = [
        ...config.module.rules.filter(rule => {
          const areCssRules =
            rule.oneOf && rule.oneOf.some(r => r.test.test("style.css"));

          return !areCssRules;
        }),
        cssRule
      ];
    }
  });

export default {
  // You likely have other configuration here but, just add this.
  plugins: [projectPlugin()]
};
```

Hopefully this makes sense / helps.

**Comment by Fruitseller** [comment]
Hey @pfodox,
is your issue resolved?

**Comment by andregamma** [comment]
Hey @seanhealy, using your code gives me a webpack error.

![image](https://user-images.githubusercontent.com/31011359/90343711-128baa00-dfe1-11ea-8758-a149297210a0.png)

Do you have any idea what it might be?
