### ISSUE TITLE
prop: useScoping does not pass to createElement

### ISSUE THREAD

**Issue by ZhenHe17** [doczjs/docz#1409]
## Bug Report

prop: useScoping does not pass to createElement

```<Playground useScoping/>```  but useScoping still false

I modified docz/dist/index.esm.js line 311, and bug is fixed, code:
``` jsx
const Playground = ({
  className,
  children,
  style,
  wrapper,
  __scope,
  __position,
  __code,
  language,
  useScoping
}) => {
  const components = useComponents();
  const PlaygroundComponent = components.playground;
  if (!PlaygroundComponent) return null;
  return createElement(PlaygroundComponent, {
    components: components,
    component: children,
    className: className,
    style: style,
    wrapper: wrapper,
    scope: __scope,
    position: __position,
    code: __code,
    language: language,
    useScoping: useScoping
  });
};
```

Please try to build a small repo with a repro of your problem and provide a link to it.

Doing that allows more people to quickly help you.

If you can't provide a repo then provide clear steps describing how to reproduce the issue.

1. create-docz-app my-docz-app && cd my-docz-app
2. Change src/index.mdx to

```mdx
### Some mdx content
<Playground useScoping/>
```

4. Run npm run docz dev
5. See error in browser

```shell
FOR BUGS: Insert debug trace
```

**Expected behavior**

prop useScoping is true

**Environment**

- docz version: 2.2.0
- OS: OSX 10.13.4
- Node/npm version: Node 10/npm

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by jesperorb** [comment]
I followed your steps:
1. `create-docz-app my-docz-app`
2. `cd my-docz-app`
3. `yarn dev`
4.
```mdx
---
name: Getting Started
route: /
---

import { Playground } from "docz"

<Playground useScoping>

</Playground>
```


And I am getting no error and the prop `useScoping` is being passed to the component and is `true`
