### ISSUE TITLE
Wrong font in Live Editor with useScoping (scoping is applied to editor)

### ISSUE THREAD

**Issue by remmythical** [doczjs/docz#1410]
Search terms: monospace font editor code useScoping useScopingInPlayground styles

## Bug Report

**Describe the bug**

Currently when using IFrame scoping (via `themeConfig.useScopingInPlayground` or `<Playground useScoping />`), the Live code editor won't load it's font and will fall back to its default implementation.

I'm assuming this is a result of the encapsulation, that is also applied to the editor view, as the referenced font `Inconsolata` is not loaded inside the IFrame.

Note: I know the Wrapper code was just edited in 251a1a5302d591dbd38eb9fee0db534d9044e863 , which is still unreleased, but as far as i can tell the core behaviour that leads to this bug hasn't changed.

**To Reproduce**

Repro in CodeSandbox: https://codesandbox.io/s/blue-firefly-dlv29?fontsize=14&hidenavigation=1&module=%2Findex.mdx&theme=dark

**Expected behavior**

Scoping has no effect on the editor font.

Personally I think the underlying issue here is not that the font isn't available inside the IFrame, but that the scoping is applied to the Editor view in the first place.

The usecase for the scoping is for proper style encapsulation of the component code. 
But the code editor is supplied by docz and there is no styling going on that would need to be encapsulated. And if it is shadowed and needs encapsulation for some reason, one should have to provide the IFrame as well.

If I find time, I could submit a PR on the next weekend, my naive solution would be to just enforce a `useScope=false` for the editor wrapper (no matter the config), using the new prop introduced in the mentioned commit.

**Environment**

- docz version: [2.3.0-alpha13] (also reproducable in 2.2.0 stable)
- OS: [macOS 10.14.6]
- Node/npm version: [Node 10.18.1 / yarn v1.21.1]

**Additional context/Screenshots**
<img width="625" alt="Screenshot fallback font" src="https://user-images.githubusercontent.com/3317423/75990780-acf5a680-5ef5-11ea-9d60-e60ea9dc16e4.png">

**Comment by remmythical** [comment]
Unrelated side note: I'm not sure if you got docz running in CodeSandbox before (It's not super easy to set up because the dependency installation seems to error sometimes, and it has to be a  server sandbox).

Feel free to fork the sandbox / recommend an official version as a repro tool, if you see fit 🙂

**Comment by jesperorb** [comment]
Do you mean here that the `useScoping` should not be passed to the editor here? The editor and the code displayin is using the same wrapper.
https://github.com/doczjs/docz/blob/24bb600ef53aa133e0a05920e9a45d230bcebab7/core/gatsby-theme-docz/src/components/Playground/index.js#L70-L97
