### ISSUE TITLE
Gatsby Theme Bundling Error - classEscape at position 19

### ISSUE THREAD

**Issue by heymega** [doczjs/docz#1412]
## Bug Report

**Describe the bug**

Running the command `npx docz dev` results in the following...

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

classEscape at position 19
    |[A-Za-z_\-\u{00a0}-
              ^

File: ..\node_modules\gatsby-theme-docz\src\index.css

failed Building development bundle - 8.018s

```

**To Reproduce**

1. Add docz to an existing react app (`react` and `react dom` are already installed) using `npm install docz `
2. Run the command `npx docz dev `

**Expected behavior**

To get passed this step 😢 

**Environment**

- docz version: 2.2.0
- OS: Windows 10
- Node/npm version: 13.10.1

I'd imagine that this has more to do with my existing react-app but I'm not sure why. Any help is greatly appreciated.

**Comment by BolotskyDev** [comment]
@heymega stuck with the same problem today trying to integrate `react-scroll-parallax`, found [this](https://github.com/gatsbyjs/gatsby/issues/17557) issue. 

There are multiple options described, but I got lucky and resolved my problem with the very first one, quote: 
> - Remove package-lock.json and/or yarn.lock
> - Issue gatsby clean to purge any stale data.
> - Remove node_modules folder.
> - Install the dependencies again with your package manager of choice, either npm or yarn.
> - Issue gatsby develop and see if the error does not pop back.

Hope it helps!

**Comment by ubugnu** [comment]
I did an update to gatsby now, and I get the same error
```
$~ gatsby -v
Gatsby CLI version: 2.8.19
Gatsby version: 2.23.3
```
