### ISSUE TITLE
Importing files into doczrc.js

### ISSUE THREAD

**Issue by gojutin** [doczjs/docz#1413]
## Question
Is it possible to break out the `.doczrc.js` file into smaller files. 

**Description**
I can't seem to figure out how to import  `js` files into the `.doczrc.js` and use them. The goal is to be able to break out certain larger values (like menu) into their own file. 

I've tried putting the `js` files at the root level, in the `src` directory and even in a `public` directory to no avail. I keep getting a `MODULE_NOT_FOUND` error for whatever file I import. I've also tried using `module.export` syntax and `import/export` syntax. Am I missing something obvious here?

**Comment by heyheman11** [comment]
We are facing this same issue as well, I'm surprised this issue has gone stale. Is there any chance that this could be addressed ? It seems like a pretty major oversight
