### ISSUE TITLE
Error when using TypeScript cast

### ISSUE THREAD

**Issue by LucasBassetti** [doczjs/docz#1414]
## Bug Report

I'm have an error when using TypeScript cast.

![image](https://user-images.githubusercontent.com/1014326/76178279-92415d00-6195-11ea-8526-ed91d728f95d.png)

```shell
  15:29  error  Parsing error: Unexpected token, expected ";"

  13 |   const isFirstPosition = useCallback(
  14 |     (step: Step) => {
> 15 |       const userStep = step as UserStep;
     |                             ^

```

**Expected behavior**

Be able to use TypeScript cast

**Environment**

- docz version: 2.2.0
- OS: OSX 10.15.3
- Node/npm version: [e.g. Node 10.15.3/npm 6.4.1]

**Additional context/Screenshots**
I'm using the TypeScript configuration with doczrc.js

```
export default {
  typescript: true
}
```

**Comment by IGoRFonin** [comment]
`typescript: true` in doczrc only for mdx.
Try to `npm i gatsby-plugin-typescript` and create file `gatsby-config.js` with
```js
module.exports = {
    plugins: [
        "gatsby-plugin-typescript"
    ]
};
```
