### ISSUE TITLE
Can't resolve '@pmmmwh/react-refresh-webpack-plugin/src/overlay' in ".docz/.cache"

### ISSUE THREAD

**Issue by Okazari** [doczjs/docz#1418]
Hey !

I've got an issue that i believe is related to `yarn` but just in case i want to point it to you as it affect `docz` users using `react-native`.

It's due to a recent change in `gatsby` that add a new dependency in this commit https://github.com/gatsbyjs/gatsby/commit/205847b833c5f7783182ea54a3ddd72f6369ee47

see https://github.com/yarnpkg/yarn/issues/7987

# Steps to Reproduce

 - git clone https://github.com/Okazari/yarnissue.git
 - cd yarnissue
 - yarn
 - yarn start

# Environment
 - Node Version: 12.16.0
 - Yarn v1 Version: 1.22.4
 - OS and version: Ubuntu 19.10

**Comment by adbayb** [comment]
Same on my side.

A temporary fix will be to add `@pmmmwh/react-refresh-webpack-plugin` in your dependency list:
`yarn add @pmmmwh/react-refresh-webpack-plugin --dev`

**Comment by DY-ZYQ** [comment]
Do you find out what caused this

**Comment by DY-ZYQ** [comment]
Do you find out what caused this？

**Comment by Okazari** [comment]
Nope :cry:
