### ISSUE TITLE
Padding on playground?

### ISSUE THREAD

**Issue by zackphilipps** [doczjs/docz#1419]
## Question

Hi there, I'm using docz v2.2.0 and it looks like components rendered in the Playground butt right up against the border. In all the screenshots on the site, the Playground components appear to have padding within them. Has something broken along the way?

Docz site:
![image](https://user-images.githubusercontent.com/3578812/76661035-c8ddf580-6550-11ea-842e-a73048a93f67.png)

My docz instance:
![image](https://user-images.githubusercontent.com/3578812/76661074-e1e6a680-6550-11ea-8e51-5f72c0d8d684.png)

**Comment by kilianc** [comment]
![image](https://user-images.githubusercontent.com/385716/77598538-50b3f000-6ebf-11ea-97f6-47dc421ed6fc.png)

I have been trying to add some padding overriding the styles but I can't find a way other than targeting the `testid` prop.

**Comment by kilianc** [comment]
```
// src/gatsby-theme-docz/src/components/Playground/styles.js

export * from 'gatsby-theme-docz/src/components/Playground/styles'

export const preview = {
  margin: 0,
  padding: '20px'
}
```
