### ISSUE TITLE
How to disable in-browser GraphQL IDE from gatsby?

### ISSUE THREAD

**Issue by someden** [doczjs/docz#1425]
How to disable in-browser GraphQL IDE (I mean: ` http://localhost:3000/___graphql`) and other useless (in my case) stuff from gatsby?
Because it takes a lot of resources and my laptop is like flying away when I running `docz dev`.

**Comment by presto2116** [comment]
This is a default part provided by gatsby. I do not believe that it is the root of the performance problems when running docz dev. I have been tryin to debug the performance issue when using docz because it is overwhelming our build and deployment tools.
