### ISSUE TITLE
Compilation error - transform-react-jsx: pragma has been set but pragmaFrag has not been set

### ISSUE THREAD

**Issue by DanielAntunes97** [doczjs/docz#1429]
## Bug Report

**Describe the bug**

My build on Docz is erroring with the following stack trace:

```
ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

unknown: transform-react-jsx: pragma has been set but pragmaFrag has not been set

File: ../src/components/Drawer.mdx

failed Building development bundle - 6.078s


```

**To Reproduce**

No idea, everything was working fine until then.
Since I didn't change anything on my side, it may be related to some node module, most potentially with `transform-react-jsx` babel plugin.

I don't know what's causing the issue.

**Expected behavior**

Should compile

**Environment**

- docz version: 2.2.0
- OS: Linux Ubuntu 19.04

**Workarounds**

Use React.Fragment
Using `<React.Fragment></React.Fragment>` instead of `<></>`

**Comment by crusoexia** [comment]
Same issue here

**Comment by molomby** [comment]
Related? https://github.com/zeit/next.js/issues/11230

**Comment by crusoexia** [comment]
upgrade @babel/preset-react v7.9.4 can solve this.
