### ISSUE TITLE
Can I structure the Menu by directory structure?

### ISSUE THREAD

**Issue by Geeman201** [doczjs/docz#1438]
## Question
Can I structure the Menu by folder structure?

**Description**
We are looking to build out some engineering-standards using docz, and basically want our menu to match the directory structure

i.e. Folder structure as follows
```
|- Javascript
  |- React
    |- Hooks
       |- Structure.md
       |- Return values.md
    |- Testing
       |- Snapshots.md
       |- Coverage.md
    |- Build tools
       |- AWS device farm.md
  |- Node
    |- Build tools
       |- CircleCi.md
```

Outputs a menu like this

```
> Javascript
  > React
    > Hooks
      > Structure
      > Return values
    > Testing
      > Snapshot
      > Coverage
    > Build tools
      > AWS device farm
  > Node
     > Build tools
        > Circle Ci
```

If not I'm pretty sure it can be done using synchronous file processing in doczrc.js was just wandering if:
a. There is something built in
b. I've missed something obvious
c. Someone had already written something

**Comment by andrewthauer** [comment]
Also wondering the same thing. Is there a way the menu structure can be built automatically without having to specify the frontmatter `menu` option?
