### ISSUE TITLE
initialColorMode config does not work for dark mode

### ISSUE THREAD

**Issue by oliikit** [doczjs/docz#1440]
## Bug Report

**Describe the bug**
Receiving this error when setting `initialColorMode` to `dark`:
```
backend.js:6 The `initialColorMode` value should be a unique name and cannot reference a key in `theme.colors.modes`. 
    in RootProvider (created by ThemeProvider)
    in ThemeProvider (at src/​index.js:12)
    in Theme (created by Anonymous)
    in Anonymous (at Layout.js:51)
    in Layout (created by MDXCreateElement)
    in MDXCreateElement (at docs/​index.md:22)
    in MDXContent (created by HotExportedMDXContent)
    in HotExportedMDXContent (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:56)
    in RouteHandler (at root.js:78)
    in EnsureResources (at root.js:66)
    in LocationHandler (at root.js:124)
    in LocationProvider (created by Location.Consumer)
    in Location.Consumer (created by Location)
    in Location (at root.js:123)
    in Root (at root.js:131)
```

Seems like there is an issue with how the [options are configured](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/theme/index.js). But this is [how the documentation](https://www.docz.site/docs/gatsby-theme#dark-mode) says to make it default.

**To Reproduce**
1. Set `initialColorMode` to dark. `doczrc.js` file should be then:
```
export default {
  themeConfig: {
    initialColorMode: 'dark'
  }
};
```

**Expected behavior**
Color mode should be dark by default.

**Environment**

- docz version: 2.3.0-alpha.14"
- OS: OSX 10.15.4
- Node/npm version: Node v10.16.3, npm 6.13.4

**Additional context/Screenshots**
N/A

**Comment by iamwelk** [comment]
have the same question

**Comment by jesperorb** [comment]
@oliikit 
What do you mean when you say:
> Seems like there is an issue with how the options are configured . But this is how the documentation says to make it default.

You linked to the file but I do not understand what you mean specifically?

But yeah, seems like the config gets set then overwritten, either by `docz` and the merging of the default config with the new config or based on how color modes are handled by [_Color Modes @ theme-ui_](https://theme-ui.com/color-modes/).

Seems like the latest version of `theme-ui` (`^3.x`) uses `useColorSchemeMediaQuery: true` to handle this, as `docz` uses `2.x` at the time of writing this.
