### ISSUE TITLE
Edit page not displaying on fresh build

### ISSUE THREAD

**Issue by oliikit** [doczjs/docz#1441]
## Bug Report

**Describe the bug**
I can't get `Edit Page` button to work. Looks like it should be feasible from the [header component](https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/src/components/Header/index.js#L54-L64). I'm expecting to see an `Edit Page` button on there, but I'm not. I was able to get the GitHub icon to show, but even then I'm not certain if it will link to the right page on the Github.

This functionality isn't documented, and I've had to dig through code and past issues to piece information together, which is frustrating.

**To Reproduce**
From what I've pieced together, I have this configuration in my `doczrc.js` file:

```
export default {
  editBranch: "master,
  repository: "org/repo"
};
```

From here, after building the server, the GitHub icon goes to `http://localhost:3000/org/repo`. I've also tried the full path URL, which takes me to the actual repo - but not on the direct page where it needs to be edit.

**Expected behavior**

I'd expect an `Edit Page` on the page and once clicked, points to the direct page on Github.

**Environment**

-  docz version: 2.3.0-alpha.14"
- OS: OSX 10.15.4
- Node/npm version: Node v10.16.3, npm 6.13.4

**Additional context/Screenshots**

Here's what the build looks like:
![image](https://user-images.githubusercontent.com/15113564/78080090-82273280-737b-11ea-9a25-f7c5e5148b68.png)

**Comment by jesperorb** [comment]
Have you specified a repository in your `package.json` similar to?
```json
"repository": {
    "type": "git",
    "url": "https://github.com/doczjs/docz.git"
}
```
If not, could you try adding it and see if you get your expected behavior? I will see to it to update the documentation around this a bit more.

**Comment by geelen** [comment]
I've now done that, but not seeing any changes: https://fab.dev/guides/getting-started should be connected to https://github.com/fab-spec/fab/blob/master/docs/guides/getting-started.mdx, perhaps because it's in a subdirectory?

**Comment by danielcardoso5** [comment]
I was having this problem by running the following script in my package.json:

`"docz-knowledge-dev": "cd knowledge-base && docz dev",`

because my doczrc.js file resized on the knowledge-base folder.

I've changed it to this:

`"docz-knowledge-dev": "docz dev --config='knowledge-base/doczrc.js'",`

and now I'm able to see the "Edit page" button.

**Comment by BhaskarRakholiya** [comment]
as i seen the core code i m not findng as a bug.
here are multiple conditions they had provided.
![image](https://user-images.githubusercontent.com/52423963/84384729-0b74a400-ac0c-11ea-95a6-a3f86949ae6b.png)
![image](https://user-images.githubusercontent.com/52423963/84384923-5e4e5b80-ac0c-11ea-8eff-8c2cf11672a8.png)
if i remove these conditions as will show edit.
![image](https://user-images.githubusercontent.com/52423963/84385236-d87ee000-ac0c-11ea-820b-faea7209627e.png)
it is not the solution by far. i'll share the solution soon
