### ISSUE TITLE
dozc dev is ultra slow

### ISSUE THREAD

**Issue by link2malkeet** [doczjs/docz#1442]
## Question

**Description**
Our library has 6 components. every time I run docz dev is very slow. Is there a way to speed up docz dev or is there a way to build only changed components.

My docz config

export default {
  src: '../packages/',
  files: '**/*.{mdx,example.tsx}',
  typescript: true,
  title: 'Lendi Shared Components',
  theme: './theme',
  dest: 'dist',
};

**Comment by agriffis** [comment]
In my project this is the slow part:

```
success source and transform nodes - 32.091s
```

Based on my experience in #1447 I think it's probably reading/parsing a lot of files even though they're supposed to be excluded

**Comment by link2malkeet** [comment]
Yeah 
in my project
`success source and transform nodes - 137.039s`

It's horrible

**Comment by AlexandrAnash** [comment]
Any news on how to speed up the build and hot reload?

**Comment by link2malkeet** [comment]
Leave Docz, the only quick solution.

**Comment by drewlustro** [comment]
@link2malkeet what did you choose instead?

**Comment by link2malkeet** [comment]
Storybook - far better than docz -  https://storybook.js.org/docs/guides/guide-react/

**Comment by prabhuignoto** [comment]
also having this slowness issues. anytime i add a new mdx file it just hangs on this.

`success Re-building development bundle - 0.308s`

I'm using typescript. killing the process and restarting works though. Not a pleasant experience at all.

**Comment by tanphamhaiduong** [comment]
Are there any solution for this problem. I'm facing with the ultra slow problem on docz

**Comment by drianoaz** [comment]
Hello guys, is there anything I can do to make my build less slow?
