### ISSUE TITLE
Can docz generate documentation pages from tsdoc comments?

### ISSUE THREAD

**Issue by pirix-gh** [doczjs/docz#1445]
## Question

**Description**

I would like to generate pages for my API with docz, but without having to create mdx files when it is not a component. I need to generate documentation for types, functions, classes from tsdoc comments. Is this possible?

Or should I do the work of generating my own API mdx files?

*I read previous issues, but the answer was not clear.*

Thanks

**Comment by rakannimer** [comment]
In it's current state, docz can't generate markdown documents from tsdoc
comments found in code (it can however use tsdoc comments in a component's
props type definition).
I think you would have to generate the markdown files yourself in your case.

**Comment by EvanPurkhiser** [comment]
I've been thinking about this myself a bit.

Just spitballing here, but it would be really neat to have a component that would take a filepath / some selector (function, class, type, etc) to get your typescript documentation documentation, and then the component renders the generated documentation (with perhaps some config) for the tsdoc.

**Comment by jesperorb** [comment]
> I've been thinking about this myself a bit.
> 
> Just spitballing here, but it would be really neat to have a component that would take a filepath / some selector (function, class, type, etc) to get your typescript documentation documentation, and then the component renders the generated documentation (with perhaps some config) for the tsdoc.

I wrote about something similar in this issue:
https://github.com/doczjs/docz/issues/1471#issuecomment-622368989
