### ISSUE TITLE
How to use another design system, like bulma or custom design system for eg.

### ISSUE THREAD

**Issue by williamnvk** [doczjs/docz#1448]
I want to use DOCZ, but, changing layout. For eg.: I have a custom design system, and typography, grid, labels, links etc with custom attributes allowed in a SASS file.
But, in Docz actual trying to use, i have difficult. More examples:
I don't need to use lateral nav and all headings use deferents fonts and colours.
Finally, I want to change 100% of current layout but using features of Docz.
Its possible, how? Thanks.

**Comment by theo-mesnil** [comment]
Hi ! You can check the documentation here https://www.docz.site/docs/creating-your-themes
