### ISSUE TITLE
why my Icon cannot show in the docz?

### ISSUE THREAD

**Issue by xijiji** [doczjs/docz#1449]

**Comment by rakannimer** [comment]
Hey @xijiji,

Do you mean your favicon ? What have you tried ?

**Comment by xijiji** [comment]
For Example: Checkbox.mdx ---
name: Checkbox
menu: Components
---

import { Playground, Props } from 'docz';
import { Checkbox } from '@my/Components';


# Checkbox

## 基本

<Playground>
        <Checkbox >Unchecked</Checkbox>
</Playground>

There is no my favicon in the Checkbox,  but other css can show;

**Comment by rakannimer** [comment]
Where is the image being fetched from ? for example "mydomain.com/images/checkbox.png" ?

**Comment by xijiji** [comment]
in css

**Comment by jesperorb** [comment]
What Icon is it? Is it a package like `FontAwesome`, where is the icon coming from? How does your `css` and component look like? This is too little information to help you on.
