### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by elmnt** [doczjs/docz#1452]
## Bug Report

Could not install, using `npx create-docz-app my-docz-app`

```
$ npx create-docz-app my-docz-app
npx: installed 1 in 1.129s
Creating a new Docz app in /Users/me/location/my-docz-app.

Downloading files for example basic. This might take a moment.


Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: e.destroy is not a function
    at e.forEach.e (/Users/me/.npm/_npx/59723/lib/node_modules/create-docz-app/dist/index.js:2:35630)
    at Array.forEach (<anonymous>)
    at streamPromise.catch.r (/Users/me/.npm/_npx/59723/lib/node_modules/create-docz-app/dist/index.js:2:35573)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Environment**

- docz version: current
- OS: OSX 10.15.4
- Node/npm version: Node v10.16.3

**Comment by Fruitseller** [comment]
Hey,
I tried the same command with Node v10.19.0 and yarn v1.22.4. The installation has completed on my machine.
Which yarn version do you have?

**Comment by makitsune** [comment]
Having the same issue with Node v16.3.0 and Yarn 1.22.10 on macOS Big Sur 11.4 arm64

**Comment by christroutner** [comment]
I'm also getting this error:

```
Aborting installation.
Unexpected error. Please report it as a bug:
TypeError: e.destroy is not a function
    at /home/trout/.config/yarn/global/node_modules/create-docz-app/dist/index.js:2:35630
    at Array.forEach (<anonymous>)
    at /home/trout/.config/yarn/global/node_modules/create-docz-app/dist/index.js:2:35573
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)

```

I get this when I run:
- `npx create-docz-app my-project`
- `npx create-docz-app psf-org-docs`

Here are the versions I'm running:
- node.js v14.17.0
- npm v7.13.0
- yarn 1.22.10

**Comment by Topener** [comment]
I too am getting this issue, I recommend re-opening this one.

**Comment by MinJieLiu** [comment]
I too am getting this issue

**Comment by robint-liu** [comment]
hi, i have the same question, It still doesn't seem to work properly.
![image](https://user-images.githubusercontent.com/34432540/125191039-05b81a80-e273-11eb-912b-7de53b6e986c.png)

**Comment by renatobenks** [comment]
I'll be checking this out, just give me a few

**Comment by renatobenks** [comment]
Well, so far I've checked, this binary is not actually official from docz, so I recommend you create that same issue on https://github.com/rakannimer/create-docz-app, which is the proper place to report that.

so, I'll be closing it once again, but @rakannimer will probably give better support to that, once he was who introduced that npx script (:

**Comment by renatobenks** [comment]
By the way, I think would be quite valuable to have this better detailed on README, exactly where is instructed that step.

Anyone feel free to help us out and contribute to it.
