### ISSUE TITLE
Show different code in Playground

### ISSUE THREAD

**Issue by smeijer** [doczjs/docz#1453]
## Question
I'm trying to use Docz to document a library, and want to render some examples using the `Playground` component.

I can use react components to render the demo in a `Playground`, but I want to show non-react (library) code as example snippet.

Is this somehow possible?

**Description**
The code that I want to show is as below, while I want to have a react component rendered:

```js
import L from 'leaflet';
import { GeoSearchControl, GoogleProvider } from 'leaflet-geosearch';

const provider = new GoogleProvider({ params: {
  key: '__GOOGLE_API_KEY__',
} });

const searchControl = new GeoSearchControl({
  provider: provider,
});

const map = new L.Map('map');
map.addControl(searchControl);
```

Alternatively, is it possible to hide the code in the playground? Then I can just render a code-block below the playground.

**Comment by jesperorb** [comment]
You can set a project-wide config to hide the editor in `doczrc.js`:
