### ISSUE TITLE
Client only code in mdx file?

### ISSUE THREAD

**Issue by smeijer** [doczjs/docz#1454]
## Question
I'm having some code in the `mdx` file that depends on the `window` object, and thereby fails to build.

The most simple example that I can come up with that fails is:

```mdx
---
name: demo
---

import L from 'leaflet';

# Leaflet Example

<Playground>
  <div id="map" />
</Playground>
```

This will throw `WebpackError: ReferenceError: window is not defined`. 

Is it possible to somehow ignore or mock the import during build, and only evaluate it on the client?

**Comment by VitamineC** [comment]
Yes
Create gatsby-node.js in root of your project, and insert something like this in it: 
```
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'develop-html') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /leaflet/,
            use: loaders.null(),
          },
        ],
      },
    });
  }
};
```

**Comment by smeijer** [comment]
Thanks, that's the solution I went with. Only to support both `docz dev` as well as `docz build`, the stage condition need to include `stage === 'build-html'` as well

```js
exports.onCreateWebpackConfig = ({ stage, loaders, actions }) => {
  if (stage === 'build-html' || stage === 'develop-html') {
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /leaflet/,
            use: loaders.null(),
          },
        ],
      },
    });
  }
};
```
