### ISSUE TITLE
why css modules doesn't work in docz

### ISSUE THREAD

**Issue by ggzhangGithub** [doczjs/docz#1462]
index.tsx
```
import React from 'react';
import EmptyIcon from '@/assets/empty.png';
import styles from './index.less';

type Style = {
  [key: string]: string;
}

interface Props {
  title?: string;
  style?: Style;
}

const Empty = (props: Props) => (
  <div className={styles.emptyWrapper} style={props.style}>
    <img src={EmptyIcon} alt="" />
    <div className={styles.title}>{props.title}</div>
  </div>
);

export default Empty;
```

index.mdx
```
---
name: Empty
route: /
---

import { Playground, Props } from 'docz';
import Empty from './';

## import

import Empty from '@/components/Empty'

## props

<Props of={Empty} />

## view

<Playground>
  <Empty />
</Playground>
```

gatsby-config.js
```
module.exports = {
  plugins: [
    'gatsby-plugin-less',
    {
      resolve: 'gatsby-plugin-import',
      options: {
        libraryName: 'antd',
        style: 'css',
      },
    },
  ],
};
```
I can't see any style on my pc window

**Comment by Fruitseller** [comment]
Hey, have you tried to rename you file from `index.less` to `index.module.less`? I think this should fix your problem.

**Comment by ggzhangGithub** [comment]
> Hey, have you tried to rename you file from `index.less` to `index.module.less`? I think this should fix your problem.

thanks! that's help a lot.

**Comment by ggzhangGithub** [comment]
> Hey, have you tried to rename you file from `index.less` to `index.module.less`? I think this should fix your problem.

@Fruitseller

**Comment by ggzhangGithub** [comment]
> Hey, have you tried to rename you file from `index.less` to `index.module.less`? I think this should fix your problem.

@Fruitseller Thanks! That's help a lot.
