### ISSUE TITLE
Crash when using context in a Component

### ISSUE THREAD

**Issue by gthibaud** [doczjs/docz#1463]
## Bug Report

**Describe the bug**

Every time one of my components uses a context, its Docz page crash. However, these components work fine in my application, and the other components (which do not use context) are displayed normally in Docz.

<img width="616" alt="Capture d’écran 2020-04-20 à 20 57 19" src="https://user-images.githubusercontent.com/27550148/79788837-8aa2d580-8349-11ea-9c4b-eebda90af85a.png">

**To Reproduce**

Code of my component:
```
import React, { useContext } from 'react';
import { Link } from 'react-router-dom';
import { NavigationContext } from '../../contexts/NavigationContext';

const BreadCrumbs = () => {
    const { path } = useContext(NavigationContext);
    return path && path.length > 1 ? (
        <div>
            <Link key="/" to="/">{path[0].name}</Link>
            {path.map(breadcrumb => breadcrumb.uri !== "/" ? (
                <Link key={breadcrumb.uri} to={breadcrumb.uri ? breadcrumb.uri : "/"}> / {breadcrumb.name}</Link>
            ) : null)}
        </div>
    ) : null;
}

export default BreadCrumbs;
```

Code of my Docz page:
```
---
name: Breadcrumbs
route: /components/breadcrumbs
menu: Components
---

import BreadCrumbs from './Breadcrumbs'
import { Playground, Props } from 'docz'

# Breadcrumbs

Breadcrumbs component render a navigation means of the path.

## Props
<Props of={BreadCrumbs} />

## Basic usage

<Playground>
    <BreadCrumbs />
</Playground>
```

Does anyone have any idea where that came from? 
Thank you :)

**Environment**

- docz version: 2.3.1
- OS: MacOS 10.15.3
- Node v12.14.0 / npm v6.13.4

**Comment by VitamineC** [comment]
You should add Provider that generate NavigationContext.
Example with redux

`
<Provider store={createStore()}>
    <BreadCrumbs/>
</Provider>
`

**Comment by jesperorb** [comment]
As @VitamineC pointed out. `BreadCrumbs` is a `Consumer` but it needs a `Context` to consume which you must provide. In your regular app that `Context` already supplied in `App.js` or similar.

But your documentation is not a part of your app and the `Playground` is in a different "context" than your app so you must supply it yourself:

```mdx
---
name: Breadcrumbs
route: /components/breadcrumbs
menu: Components
---

import BreadCrumbs from './Breadcrumbs'
import { NavigationContext } from '../wherever this is/NavigationContext';
import { Playground, Props } from 'docz'

# Breadcrumbs

Breadcrumbs component render a navigation means of the path.

## Props
<Props of={BreadCrumbs} />

## Basic usage

<Playground>
	<NavigationContext.Provider value={"whatever your value is"}>
       <BreadCrumbs />
    </NavigationContext.Provider/>
</Playground>
```

**Comment by gthibaud** [comment]
Thank you very much for your answers 😊
