### ISSUE TITLE
Analytics snippets?

### ISSUE THREAD

**Issue by geelen** [doczjs/docz#1469]
## Question

Genuinely confused how to add some analytics to the page. I know this is gatsby under the hood, and gatsby has [analytics plugins](https://www.gatsbyjs.org/docs/adding-analytics/) (never use two lines of HTML when you could use a whole plugin, hey Gatsby?) but I really just want somewhere I can customise the raw HTML template for my site.

In the end, I was able to drop in:

```jsx
      <script
        data-goatcounter="https://fab.goatcounter.com/count"
        async
        src="https://gc.zgo.at/count.js"
      />
```

Into my `Wrapper` component's `<Helmet>` tag, but trying to add:

```jsx
      <script
        dangerouslySetInnerHTML={{
          __html: `
            !function(t,e){var o,n,p,r;e.__SV||(window.posthog=e,e._i=[],e.init=function(i,s,a){function g(t,e){var o=e.split(".");2==o.length&&(t=t[o[0]],e=o[1]),t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}}(p=t.createElement("script")).type="text/javascript",p.async=!0,p.src=s.api_host+"/static/array.js",(r=t.getElementsByTagName("script")[0]).parentNode.insertBefore(p,r);var u=e;for(void 0!==a?u=e[a]=[]:a="posthog",u.people=u.people||[],u.toString=function(t){var e="posthog";return"posthog"!==a&&(e+="."+a),t||(e+=" (stub)"),e},u.people.toString=function(){return u.toString(1)+".people (stub)"},o="capture identify alias people.set people.set_once set_config register register_once unregister opt_out_capturing has_opted_out_capturing opt_in_capturing reset".split(" "),n=0;n<o.length;n++)g(u,o[n]);e._i.push([i,s,a])},e.__SV=1)}(document,window.posthog||[]);
            posthog.init('<POSTHOG TOKEN>', {api_host: 'https://app.posthog.com'})
          `,
        }}
      />
```

cause I wanted to play with https://posthog.com/ instead wouldn't work. Something is stripping the tag, trying 

```jsx
      <script
        dangerouslySetInnerHTML={{
          __html: `
            console.log("sup");
          `,
        }}
      />
```

never logged anything.

Fully expect that there's something obvious I was missing but if in the `doczrc.js` I could pass a `injectHTMLBeforeBodyEnd` that would let me add analytics code that would be awesome.

**Comment by devboldly** [comment]
Here's how I ended up doing it using [react-ga](https://www.npmjs.com/package/react-ga):

```jsx
import React from 'react';
import ReactGA from 'react-ga';

// See: https://github.com/doczjs/docz/tree/master/core/gatsby-theme-docz#wrapping-the-entire-app

const trackingId = 'UA-000000000-0';

let gaInitialized = false;
let lastPageview = undefined;

export default ({ children }) => {
  if (typeof window !== 'undefined') {
    if (!gaInitialized) {
      ReactGA.initialize(trackingId);
      gaInitialized = true;
    }
    // Track page view
    const newPageview = window.location.pathname + window.location.search;
    if (newPageview !== lastPageview) {
      ReactGA.pageview(newPageview);
      lastPageview = newPageview;
    }
  }
  return children;
};
```

Works for me, but always open to an "official" way of doing things. 

@geelen were you able to figure out how to add your own Gatsby plugins? I myself couldn't find it in the documentation.

**Comment by jesperorb** [comment]
Add a file named `gatsby-ssr.js` in the root folder of your project and try the following:
```js
import React from 'react'

export const onRenderBody = ({ setPostBodyComponents }) => {
  setPostBodyComponents([
	  <script
        data-goatcounter="https://fab.goatcounter.com/count"
        async
        src="https://gc.zgo.at/count.js"
      />
  ])
}
```

**Comment by geelen** [comment]
Worked perfectly, thanks heaps!

Out of interest, was that documented somewhere that I missed? If I google `setPostBodyComponents` I get https://www.gatsbyjs.org/docs/ssr-apis/ but that's kind of a misleading page (since it's being called at build time, not server-side, right?) and I didn't realise it'd slot straight in to a docz app.

**Comment by jesperorb** [comment]
> 
> 
> Worked perfectly, thanks heaps!
> 
> Out of interest, was that documented somewhere that I missed? If I google `setPostBodyComponents` I get [gatsbyjs.org/docs/ssr-apis](https://www.gatsbyjs.org/docs/ssr-apis/) but that's kind of a misleading page (since it's being called at build time, not server-side, right?) and I didn't realise it'd slot straight in to a docz app.

No I wouldn't say you missed it. The documentation on `docz` is missing some steps and this is partly because a large part of the process is primarily Gatsby so kinda hard to know what to document and what to leave to Gatbsy. At the same time I think this is something that could be a part of `docz` because we are extending Gatsby. I got to that link too but found it confusing but that led me to this issue
https://github.com/gatsbyjs/gatsby/issues/11013#issuecomment-610886184

**Comment by geelen** [comment]
My problem is I find Gatsby overwhelmingly confusing, and Docz in general feels way more straightforward. In fact I think the whole idea of Docz as being gatsby-powered but shielding the user from Gatsby's config complexity is such a good sweet spot, there's just a lot of surface area!

At least now we have this issue for people googling in future to find, so that'll help :)

**Comment by SNandini8698** [comment]
> Add a file named `gatsby-ssr.js` in the root folder of your project and try the following:
> 
> ```js
> import React from 'react'
> 
> export const onRenderBody = ({ setPostBodyComponents }) => {
>   setPostBodyComponents([
> 	  <script
>         data-goatcounter="https://fab.goatcounter.com/count"
>         async
>         src="https://gc.zgo.at/count.js"
>       />
>   ])
> }
> ```

Hi, @jesperorb thanks for the code. A small doubt should we add anything more in the gatsby-browser.js file in addition to this??
