### ISSUE TITLE
How to import third-party theme

### ISSUE THREAD

**Issue by iamwelk** [doczjs/docz#1470]
## Question

I can't import https://github.com/umijs/docz-theme-umi to my project.
Is there any way to import third-party theme to Docz conveniently?

```js
//gatsby-config.js
module.exports = {
  plugins: ["docz-theme-umi "],
};
```

**Comment by jesperorb** [comment]
Looking at the theme you linked it says that it uses [`v.1.0.4` of `docz`](https://github.com/umijs/docz-theme-umi/blob/c461509da380c3d94c5c05a072f968515c5eaf06/package.json#L28). Version `1` of `docz` does not use _Gatsby_ so I am guessing that it is not possible becuase that theme is made for the non-Gatsby `docz`.
