### ISSUE TITLE
Documenting Public Methods Support

### ISSUE THREAD

**Issue by wj2061** [doczjs/docz#1471]
## Is there a way to extracting public method document from Component? 

My Component has some public methods, I want to document them, but I have to write them by hand.  Is there a way to extracting public method document from Component automatically?

**Comment by jesperorb** [comment]
Are you refering to adding comments to methods inside of components like this? Yes, `description` and comments on methods are being picked up but there is for the moment no public API for getting this documentation as `docz` focuses mainly on `props` of components.

<img width="590" alt="Screenshot 2020-05-01 at 14 16 07" src="https://user-images.githubusercontent.com/21122051/80804832-a82c3680-8bb6-11ea-9b37-0a0ba029bc34.png">

As you can see the values are being parsed and added to the global `db`-object. But `docz` do not expose these values anywhere:
<img width="711" alt="Screenshot 2020-05-01 at 14 15 41" src="https://user-images.githubusercontent.com/21122051/80804835-a9f5fa00-8bb6-11ea-9fd7-42bf13938356.png">

`docz` have hook called `useComponentProps` which will return only the `props`-property of this parsed object. So in theory we could expose more than the props and build a helper component for this like so:
```jsx
import React from 'react'
// This hook does not exist
import { useComponentDocumentation } from "docz";

export const ComponentMethods = () => {
  const doc = useComponentDocumentation();
  // Do something with doc.methods
  return <div></div>;
}
```

I can see that it would be useful but it is not `docz` main concern but if someone would submit a PR for it we could discuss it :)
