### ISSUE TITLE
"Edit this on GitHub" button

### ISSUE THREAD

**Issue by geelen** [doczjs/docz#1473]
Bit confused, I found some old references to `EditPage` that would let you say "Edit this on GitHub" on each page. I'd love that for https://fab.dev but I can't get it working.

For reference, I want something that works like [this on Cloudflare Workers](https://developers.cloudflare.com/workers/about/how-it-works):

![image](https://user-images.githubusercontent.com/23264/80506580-b4718300-896d-11ea-9cbc-32d55f647ee8.png)

**Comment by jesperorb** [comment]
This should be supported by `docz`. Every entry in the documentation should get a `link`-property but if that property is empty the edit-button will not be displayed.

A guess is that it failes to extract the git-info somewhere here, I am looking into it.
https://github.com/doczjs/docz/blob/c7da16ba26252e80c7a044ef209e1d497cb34322/core/docz-core/src/utils/repo-info.ts#L48-L72

**Comment by jesperorb** [comment]
Duplicate of #1441
