### ISSUE TITLE
Shadowed Wrapper-component doesn't receive doc prop

### ISSUE THREAD

**Issue by shkoliar** [doczjs/docz#1476]
## Bug Report

From the docs section [Add favicon and metadata](https://www.docz.site/docs/add-favicon-and-metadata)

Comment in code example states for "The `doc` prop contains some metadata about the page being rendered that you can use."

```
// The doc prop contains some metadata about the page being rendered that you can use.
const Wrapper = ({ children, doc }) => <React.Fragment>
    <Helmet>
      ...
```
But in the shadowed `Wrapper` component `doc` is always undefined.

**To Reproduce**

Create the Wrapper-component by shadowing the original Wrapper-component.

Check that `doc` prop is `undefined`. 

**Expected behavior**

Have access to `doc` prop to use its values for SEO related information or provide another way to alter SEO meta information.

**Environment**

- docz version: 2.3.1
- MacOS 10.14.6
- Node 13.13.0 / yarn 1.22.4

**Additional context/Screenshots**

From the codebase in the `Layout` component, the `Wrapper` component is used and doesn't receive any props.

```
<MDXProvider components={components}>
  <Wrapper>
    <Layout {...props}>{children}</Layout>
  </Wrapper>
</MDXProvider>
```

**Comment by jesperorb** [comment]
That seems to be a mistake in the documentation or maybe that the components has changed since the writing of that part of the documentation. 

I think that the correct way is to shadow the `SEO`-file:
`your project/src/gatsby-theme-docz/base/Seo.js`:
```js
import React from 'react'
import { Helmet } from 'react-helmet-async'

const SEO = (metadata) => {
  return (
    <Helmet
      title={"My custom Title"}
      titleTemplate={`%s | ${"My custom title"}`}
    />
  )
}
export default SEO
```

**Comment by shkoliar** [comment]
@jesperorb 

Basically `SEO` component receives the only `title` prop which is based on a page name. We need also to make the  `Layout` shadow component with appropriate changes in this case.

I've created [PR](https://github.com/doczjs/docz/pull/1477) which allows setting SEO information without shadowing components.

**Comment by drewlustro** [comment]
I think the stale bot is too aggressive. There are so many valid, active issues on Docz that get auto-closed because the maintainers don't have time (at the moment) to engage with the project.

Please disable the stale bot.
