### ISSUE TITLE
Relative links inside MDX files causing full-page reloads

### ISSUE THREAD

**Issue by geelen** [doczjs/docz#1478]
Not sure if this is easily possible, or if maybe my app is broken somehow, but I noticed that links within my `.mdx` files that point to other documentation pages are causing full-page reloads, but links in the sidebar do not (presumably they're using gatsby's `Link` component).

For example the first link on https://fab.dev/guides/getting-started points to https://fab.dev/guides/feedback but isn't an instantaneous page transition. Not that it's a big deal, since the site is fast, but I still wonder why Gatsby is rehydrating the page if it's not automatically picking these sorts of things up?

Am I missing something?

**Comment by jesperorb** [comment]
I get the same result when testing locally on a test-project. The links are getting formatted correctly `/relative` but on click I get a reload.

The Sidebar is part of the theme and in `docz` control and is using as you said `Link`.

The links inside of the `.mdx`-pages are generated with `gatsby-plugin-mdx` and `docz` doesn't do much on that part I think. But they should be behaving like the sidebar. Maybe something is up on how `docz` is using these plugins
https://github.com/doczjs/docz/blob/master/core/gatsby-theme-docz/gatsby-config.js

**Comment by geelen** [comment]
Thanks for your quick replies on this, but I think I've had the same problem with Gatsby by itself, maybe this plugin is required: https://www.gatsbyjs.org/packages/gatsby-plugin-catch-links/

**Comment by jesperorb** [comment]
Alright, nice, seems like something either `docz` should do by default or it should be an opt-in or opt-out via `doczrc.js`, will evaluate. As I expect the same as you did, no refresh on relative links.

**Comment by geelen** [comment]
Ah awesome. While you're looking into it, it just occurred to me that it'd be great if all non-relative URLs to open in a new tab, since they're invariably links off to other discussions or other projects. That's something that has always bugged me about Markdown, that there's no easy way to add `target="_blank"` to a markdown link without rewriting it as an `<a>`.

Imo that'd be another good default behaviour that makes Docz "just work like you want", though again I have no idea what Gatsby plugin might actually do that...
