### ISSUE TITLE
Does this support with react 15 version

### ISSUE THREAD

**Issue by vashi38** [doczjs/docz#1483]
## Does this support with react 15?

My project is in react 15 and wanted to create the components library for internal use. So I just wanted to know, is it work with react 15?
If no, can you suggest any other which work with react 15.

Thanks

**Comment by jesperorb** [comment]
Since `1.0` you need `react` and `react-dom` **>=16.8.0** installed.

And no, sorry, I do not know the version dependencies for other tools.
