### ISSUE TITLE
Nested menus not working and no documentation or example to help

### ISSUE THREAD

**Issue by rcline** [doczjs/docz#1484]
Hello all!  Thank you for this great open source tool!!!

## Bug Report

**Describe the bug**

I am trying to migrate my documentation site to use Docz.  A nested menu structure is a required feature for me, and it looks like you have put thought into how that can work.  I see the [config menu documentation](https://www.docz.site/docs/project-configuration#menu) that references both ordering a menu and nesting menus. 

**To Reproduce**

An example menu structure:
```
- TechOrg
  - Teams
    - Team 1 Page
    - Team 2 Page
  - Guilds
    - Guild 1 Page
    - Guild 2 Page
```

The top of Team 1 Page's markdown file would look like this:
```
---
name: A Team
menu: Teams
---
```

And the docz config file would look like this:
```
export default {
  menu: {
    name: 'TechOrg',
    menu: [
      'Teams',
      'Guilds',
    ],
  },
}
```

However, instead of nesting these pages in the menu provided, they are put as top level menu items (with black placeholders for nesting under `TechOrg`:
![Screen Shot 2020-05-01 at 11 38 43 AM](https://user-images.githubusercontent.com/1102747/80828095-f5ea7400-8ba1-11ea-9b52-ed1d6aa74b42.png)

**Expected behavior**

I would love some more documentation on this and/or a nested menu example.

I have tried to dig into the code a bit.  It seems the merge method is very top level:
https://github.com/doczjs/docz/blob/master/core/docz/src/hooks/useMenus.ts#L52

We might have to consider using a pattern to specify which nested menu item a page is assigning itself to.  Something like `TechOrg/Teams`.  And then be able to split on `/`, traverse the target menu config, and apply the page there.

**Environment**

- docz version: 2.3.1
- OS: OSX 10.15.4
- Node/npm version: Node v12.13.1/npm 6.13.4

**Additional context/Screenshots**

It seems a tangental issue is ordering the children of a menu parent.  The menu is properly ordered per the config, but I am unsure how pages that subscribe themselves to a specific menu parent can be ordered among other pages in that menu parent.

Again, thank you for this tool!!! ❤️ 🙇‍♂️

**Comment by rcline** [comment]
Another screenshot to show where the pages (Frontend Guild and Guild List) are being placed:

![Screen Shot 2020-05-01 at 11 58 17 AM](https://user-images.githubusercontent.com/1102747/80832596-2cc48800-8baa-11ea-92c6-504c9d569ed3.png)

**Comment by rcline** [comment]
Bump

**Comment by Tymek** [comment]
Can we reopen this please? Documentation on this topic is still missing or hard to find
