### ISSUE TITLE
Font awesome icons are not getting rendered in the docz demo

### ISSUE THREAD

**Issue by mano3493** [doczjs/docz#1486]
Font awesome icons are not getting rendered in the docz demo ?

My project using font awesome for few icons, when i integrated with docz those icons are not visible in the preview section.

I don't see any error in the console as well, Can you please help me here ?? 

<img width="1253" alt="Screenshot 2020-05-05 at 1 37 02 PM" src="https://user-images.githubusercontent.com/8075363/81046222-85ab5d80-8ed5-11ea-8706-38ff90528044.png">

<img width="1346" alt="Screenshot 2020-05-05 at 1 35 58 PM" src="https://user-images.githubusercontent.com/8075363/81046195-71fff700-8ed5-11ea-9f65-9320143e36e7.png">

**Comment by jesperorb** [comment]
How are you setting up your icons? How are you importing them and using them?

**Comment by mano3493** [comment]
In doczrc.js I am passing htmlContext head and passing the link tag

<img width="1124" alt="Screenshot 2020-05-05 at 2 04 09 PM" src="https://user-images.githubusercontent.com/8075363/81048206-7f1ee500-8ed9-11ea-846e-8c0f46a2459c.png">

**Comment by mano3493** [comment]
I have also tried this

<img width="1135" alt="Screenshot 2020-05-05 at 2 50 33 PM" src="https://user-images.githubusercontent.com/8075363/81051689-cc05ba00-8edf-11ea-9e65-945f0d1f4726.png">

**Comment by mano3493** [comment]
Directly importing font-awesome in my MDX solved the problem. Closing the issue :)
