### ISSUE TITLE
Docz Playground dragging and reducing the screen size missing in new version

### ISSUE THREAD

**Issue by mano3493** [doczjs/docz#1488]
Hi,

This is old version of Docz 0.12.13, here playground looks super cool with drag and resize, expand collapse, mobile view, tablet view and desktop.Attaching the images for the same.

<img width="656" alt="Screenshot 2020-05-05 at 3 48 03 PM" src="https://user-images.githubusercontent.com/8075363/81056438-2c005e80-8ee8-11ea-9080-70a86d0a841d.png">
<img width="935" alt="Screenshot 2020-05-05 at 3 48 08 PM" src="https://user-images.githubusercontent.com/8075363/81056443-2dca2200-8ee8-11ea-9fe0-9fa2a9b486a7.png">
<img width="406" alt="Screenshot 2020-05-05 at 3 48 16 PM" src="https://user-images.githubusercontent.com/8075363/81056454-2f93e580-8ee8-11ea-8724-944a451c5e91.png">
<img width="376" alt="Screenshot 2020-05-05 at 3 48 24 PM" src="https://user-images.githubusercontent.com/8075363/81056466-328ed600-8ee8-11ea-92a6-8b05d9e473e9.png">

But In my other project I am using the version 2.3.1, Where Playground doesn't have this options, Should i add any configuration to get like above one ??

Current play ground

<img width="1260" alt="Screenshot 2020-05-05 at 3 52 09 PM" src="https://user-images.githubusercontent.com/8075363/81056579-67029200-8ee8-11ea-9a4d-221bac6712ab.png">

Please help here :)

**Comment by jesperorb** [comment]
These features went away with version 2 of Docz sadly. I opened a PR some time ago where I adressed these issues but didn't have time to continue and merge conflicts built up.

So you can't get the same view as in version 1. I will try to reopen my previous PR if I have the time as most of the work on this was done:

https://github.com/doczjs/docz/pull/1159
