### ISSUE TITLE
D3 visuals not working `docz build` but works on `docz dev`

### ISSUE THREAD

**Issue by danm** [doczjs/docz#1494]
We have a Docz V2 project written in typescript, using styled-components, generating a static site to Github pages using `docz build`.

I had to add a Gatsby config to include  `plugins: ['gatsby-plugin-styled-components']` for the styles to render which makes sense (though I might add this to your docs somewhere sensible). Next problem I'm running into is our D3 charts don't render. I can't find any docs to say why this might be or what plugins I might need to add.

The project is a work in progress but you can see the current build here : https://bbc.github.io/telescope-kit/charts/horizontal-chart/

It should look like this (rendered using `docz dev`)
![Screenshot 2020-05-07 at 16 38 57](https://user-images.githubusercontent.com/6394846/81314700-576a8100-9081-11ea-9937-629b75150630.png)

Curiously, the menus don't work either when building, though they do when using `dev`

I am overriding the default gatsby-theme-docz which just uses a custom homepage, and a custom logo. 

Everything works out the box when running `docz dev`. But `docz build` is a totally another story. What am I missing! Cheers!!

**Comment by 18518300669** [comment]
我认为我们遇到了类似的问题。我的svg和less在docz dev时是没有问题的，但是在docz build 托管至github pages时，不起作用了。使用了'gatsby-plugin-less','gatsby-plugin-svg-sprite'。
这让我有点失去对docz的使用信心。

**Comment by 18518300669** [comment]
我的问题已经解决，是package中sideEffects带来的问题。
