### ISSUE TITLE
TypeError: `mergeWith` is not a function

### ISSUE THREAD

**Issue by inlet** [doczjs/docz#1498]
When running `docz build` this error is thrown:

```
ERROR #10123  CONFIG

We encountered an error while trying to load your site's gatsby-config. Please fix the error and try again.

  TypeError: mergeWith is not a function

  - gatsby-config.js:122 Object.<anonymous>
    /Users/pbrouwer/test/.docz/gatsby-config.js:122:15
```

The first line of the generated config:

```js
const { mergeWith } = require('docz-utils')
```

But it seems that `mergeWith` is not exported in `docz-utils`:

![image](https://user-images.githubusercontent.com/232559/81664854-39659d80-9440-11ea-96d7-6603e1bbf814.png)

**Comment by inlet** [comment]
I have the latest version of `lodash` installed, if I remove that the docz will build.

Any ideas?

**Comment by thecotne** [comment]
you need to install `docz-utils@^2.3.0` separately and it will work ... (latest version for now is 2.3.0)

**Comment by Glinkis** [comment]
I'm also getting this error. Why would I need to install the utils separately when they are already installed with the main package?

**Comment by Freddixx** [comment]
That definitely solved it, thanks. 

Is that solved by a clean install (because I just upgraded deps from v1 to v2)?
