### ISSUE TITLE
Can't using cra with docz

### ISSUE THREAD

**Issue by luisfagottani** [doczjs/docz#1499]
## Bug Report

**Describe the bug**
If I install docz on an already configured cra, when trying to run the cra there is a preflight-check error.
The error points to a dependency called webpack-dev-server.
If I remove dependde from node_modules, everything will be back to normal.
There is a conflict with react-scripts.

**To Reproduce**
```shell
yarn create react-app my-app
yarn add docz
yarn dev
```

**Environment**

- docz version: 2.0.0-rc.x 
- OS: OSX 10.13.4
- Node/npm version: Node 10.16.3/npm 6.11.3

**Additional context/Screenshots**

<img width="930" alt="Captura de Tela 2020-05-14 às 11 09 13" src="https://user-images.githubusercontent.com/13802932/81944597-60080d80-95d3-11ea-8a70-c9ef40a3aba0.png">

**Comment by ecspertiza** [comment]
I have the save problem

**Comment by kkarpeev** [comment]
Same issue

**Comment by luisfagottani** [comment]
Anyone?

**Comment by Rajdeepc** [comment]
put an .env file in your root folder and add SKIP_PREFLIGHT_CHECK=true
this works, I have tested it

To avoid build issues: put docz package in devDependencies.
