### ISSUE TITLE
Theming is broken or misdocumented.

### ISSUE THREAD

**Issue by steveruizok** [doczjs/docz#1502]
## Bug Report

I'm trying to follow the instructions [here](https://www.docz.site/docs/creating-your-themes) and am running into a few problems.

1. The `ThemeProvider` component does not accept the `config` returned by `useConfig`. It only works with `config.themeConfig`.

❌ Does not work
```jsx
import React from 'react'
import { theme, useConfig } from 'docz'
import { ThemeProvider } from 'theme-ui'

const Theme = ({ children }) => {
  const config = useConfig() // 👎
  return (
    <ThemeProvider theme={config}> // 👎
      <div>{children}</div>
    </ThemeProvider>
  )
}

export default theme(themeConfig)(Theme)
```

✅ Works
```jsx
import React from 'react'
import { theme, useConfig } from 'docz'
import { ThemeProvider } from 'theme-ui'

const Theme = ({ children }) => {
  const { themeConfig } = useConfig() // 👍
  return (
    <ThemeProvider theme={themeConfig}> // 👍
      <div>{children}</div>
    </ThemeProvider>
  )
}

export default theme(themeConfig)(Theme)
```

2. Even after applying the fix above, passing a `themeConfig` object to the `theme` function does not merge this `themeConfig` into the default theme configuration.

❌ Does not work — The `themeConfig` returned from `useConfig` is **just** the `myThemeConfig` object.
```jsx
// src/gatsby-theme-docz/index.js
import React from 'react'
import { theme, useConfig } from 'docz'
import { ThemeProvider } from 'theme-ui'

const Theme = ({ children }) => {
  const { themeConfig } = useConfig()
  return (
    <ThemeProvider theme={themeConfig}>
      <div>{children}</div>
    </ThemeProvider>
  )
}

const myThemeConfig = {
  colors: {
    primary: 'tomato',
    secondary: 'khaki',
    gray: 'lightslategray',
  },
}

export default theme(myThemeConfig)(Theme)  // 👎
```

✅ Works — Here we're merging the two configs ourselves.
```jsx
// src/gatsby-theme-docz/index.js
import React from 'react'
import { theme, useConfig } from 'docz'
import { ThemeProvider } from 'theme-ui'

import defaultTheme from 'gatsby-theme-docz/src/theme';  // 👍

const Theme = ({ children }) => {
  const { themeConfig } = useConfig()
  return (
    <ThemeProvider theme={themeConfig}>
      <div>{children}</div>
    </ThemeProvider>
  )
}

const myThemeConfig = {
  ...defaultTheme,  // 👍
  colors: {
    ...defaultTheme.colors,  // 👍
    primary: 'tomato',
    secondary: 'khaki',
    gray: 'lightslategray',
  },
}

export default theme(myThemeConfig)(Theme)  // 👍
```

> 👋 **Note:** If you're having problems too and have found this issue from a search, this is probably the code you're after. You can copy and paste the code above into `yourProject/src/gatsby-theme-docz/index.js`. 
>
> Another option is to copy the entire `gatsby-theme-docz` folder from `yourProject/.docz/src` into `yourProject/src/`, then hack from there.

**To Reproduce**

1. create-docz-app my-docz-app && cd my-docz-app
2. Follow [instructions here](https://www.docz.site/docs/creating-your-themes)

**Expected behavior**

The API described in the docs would be fantastic if it worked as described. 

I believe the fix is partially in code—by making the `theme` function correctly deep merge the provided config with the original theme—and partially in the docs, by changing `theme={config} to `theme={config.themeConfig}`.

**Environment**

- docz version: ^2.3.1
- OSX
- Node/npm version: 10.13.0

**Comment by drewlustro** [comment]
This is not stale.

**Comment by vittoriozamboni** [comment]
Thank you, found the same issue.
