### ISSUE TITLE
Multi-language box?

### ISSUE THREAD

**Issue by oeddyo** [doczjs/docz#1503]
## Question
Hi there,
I'm wondering how can I add a box which shows multiple languages for the same logic? This is useful in many API docs

for example in Meilisearch they have:
![image](https://user-images.githubusercontent.com/1943146/82125655-375f4f80-975c-11ea-8849-6c63d48bd3bc.png)

https://docs.meilisearch.com/guides/introduction/quick_start_guide.html#download-and-launch
a box for how to do the same thing in various languages

**Description**
*Give more information about your doubt*

* Twitter: If it's just a quick question you can ping me on Twitter: https://twitter.com/pedronauck

**Comment by oeddyo** [comment]
asked on twitter but for search visibility posted here as well

**Comment by Dragomir-Ivanov** [comment]
Any resolution for this issue?

**Comment by oeddyo** [comment]
@Dragomir-Ivanov I didn't find anything

**Comment by Dragomir-Ivanov** [comment]
Thanks mate!
