### ISSUE TITLE
My docz:buils is failing with webpack error

### ISSUE THREAD

**Issue by mano3493** [doczjs/docz#1524]
Hi,

I did docz setup for one of my projects. My docz:dev is running successfully without any error. But  docz:build failing with webpack error. Can you please check this issue ?? 

Please check the below issue

success run queries - 136.051s - 60/60 0.44/s
failed Building static HTML for pages - 30.779s

 ERROR #95313 

Building static HTML failed for path "/components-timeline-readme"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  1986 |         this.setState({ theme: themeProp });
  1987 |       } else {
> 1988 |         var subscribe = styledContext.subscribe;
       | ^
  1989 | 
  1990 |         this.unsubscribeId = subscribe(function (nextTheme) {
  1991 |           var theme = determineTheme(_this2.props, nextTheme, defaultProps);

  WebpackError: TypeError: Cannot read property 'subscribe' of undefined
  
  - styled-components.es.js:1988 WithTheme.componentWillMount
    node_modules/styled-components/dist/styled-components.es.js:1988:1
  
  - README.mdx:71 Promise._resolveFromExecutor
    components/ActionMenu/README.mdx:71:28

<img width="1665" alt="Screenshot 2020-06-15 at 11 30 23 AM" src="https://user-images.githubusercontent.com/8075363/84622871-a9fa5100-aefb-11ea-8e55-4732764c0e4f.png">

**Comment by testuserdecz** [comment]
Hi @mano3493  did you manage to fix this?
