### ISSUE TITLE
WebpackError: Invariant Violation for "tinycolor2"

### ISSUE THREAD

**Issue by jeggy** [doczjs/docz#1528]
## Bug Report

**Describe the bug**
I'm trying to use mdx with an a component that is using GraphQL and ant design less styling.

I'm then getting this error: `WebpackError: Invariant Violation:`

![image](https://user-images.githubusercontent.com/51459/84837900-132fb080-b031-11ea-8dc1-86a08694f0c2.png)

<details>
<summary>Full logs</summary>
 ERROR 

WebpackError: Invariant Violation:

  4 | };
  5 | Object.defineProperty(exports, "__esModule", { value: true });
> 6 | var tinycolor2_1 = __importDefault(require("tinycolor2"));
    |                                            ^
  7 | var hueStep = 2; // 色相阶梯
  8 | var saturationStep = 16; // 饱和度阶梯，浅色部分
  9 | var saturationStep2 = 5; // 饱和度阶梯，深色部分

  Error: WebpackError: Invariant Violation:
  
  - build-html.ts:127 doBuildPages
    [cra-antd-docz]/[gatsby]/src/commands/build-html.ts:127:24
  
  - build-html.ts:147 buildHTML
    [cra-antd-docz]/[gatsby]/src/commands/build-html.ts:147:3
  
  - develop-process.ts:121 createIndexHtml
    [cra-antd-docz]/[gatsby]/src/commands/develop-process.ts:121:7
  
  - develop-process.ts:144 startServer
    [cra-antd-docz]/[gatsby]/src/commands/develop-process.ts:144:3

  - develop-process.ts:448 module.exports
    [cra-antd-docz]/[gatsby]/src/commands/develop-process.ts:448:39
</details>

**To Reproduce**

I have created a reproducible project here: https://github.com/jeggy/docz-cra-antd-apollo-bug

**Comment by NightFox7** [comment]
We are having the same issue. Did you find a solution ?

**Comment by jeggy** [comment]
Nope, as this is most likely some problem in some external code. I just decided to try to make a simple example and hopefully someone could pinpoint where the issue actually lies. 

Without a lot of knowledge within the whole javascript ecosystem. It seems like it has something to do with the compiled code from typescript code within node_modules? Both Apollo and Ant have a big part written in Typescript.

**Comment by johnatspreadstreet** [comment]
Also having the same issue, but more specifically in Gatsby (using AntD)

![image](https://user-images.githubusercontent.com/37089166/85408265-4b078e00-b532-11ea-86c8-7db3d03e5e4c.png)
