### ISSUE TITLE
Menu Sort

### ISSUE THREAD

**Issue by max10rogerio** [doczjs/docz#1531]
## Question

**Description**
I need create the menu in the order:
```
Get Started
Button
```
The `Get Started` is the README.md file and contains:
```
---
name: Get Started
route: /
---
```
And progress button contains:
```
---
name: ProgressButton
route: /buttons/progress-button
menu: Buttons
---
```

But the menu ordem generate wrong... see the image:
![image](https://user-images.githubusercontent.com/21085292/85176594-8b27f180-b250-11ea-9020-c6d9dbd254c2.png)

How do I sort the menu?

**Comment by RayBans2111** [comment]
Did you figure out how to do this? I had to resort to putting roman numerals at the beginning of each name in my front matter in order to organize my pages correctly.
