### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by mxs888** [doczjs/docz#1559]
## Question

I tried running the following the commands:

`yarn add docz # react react-dom`

&

`yarn docz dev`

after which I got the following error:

`yarn run v1.22.4
$ /home/nigless/projects/AmaPro-frontend/node_modules/.bin/docz dev

Building app

 ERROR 

(node:5783) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

(node:5797) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

Debugger listening on ws://127.0.0.1:9229/6b29c932-de0c-41a7-a9c6-619372329ad9
For help, see: https://nodejs.org/en/docs/inspector

 ERROR 

(node:5804) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time

success open and validate gatsby-configs - 0.526s
success load plugins - 0.355s
success onPreInit - 0.034s
success initialize cache - 0.009s
success copy gatsby files - 0.041s
success onPreBootstrap - 0.053s
success createSchemaCustomization - 0.007s
warn The gatsby-plugin-mdx plugin has generated no Gatsby nodes. Do you need it?
success Checking for changed pages - 0.002s
success source and transform nodes - 0.407s
success building schema - 0.394s
success createPages - 0.003s
success Checking for changed pages - 0.002s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allDoczEntries" on type "Query".

If you don't expect "allDoczEntries" to exist on the type "Query" it is most likely a typo.
However, if you expect "allDoczEntries" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allDoczEntries" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: ../node_modules/gatsby-theme-docz/lib/createPagesStatefully.js:28:10

success createPagesStatefully - 0.125s
success update schema - 0.029s
success write out redirect data - 0.002s
success onPostBootstrap - 0.002s
info bootstrap finished - 5.939s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.095s
success write out requires - 0.006s
success run page queries - 0.027s - 3/3 112.41/s

 ERROR 

ENOENT: no such file or directory, open '/home/nigless/projects/AmaPro-frontend/.docz/public/page-data/sq/d/1635659820.json'

  Error: ENOENT: no such file or directory, open '/home/nigless/projects/AmaPro-frontend/.docz/  public/page-data/sq/d/1635659820.json'
  
  - websocket-manager.ts:94 forEach
    [AmaPro-frontend]/[gatsby]/src/utils/websocket-manager.ts:94:27
  
  - Map.forEach
  
  - websocket-manager.ts:83 getCachedStaticQueryResults
    [AmaPro-frontend]/[gatsby]/src/utils/websocket-manager.ts:83:25
  
  - websocket-manager.ts:126 WebsocketManager.init
    [AmaPro-frontend]/[gatsby]/src/utils/websocket-manager.ts:126:38
  
  - start-server.ts:297 startServer
    [AmaPro-frontend]/[gatsby]/src/utils/start-server.ts:297:35
  
  - start-webpack-server.ts:45 startWebpackServer
    [AmaPro-frontend]/[gatsby]/src/services/start-webpack-server.ts:45:7
  

not finished Building development bundle - 0.106s`

I have tried getting this to work all night but no avail. Please help.

**Comment by jcowman2** [comment]
@mxs888 Do you have any mdx files in your directory? I had a similar error as yours, but I created `index.mdx` in the root directory with the following contents:

```
---
name: Hello world
route: /
---

# Hello world

Hello, I'm a mdx file!
```
After that I reran `docz dev` and it worked! Hope this helps. 😄

**Comment by Himadu2000** [comment]
I also have a similar problem. here is an example repo, [Repo](https://github.com/Cezerin3/Documentation/tree/updating-sass)

**Comment by sophyphreak** [comment]
I have a similar problem to this issue

**Comment by renatobenks** [comment]
exactly as pointed out for @jcowman2, currently, if you don't have any `.mdx` files in your codebase, or even simple `md`, the docz will gonna breakdown because it the parsing processes trusts that you're running it into some existent files to be shown as an documentation output, and once you don't have it, it unfortunately breaks. We're going to add a step to solve this in a way that you'll have a friendly message for that kind of error. But either way, you should try to run this with a couple markdown files to be reached and shown.
