### ISSUE TITLE
Lerna monorepo with separated docs can't resolve other packages

### ISSUE THREAD

**Issue by vittoriozamboni** [doczjs/docz#1578]
## Bug Report

**Describe the bug**

When using a lerna monorepo and setting up docz in a separated package, it's not able to resolve other packages.

**To Reproduce**

I tried in my repository first, where I have lerna setup and working with two packages: 

```bash
borrow-ui/
  | lerna.json
  | packages.json
  | packages /
  |  | ui/
  |  | docs/    
```

But the same is happening with the example repository.

```bash
cd ~/repositories;
yarn create docz-app docz-app-monorepo-separate-docs --example monorepo-separate-docs
cd docz-app-monorepo-separate-docs/packages/docs
yarn
yarn dev
```

Adding the workspaces as per documentation doesn't help (even with variations):

```javascript
  "workspaces": [
    "../../packages/**/*",
    "../../../packages/**/*"
  ]
``` 

```shell
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve 'Alert' in '/home/vittorio/repositories/docz-app-monorepo-separate-docs/packages/docs/.docz/.cache/caches/gatsby-plugin-mdx/mdx-scopes-dir'

If you're trying to use a package make sure that 'Alert' is installed. If you're trying to use a local file make sure that the path is correct.

File: .cache/caches/gatsby-plugin-mdx/mdx-scopes-dir/8a711ec297178d9cf83a46b084cb894c.js
```

**Expected behavior**

A working build with other packages available through import.

**Environment**

- docz version: [2.3.1]
- OS: Ubuntu 20.04 LTS on WSL2
- Node/npm version: [Node 14.10.0 / yarn 1.22.5]

**Comment by 0length** [comment]
I have this problem so

**Comment by gmonte** [comment]
Try add this content in your docs path:

When using a monorepo, you need to tell Docz where your packages are that you want to appear in your documentation:
`doczrc.js`
```js
export default {
  files: ['../ui/**/*.mdx'],
  ignore: ['../ui/node_modules'],
  docgenConfig: {
    searchPatterns: ['../ui/**/*.js']
  }
}
```

If you are using React with jsx syntactic sugar, you need transpile your monorepo packages changing the webpack default configuration: 
`gatsby-node.js`
```js
exports.onCreateWebpackConfig = ({ loaders, getConfig }) => {
  const config = getConfig()
  config.module.rules = [
    // Omit the default rule where test === '\.jsx?$'
    ...config.module.rules.filter(
      rule => String(rule.test) !== String(/\.jsx?$/)
    ),
    // Recreate it with custom exclude filter
    {
      // Called without any arguments, `loaders.js()` will return an
      // object like:
      // {
      //   options: undefined,
      //   loader: '/path/to/node_modules/gatsby/dist/utils/babel-loader.js',
      // }
      // Unless you're replacing Babel with a different transpiler, you probably
      // want this so that Gatsby will apply its required Babel
      // presets/plugins.  This will also merge in your configuration from
      // `babel.config.js`.
      ...loaders.js(),
      test: /\.jsx?$/,
      // Exclude all node_modules from transpilation, except for your monorepo packages
      exclude: modulePath => /node_modules/.test(modulePath)
        // eslint-disable-next-line no-useless-escape
        && !/node_modules[\/\\](@yourMonorepoBaseName)/.test(modulePath)
    }
  ]
}
```

I recommend that your monorepo packages have the same base name, such as::
```
borrow-ui/
  | packages/
  |  | ui/ <- @myMonorepo/ui
  |  | docs/   <- @myMonorepo/docs
```

**Comment by vittoriozamboni** [comment]
Thank you for your help. 
I tried your solution and  it works! However, I found that I need to keep a watcher running to generate my library code as well. 

I took a little bit of time before coming back and investigating other threads as well I found a different solution that allows me to drop the watcher and work just with docz dev server.

1. I added the peer dependencies of my application to the docs `package.json`;
2. Added the following code to `gatsby-node.js`; the alias is pointing to the `src` folder directly, so I can use the standard import path but include the components directly:

```js
const path = require("path");

exports.onCreateWebpackConfig = (args) => {
  args.actions.setWebpackConfig({
    resolve: {
      alias: {
        "@borrow-ui/ui": path.resolve(__dirname, "../../../packages/ui/src"),
      },
    },
  });
};
```

3. Configured `doczrc.js` as follow, to include only relevant JS/mdx from the `ui` package and the mdx of the docs package:

```js
export default {
  docgenConfig: {
    searchPatterns: ["../ui/**/*.js"],
  },
  filterComponents: (files) =>
    files.filter((filepath) => /\/[A-Z]\w*\.(js|jsx)$/.test(filepath)),
  files: ["**/*.docz.mdx", "../ui/**/*.docz.mdx"],
  ignore: ["../ui/node_modules"],
};
```

For completeness, this is the `gatsby-config.js` content, to load sass files:

```js
module.exports = {
  plugins: ["gatsby-plugin-catch-links", "gatsby-plugin-sass"],
};
```
