### ISSUE TITLE
docz dev is failing

### ISSUE THREAD

**Issue by mano3493** [doczjs/docz#1637]
Hi,

docz dev is failing with below error, Can you please check this ? 

 ERROR 

Panicking because nodes appear to be being changed every time we run queries. This would cause the site to recompile infinitely.
Check custom resolvers to see if they are unconditionally creating or mutating nodes on every query.
This may happen if they create nodes with a field that is different every time, such as a timestamp or unique id.

<img width="1670" alt="Screenshot 2021-06-14 at 12 31 51 PM" src="https://user-images.githubusercontent.com/8075363/121852279-e201c300-cd0c-11eb-9a2b-81bd45ddc623.png">

**Comment by jedychen** [comment]
I have the same issue, when running Docz on a React Native repo (MacOS).

**Comment by renatobenks** [comment]
I'll be closing this one as we're going to wanna get it solved in a single issue (https://github.com/doczjs/docz/issues/1654), as referred above. If it's happening also in a web environment (or non-react-native projects), please, open a new issue.
