### ISSUE TITLE
Can I use docz to document my vue component lib?

### ISSUE THREAD

**Issue by AlanKnightly** [doczjs/docz#1643]
## Can I use docz to document my vue component lib?

**I search for a while but can not find even one example of documenting vue componet with docz. Is that possible?  Or is there any plan to support vue? **

**Comment by RealSGII2** [comment]
Considering `docz` was written with React, I doubt support for Vue would be added.

Some things you can use, however (taken from [Vue Community](https://vue-community.org/guide/ecosystem/documentation.html#documentation-websites)):
- [Vuepress](https://vuepress.vuejs.org/) 
- [Docutate](https://docute.org/)
- [Storybook](https://storybook.js.org/)
- [Vue Styleguidist](https://vue-styleguidist.github.io/)

**Comment by renatobenks** [comment]
Unfortunately not, docz was made exclusively to work with React underneath. That said, we're not intending to support other community libraries, considering that those communities already have their own documentation libraries.
