### ISSUE TITLE
Images not loading in Gatsby v3

### ISSUE THREAD

**Issue by fostimus** [doczjs/docz#1659]
## Bug Report

**Describe the bug**

Images in mdx don't load when migrating to Gatsby V3

**To Reproduce**

1. Have an existing docz powered site with images
2. Upgrade to Gatsby 3.x
3. Images don't load

```mdx
![alt text shows](./but-i-do-not.png)
```

**Expected behavior**

Images load

**Environment**

- docz version: 2.3.1
- OS: OSX
- Node/npm version: Node 12.19.0

**Additional context/Screenshots**
Dev tools looks like the image is loaded by webpack, and then put as the `src` of an image tag. Is there some way to just use the image loaded by webpack?

<img width="391" alt="Screen Shot 2021-10-02 at 7 34 26 PM" src="https://user-images.githubusercontent.com/8053880/135734446-0a0e0246-12db-4a13-8714-1d9744b5071f.png">
<img width="179" alt="Screen Shot 2021-10-02 at 7 32 04 PM" src="https://user-images.githubusercontent.com/8053880/135734445-113abc7f-6673-4f70-8c22-76cbb72b1a1f.png">

**Comment by fostimus** [comment]
For anyone coming here for help: the problem is that the default export is no longer being imported. There needs to be an update to how `remark-docz` processes the markdown so webpack can properly handle the image.

The workaround I'm doing for now: import images directly into .mdx and use img tags. Not ideal for writing markdown, but this lets webpack handle the imgs directly

**Comment by renatobenks** [comment]
Well done @fostimus, thank you for sharing your workaround to this, it'll be helpful.

I'll be closing this issue once we have an entire roadmap, and we're going through it, which involves upgrading gatsby as well as everything else needed to that, including remark.
