### ISSUE TITLE
Gatsby dependency upgrade plans

### ISSUE THREAD

**Issue by emacoti** [doczjs/docz#1684]
Hi there, are there any plans to upgrade to the newer v4 of Gatsby?

**Comment by renatobenks** [comment]
Hey, sure thing! We're actually working to make it even better by introducing a new way to how gatsby is used and integrated. We're planning to release soon, in a few weeks, a newer version of docz, in alpha with a few of these upcoming changes.

In the meantime, we can try to explore how to support what you wanna do, or any problem that you might be having with the outdated version, but if so, please, just open a new issue with the proper title and description. Thanks!
