### ISSUE TITLE
node_modules\.bin\gatsby 

### ISSUE THREAD

**Issue by XueWenPeng** [doczjs/docz#1714]
## Bug Report

**By run docz  dev, it's show node_modules\.bin\gatsby not an internal or external command, nor a runnable program
or batch file**

I saw code in node_modules\docz-core\dist\index.js:
`const gatsbyPath = path$1__default.join(repoRootPath, 'node_modules/.bin/gatsby');`
```
spawn$1(gatsbyPath, ['develop', '--host', `${args.host}`, '--port', `${args.port}`, useHttps ? '--https' : '', ...caFileOption, ...keyFileOption, ...certFileOption].filter(Boolean), {
    stdio: 'inherit',
    cwd: docz
  });
```
but there is no `gatsby` file in `node_modules\.bin`

**Comment by zhuyudong** [comment]
`npm i gatsby-cli` or `yarn add gatsby-cli`

**Comment by XueWenPeng** [comment]
> `npm i gatsby-cli` or `yarn add gatsby-cli`

谢谢！

**Comment by FontEndArt** [comment]
请恕我直言，官方入门文档上并没有找到关于这段描述，导致我一度以为是自己操作有问题
