### ISSUE TITLE
Error on first install. nError handler for invocation 'building-schema', error was 'TypeError: (0 , _buildASTSchema.getDescription)

### ISSUE THREAD

**Issue by renanbronchart** [doczjs/docz#1721]
## Bug Report

I have a react-native project with dependency to "graphql": "^15.6.1", "react-native": "0.65.1", "react": "17.0.2", "react-dom": "17.0.2",

When I tried to run docz after install
`yarn docz:dev`

I have this error:
```
Missing onError handler for invocation 'building-schema', error was 'TypeError: (0 , _buildASTSchema.getDescription) is not a function'. Stacktrace was
'TypeError: (0 , _buildASTSchema.getDescription) is not a function
```

**Comment by JamesIves** [comment]
I'm getting this also. Is there a fix available for this?

**Comment by renatobenks** [comment]
duplicated by #1624
