### ISSUE TITLE
What font is used in Docz image?

### ISSUE THREAD

**Issue by obtusedev** [doczjs/docz#1729]
## What font is this?

![font](https://user-images.githubusercontent.com/66740598/167921864-65e28930-e4bd-428b-8502-dedd5940dee2.png)

**Comment by abhilipsasahoo03** [comment]
Found a really similar one on MyFonts. This one's called Hernández Niu Bold. 

![IMG_20220829_131710.jpg](https://user-images.githubusercontent.com/80174214/187151078-cf94adff-a907-435b-8399-8af27e017f77.jpg)

**Comment by pedronauck** [comment]
I really don't remember anymore the font I used 😕 and recently I've been stolen and my computer with all my fonts were lost, so will be hard to find which one was.

**Comment by obtusedev** [comment]
> I really don't remember anymore the font I used confused and recently I've been stolen and my computer with all my fonts were lost, so will be hard to find which one was.

Really sorry to hear that. Thanks for your help.
