### ISSUE TITLE
supply the readme in npm 

### ISSUE THREAD

**Issue by ycjcl868** [doczjs/docz#188]
## Question
may supply the `readme` in the [npm](https://www.npmjs.com/package/docz)  , or looks like sham.

**Comment by marwahaha** [comment]
I'm not sure if a symlink will work, but perhaps README.md in that package can point to the top-level file. You could try publishing and see what happens.

These 5 packages don't have a readme:
https://github.com/pedronauck/docz/tree/master/packages/docz
https://github.com/pedronauck/docz/tree/master/packages/docz-core
https://github.com/pedronauck/docz/tree/master/packages/load-cfg
https://github.com/pedronauck/docz/tree/master/packages/rehype-docz
https://github.com/pedronauck/docz/tree/master/packages/remark-docz

**Comment by rakannimer** [comment]
Thanks for pointing this out 👍 I added READMEs that point to the main package with a small explanation of what the package does.
