### ISSUE TITLE
Code inside Playground doesn't accept anonymous async arrow functions.

### ISSUE THREAD

**Issue by rakannimer** [doczjs/docz#229]
## Bug Report

**Describe the bug**

If code inside the Playground Component contains an async arrow function, a syntax error overlay is shown on top the rendered component, but the component renders normally.

## Renders error overlay 

when 
```javascript
didMount={async val => {console.log('Oh hai Mark'); }}
```
<img width="767" alt="screen shot 2018-08-15 at 10 51 52 am" src="https://user-images.githubusercontent.com/1270909/44137608-b079d100-a079-11e8-9d60-e77349a4d3c4.png">

## Works as expected 
when  

```javascript
didMount={async function(component) => {console.log('Hai'); })
```
<img width="795" alt="screen shot 2018-08-15 at 10 52 18 am" src="https://user-images.githubusercontent.com/1270909/44137712-070bd2d4-a07a-11e8-94e6-408d30ace688.png">

**To Reproduce**

1. Go to any mdx file
2. Inside <Playground> place an async function
3. See error overlay

Example Code : 

```jsx
<Playground>
	<Component 
    	initialState={{dataLoadingStatus: "loading", chartData:[]}}
	    didMount={async (component) => {}}
	>
		Oh hai !
	</Component>
</Playground>
```

[Link to repro](https://github.com/rakannimer/react-google-charts/blob/6ae25f5f2698100696e6e9a43404a2c4d2df7483/src/docs/FromAPI.mdx)

**Environment**

* OS: OSX 10.13.4
* Node/npm version: Node 9.11

**Additional context/Screenshots**

It's not a big problem since it can be easily solved by replacing the arrow function with a function as shown in the screenshot, but might be good to know !

Cheers !

**Comment by pedronauck** [comment]
For sure 😕 Since `async` is something supported just in modern browsers and need to be compiled to run, I think that this can be a real problem. By now, I don't have anything on my mind to fix this, I need to figure out or maybe use some runtime and faster compiler (e.g, [buble](https://github.com/Rich-Harris/buble)) before passing the code to `react-live`.

**Comment by pedronauck** [comment]
But even with the right syntax this bug came up: `SyntaxError: Unexpected identifier`

**Comment by SFantasy** [comment]
Does this issue have any progress?

**Comment by ronghang** [comment]
The same problem occurs when I use the arrow function in .mdx files.

**Comment by rakannimer** [comment]
Fixed in v2
