### ISSUE TITLE
Syntax Error on empty anchor tag

### ISSUE THREAD

**Issue by wldcordeiro** [doczjs/docz#336]
## Bug Report

I had originally report this to the [`mdx`](https://github.com/mdx-js/mdx) project but they weren't able to recreate this issue so I'm opening the issue against docz now to see if it may be the usage of mdx here.

```
Syntax Error: SyntaxError: /Users/wellingtoncordeiro/Documents/projects/my-proj/CHANGELOG.md: Expected corresponding JSX closing tag for <MDXTag> (24:0)

  22 | Features
  23 |
> 24 | </a>
     | ^
  25 | Change Log
  26 |  (2018-09-04)
  27 |


 @ ./docs/changelog.mdx 9:0-40 22:25-34
```

Example MD that broke when parsed.

```md
# Change Log

All notable changes to this project will be documented in this file.
See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.

<a name="11.0.1"></a>
## [11.0.1](https://gitlab.com/group/proj/compare/v11.0.0...v11.0.1) (2018-09-10)


### Bug Fixes

```

**Comment by nicholasess** [comment]
@wldcordeiro Do you try ```<a name="11.0.1" />```?

**Comment by wldcordeiro** [comment]
It's a generated changelog that updates each time lerna publishes while that fixes it (and I tried it way before ever thinking of posting...) that isn't a viable option because I'd have a broken deploy till I went and fixed the links all over again.

**Comment by silvenon** [comment]
I managed to simplify breaking code to this:

```md
[foo](bar)

<a></a>

<a></a>

[foo](bar)

<a></a>
```

If any of these elements gets removed, the compilation is successful. 🤔

**Comment by nicholasess** [comment]
@wldcordeiro the example of @silvenon work for you?

**Comment by silvenon** [comment]
The above is just a reduction. @wldcordeiro provided a [demo repository](https://github.com/wldcordeiro/docz-bug) with the full changelog, so I just removed piece by piece until it the syntax error disappeared. The above is the minimal code which crashes docz.

I already tried upstream and this code works, so I think something in docz is causing this. 😕

**Comment by nicholasess** [comment]
@silvenon we are accepting a PR with the changes.

**Comment by sidewalksalsa** [comment]
I am also running into this bug. Strange issue.

The work around is to put `<a>` and `</a>` on separate lines such as:

```html
<a name="something">
</a>

#### Heading
```

That works.

However, that will **not** work if it is up against a heading like so:

```html
<a name="something">
</a>
#### Heading
```

The above breaks again.

**Comment by sidewalksalsa** [comment]
**UPDATE**

```html
<a name="something" />

#### Heading
```

The above **works**.

But the below does not:

```html
<a name="something"></a>
#### Heading
```

**Comment by wldcordeiro** [comment]
Still seeing this problem. Where in Docz is this parsing done? Something unique about the configuration is causing this breakage and I'd really like to be able to get my changelogs in to my doc site. 😄

**Comment by sidewalksalsa** [comment]
@wldcordeiro - Are you setting a `files` (https://www.docz.site/documentation/project-configuration) flag?

I had originally set my a `files: './docs/` where all my `.mdx` files were living.  I was then trying to import my "changes.md" file into a .mdx file in docs folder.

The problem was, the "changes.md" file was not being "looked at".  As soon as I removed the `file` config option and just let Docz do its thing, I was able to pull in my changelog no problem.

**Comment by sidewalksalsa** [comment]
Sorry I meant `src` option not `files` - updated my comment above.

**Comment by wldcordeiro** [comment]
@sidewalksalsa 

No that setting hasn't been altered for me.

```js
const { resolve } = require('path');
const webpack = require('webpack');
const merge = require('webpack-merge');
const DOCS_ROOT = resolve(__dirname, 'docs');

const modifyBundlerConfig = config => {
  return merge(config, {
    resolve: {
      alias: {
        '@components': `${DOCS_ROOT}/components`,
        '@images': `${DOCS_ROOT}/images`,
      },
    },
    plugins: [new webpack.EnvironmentPlugin({ DOCZ_ENV: true })],
  });
};

module.exports = {
  base: '/citadel',
  description: 'The home for CNC projects.',
  hashRouter: true,
  modifyBundlerConfig,
  title: 'CNC Citadel',
  themeConfig: {
    colors: { primary: '#fd0e35' },
  },
};
```

**Comment by wldcordeiro** [comment]
I'm starting to think this is coming from this file https://github.com/pedronauck/docz/blob/3296de66bc882c16d4fcb01aa3e76425d2f2745a/packages/remark-docz/src/index.ts#L35

**Comment by tibotiber** [comment]
Note that #282, which is not related per se, might affect your debugging experience of this issue.
