### ISSUE TITLE
Feature Request : Require external md(x) & Override

### ISSUE THREAD

**Issue by iam-merlin** [doczjs/docz#348]
Hi, it's me again :P

To be truly awesome, the last feature for us will be the ability to required markdown/docz project from external package and override header metadata.

For example (quick code... just a sample that can be false xD)) :

```js
module.exports = {
  external: {
    '~/awesome-doc': {
      // load from node_modules/awesome-doc
      '/architecturePattern/event-sourcing.mdx': {
        route: '/architecture/event-sourcing',
        menu: 'Principle',
      },
    },
    '~/my-backend': {
      // load from node_modules/my-backend
      menu: '/project/backend', // inject full docz from my-backend
    },
  },
};
```

I think the principle above could be implemented differently using a docz.js config file (markdown import for example).

For my company, the idea behind is to capitalize documentation from multiple sources (ui guidelines, internal and external components, architecture pattern, api doc, etc.).

What do you think about that?

(fyi, I'll be on an internal subject "living documentation" today and docz will be a part in my approach, thanks a lot for your great work.)

**Comment by wonskarol** [comment]
👍 for that feature. 
In my company we need exactly the same, because we have several ui modules and each is a separate node package
