### ISSUE TITLE
Support absolute paths

### ISSUE THREAD

**Issue by kentcdodds** [doczjs/docz#353]
I'm making a toolkit where the configuration for docz will be generated by my toolkit. I need to be able to specify an absolute filepath for options like `source` and `dest`. Right now if I do that, the absolute path is appended to the CWD.

**Comment by pedronauck** [comment]
I need to think a little bit what's the best way to make this change since the client and a lot of entries path depends on this, but I think that can be possible.

**Comment by damassi** [comment]
Wondering if this might be related? 

I've update all of my code to support abs paths -- and everything works, including docz -- but for some reason this is output when docs is building: 

![screen shot 2018-10-02 at 6 07 12 pm](https://user-images.githubusercontent.com/236943/46384961-238dd500-c66e-11e8-8b54-9d91ea8c7a92.png)

Any help figuring out where this is coming from would be appreciated!

**Comment by aryzing** [comment]
Not sure if related (I'll open new issue if not), but I've updated the webpack config using docz's `modifyBundlerConfig` like so:

```
const myConfig = {
    output: {
        path: path.resolve(__dirname, 'dist/static-site')
    },
}

export default {
    modifyBundlerConfig: config => {
        return merge(config, myConfig);
    }
};
```

The site is built succesfully, but errors are reported:

```
aryzing ~/workspace/project$ yarn run docz:build
yarn run v1.13.0
$ docz build
{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
✓ Parsing mdx files 101 ms
✓ Initializing data server 132 ms
✓ Running onPreBuild() 0 ms
✓ Creating production build 14.4 secs

File sizes after gzip:


✖  fatal     Failed to compile.

ENOENT: no such file or directory, open '/Users/aryzing/workspace/project/.docz/dist/static/js/6.99c9d021.js'


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/Cellar/node/11.6.0/bin/node
Arguments: /usr/local/Cellar/yarn/1.13.0/libexec/lib/cli.js run docz:build
Directory: /Users/aryzing/workspace/oos-frontend-platforms/packages/oos-ui
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
```

**Comment by ericclemmons** [comment]
Is this related to https://github.com/pedronauck/docz/issues/608?

I'm wondering if a fix would address both issues (but haven't heard back).
