### ISSUE TITLE
PropTable key orders is defined by defaultProps instead of propTypes when using vanilla js or flow

### ISSUE THREAD

**Issue by fkhadra** [doczjs/docz#379]
# Question

Hey,

I have a component as follow:

```js
class Foo extends Component{
  static propTypes = {
    id: PropTypes.oneOfType([PropTypes.string, PropTypes.number]).isRequired,
    foo: PropTypes.string,
    bar: PropTypes.object,
  }
  static defaultProps = {
    foo: 'abc',
    bar: 'xyz'
  }
}
```

When I use the `PropTable` component I expect the order of keys to be the same as `Foo.propTypes` but it seems that the order used is the one defined by  `Foo.defaultProps`

<img width="885" alt="screenshot 2018-09-30 at 21 00 05" src="https://user-images.githubusercontent.com/5574267/46261451-fd442a00-c4f3-11e8-8e77-852dfe59575a.png">

It's a choice by design ?

> Edit, I though that it was caused by react-docgen but I checked. React-docgen does respect the order:
```json
"props": {
    "id": {
      "type": {
        "name": "union",
        "value": [
          {
            "name": "string"
          },
          {
            "name": "number"
          }
        ]
      },
      "required": true,
      "description": ""
    },
    "foo": {
      "type": {
        "name": "string"
      },
      "required": false,
      "description": "",
      "defaultValue": {
        "value": "'abc'",
        "computed": false
      }
    },
    "bar": {
      "type": {
        "name": "object"
      },
      "required": false,
      "description": "",
      "defaultValue": {
        "value": "'xyz'",
        "computed": false
      }
    }
  }
```

Edit 2 > The issue can be reproduced using the basic example just by adding 
```js
Button.propTypes = {
  id: t.number,
 ...other props defined
}
```

Thank you, I'll try to dig more in the meantime.

PS: docz is really amazing 👌

**Comment by IhToN** [comment]
Any news on the resolution of this issue?
It does not makes sense to have the "required" PropTypes at the bottom of the PropTable because they doesn't appear on the "defaultProps".
