### ISSUE TITLE
PropsTable is not working with components created using createElement()

### ISSUE THREAD

**Issue by thalseth** [doczjs/docz#400]
## Bug Report

PropTypes defined on Components using createElement() are not presented in PropsTable.

I used some time trying to create example using project examples but then i received a new error related to this: https://github.com/pedronauck/docz/issues/339 

Component: 
```jsx
const Button = ({
  as, children, ...other
}) => createElement(
  as || 'button',
  {
    type: 'button',
    ...other,
  },
  <div>{children}</div>,
);
```

**Comment by ozzyogkush** [comment]
FWIW I'm unable to get the PropsTable to work with simple functional and class components as well.

**Comment by kamalgill** [comment]
Same problem here... PropsTable is empty for class-based components despite adding static propTypes

**Comment by escapiststupor** [comment]
Same here for the latest version...

**Comment by jamesg1** [comment]
Yeah it appears blank on functional component propTypes

**Comment by JackCuthbert** [comment]
@kamalgill & @jamesg1, using TS I managed to work around this by using `import * as React from 'react'` instead of `import React from 'react'` in my components. The latter doesn't seem to be able to produce a PropsTable.
