### ISSUE TITLE
Styleguide web app crashes

### ISSUE THREAD

**Issue by selrond** [doczjs/docz#521]
## Bug Report

**Describe the bug**

I've updated to the `v0.13.2`, but after I run `docz dev` and open it in browser, it won't load up anything, but shows this error in the console:

![image](https://user-images.githubusercontent.com/6603389/50107694-a49f4600-0233-11e9-8576-90cc9ea0d33d.png)

**Comment by pedronauck** [comment]
First of all, try to reset node_modules and yarn.lock, sometimes this help.
So, can you give us more information about that? Your package.json, node version, etc. Some repo with the minimal setup is good too :)

**Comment by Poltergeist** [comment]
I ran into the same problem I solved it by upgrading my dependecy of emotion from 9 to 10. Maybe we should consider adding emotion as a peer dependecy to the default theme.
