### ISSUE TITLE
Incompatible with react@16.7.0-alpha.2

### ISSUE THREAD

**Issue by jedrichards** [doczjs/docz#527]
## Bug Report

Cryptic error when docz is run in a `react@16.7.0-alpha.2` repo.

I know there's no reason why Docz _should_ work with an alpha version of React, this is just heads up. If you want to play around with React hooks you need the above version of React, and it'd be nice if this worked with Docz.

**To Reproduce**

```shell
mkdir test
cd test
yarn init --yes
yarn add docz docz-theme-default
yarn add react@16.7.0-alpha.2 react-dom@16.7.0-alpha.2
node_modules/.bin/docz dev
```

**Expected behavior**

The Docz dev site should work.

Instead there's an error:

<img width="1037" alt="screenshot 2018-12-19 at 15 16 34" src="https://user-images.githubusercontent.com/1078571/50228952-1779ff80-03a1-11e9-9008-bf5836f054c4.png">

**Comment by pedronauck** [comment]
I release a patch fixing this issue, but the theme it's not being applied, can be a conflict between @emotion/theme and the alpha release of react. I need to investigate more.

**Comment by alidcastano** [comment]
just ran into this issue. works if you don't use the default theme (which uses emotion)

**Comment by clucasalcantara** [comment]
Hey @alidcastano. How do you solve this changing theme? You've created a new one from scratch?

**Comment by aryzing** [comment]
Not sure if related, but when using hooks, docz throws an error:

> Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)

Specifically, I'm using hooks in the MDX file. Using hooks only in a component works fine. 

The code that's throwing an error: 

```js
import { Playground } from 'docz';
import { Search } from '.';
import { useState } from 'react';

<Playground>
    <div>
        {(() => {
            const [inputValue, setInputValue] = useState('');
            return (
                <Search
                    placeholder="Placeholder"
                    value={inputValue}
                    onChange={e => setInputValue(e.target.value)}
                />
            );
        })()}
    </div>
</Playground>
```

I've tried the [duplicate react test](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) suggested by the docs, and it turns out there are two instances of react being loaded :(

The suggestion to use yarn's resolutions field did not work.
