### ISSUE TITLE
Use with React.memo

### ISSUE THREAD

**Issue by JClackett** [doczjs/docz#541]
## Question

Is there anyway to use PropsTable when exporting a component wrapped in a React.memo?

**Comment by arvigeus** [comment]
Same question. Tried `Component.type`, still didn't work

**Comment by Glinkis** [comment]
I also have this problem. I know one solution is to export the memoized and original components, and then use the original in props table. Its a pretty bad workaround though.

**Comment by dartess** [comment]
Same problem
