### ISSUE TITLE
page with route and menu?

### ISSUE THREAD

**Issue by giladgray** [doczjs/docz#544]
I'm attempting to recreate the nav sidebar from https://blueprintjs.com/docs/#core in Docz and struggling with nested pages.

### Given the following (partial) file structure:

```md
// core.mdx
---
name: Core
route: /core
---

# Core

This page is supposed to contain all the components, but it also has its own content 
about package usage.
```

```md
// alert.mdx
---
name: Alert
route: /core/components/alert
menu: Core
---

# Alert

This should be a child of the Core page that explains one component, but it never 
appears in the nav.
```

### Expected behavior

pages are nested in nav like so: Core > Alert

### Actual behavior

The `Alert` page never appears in the nav. The `Core` menu entry does not have a `menu` field. 

It seems like a menu entry can have **either `menu` or `route`** but not both. Why? Seems pretty essential and easy to support both -- an entry that is both a link and a menu container.

**Comment by pedronauck** [comment]
Really, with the actual logic, this isn't possible :confused: If you have some page that has the same name of any menu, will just appear one or another in the menu. That's something that need to be improved 👍

**Comment by giladgray** [comment]
can you point me to where the menu ordering is actually constructed? i'm having trouble locating it myself in the source.
