### ISSUE TITLE
nested `menu` metadata regression

### ISSUE THREAD

**Issue by giladgray** [doczjs/docz#546]
## Bug Report

**Describe the bug**

#10 has regressed, likely due to new `menu` doczrc feature.

*A clear and concise description of what the bug is.*

**To Reproduce**
```js
// doczrc.js
    menu: [
        "Home",
        "Guides",
        {
            name: "Components",
            menu: [
                "Core",
                "Datetime",
                "Icons",
                "Select",
                "Table",
                "Timezone",
                "Labs",
            ],
        },
        "Resources",
    ]
```

```md
// alert.mdx
---
menu: Components/Core
name: Alert
---

# Alert
```

**Expected behavior**

Components > Core > Alert

**Actual Behavior**

Components/Core > Alert

**Additional context/Screenshots**

<img width="232" alt="blueprint" src="https://user-images.githubusercontent.com/464822/50367242-b6366580-0533-11e9-9d11-ca54505307cb.png">

**Comment by EmaSuriano** [comment]
Is anyone working on this one? I can take it, because I need the same feature for one of my projects.

**Comment by pedronauck** [comment]
There's no way yet for a third level menu, we're launching v1, after the release that's one of our goal. Pr are welcome @EmaSuriano ;)

**Comment by darrenhaken** [comment]
Any update on this?

**Comment by EmaSuriano** [comment]
I ended up with a simpler solution using only a 2 level menu. So I didn't implement this feature.

**Comment by tijmenvangurp** [comment]
I want to use Docz, but for me its a requirement to have at least 3 levels of navigation in the sidebar. Is there any way of doing this in the latest version? I see this bug is closed, it seems it was possible but the bug has never been resolved?
