### ISSUE TITLE
Crashes when using Playground Component - docz v0.13.7

### ISSUE THREAD

**Issue by rodrigowpl** [doczjs/docz#559]
## Bug Report

Crashes when using the Playground component

**To Reproduce**

Just wrapping my components in

```shell
🚨 Whoops, we crashed 🚨
Passed an incorrect argument to a color function, please pass a string representation of a color.
Stack trace
in Styled(div) (created by right)
in right (created by Resizable)
in div (created by Resizer)
in Resizer (created by Resizable)
in span (created by Resizable)
in div (created by Resizable)
in Resizable (created by RenderBase)
in div (created by Context.Consumer)
in Styled(div) (created by RenderBase)
in div (created by LiveProvider)
in LiveProvider (created by RenderBase)
in RenderBase (created by Context.Consumer)
in ThemeConfig (created by Render)
in Render (created by BasePlayground)
in BasePlayground (created by Context.Consumer)
in Component (at text.mdx:19)
in div (created by MDXTag)
in MDXTag (created by Context.Consumer)
in Component (at text.mdx:14)
in MDXContent (created by AsyncComponent)
```

My mdx code:

```
---
name: Button
---

import { Playground } from 'docz'
import { Button } from './button'

# Button

## Basic usage

<Playground>
  <Button
    label='Click me'
  />
</Playground>
```

More Information:
I already see this issue: https://github.com/pedronauck/docz/issues/540
And I already install the docz-theme-default and still crash

EDIT: I did this example app to simulate the problem, take a look:
https://github.com/rodrigowpl/rn-docz-play

**Expected behavior**

Render without crashing

**Environment**

* OS: OSX 10.14.2
* Node/npm version: [e.g. Node 8/npm 6]
* react-native 0.57.8
* react 16.6.3
* styled-components 4.1.3
* docz 0.13.7

**Comment by dmitrij-borchuk** [comment]
Same on my Windows, apart of it there missed some theme styles, so menu looks broken

**Comment by GiancarlosIO** [comment]
Same here! :cry:

**Comment by eugeneoshepkov** [comment]
Any updates? Have the same problem with 0.13.7

**Comment by rodrigowpl** [comment]
I've updated my comment and add an example app that I did just to simulate the problem

**Comment by lintu** [comment]
thrown from 
node_modules/polished/lib/color/parseToRgb.js
