### ISSUE TITLE
Configurable route paths

### ISSUE THREAD

**Issue by kripod** [doczjs/docz#561]
According to the docs, ["By default, if you don't pass any route, we'll use some kinda slug that is a filepath of your file with a route format."](https://www.docz.site/introduction/customizing#document-settings)

I think there should be an overridable function inside `doczrc.js` which would allow transforming file paths based on custom rules:

```js
// doczrc.js
export default {
  transformRoute: (extensionlessRelativeFilePath) =>
    `/${extensionlessRelativeFilePath.toLowerCase().replace(/\//g, '-')}`,
};
```

For instance, the `transformRoute` function could receive `src/components/Box` as an example and transform it to `/components/box`:

```js
// doczrc.js
export default {
  transformRoute: (extensionlessRelativeFilePath) =>
    extensionlessRelativeFilePath.includes('/components/') &&
      `/components/${extensionlessRelativeFilePath.split('/').slice(-1)[0].toLowerCase()}`,
};
```

Returning a falsey value would cause the default slug transform to be applied.

**Comment by crusoexia** [comment]
want this

**Comment by rakannimer** [comment]
Yep this is a great idea, happy to help/review/merge if someone would like to submit a PR for it.

**Comment by DominicTobias** [comment]
Or use the default Gatsby routing which does segmented paths which are imo nicer than hyphenated everything
