### ISSUE TITLE
edit page button can only be clicked on the left half

### ISSUE THREAD

**Issue by capaj** [doczjs/docz#562]
## Bug Report

**Describe the bug**

the github corner badge is obstructing the button.

**To Reproduce**
Run and inspect.

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

the "edit page" button is not obstructed

**Environment**

doesn't matter

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/1305378/50608809-01eef480-0ece-11e9-91e3-a2561e588193.png)

it needs z-index tweak

**Comment by jancassio** [comment]
Which url is that @capaj ?

**Comment by redbugz** [comment]
This is happening on our site as well, but we don't have a public URL.
But this one has the same problem:
https://dfee.github.io/rbx/
