### ISSUE TITLE
Support Relative Path

### ISSUE THREAD

**Issue by huchenme** [doczjs/docz#563]
Currently `docz` expect `base` in config and it only works in absolute paths, it will be nice that Docz support relative mode as well so that it should directly be opened without serving

**Comment by huchenme** [comment]
@jancassio yes, we would like to publish the generated docs in Jenkins HTML publisher plugin(https://wiki.jenkins.io/display/JENKINS/HTML+Publisher+Plugin) so that code reviewer could visualize changes before approval.

We are currently using styleguidist and the generated html is able to open directly that way and it works with Jenkins, hope Docz is able to support that so that we could switch to it faster

**Comment by jancassio** [comment]
Jenkins has some several restrictions about run static contents.

https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

Seems you need to relax those restrictions to run static content properly.

**Comment by huchenme** [comment]
The problem is not those restrictions but be able to open the generated index.html file directly instead of serve by a server

**Comment by jancassio** [comment]
> The problem is not those restrictions but be able to open the generated index.html file directly instead of serve by a server

Could you explain how are you doing that and which errors are had you taken with?

**Comment by huchenme** [comment]
try `npx docz build && open .docz/dist/index.html` and you will see nothing appear on the screen.

Expected behavior: browser should render documentation just as `npx docz dev`

**Comment by huchenme** [comment]
![screenshot 2019-01-09 at 3 19 52 pm](https://user-images.githubusercontent.com/2078389/50883123-15481580-1422-11e9-8b18-de3460746abc.jpg)

**Comment by schester44** [comment]
+1 relative paths would be nice

**Comment by iaincollins** [comment]
Relative path seems like a sensible default to me, given it will also still work on any server but doesn't actually need a server just to open the HTML page in a browser.

**Comment by jaikiratsingh** [comment]
Any progress on this ?

**Comment by RobinClowers** [comment]
This is supported, check out the `base` param in the docs: https://www.docz.site/docs/project-configuration.

**Comment by iaincollins** [comment]
@RobinClowers

The `base` parameter does not support relative paths, it only supports absolute paths.

From the docs: `it should always start and end with a slash.`

One example use case is people being able to just open an HTML file and read some documentation that is in those HTML files, without having to install Node.js or start a server on the computer they are viewing it on.

Another is being able to serve them from a static location (e.g. network file share, or static site) where the full URL may not be known or may be variable (especially over time).

**Comment by RobinClowers** [comment]
Oh, I see, I wasn't thinking about relative vs absolute, that's a fair point.

**Comment by huchenme** [comment]
@rakannimer what is the reason this issue get closed?

**Comment by rakannimer** [comment]
This enhancement sounds good, it's maybe better to continue the discussion in a PR ?
