### ISSUE TITLE
docz dev command crashes when .babelrc is a JS Object

### ISSUE THREAD

**Issue by everdimension** [doczjs/docz#565]
## Bug Report

**Describe the bug**

When `.babelrc` looks like this:

```
{
  presets: ["@babel/preset-react"]
}
```

Running `docz dev` produces an error:

>*> docz dev
There was an error loading your config:
SyntaxError: /app/.babelrc: Unexpected token p in JSON at position 4
    at JSON.parse (<anonymous>)*

If you change `.babelrc` to be in JSON format like this:

```
{
  "presets": ["@babel/preset-react"]
}
```
(notice the quotes around the key `"presets"`)
Then the command works.

**Expected behavior**

I'm not sure whether this is a bug of docz, but I guess it is because when I'm running babel separately it works fine when the config is a js object and not JSON. So I expect docz to work the same.

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: MacOS 10.14.2
* Node version: v10.9.0
* npm version: v6.5.0
* docz version: 0.13.7

**Comment by rkhayat** [comment]
I upgraded babel, used `babel.config.js` and experienced the same issue.
