### ISSUE TITLE
Remember menu state

### ISSUE THREAD

**Issue by marcuslindfeldt** [doczjs/docz#569]
The sidebar menu collapses each time I press a menu item in the default theme and it's pretty annoying to be honest :) Maybe an option to make the menu remember it's state or change the default behaviour.

**Comment by angular-moon** [comment]
i tested the examples:
basic is ok:
not collapse, has sub menu item
![image](https://user-images.githubusercontent.com/7876335/50979358-4105f100-1531-11e9-8bd6-2c6e21a1b125.png)

typescript has this problem:
collapses each time press a menu, not have sub menu item
![image](https://user-images.githubusercontent.com/7876335/50981599-4b76b980-1536-11e9-967e-75000111acf8.png)

typescript example can't render propsTable
```
export const Alert: SFC<AlertProps> = ({ kind, ...props }) => (
  <AlertStyled {...props} kind={kind} />
);

// must be written as
export const Alert = ({ kind, ...props }: AlertProps) => (
  <AlertStyled {...props} kind={kind} />
);
```

**Comment by marcuslindfeldt** [comment]
We don't use typescript but we do use styled-components. We don't see any sub menu items either.

**Comment by sunkeysun** [comment]
> i tested the examples:
> basic is ok:
> not collapse, has sub menu item
> ![image](https://user-images.githubusercontent.com/7876335/50979358-4105f100-1531-11e9-8bd6-2c6e21a1b125.png)
> 
> typescript has this problem:
> collapses each time press a menu, not have sub menu item
> ![image](https://user-images.githubusercontent.com/7876335/50981599-4b76b980-1536-11e9-967e-75000111acf8.png)
> 
> typescript example can't render propsTable
> 
> ```
> export const Alert: SFC<AlertProps> = ({ kind, ...props }) => (
>   <AlertStyled {...props} kind={kind} />
> );
> 
> // must be written as
> export const Alert = ({ kind, ...props }: AlertProps) => (
>   <AlertStyled {...props} kind={kind} />
> );
> ```

hello , I see your submenu demo is perfect, may you share the code for this?  because my submenu auto collapses every time, when i change menu active. Thanks

**Comment by sunkeysun** [comment]
If is possible to unfold submenu default instand of collapses? submenu always collapses when i change active menu. Thanks

**Comment by smeijer** [comment]
This one is quite frustrating. Any ETA?
