### ISSUE TITLE
PropsTable not working with shared PropTypes

### ISSUE THREAD

**Issue by ylin6** [doczjs/docz#570]
## Bug Report

**Describe the bug**

Shared PropTypes are not rendered into the PropsTable

**To Reproduce**
In a shared utils file, I have props types like this: 
```
const PROP_TYPES = {
    prop1: PropType.bool
}

```

In a separate component, I import the PropTypes
```
 import { PROP_TYPES } from '../utils.js'  
 Component.propTypes = {
        someProp2: PropType.func,
       ...PROP_TYPES
  }
```
 and the PropTable only renders with someProp2 and prop1 is missing
**Expected behavior**

The PropTable should render someProp2 and prop1

**Environment**
Node: v8.11.1

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by ylin6** [comment]
Found a solution where in the shared proptypes file, I created a dummy components that used those proptypes and then used that dummy component in the propsTable

**Comment by victorsilent** [comment]
@ylin6 can you show the code? I'm with the same issue

**Comment by ylin6** [comment]
Here an example:


sharedPropTypes.js
```
const SharedPropTypes = {
   name: PropTypes.string.isRequired
};

const dummyPropTypesComponent = () => <div></div>
dummyPropTypesComponent.propTypes = SharedPropTypes;

export { SharedPropTypes, dummyPropTypesComponent };
```


Componend.mdx

```
<PropsTable of={dummyPropTypesComponent}/>
```

Pretty hacky, but as long as the shared proptypes are update, it doesnt really matter if the PropsTable is looking a different component

**Comment by MihaiWill** [comment]
so that was the problem!!!!
also your workaround is okeish. I hope we can share proptypes in near future
