### ISSUE TITLE
Shadow DOM to isolate Playground

### ISSUE THREAD

**Issue by marcuslindfeldt** [doczjs/docz#574]
There is a bullet in the roadmap to use iframes for the playground component.
An alternative could be to use shadow dom instead.

This project https://github.com/Wildhoney/ReactShadow allows you to render react components in shadow dom.

As described in this article https://css-tricks.com/playing-shadow-dom/#article-header-id-1 you also need to reset all elements to their initial value because "Inherited styles still inherit through the shadow DOM"

So if you update/wrap the playground component to something like below it should work nicely.

```
    <ShadowDom>
      <div style={{ all: 'initial' }}>
         {children}
      </div>
    </ShadowDom>
```

Using Shadow DOM could be a quick and easy way to improve isolation in the playground.

**Comment by karlhedins** [comment]
+1 :)

**Comment by Dobby89** [comment]
@marcuslindfeldt Would shadow DOM still allow examples to be opened in a new window/tab?

The main advantage of hosting them in separate iframes for me would be to be able to preview components which can only be appreciated in a completely separate full window. For example a header or footer component which needs the full screen real estate.

**Comment by marcuslindfeldt** [comment]
@Dobby89 I'm not sure to be honest but I don't see why it shouldn't be possible in combination with e.g. `window.open` 

My main issue with the current solution is that the styles are not isolated. If you can get the iframe solution to work nicely I'm all for it.

**Comment by zicodeng** [comment]
Hi, is anyone working a solution for this. I didn't see the latest docz playground support iframe. I ended up creating a iframe wrapper for my components: https://github.com/zicodeng/docz-iframe-playground
