### ISSUE TITLE
The build results run with many warnings and errors

### ISSUE THREAD

**Issue by angular-moon** [doczjs/docz#575]
## Bug Report

**Describe the bug**
The build results run with many warnings and errors

*A clear and concise description of what the bug is.*
![image](https://user-images.githubusercontent.com/7876335/50983109-a9f16700-1539-11e9-80c4-07de17047d40.png)

**To Reproduce**

1. clone examples/typescript
2. yarn & yarn build
3. serve .docz/dist

**Expected behavior**

1. The result does not include `react-error-overlay` and  `react-hot-loader`
2. do not create websocket 

**Environment**

* OS:  OSX 10.13.6
* Node/npm version: Node v8.10.0/npm 5.6.0
* yarn 1.10.1

**Comment by gismanli** [comment]
+1， why production mode use socket ?
