### ISSUE TITLE
Module not found: Can't resolve 'emotion' after upgrading to emotion 10.0

### ISSUE THREAD

**Issue by bradringel** [doczjs/docz#577]
## Bug Report

**Describe the bug**
After upgrading my project and components to use the newest version of emotion, i get the following error when i try to run docz

`./src/App/UI/components/PanelTabs/PanelTabs.js
Module not found: Can't resolve 'emotion' in '/Users/bringel/source/snowdrop-web/src/App/UI/components/PanelTabs'`

That file doesn't try to import anything from `emotion`. Its emotion imports look like this:

```
import { css, jsx } from '@emotion/core';
import styled from '@emotion/styled';
```

**To Reproduce**

Upgrade to emotion 10
Run docz:dev

*In order to allow us to quickly reproduce you issue please include a link to a reproduction repository.*

**Expected behavior**

*A clear and concise description of what you expected to happen..*

**Environment**

* OS: OS X 10.14
* Node/npm version: Node 11.1 npm 6.4.1 yarn 1.10.1
* docz 0.13.7
* @emotion/core 10.0.5

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

**Comment by bradringel** [comment]
I did a quick test this morning, this appears to be related to using the `/** @jsx jsx */ statement to set the pragma at the top of the file. If I remove that statement, the file no longer errors, is there another way I should be setting the jsx pragma?

**Comment by bradringel** [comment]
I did eventually getting this to work by adding `emotion` to my dev dependencies. Not sure what exactly is requiring it, my app built fine without that dependency before

**Comment by enieber** [comment]
I have a similar problem with import local module and have a similar error [trying to use the component-docs](https://github.com/callstack/component-docs/issues/19).

**Comment by pleunv** [comment]
Same problem here, but unrelated to docz. We are however using `@emotion/babel-preset-css-prop` to avoid having to manually override the pragma. Not a single `emotion` reference in the project code, but running into the same `Module not found: Can't resolve 'emotion'` when running a production build, and *only* on the CI env.

**Comment by rangermeier** [comment]
I had the same error after upgrading from emotion 9 to emotion 10 (not using docz though). Turned out I forgot to also update `babel-plugin-emotion`. Upgrading this fixed the issue for me.
Hope this helps others who stumble on this issue.

**Comment by ajayshewale** [comment]
I had a similar issue, I install react-spinner and problem solved...!
`npm install react-spinners --save`

**Comment by nassif7** [comment]
probably you need to install `@emotion/styled` i got the same issue and it was solved doing that

**Comment by Damian-101** [comment]
install this "npm i @emotion/styled @emotion/core"
