### ISSUE TITLE
Playground editing does not show cursor when focused

### ISSUE THREAD

**Issue by huchenme** [doczjs/docz#581]
## Bug Report

**Describe the bug**

*A clear and concise description of what the bug is.*

**To Reproduce**

1. Go to Playground
2. Clicked expand code
3. Click coding area

**Expected behavior**

Show show a blinking cursor.

**Actual behavior**

No blinking cursor is shown, user does not know it is editable.

**Comment by huchenme** [comment]
@rakannimer what is the reason this issue get closed?

**Comment by jesperorb** [comment]
@huchenme What version of docz are you using? I am using the lastes `@next` and I am getting a blinking cursor when editing.
