### ISSUE TITLE
Parse markdown in PropTypes descriptions

### ISSUE THREAD

**Issue by cesarcosta99** [doczjs/docz#584]
I was wondering about parse markdown in the PropTypes descriptions to improve the way we describe the PropTypes, for instance:

```javascript
Button.propTypes = {
  /** HTML type of button. See [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Attributes) */
  htmlType: PropTypes.oneOf(['button', 'reset', 'submit'])
}
```

What do you think? I'm willing to help on this.

BTW, great job on this project! 👏

**Comment by huchenme** [comment]
This will be great

**Comment by huchenme** [comment]
@rakannimer what is the reason this issue get closed?
