### ISSUE TITLE
Link to markdown files

### ISSUE THREAD

**Issue by huchenme** [doczjs/docz#588]
It will be nice to be able to link to some markdown files and display it as content/modal of a page.

Use case, there are automatically generated CHANGELOG.md for each package and there is a `mdx` file for each package, we want to show the content of CHANGELOG as part of the documentation

**Comment by huchenme** [comment]
It will be nice to achieve something like this: https://atlaskit.atlassian.com/packages/core/checkbox

-----> Click "Changelog" button

**Comment by pedronauck** [comment]
Closed in order to #584

**Comment by huchenme** [comment]
@pedronauck I think they are different issue, #584 is related markdown format in propTables and this issue is about display content of markdown file in MDX file (or link to markdown content)

**Comment by pedronauck** [comment]
Sorry @huchenme, I close the wrong issue, my bad 🙏

**Comment by huchenme** [comment]
@rakannimer what is the reason this issue get closed?

**Comment by rakannimer** [comment]
I'm not sure I understand the exact issue, maybe we can move this discussion to a PR ?
