### ISSUE TITLE
Active link and submenus in sidebar no longer working

### ISSUE THREAD

**Issue by nmessager** [doczjs/docz#590]
## Bug Report

I have the same problem as #526 but in my case i also have these dependencies installed
```
"dependencies": {
    "docz": "^0.13.7",
    "docz-theme-default": "^0.13.7",
    "webpack": "^4.28.4",
    "webpack-bundle-analyzer": "^3.0.3",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14"
  }
```
When i remove all webpack dependencies from my package.json it works when i use yarn. Any idea ?

Follow the README of this repo to reproduce:
https://github.com/nmessager/docz-issue-sandbox

**Comment by MaluNoPeleke** [comment]
Same problem for me with docz 0.13.7 and Yarn 1.13.
This command doesn't fix it:
`yarn add docz docz-theme-default react react-dom`
