### ISSUE TITLE
BundlerConfig - Add custom rule ?

### ISSUE THREAD

**Issue by melMass** [doczjs/docz#591]
## Question

Hi folks,

I'm trying to use a rule to use base64 loader for fonts but it won't convert my imports ...

**Description**
Here is the relevant part of my docz:

```js
modifyBundlerConfig: config => {
    config.module.rules.push( {
      test: /\.(ttf|eot|otf|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/,
      use: 'base64-inline-loader'
    } ) 
    return config
  },
}
```

**Comment by newtriks** [comment]
I'm having a similar issue with a custom SVG loader. I have a gut feeling that adding new rules do not override existing rules...?
