### ISSUE TITLE
This experimental syntax requires enabling the parser plugin: 'classProperties'

### ISSUE THREAD

**Issue by HadeAs** [doczjs/docz#594]
## Bug Report

**Describe the bug**

*Look the title, this is an error when i use class component in `<Playground>`*

**.babelrc code**
```
{
    "plugins": ["@babel/plugin-proposal-class-properties"]
}
```

**.mdx code**
```
<Playground>
{() => {
    const columns = [{
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        width: 200,
    }, {
        title: 'Age',
        dataIndex: 'age',
        width: 100,
        key: 'age',
    }, {
        title: 'Sex',
        dataIndex: 'sex',
        width: 100,
        render: (text) => text === 'M' ? 'male' : 'female'
    }, {
        title: 'Birth',
        dataIndex: 'birth',
        width: 150,
    }, {
        title: 'Address',
        dataIndex: 'address',
        width: 200,
        key: 'address',
    }];

    const result = [];
    for (let i = 1; i <= 100; i++) {
        result.push({
            key: i,
            name: 'John Brown',
            age: 20+i,
            sex: i%2 === 0 ? 'M' : 'F',
            birth: `${1980+i}-01-01`,
            address: 'New York No. 1 Lake Park', 
        })  
    }

    class Demo extends React.Component {
        state = {
            data: [],
            pagination: {},
            loading: false,
        };

        componentDidMount() {
            this.fetch();
        }

        handleTableChange = (pagination) => {
            const pager = { ...this.state.pagination };
            pager.current = pagination.current;
            this.setState({
                pagination: pager,
            });
            this.fetch({
                pageSize: pagination.pageSize,
                pageIndex: pagination.current,
            });
        }

        fetch = ({ pageSize = 10, pageIndex = 1 } = {}) => {
            this.setState({ loading: true });
            new Promise(resolve => {
                setTimeout(() => {
                    resolve(result.slice((pageIndex-1)*pageSize, pageIndex*pageSize));
                }, 2000)
            }).then((data) => {
                const pagination = { ...this.state.pagination };
                pagination.total = 100;
                this.setState({
                    loading: false,
                    data,
                    pagination,
                });
            });
        }

        render() {
            return (
                <Table
                    columns={columns}
                    dataSource={this.state.data}
                    pagination={this.state.pagination}
                    loading={this.state.loading}
                    onChange={this.handleTableChange}
                />
            );
        }
    }
    return <Demo />
}}
</Playground>
```

**Comment by HadeAs** [comment]
@pedronauck hello?

**Comment by savioserra** [comment]
@HadeAs Have you tried to put your `state` declaration inside a `constructor`?

**Comment by ronghang** [comment]
Have you solved the problem？ The same problem i have met when i use `arrow functions` in mdx files.

**Comment by HadeAs** [comment]
@ronghang  not tet

**Comment by yeatszhang** [comment]
I have the same problem~

**Comment by gitaoliao** [comment]
> ## Bug Report
> **Describe the bug**
> 
> _Look the title, this is an error when i use class component in `<Playground>`_
> 
> **.babelrc code**
> 
> ```
> {
>     "plugins": ["@babel/plugin-proposal-class-properties"]
> }
> ```
> 
> **.mdx code**
> 
> ```
> <Playground>
> {() => {
>     const columns = [{
>         title: 'Name',
>         dataIndex: 'name',
>         key: 'name',
>         width: 200,
>     }, {
>         title: 'Age',
>         dataIndex: 'age',
>         width: 100,
>         key: 'age',
>     }, {
>         title: 'Sex',
>         dataIndex: 'sex',
>         width: 100,
>         render: (text) => text === 'M' ? 'male' : 'female'
>     }, {
>         title: 'Birth',
>         dataIndex: 'birth',
>         width: 150,
>     }, {
>         title: 'Address',
>         dataIndex: 'address',
>         width: 200,
>         key: 'address',
>     }];
> 
>     const result = [];
>     for (let i = 1; i <= 100; i++) {
>         result.push({
>             key: i,
>             name: 'John Brown',
>             age: 20+i,
>             sex: i%2 === 0 ? 'M' : 'F',
>             birth: `${1980+i}-01-01`,
>             address: 'New York No. 1 Lake Park', 
>         })  
>     }
> 
>     class Demo extends React.Component {
>         state = {
>             data: [],
>             pagination: {},
>             loading: false,
>         };
> 
>         componentDidMount() {
>             this.fetch();
>         }
> 
>         handleTableChange = (pagination) => {
>             const pager = { ...this.state.pagination };
>             pager.current = pagination.current;
>             this.setState({
>                 pagination: pager,
>             });
>             this.fetch({
>                 pageSize: pagination.pageSize,
>                 pageIndex: pagination.current,
>             });
>         }
> 
>         fetch = ({ pageSize = 10, pageIndex = 1 } = {}) => {
>             this.setState({ loading: true });
>             new Promise(resolve => {
>                 setTimeout(() => {
>                     resolve(result.slice((pageIndex-1)*pageSize, pageIndex*pageSize));
>                 }, 2000)
>             }).then((data) => {
>                 const pagination = { ...this.state.pagination };
>                 pagination.total = 100;
>                 this.setState({
>                     loading: false,
>                     data,
>                     pagination,
>                 });
>             });
>         }
> 
>         render() {
>             return (
>                 <Table
>                     columns={columns}
>                     dataSource={this.state.data}
>                     pagination={this.state.pagination}
>                     loading={this.state.loading}
>                     onChange={this.handleTableChange}
>                 />
>             );
>         }
>     }
>     return <Demo />
> }}
> </Playground>
> ```

I have the same problem, I have resolved this by changing the arrow funciton  to the traditonal funciton.
