### ISSUE TITLE
Build log is too long in CI

### ISSUE THREAD

**Issue by kachkaev** [doczjs/docz#597]
Hi @pedronauck 👋!

## Bug Report

**Describe the bug**

Before upgrading from docz 0.11 to 0.13, stdout in build logs was pretty concise:
![screenshot 2019-01-22 at 15 51 46](https://user-images.githubusercontent.com/608862/51547216-bccf3a00-1e5d-11e9-9f32-145718d4d348.png)

And now they are nearly endless, because a new line is appended to stdout every fraction of a second
![screenshot 2019-01-22 at 15 48 11](https://user-images.githubusercontent.com/608862/51547255-ce184680-1e5d-11e9-8269-5f5e8764779c.png)

**To Reproduce**

Build docz in a non-tty environment (e.g. in CI)

**Expected behavior**

I'd expect no animation when printing out `⠏ Creating production build`, which only works in TTY

**Environment**

* OS: Linux VM in Azure Pipelines

**Hint**

```js
if (process.stdout.isTTY) {
  // animated output (erasing and restoring the current line's output is supported)
} else {
  // plain console output (can't erase what's already been printed)
}
```

**Comment by kachkaev** [comment]
Looks like relying on `process.stdout.isTTY` is not enough – it's true in some CIs, which is misleading. There'll be a need for a custom `isTTY()` function similar to one here: https://github.com/prettier/prettier/pull/5804

**Comment by ondrejbartas** [comment]
Hi most CI has `process.env.CI` = `true` waht about using this env variable for disabling progress print?

**Comment by kachkaev** [comment]
I'd recommend copy-pasting [Prettier's `isTTY()` function](https://github.com/prettier/prettier/blob/36aeb4ce4f620023c8174e826d7208c0c64f1a0b/src/utils/is-tty.js). Neither `process.env.CI` nor `process.stdout.isTTY` provide a sufficient check for all real-life scenarios.
