### ISSUE TITLE
withCSSContext' is not exported from '@emotion/core

### ISSUE THREAD

**Issue by danilosilvadev** [doczjs/docz#607]
## Bug Report

**withCSSContext' is not exported from '@emotion/core problem**

*I'm getting this problem today. I did try everything, included create a new project, but always is getting this warning and the project is not loading.*

`./node_modules/@emotion/styled-base/dist/styled-base.browser.esm.js
Attempted import error: 'withCSSContext' is not exported from '@emotion/core'.`

*PS: I don't have storybook at this project, but i do have getstorybook at global installation on my OS and i'm using CRA*

**Environment**

* OSX
* Node/npm version: the current lts

**Comment by MateusGabi** [comment]
I'm facing this problem too, but I have storybook installed.

**Comment by existenzial** [comment]
You might be able to solve this problem by adding `@emotion/core` to your devDependencies. That's what fixed it for me. 

I included it in my latest docz project - [design-ui](https://github.com/existenzial/design-ui/blob/c53437efb4c723ccc61076ffd80c1baba4673020/styled/styled-project/package.json#L45)

**Comment by MateusGabi** [comment]
At another project, I just installed docz and works!! It's so strange!

**Comment by thedaviddias** [comment]
Same problem too, same as @MateusGabi

**Comment by ThusharaBuddhika** [comment]
Don't ask how. 
But I tried with `npm install` and `npm start`. 
It didn't work.
Then I tried with `yarn` and `yarn start`.
Worked just fine.
