### ISSUE TITLE
Extend docz-default-theme Page component

### ISSUE THREAD

**Issue by huchenme** [doczjs/docz#612]
Is it possible to extend `docz-default-theme` Page component in an easy way?

For example, some of the documentation pages might have some meta data

`PackageA.mdx`:

```md
---
name: Textfield
menu: Core
route: /core/textfield
version: 1.1.0
author: Hu Chen
packageName: textfield
link: http://google.com
---

Some content
```

For these pages, I would like to display a custom React component with these data (a custom Table component) before the content in mdx file as they repeat over and over again.

Can we add support for something like this?

**Comment by huchenme** [comment]
The reason not to use a custom components is that I want to include some markdown headings in it as well:

```
# {Header from data}

## Installation

```
yarn add {some dynamic content from package.json}
```

## Versions

A React component with some data
```

**Comment by huchenme** [comment]
Or can how can we make markdown content dynamic? Can we expose the H1 - H6 component from `docz-default-theme`? what do you think

**Comment by weslleyaraujo** [comment]
exposing the components from docz-default-theme gonna be awesome! 😍

**Comment by rupification** [comment]
just noticed there is already a request for this.. closing mine: https://github.com/pedronauck/docz/issues/647

**Comment by huchenme** [comment]
@rakannimer what is the reason this issue get closed?
