### ISSUE TITLE
Error with SockJs on production build

### ISSUE THREAD

**Issue by savioserra** [doczjs/docz#616]
## Bug Report

**Describe the bug**

When running `build`, there are two issues:

- The `src` paths generated in the html file can't be found (but I can fix it manually inserting a `./` before each path.
- When opening the html file in the browser, I got an error as the screen bellow shows.

**To Reproduce**

1. Run `build`
2. Fix paths on index.html
3. Open in the browser

![image](https://user-images.githubusercontent.com/12066798/52167500-f2e4a780-2702-11e9-9e73-1636fc5d5b1f.png)

**Environment**

* OS: Windows 10
* Node/npm version: Node 10.15.1/yarn 1.13.0

**Additional context/Screenshots**
![image](https://user-images.githubusercontent.com/12066798/52167417-c7ad8880-2701-11e9-9920-3c195b4c8bdc.png)

**Comment by msokk** [comment]
For some reason built site still includes `react-dev-utils/webpackHotDevClient` causing SockJS to run and generate errors. This happens to me with v0.13.7
