### ISSUE TITLE
Add documentation for contributors

### ISSUE THREAD

**Issue by schalkventer** [doczjs/docz#618]
We use Docz extensively in our dev team (and in my personal projects too). I am extremely grateful for this amazing tool and would love to give back/contribute. 

However ([apart from the distinction between the `docz` and `docz-core` folder](https://github.com/pedronauck/docz/blob/6720344ff7d75d34b43e8fad079b6a3e0e386313/CONTRIBUTING.md)) there is not a lot of supporting documentation explaining the underlying architecture and conventions. I also don't see the addition of additional contributor documentation mentioned in the project roadmap (http://feedback.docz.site/roadmap).

I'm happy to help create this documentation if someone in the team or someone with experience contributing is able to give me a basic overview of the architecture.

**Comment by sw-yx** [comment]
hey! as a new contributor i'd love this too. not actually sure who apart from Pedro we can ask. I'd love for him to sketch out some outlines.

**Comment by pedronauck** [comment]
Hi folks, sorry the too late response I was very busy with the v1.
Now that I have the v1 released, I'll try to improve our contribution guide in order to be more easy to understand and help me in the project.

Btw, we really need core developers to help and maintain Docz 🙏
