### ISSUE TITLE
Anchor link not changing opacity

### ISSUE THREAD

**Issue by pavanpodila** [doczjs/docz#619]
## Bug Report

**Describe the bug**

The anchor link that shows up next to headers is not rendering upon hover. I am using the default configuration with only color changes.

The code can be seen [here](https://github.com/mobxjs/mobx.dart/tree/master/website): 

The live version is [here](https://mobx-dart.netlify.com/).

More specifically, the selector shows up like below. That seems to cause the problems as the SVG element (`Icon`) no longer gets targeted.

```
.css-18hsff8:hover NO_COMPONENT_SELECTOR{opacity:1;}
```

**Comment by josephthomashines** [comment]
> The code can be seen [here](https://github.com/mobxjs/mobx.dart/tree/master/website):

This link is dead for me, but my fix can be found [here.](https://github.com/josephthomashines/docz/blob/master/packages/docz-theme-default/src/components/ui/H2.tsx)

It's just a small one line change to the hover selector.
