### ISSUE TITLE
Can search engines like Googlebot index a Docz site?

### ISSUE THREAD

**Issue by kajmagnus** [doczjs/docz#621]
## Question

When I look at the HTML source for e.g. https://www.docz.site/documentation/creating-themes, I don't see any text that would be indexable by Googlebot.  Nevertheless, when I websearch for text on that page:  `"main features of Docz"`   — then Googlebot does find https://www.docz.site/documentation/creating-themes in its one and only search result.

I'm wondering, why does Googlebot find that page although the html source is empty? (only javascript files)  and more generally, are sites created with Docz indexable by search engines?

**Comment by samghelms** [comment]
@kajmagnus I don't know a ton about this, but from working in e-commerce, I believe that Googlebot will actually render javascript to html and index that. Check this article out: https://medium.freecodecamp.org/seo-vs-react-is-it-neccessary-to-render-react-pages-in-the-backend-74ce5015c0c9

**Comment by kajmagnus** [comment]
@samghelms  Ok, thanks for the reply.  I've read somewhere me too that Googlebot does that, but I didn't expect it to work so well, until now when I had a look at the article you linked :- ) Interesting that also duckduckgo understands "javascript pages".
