### ISSUE TITLE
Feature Request: PalletColor component

### ISSUE THREAD

**Issue by wilsson** [doczjs/docz#623]
I was working on the design of a component that represents the color palette of my style guide

![group 4](https://user-images.githubusercontent.com/4754339/52544507-3a140d80-2d7f-11e9-8c87-2194e40c4da4.png)

It would be good to have a component as such inside the package `docz`, I would like to know if I could contribute with it

**Comment by gaui** [comment]
I would also want this. This makes it possible to implement a Design System with Docz, instead of just a component library.

Something like this:
https://docs.catalog.style/specimens
https://www.catalog.style/try

**Comment by antonsamper** [comment]
I think this will be useful too. Its quite common to showcase a color palette. I wonder if this could be implemented as a plugin instead of adding it to the module?
