### ISSUE TITLE
Code selection in Playground is broken

### ISSUE THREAD

**Issue by ivan-dalmet** [doczjs/docz#637]
## Bug Report

**The selection in Playground code (CodeMirror) is not what you see.**
So in some case you can't select some code.
And if you copy/paste it's not what you expected.

*A clear and concise description of what the bug is.*

**To Reproduce**

1. Go to `examples/basic`
2. Click on the second Playground code button
3. Try to select all the code (with mouse not `ctrl+a`)
4. You can't :/
![codemirror-bug](https://user-images.githubusercontent.com/9749061/52865360-c5552080-313c-11e9-92cb-365deeaad14e.gif)

CodeMirror instance is not loaded correctly. You can resize your window and it will works (because CodeMirror refresh itself when window size change).

We have a fix and we will submitted a PR ;)

**Comment by idmontie** [comment]
Looks like the last line is not intractable at all until you type a character. Arrow keys don't force it to correctly render either.

**Comment by ivan-dalmet** [comment]
Yep the interactive part of CodeMirror is desync with the visual part. If you copy/paste you will see that it's not what you visually selected.

We have submitted a PR that fix the problem :)
