### ISSUE TITLE
Update react-hot-loader

### ISSUE THREAD

**Issue by bravecow** [doczjs/docz#645]
## Bug Report

React hook `useEffect` is broken

https://github.com/facebook/react/issues/14767#issuecomment-461118304

**Comment by bravecow** [comment]
![image](https://user-images.githubusercontent.com/988471/53015766-7f59ce80-3454-11e9-869d-be4f6380fb06.png)

**Comment by bravecow** [comment]
Workaround:

```
"resolutions": {
    "docz-core": "^0.13.7"
  }
```

**Comment by Grsmto** [comment]
I had to pop other stuff to get it working:
```
"resolutions": {
    "react-hot-loader": "4.7.1",
    "docz-core": "^0.13.7",
    "ansi-styles": "^3.2.0"
  },
"devDependencies": {
  "@emotion/cache": "^10.0.0",
  "@emotion/core": "^10.0.6"
}
```

Feels super dodgy but works for now 🙏
