### ISSUE TITLE
Add ability to pass PropTypes into PropsTable

### ISSUE THREAD

**Issue by mlshv** [doczjs/docz#685]
On my current project I have a custom utility that generates simple components, e.g.:
```js
const InputBox = generateComponent('input-box', {
    buttons: PropTypes.oneOf(['left', 'right', 'all']),
    disabled: PropTypes.bool,
    focus: PropTypes.bool,
    'has-error': PropTypes.bool,
    'has-value': PropTypes.bool,
    size: PropTypes.oneOf(['big', 'small']),
})
```

However, react docgen doesn't seem to be able to read PropTypes, even if I assign them like this:

```js
const propTypes = {
    // ...
}

const InputBox = generateComponent('input-box', propTypes)

InputBox.propTypes = propTypes
```

So PropsTable doesn't render:
```js
<PropsTable of={InputBox} /> // this returns null
```

Is it possible to make PropsTable able to receive propTypes as a separate prop bypassing react docgen? Something like this:
```js
<PropsTable propTypes={InputBox.propTypes} />
```

**Comment by mlshv** [comment]
Hey @pedronauck, if you agree that this feature is a good idea, I could work on it myself. What do you think?

**Comment by pedronauck** [comment]
Yeah, feel free to make some pull request 🙏

**Comment by transitive-bullshit** [comment]
I needed this for a non-docz project and really loved docz's old `PropsTable`, so I just published [react-docgen-props-table](https://github.com/transitive-bullshit/react-docgen-props-table) which does what you want.

@pedronauck curious why you chose to drop PropsTable in favor of Props? imho it's a move in the wrong direction for the design & usability of Docz.
