### ISSUE TITLE
PropsTable: What's about nested Props 

### ISSUE THREAD

**Issue by bsssp** [doczjs/docz#689]
Is: The following example show only the name of the type "A",
Should: I missed the content of the type "A {a: string,b: string}", maybe as a tooltip by mouseover?

type A {
a: string,
b: string
}
type Props {
 a: A
}
const comp = (props: Props) => {
...
}

**Comment by mlshv** [comment]
I had the same issue. I think it relates to react-docgen, maybe you can find something in their repo: [reactjs/react-docgen](https://github.com/reactjs/react-docgen)

**Comment by ggzhangGithub** [comment]
@bsssp how do you fixed your problem, I just have the same issue

**Comment by ggzhangGithub** [comment]
@rakannimer how can I fixed this problem in docz?
