### ISSUE TITLE
Community Status of Docz

### ISSUE THREAD

**Issue by joeljeske** [doczjs/docz#690]
Hey @pedronauck, thanks so much for all you have done! This is a wonderful project and I have enjoyed using it. 

In the past 6 months, the [weekly download count has tripled](https://www.npmtrends.com/docz), which I think is awesome! Well done. My concern is that you [currently stand alone as this project's sole maintainer](https://github.com/pedronauck/docz/graphs/contributors)  and your own personal contributions has [dropped a bit in the past few months](https://github.com/pedronauck/docz/graphs/contributors). Do you think you would be open to fostering a community of contributors?  I know how difficult and time consuming maintaining a large project like this can be and I would think that enabling contributors to carry out grunt work might be beneficial for you and the project and all of its beneficiaries. 

Ticket #618 seems to be the community reaching out to provide support to better help you and the project. I know that using issue labels ("help-wanted", "good-first-issue", etc...) for guiding new and existing contributors have proved helpful in other projects and might be a low-burden way of encouraging contributors. 

I want to re-iterate that I am very thankful for all your hard work and I do not want to come off as entitled or demanding. Just wanting to get a feel for your thoughts on this project and about enabling contributors. 

Thanks!

**Comment by pedronauck** [comment]
Hey Guys, sorry about the too late response, I was very busy with the [new release](https://github.com/pedronauck/docz/releases/tag/v1.0.0-rc.3). 

First of all, I really appreciate your compliments @joeljeske  🙏🏻
And of course, in the months was very hard to me maintain Docz and answer issues here, one of the main reasons is why I'm the only maintaining for the project and this is very bad. I want a lot of help from people that really want to be active in the project, not just to answer issues, but to help me developing features and fixing bugs, we'd a long roadmap and a lot of things to do in the project, but I need help and support.

So, if you or anyone that wants to help me, please send me some message 🙏

**Comment by joeljeske** [comment]
@pedronauck, thanks for the response! I really appreciate it. First off, I missed all the stuff you were working on in v1, which led to skewed contribution charts as they were only targeted at master. You have been working hard!!

I see you have a contribution guide, which is very helpful for new devs getting started.  One thought I have, is that your roadmap does not seem to express _your_ desires for the project very well. Meaning, I see a lot of feature requests that look valuable to me but I do not see responses from you that either agree with the proposal or reject it. This can make it discouraging for people that want to contribute to that feature, but might be afraid you will reject a PR based on the idea itself, regardless of the implementation. Your roadmap seems to be heavily focused on adding support for additional frameworks. Whereas that will definitely expand your audience, you likely will not get much contribution support for adding framework support as that audience is not likely tracking Docz very much. 

Personally, I would be very interested in the following features, but myself and others likely don't know if you would accept contribution toward those goals or perhaps even where to begin. 

http://feedback.docz.site/roadmap/p/new-package-docz-ui
http://feedback.docz.site/roadmap/p/support-for-versioning
http://feedback.docz.site/roadmap/p/multiple-levels-of-hierarchy
http://feedback.docz.site/roadmap/p/customizable-tabs-in-playground

Again, please take my words as suggestions and my thoughts. I really do appreciate your work and vision for this project!
