### ISSUE TITLE
Duplicated menu when using hierarchy

### ISSUE THREAD

**Issue by lucasconstantino** [doczjs/docz#694]
## Bug Report

When adding sub-menu items, I'm facing an item both inside it's parent and in the root level:

![joxi_screenshot_1553196055980](https://user-images.githubusercontent.com/2688512/54779291-94618300-4bf5-11e9-8a4f-c0a4154ff768.png)

Here is the document configuration:

```md
---
name: Composition
route: /concepts/composition
menu: Concepts
---
```

And here is the menus config:

```md
// doczrc.js
module.exports = {
  menu: [
    'Introduction',
    'Getting Started',
    { name: 'Development', menu: ['Structure', 'Environment & Commands'] },
    { name: 'Concepts', menu: ['Composition'] },
    { name: 'Reference', menu: ['Routing', 'Layouts & Blocks', 'Menus'] }
  ]
}
```

**Expected behavior**

Once I configure an item to be shown under a parent, it should not be shown in the root level.

**Comment by pedronauck** [comment]
@lucasconstantino try to update to the new release, this can be fixed on it 🙏

**Comment by JeroenReumkens** [comment]
@pedronauck  I'm currently having the same issue on 1.2.0. So I think this is not yet fixed unfortunately.

**Comment by klappy** [comment]
Is there an example of a working implementation of docz v1.2.0 with a custom menu using the above structure? I am getting both duplicate entries, but the one in the sub-menu is not clickable and does not function.

**Comment by rumblefrog** [comment]
This regression exists in v2 as well.

**Comment by jakemmarsh** [comment]
Any updates on this? Makes using the `menu` option basically infeasible.

**Comment by mAAdhaTTah** [comment]
Still not stale, running into this now.

**Comment by jakemmarsh** [comment]
In case it helps anyone else, I'm currently working around this by explicitly hiding the undesired links via CSS:

```scss
// Hack to hide duplicate nested menu items https://github.com/doczjs/docz/issues/694
div[data-testid="sidebar"] > a[href*="/entities/"] {
  display: none;
}
```

**Comment by mickaelzhang** [comment]
Hello @jakemmarsh @mAAdhaTTah !
Do you guys still run into this issue ? I tried to replicate your issue but I can't seem to reproduce it
If you do, can you guys give me your project's version of `docz` + `gatsby-theme-docz` ?
(Upgrading it might solve the issue)

**Comment by jakemmarsh** [comment]
@mickaelzhang this issue does still exist for me on the latest versions: `docz@2.2.0` and `gatsby-theme-docz@2.2.0`

**Comment by edmundojr** [comment]
Running into the same issue on version `docz@2.3.1`.

**Comment by mickaelzhang** [comment]
Can you guys direct me to a project where you have this issue?

**Comment by mAAdhaTTah** [comment]
I ended up rewriting the menu setup to avoid it so I don't have a case right now. I'll see if I can reproduce it.

**Comment by Phil-Barber** [comment]
This appears to be fixed in master. Tried to reproduce in the basic example:

![image](https://user-images.githubusercontent.com/42933362/83971768-f8449a00-a8d4-11ea-9fff-b0a017d6c175.png)

doczrc.js
```
export default {
  menu: [
    'Getting Started',
    'Readme',
    { name: 'Components', menu: ['Alert2', 'Alert'] },
  ],
}
```
