### ISSUE TITLE
warning: Could not stat path Filename too long

### ISSUE THREAD

**Issue by sag1v** [doczjs/docz#728]
I'm getting the following warnings while trying to deploy:
> warning: Could not stat path 'static/js/mdx-breakpoints~mdx-easing~mdx-enable-auto-play~mdx-focus-on-select~mdx-go-to~mdx-index~mdx-initial-~7647ae80.115502fd.js': Filename too long

Indeed this path (and the corresponding `.map` file) exists and it seems that its combined by the names of all my menus together for some reason.

This preventing me from deploy my docz to gh-pages. 

Am i doing something wrong?

this is [my repo](https://github.com/sag1v/react-elastic-carousel)

![image](https://user-images.githubusercontent.com/9153149/55060746-d3bb2400-507a-11e9-96ea-aafff880537a.png)

**Comment by pedronauck** [comment]
Hi @sag1v, try to update to the newest version, we are no longer giving support for `0.13.7`

**Comment by sag1v** [comment]
@pedronauck For some reason when i use the latest version of `docz` i can't use class fields anymore. so i get parse:
>Module parse failed: Unexpected token
You may need an appropriate loader to handle this file type.

For example: 
```
class MyComponent extends React.Component {
  state = { // <- this is a class field

  };
}
```

**Comment by pedronauck** [comment]
Can you show me some repo with the minimal setup @sag1v ?

**Comment by sag1v** [comment]
Basically [this is the repo](https://github.com/sag1v/react-elastic-carousel) i'm having the issue.
