### ISSUE TITLE
Props component defaultProps oneOf display

### ISSUE THREAD

**Issue by rupification** [doczjs/docz#739]
pretty minor request as I noticed the `<em>= 'primary'` it not displaying correctly in smaller screens when there are a number of `oneOf` values.

suggest to drop the `= 'default'` and just add style to the list of `oneOf` 

### currently
`kind` 'primary' | 'secondary' = 'primary'
### suggested
`kind` **'primary'** | 'secondary' <-- maybe bold or underline or something else

**Comment by pedronauck** [comment]
Can you give me some example @rupification ?

**Comment by rupification** [comment]
@pedronauck 
not sure if this is what you are after. or do you need some kind of style template?
```
// MyButton
MyButton.propTypes = {
  kind: PropTypes.oneOf(['primary', 'secondary']);
}

MyButton.defaultProps = {
  kind: 'primary'
}
```
```
import { Props } from 'docz';
import MyButton from './Button';

# Properties
<Props of={MyButton} />
```

displays as

`kind` `'primary' | 'secondary'` _= 'primary'_

suggested

`kind` `**primary** | 'secondary'`

**primary** is bold or can be any style like text-decoration: underline using primary color

**Comment by Glazy** [comment]
Hey @rupification,

Nice suggestion. Would be happy to accept a PR for this if you have the time to implement this :muscle:
