### ISSUE TITLE
Playground editing re-render the component too fast 

### ISSUE THREAD

**Issue by bsssp** [doczjs/docz#781]
If I change a required property, before I finish writing, the component make a re render and it became an error over the whole page.
It'll be great if i can disable the auto re-render, so can i re-render manually ove a button.

**Comment by jchadwick** [comment]
I think a good middle-ground might be to offer some sort of throttling or timeout to wait until the user is "done" typing before re-rendering.

**Comment by skrSiteimprove** [comment]
+1 for this!
