### ISSUE TITLE
Docz not building on Windows

### ISSUE THREAD

**Issue by ejuo** [doczjs/docz#783]
## Bug Report
Get error when build Docz v1.0.0-rc.8 (all v1 same error).

```
...
...
...
src/ast.ts, src/codesandbox.ts, src/format.ts, src/fs.ts, src/index.ts, src/imports.ts, src/jsx.ts, src/mdast.ts → lib...
[!] Error: './format' is imported as an external by src\codesandbox.ts, but is already an existing non-external module id.
Error: './format' is imported as an external by src\codesandbox.ts, but is already an existing non-external module id.
    at error (C:\Git\docz.next\docz-master\node_modules\rollup\dist\rollup.js:3598:30)
    at C:\Git\docz.next\docz-master\node_modules\rollup\dist\rollup.js:18014:21
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
```
to fix this I take only 1 entry 'src/index.ts' in [rollup.config.js](https://github.com/pedronauck/docz/blob/master/core/docz-utils/rollup.config.js).
Then after successfully build, all tests failed
```
Test Suites: 1 failed, 1 total
Tests:       6 failed, 6 total
Snapshots:   6 failed, 6 total
Time:        6.887s
Ran all test suites.
error Command failed with exit code 1.
```

**To Reproduce**

1. clone docz.
2. `yarn install`
3. `yarn bs`
4. `yarn packages`

I suspect, rollup don't resolves dependences, all bundles has links to src .ts files.
Example:
index.esm.js from [docz-utils](https://github.com/pedronauck/docz/tree/master/core/docz-utils) contains
```
export * from './ast.ts';
export * from './codesandbox.ts';
export * from './fs.ts';
export * from './imports.ts';
export * from './jsx.ts';
export * from './mdast.ts';
export { format } from './format.ts';
```
**Expected behavior**

It should build completly bundles.

**Environment**

* OS: Windows 10
* yarn 1.13.0 (or npm 6.5.0), 
* node 11.13.0 (or 10.15.0)

**Comment by fi3ework** [comment]
Not sure exactly why. How about run `yarn build` in `docz-utils` packages, can it build successfully? For me, I must precompile `docz-utils` manually otherwise `yarn packages` will fail. But it might be a problem of rollup with Windows.

**Comment by ejuo** [comment]
I separate docz-utils to new folder. Add docz-rollup and other required modules. Take parent tsconfig.json from docz. And made: `yarn`, `yarn build` and got same error, full trace:
```
C:\Git\docz.next\docz-utils>yarn build
yarn run v1.13.0
$ trash lib && cross-env NODE_ENV=production rollup -c

src/ast.ts, src/codesandbox.ts, src/format.ts, src/fs.ts, src/index.ts, src/imports.ts, src/jsx.ts, src/mdast.ts → lib...
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en#error-this-is-undefined
src\codesandbox.ts
1: var _this = this;
               ^
2: import * as tslib_1 from "tslib";
3: import * as path from 'path';
src\fs.ts
1: var _this = this;
               ^
2: import * as tslib_1 from "tslib";
3: import * as path from 'path';
[!] Error: './format' is imported as an external by src\codesandbox.ts, but is already an existing non-external module id.
Error: './format' is imported as an external by src\codesandbox.ts, but is already an existing non-external module id.
    at error (C:\Git\docz.next\docz-utils\node_modules\rollup\dist\rollup.js:3766:30)
    at C:\Git\docz.next\docz-utils\node_modules\rollup\dist\rollup.js:18248:21
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:871:11)
    at internal/main/run_main_module.js:21:11

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
What I'm doing wrong?

**Comment by patricksevat** [comment]
Hi @ejuo I'm encountering the same problem and I'm looking into the same direction as you. I've found that the failed tests are sorta unrelated, so don't worry about those.

The issue is in `docz/core/docz-rollup/src/index.js` where on line 8 this fn is defined 
```
const defaultExternal = id =>
  !id.startsWith('\0') && !id.startsWith('.') && !id.startsWith('/')
```

On Unix systems this probably works fine but on Windows not when logging `id` I get this output:
```
...
{ id: 'humanize-string' }
{ id: 'lodash/flatten' }
{ id: 'lodash/get' }
{ id: 'C:\\docz\\core\\docz-utils\\src\\format.ts' }
...
```

I'll try and fix this and create a PR

**Comment by ejuo** [comment]
Exactly! In general, a rather strange (and dangerous) approach to filter internal/external modules through `startsWith`.

**Comment by patricksevat** [comment]
I have limited experience with rollup and its best practices, but I've got it working and submitted a PR, feel free to propose a better solution if you know one.

**Comment by ejuo** [comment]
I can offer an alternative solution, resolving through the package.json (using rollup-plugin-peer-deps-external).
@patricksevat, @pedronauck, what do you think?

**Comment by ejuo** [comment]
@pedronauck
Version 1.1.0 broken again.

Solutions:
https://github.com/pedronauck/docz/pull/812
https://github.com/pedronauck/docz/pull/830

**Comment by jesperorb** [comment]
Getting the same error on windows as well. The commit https://github.com/patricksevat/docz/commit/8e0e0808bf7081191697787b8066b1d181626f7e would fix this but it was added as a commit in a larger PR that he closed, but this fix still needs to be applied for v2 to work on Windows. Could you possibly open a PR with just that commit @patricksevat?
