### ISSUE TITLE
RFC: support dynamic rendering of a MDX code block

### ISSUE THREAD

**Issue by cdaringe** [doczjs/docz#785]
# context

consider the lodash.com docs.

- onload, the docs present the user with a static snippet
- onclick "Try with REPL", it flips into a runkit context

![doc-block-swap mov](https://user-images.githubusercontent.com/1003261/55916915-9094a100-5ba2-11e9-9d89-f031dd577e33.gif)

# problem

- i have implemented a `<Runkit />` integration that--like the lodash docs--i do not want to eager load.  instead, i want the nice static content by default, and only later to swap into the runkit context on user request.

here's a functional example:  https://cowtown.surge.sh/stack-middlewares

in the example you will see that _i don't render_ the underlying code on initial render as i do not have a mechanism to tell react and/or docz "render this source code into a typescript code block".  i _do have_ the code snippet available in an imported `string` variable.

# discussion

- i could roll my own thing and get my source onto the page, but, i'd rather
- use `docz` provisions to get all of the nice benefits of the theme

i'm not sure if `docz` owns mdx parsing and translation into react or if that's handled completely by some 3rd party `mdx` lib.  regardless, my underlying desire is to figure out **how to dynamically render a code block**.

thanks!

**Comment by jchadwick** [comment]
I have a similar need - I want to parse the MD(X) in my JSDoc contents.

It appears the work is done in [core/docz-utils/src/mdast.ts](https://github.com/pedronauck/docz/blob/094afcf021301009d58d61f239b84fd7447e63d4/core/docz-utils/src/mdast.ts#L14).  The current implementation deals with files on disk rather than strings, but the first line is to read the file contents in, so it should be easy to expose the actual parsing logic.

**Comment by cdaringe** [comment]
@rakannimer, any feedback?

**Comment by rakannimer** [comment]
Hey,

The only way I can think of to do what you're looking for would be to :

- Extract the Code component from gatsby-theme-docz to docz-components
- Expose the Code component from docz

In your mdx :
```mdx
import {useState} from 'react'
import {Code} from 'docz'
import RenderChildrenFunction from './`

<RenderChildrenFunction>
{() => {
	const [showStaticCode, setShowStaticCode] = useState(true)
	return <>
	{showStaticCode?<Code>{code}</Code>:<Runkit code={code}/>}
	</>
}}
</RenderChildrenFunction>
```

In your jsx :
```jsx
import React from 'react'
const RenderChildrenFunction = ({children}) => children()
export default RenderChildrenFunction;
import {Code} from 'docz'
import RenderChildrenFunction from './`

<RenderChildrenFunction>
{() => {
	const [showStaticCode, setShowStaticCode] = useState(true)
	return <>
	{showStaticCode?<Code>{code}</Code>:<Runkit code={code}/>}
	</>
}}
</RenderChildrenFunction>
```


Would something like that solve your problem ?

**Comment by cdaringe** [comment]
yep.  #1206 submitted
