### ISSUE TITLE
Menu click always back to the top of screen

### ISSUE THREAD

**Issue by HadeAs** [doczjs/docz#824]
## Question
In my doc, I has lots of menu, such as the below:
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/12652964/56490474-e7da3000-6517-11e9-82a4-0b1646ec0b24.png">

when I scroll down and click a menu, I want the scroll not back to top, like the below:
![20190422160605](https://user-images.githubusercontent.com/12652964/56490679-92525300-6518-11e9-8d84-1472cebbd1fc.jpg)

but it will not perform like i want:
![20190422160740](https://user-images.githubusercontent.com/12652964/56490744-cb8ac300-6518-11e9-8cf3-0f7aeb2d01e9.jpg)

i want know how can i solve this problem @pedronauck

**Comment by pedronauck** [comment]
Great, pull requests are welcome 🙏

**Comment by Glazy** [comment]
Hey @HadeAs thanks for the bug report!

I have labelled this as a 'good first issue' so hopefully someone comes along and takes a look at it. I am quite busy at the moment but if someone hasn't looked at it soon I will try take a look for you :muscle:

**Comment by co16353sidak** [comment]
@Glazy @pedronauck Hey, would love to work on this as my first issue here.

**Comment by kmoiseenko** [comment]
Hello everybody.
I thought that i could handle this issue and tried to reproduce it. But it seems to me, that everything works as expected. 
@HadeAs could you please approve, that this issue is still reproducing? Could you text me and provide more information about how to reproduce it?

**Comment by baxtergu** [comment]
Have the same issue in my own docz project. It seems like the menu on left won't hold its own scroll position after each menu click.

**Comment by rakannimer** [comment]
Hey @co16353sidak, @kmoiseenko 

I know this is a bit late, but are you still interested in giving this a shot ?

You can find a repro here : https://github.com/rakannimer/docz-issue-824

Happy to help get it done if you are 👍

**Comment by rubenmoya** [comment]
I think this can be closed, right?

**Comment by rakannimer** [comment]
Hey @rubenmoya 

Thanks for reminding me. Yep this behavior was added to docz 👍 

Going to close this, please feel free to open a new issue for any other bug/requests.

**Comment by maxxiaobao** [comment]
@HadeAs Did you resolve this issue, I met this issue as well.
