### ISSUE TITLE
Docgen does not pick up types from d.ts declaration files

### ISSUE THREAD

**Issue by joeljeske** [doczjs/docz#827]
## Bug Report

**Describe the bug**

The docgen props parser properly picks up types found in TS source files, but it does not pick up types that declared in d.ts files next to .js files.

I have some custom build settings that would be difficult to replicate in webpack and want to build my packages first, and then have Docz find the related MDX files that import the build .js and d.ts packages.

**Expected behavior**

I would expect the props parser to find the .d.ts files and find the related prop types to be included in the docgen output.

**Environment**

* OS: OSX 10.13.6
*  Node 8/npm 5

**Comment by ejuo** [comment]
I also thought about it.
Originally planned to separate the library and documentation in different repositories.
But there is the big problem in that when building the library, the react components lack metadata and cannot be unambiguously compared with the source files (including d.ts).
But from a practical point of view, there is such an opportunity.  Do not strictly match the names of files and properties of components (eg. `displayName`), in most cases this will be enough. For this you need:
1. For each documented component, specify `displayName` property, which is equal to its file name.
2. Modify the doczrc.js like this:
```
export default {
  typescript: true,
  docgenConfig: {
	  propFilter: () => true,
	  searchPath: 'node_modules/your-component-library',
	  },
  filterComponents: (files) =>
    files.filter(filepath => /\/[A-Z]\w*(.d)?\.(js|jsx|ts|tsx)$/.test(filepath))
}
```
Also minor improvements of the `Docz` are required. [PR](https://github.com/pedronauck/docz/pull/846) I prepared.
@pedronauck, what do you think?

**Comment by joeljeske** [comment]
Interesting. Yea it would be nice if there was better support. 

This was very important for me so i ended up with the following workaround: 


```js
//doczrc.js

export default {
  filterComponents: () => Object
    .entries(require('./package.json').dependencies)
    .map(([dep]) => {
        const { types } = require(`${dep}/package.json`);
        if (types) {
          return path.relative(__dirname,  require.resolve(`${dep}/${types}`));
        }
    })
    .filter((typesPath) => !!typesPath)
}
```

And then I re-wrote the paths for the db props inside a "custom" theme that just redirects into the default theme


```js
import Theme from 'docz-theme-default';
import { createElement, FC, useMemo } from 'react';

export const ThemeWrapper: FC<any> = ({
  db,
  ...props
}) => {
  // We have to re-write the props so we can support .d.ts files instead of JS files
  if (db && Array.isArray(db.props)) {
    db.props.forEach((prop: any) => {
      const ext = '.d.ts';
      if (prop.key && prop.key.endsWith(ext)) {
        prop.key = prop.key.slice(0, ext.length * -1) + '.js';
      }
    });
  }
  return <Theme {...props} db={db} />;
};

```

The main issue here is that the d.ts *has* to be right next to the .js file, which was true for how i configured all of my projects. But that might not be true for all projects.

**Comment by joeljeske** [comment]
Another potential solution that would better for Docz likely is if "allowJS" was forced in the ts files, and then .js files were also pushed through the ts docgen parser which should also allow the TS parser to read the .d.ts files and then match up the metadata by export name. I could not get that working however without changes to docz which I was not wanting to do.

**Comment by NexxLuo** [comment]
How to use this with d.ts file ? Could you provide a simple demo ? I try it such as above , but not work.

**Comment by ejuo** [comment]
@NexxLuo, like in this [comment](https://github.com/pedronauck/docz/issues/827#issuecomment-488334691)?

**Comment by NexxLuo** [comment]
My mdx files is in examples , d.ts is in folder types .  
How to let the Props  render by the d.ts file  ?
![QQ图片20190718105442](https://user-images.githubusercontent.com/18549980/61425732-81b04e00-a94a-11e9-8983-168724ca561e.png)

The doczrc.js like this, is that right?

```javascript
 export default {
  typescript: true,
  docgenConfig: {
	  propFilter: (prop) => prop.parent.fileName.includes('types'),
          resolver: (exp, source) => {
		  var name = path.basename(source.fileName, path.extname(source.fileName))
		  return path.basename(name, path.extname(name))
		  },
	  searchPath: 'types',
	  },
  filterComponents: (files) =>
    files.filter(filepath => /\/[A-Z]\w*.d.ts$/.test(filepath))
}```

**Comment by ejuo** [comment]
@NexxLuo, possibly, index.d.ts file not matched by regexp in filterComponents `/\/[A-Z]\w*.d.ts$/`.
