### ISSUE TITLE
Add more props to Playground component

### ISSUE THREAD

**Issue by crazyxhz** [doczjs/docz#828]
add more props to Playground: For example, user can control a playground code is expanded by default or has the sandbox button

**Comment by fi3ework** [comment]
See this great pr: https://github.com/pedronauck/docz/pull/823. Some props have been added. Feel free to leave a message for your wanted props 😀

**Comment by Glazy** [comment]
Hey @crazyxhz :wave:

It would be awesome if you could come up with a concrete list of props you would like to see added to the `<Playground />` component :muscle:
