### ISSUE TITLE
Warning about multiple instances of styled-components, docz theme messed up

### ISSUE THREAD

**Issue by eranimo** [doczjs/docz#838]
## Bug Report
When using docz with components written in styled-components, I get the following warning when loading docz. Also, the build-in theme's styles are all messed up.

```
It looks like there are several instances of "styled-components" initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes you application bigger without a good reason.

If you are using a building tool like webpack, consider checking your bundle for duplication of the "styled-components" module.
```

**To Reproduce**

1. Create a component with styled-components
2. Use the default docz config
3. Load docz page
4. See console for warning

**Expected behavior**

- docz should load without styles messed up

**Comment by gesquinca** [comment]
I'm running into the same issue. 

I'm trying to document a component library that uses `styled-components` as a `devDependency` and I can't get the styles to properly render in the `Playground`. 

Anyone find a fix for this?

**Comment by eranimo** [comment]
@gesquinca The styled-components docs mention hoisting your dependencies if you're using lerna, I tried that and it didn't work. I also tried aliasing the dependencies so that the same instance was used, but that didn't work either? I gave up and switched to storybook :/
