### ISSUE TITLE
The "useDocs()" hook returns an empty array within a Gatsby project 

### ISSUE THREAD

**Issue by alec-buda** [doczjs/docz#842]
## Bug Report

**Describe the bug**

*The useDocs() hook returns an empty array within a Gatsby project even though docz is able to successfully import MDX files*

**To Reproduce**

Here is a minimal example to reproduce the issue.
```
git clone https://github.com/lemon-31/gatsby-docz-example.git
cd gatsby-docz-example
npm install
gatsby develop
```
Navigate to localhost:8000 in your browser. You will notice that docz is running successfully and is displaying our index.mdx file as expected.

Next, navigate to our test page where we called the hook:
```
localhost:8000/test-page
```

You will likely notice that the docs array is empty. This can be checked in the console where the docs array is logged or alternatively in the DOM where the contents inside our `<div>` are empty.

**Expected behavior**

I expected the data from the index.mdx file to be present within the returned value of useDocs()

**Environment**
```
Windows 10 Pro Version 1803
gatsby --version
2.5.12
npm --version
6.4.1
node --version
v10.15.3
```

**Additional context/Screenshots**
Feel free to let me know if you would like any further information. Also, could the problem have something to do with the following line observed in the build:
```
error (node:13740) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
Thanks

**Comment by evanvin** [comment]
I'm getting the same Tapable.plugin error. I'm using a simple CRA app to try and get this to work

**Comment by dobrea-v** [comment]
I have the same behavior when i try to use `useDocs` inside gatsby project, when trying to display it on main page (pages/index.js). Maybe i miss some additional configuration?
