### ISSUE TITLE
Bug: CodeMirror css styles are not applied when offline.

### ISSUE THREAD

**Issue by hastebrot** [doczjs/docz#843]
## Bug Report

**Describe the bug**

*A clear and concise description of what the bug is.*

**To Reproduce**

1. Go offline
2. Open generated docz site with code block in markdown
3. See codemirror syntax highlighted pane empty (white background)

**Expected behavior**

Syntax highlighted code block should be shown

**Environment**

* Docz v1.0.1
* Corporate network which blocks outside requests.
* or, horrible german mobile internet with EDGE connections outside of bigger cities

<img width="923" alt="Screenshot 2019-04-30 at 10 18 09" src="https://user-images.githubusercontent.com/496255/56948723-4c594880-6b31-11e9-8a3a-d3fad5a030ad.png">

**Comment by focus7eleven** [comment]
I came across the same problem. Any update?

**Comment by focus7eleven** [comment]
workaround: 
1. remove `@import url('https://unpkg.com/codemirror@5.42.0/lib/codemirror.css');` in `styles/global.ts`
2. add `import 'codemirror/lib/codemirror.css';` in `ui/CodeMirror/index.tsx`

it works to me
