### ISSUE TITLE
Local theme file doesn't work

### ISSUE THREAD

**Issue by Kerumen** [doczjs/docz#856]
## Bug Report

**Describe the bug**

As described in the [docs here](https://www.docz.site/docs/project-configuration#theme), I tried to add a local theme file.

**To Reproduce**

I created a simple file `theme.js` inside my `./src` folder and added it in my `doczrc.js`:

```js
{
  ...
  theme: './src/theme.js',
  ...
}
```

When I run `yarn docz dev` I get this error:

```shell
Failed to compile.

./.docz/app/root.jsx
Module not found: Can't resolve './src/theme.js' in '/Users/yannpringault/git/PayFit/components/.docz/app'
```

**Expected behavior**

The docz command should spin up the doc site with the local theme loaded.

**Environment**

* OS: MacOS v10.14
* Node/npm version: Node v10 / npm v6

**Additional context**

I had a quick look and it seems that the theme file is replaced in the `.docz/app/root.jsx` without any transformation, hence the relative URL doesn't work here.

**Comment by Kerumen** [comment]
Ok, I fixed it by changing the import to `'src/theme.js'`.

This leads me to another question, is it possible to override only the components without redefining the whole theme?

I'd like to keep the default `docz-theme-default` bt only change the headings.

I can open another issue for that.

**Comment by draperunner** [comment]
I also had this problem with finding out how to specify the theme path. I think the documentation could be much better on this point. An example that shows a file structure and an extract of the `.doczrc` would be very helpful. 

It's confusing that the docs say "relative path" and show the example `theme: '/src/my/theme/folder',`, which to me looks like an absolute path. And if a relative path is OK, why doesn't `./src/my/theme/folder` work...?

**Comment by skrSiteimprove** [comment]
Hi, I'm having problems simply following the example in the docs.

In `doczrc.js`
```javascript
export default {
	theme: "docz-theme.jsx"
};
```

And in `docz-theme.jsx`

```jsx
import React from 'react'
import { theme } from 'docz'

const Theme = ({ children }) => <div>{children}</div>

export default theme()(Theme)
```

I get this error message: [screenshot](https://i.imgur.com/R6y9dNT.png)
