### ISSUE TITLE
Support for external prop files

### ISSUE THREAD

**Issue by evanvin** [doczjs/docz#861]
My project has a lot of components, and one way to clean up all that proptype clutter was to externalize all the _types_ and _defaultProps_ in each component to one file.

**src/foo/FooComponent.jsx**
```jsx
import React from 'react';
import { fooComponentType, fooComponentDefault } from '../propTypes';

class FooComponent extends React.Component {
  render(){
    return <div>{this.props.name} - {this.props.age}</div>;
  }
}
...

FooComponent.displayName = 'FooComponent';

FooComponent.propTypes = {
  ...fooComponentType
};

FooComponent.defaultProps = {
  ..fooComponentDefault
};

```

**src/propTypes/index.js**
```jsx
export * from './types';
export * from './default';
```

**src/propTypes/types.js**
```jsx
import {
  number,
  string
} from 'prop-types';

export const fooComponentType = {
  name: string,
  age: number
};
```

**src/propTypes/defaults.js**
```jsx
export const fooComponentDefault = {
  name: 'Bill Nye',
  age: 63
};
```

This setup works for cleaning up my project, but Docz can't seem to find the props with this setup. Would this feature be hard to add?

**Comment by JiangWeixian** [comment]
any solution?

**Comment by klappy** [comment]
This appears to be a common request scattered in issues related to this style of setting propTypes not rendering.

**Comment by cjpablo92** [comment]
Is this in any build? i could find the reference. Im actually needing this feature too.
