### ISSUE TITLE
Playground breaks with template literals in child function

### ISSUE THREAD

**Issue by cdfa** [doczjs/docz#862]
## Bug Report
I get `SyntaxError: expected expression, got keyword 'var'" when using template literals.

**To Reproduce**
```
import styled from "styled-components";
import { Playground } from "docz";

<Playground>
    {() => {
		const i = styled.div``;
    }}
</Playground>
```

**Expected behavior**

Template literal works like in de [the spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_templates)

**Environment**

* OS: `4.19.36-1-MANJARO GNU/Linux`
* Node/npm version: Node `10.15.3`/NPM `6.4.1`

**Comment by mattietea** [comment]
did you find a workaround for this?

**Comment by cdfa** [comment]
Not really. You can manually desugar the template literals and turn it into a normal function cal, but then you're not really using template literals anymore.

**Comment by mattietea** [comment]
yeah, damn. react-live seems to work with template literals. https://codesandbox.io/s/jpkk6vjjow
