### ISSUE TITLE
[Feature? Bug?] Markdown without line wrapping

### ISSUE THREAD

**Issue by sw-yx** [doczjs/docz#865]
Currently, if i try to write this kind of long diagram in markdown, it shows nicely on github with left-right scrolling:

```

                               ┌────────────────────────────┐
                               │                            │
                               │  Current SFC architecture  │
                               │  (inspired by Vue-loader)  │
                               │                            │
                               └────────────────────────────┘
┌───────Webpack───────┐                                        ┌─────────Webpack──────────┐
│   inline modules    │                                        │       build output       │
│            ┌──────┐ │  ┌──────────────────┐                  │                  ┌──────┐│
│            │      │ │  │                  │                  │                  │      ││
│         ┌─▶│  JS  │─┼─▶│ componentWrapper │─────────┐        │               ┌─▶│  JS  ││
│ ┌─────┐ │  │      │ │  │                  │         │        │┌───────────┐  │  │      ││
│ │     │ │  └──────┘ │  └──────────────────┘         │        ││           │  │  └──────┘│
│ │ SFC │─┤           │                               └───────┬▶│  loaders  │──┤          │
│ │     │ │  ┌──────┐ │  ┌──────────────┐    ┌──────────────┐ │││           │  │  ┌──────┐│
│ └─────┘ │  │      │ │  │              │    │              │ ││└───────────┘  │  │      ││
│         └─▶│ CSS  │─┼─▶│ wrappedStyle │───▶│    postCSS   │─┘│               └─▶│ CSS  ││
│            │      │ │  │              │    │              │  │                  │      ││
│            └──────┘ │  └──────────────┘    └──────────────┘  │                  └──────┘│
└─────────────────────┘                                        └──────────────────────────┘
```

however, when i view it in docz, it does wordwrapping for me which i believe isnt the correct behavior:

![image](https://user-images.githubusercontent.com/6764957/57576907-91d31b00-7439-11e9-8fa8-faa1b6f20cae.png)

what do you think, should we turn off markdown word wrapping?

**Comment by patricksevat** [comment]
Hi @sw-yx ,

I think this might also be related to formatting done by Prettier, just like my issue earlier: https://github.com/pedronauck/docz/issues/813 .

I've done some very specific work on my issue, but I think it might be too specific. Did not receive any feedback on it either.

I could tackle both issues by adding a configuration option to bypass Prettier all together, was planning to do that today or tomorrow

**Comment by patricksevat** [comment]
Still not great, but better than before by bypassing Prettier formatting:
![image](https://user-images.githubusercontent.com/16444755/57651902-b4e30380-75ce-11e9-9c20-49b565e5fd68.png)

**Comment by sw-yx** [comment]
i dont think so, i have prettier enabled in VS Code and i just double checked and it is not screwed up when prettified.
