### ISSUE TITLE
Is there any support for createGlobalStyle from styled-components?

### ISSUE THREAD

**Issue by rafalpetryka** [doczjs/docz#867]
## Is there any support for createGlobalStyle from styled-components?

**Description**
Hi. In my project I've decided to use docz <3 styled-components and typescript. I've seen many examples which you added to this project. But I really don't, know how to use createGlobalStyle from styled-components in docz. I created sample global style to set default font for my app.
```typescript
import { createGlobalStyle } from 'styled-components';

export default createGlobalStyle`
  body {
    @import url('https://fonts.googleapis.com/css?family=Notable');
    font-family: 'Notable', sans-serif !important;
  }
`;
```
Then I add that style to index.tsx. 
```typescript
import GlobalStyles from './GlobalStyles';

ReactDOM.render(
  <>
    <GlobalStyles />
    // rest app
  </>,
  document.getElementById('root'),
);
```
Everything works in react app, but not in docz, because docz read only specific components. So I've decided to add ```<GlobalStyles/>``` to Playground. And it, works, but it is overrided by default font-family from docz-theme-default.
![image](https://user-images.githubusercontent.com/9085584/57583157-fdff5e80-74cd-11e9-8d37-197c87d39213.png)
So is there any possibility to use createGlobalStyle? If not, I would like to write that feature, but I would need information on how I can do it ;)

**Comment by rafalpetryka** [comment]
Hi @rakannimer any reason of close this issue. Maybe you do not wanna support for styled components? :)

**Comment by jesperorb** [comment]
Hi @rafalpetryka what version of docz are you on?

**Comment by rafalpetryka** [comment]
Currently ```1.3.2```
