### ISSUE TITLE
v1 doesn't scroll to top anymore

### ISSUE THREAD

**Issue by madou** [doczjs/docz#869]
## Bug Report

**Describe the bug**

In v0 when you navigated through the app it would scroll to top automatically on route change. It doesn't do that anymore.

**To Reproduce**

1. Go to any docz site
2. Scroll down
3. Navigate
4. Notice you won't be scrolled to the top of the new page

**Expected behavior**

Page is scrolled to top.

**Environment**

* OSX/Firefox

**Additional context/Screenshots**

![scroll-bug](https://user-images.githubusercontent.com/6801309/57607100-a506f780-75ad-11e9-8cfb-0031ee27b86f.gif)

**Comment by johnnorris** [comment]
This is causing us problems as well. Any update?

**Comment by corysimmons** [comment]
This is affecting almost every Docz site I've seen lately. I think it's because of a `@reach/router` bug https://github.com/reach/router/issues/242

**Comment by mattswart** [comment]
Has anyone found a minimal jank solution?

**Comment by johnnorris** [comment]
It's not great, but in our custom Docz theme we put this into one of the components:

```
componentDidMount() {
    window.scrollTo(0, 0);
}
```

Seems to work for us, but obvs a bit jank.

**Comment by corysimmons** [comment]
@rakannimer Was this fixed? In a specific commit/package version?
