### ISSUE TITLE
[v1.2.0] use local package ( yarn link || npm link), run docz:dev error

### ISSUE THREAD

**Issue by mizi-lin** [doczjs/docz#872]
## Bug Report

![image](https://user-images.githubusercontent.com/2802841/57677544-aaba1700-7659-11e9-922b-e060c698651a.png)

```mzmu``` is i use yarn link add local development package;

and use install mzmu is work

**Comment by draperunner** [comment]
Does your local package `mzmu` have a compile/build/transpile step? I guess you need to transpile your source code before importing it. A common pattern is having `mzmu/src/utils.ts`, and a build step that runs babel and typescript compilation so you end up with `mzmu/lib/utils.js`.

You could also try to configure the doczrc build setup to run your dependency through babel... and remember `typescript: true` in the config.

**Comment by amily4555** [comment]
because mzmu is local dev version, so not compile; and have been set typescript: true in my doczrc, but then not work 

@draperunner
