### ISSUE TITLE
How to include babel plugin 

### ISSUE THREAD

**Issue by pete-redmond-cko** [doczjs/docz#874]
## Question

How do I include a babel plugin in docz? 

**Description**

The component library I am building uses `babel-plugin-emotion`. When importing these components in `docz` it blows up saying with this error `Error: Component selectors can only be used in conjunction with babel-plugin-emotion.`

I have added 👇  to `doczrc.js` but it still doesnt work, am I missing something? 

```
modifyBabelRc: babelrc => {
    const newBabelRc = {
      ...babelrc,
      plugins: [...babelrc.plugins, require.resolve('babel-plugin-emotion')],
    };
    return newBabelRc;
  },
```

**Comment by pete-redmond-cko** [comment]
https://github.com/pedronauck/docz/issues/441 sounds similar

**Comment by draperunner** [comment]
I am trying to include `@babel/preset-env` in order to support browserslist, in order to support IE 11 (the vendors.[hash].js file includes arrow functions which is not supported on IE 11). 

But, this doesn't seem to do anything. 🤔 

```
modifyBabelRc: (babelRc) => {
        return {
            ...babelRc,
            presets: [
                ...babelRc.presets,
                [
                    '@babel/preset-env',
                    {
                        targets: {
                            browsers: [
                                'ie 11',
                            ],
                        },
                    },
                ],
            ],
        }
    },
```

**Comment by pete-redmond-cko** [comment]
@draperunner I got this working by deleting the `.docz` cache folder
