### ISSUE TITLE
<Props /> only working after changes to file

### ISSUE THREAD

**Issue by julians** [doczjs/docz#893]
## Bug Report

`<Props of={MyComponent} />` doesn’t render anything until I change and save the component‘s file. While this is annoying locally, it breaks the static build.

Happens with a clean npm project with only docs installed.

`index.mdx`:

```mdx
import Test from "./Test.js";
import { Props } from "docz";

# Yay

lorem ipsum huhuhu

<Test>yay</Test>

<Props of={Test} />
```

`Test.js`:

```js
import React from "react";
import PropTypes from "prop-types";

const Test = ({ children, className }) => {
  return <p className={className}>1 {children} 2</p>;
};

Test.propTypes = {
  /** Additional className for container */
  className: PropTypes.string
};

export default Test;
```

**Expected behavior**

Props table should render

**Environment**

* OS: OSX 10.14.5
* Node/npm version: v12.2.0

**Comment by klujanrosas** [comment]
@pedronauck here's a repo that reproduces this issue:
https://github.com/klujanrosas/docz-error-repro

Tested this on 
Node v10.12.0 - Linux PopOS 18.04 LTS

And on
Node v10.15.3 - Windows 10

**Comment by zicodeng** [comment]
Related: https://github.com/pedronauck/docz/issues/777

**Comment by ejuo** [comment]
@klujanrosas, 
Problem due to very strict filtering of component files on initial build. In watch mode only keys are compared. You need one of two things:
1. Move your source code to a subfolder, for example src/Button.js.
2. Overwrite [filterComponents](https://github.com/pedronauck/docz/issues/777#issuecomment-489541127).

**Comment by nathsimpson** [comment]
Happening for me as well :(

**Comment by brandonarbini** [comment]
@ejuo's comment worked for me in dev, but not for build. Super confused by this.

**Comment by jesperorb** [comment]
Does this refer to `v1` of docz?
