### ISSUE TITLE
Question: Showing a full source code of component

### ISSUE THREAD

**Issue by FredyC** [doczjs/docz#894]
## Question

Have a look at [current docs site](https://mobx-react.netlify.com/). There is an interactive MobX example made [as a component](https://github.com/mobxjs/mobx-react-docz/blob/1da502adaa9d6f27678116fc464dff9333e2d66b/content/examples/TodoList.tsx) and wrapped into `Playground`. Right below it is some copy of that source file. It's somewhat hard to maintain both versions if I need to change something there.

The current `Playground`'s function to show source code feels fairly useless as it shows only what's in the MDX, not the source of the component.

One way would be adding a link directly to GitHub source, but that's fairly awkward, I would like people to stay on the site.

So I am thinking if I can somehow prepare a plugin similar to the Playground, but it would have a tight connection to a source file and show it inline when the user toggles the button (or show it open initially).

**Comment by sonhanguyen** [comment]
it might be easier than you guys think:
1. Install `raw-loader`
2. Use it
```mdx
import source from '!raw-loader!test.mdx'
<editor>{ source }</editor>
```

**Comment by xaviergonz** [comment]
The only way I could make it work is like this

create a symbolic link to the source code file as ".txt"
```
import source from '!!raw-loader!whatever.txt' //the double !! at the beginning matter or else you will see the compiled code
<editor>{ source }</editor>
```

**Comment by sonhanguyen** [comment]
@xaviergonz yeah I don't know why I worked for me with just `!`, either webpack's behavior changed or I just forgot it. Anyway, if you already override the configured loader then there is no need to symlink.
