### ISSUE TITLE
Allow splitting props into groups 

### ISSUE THREAD

**Issue by droganov** [doczjs/docz#895]
The case:
I'm documenting tsx UI lib. In that lib, modules compose other modules, so do props:

```
export interface Props extends AtomProps {
  fitAll?: boolean;
  fitLeft?: boolean;
  fitRight?: boolean;
}
```

Docz `Props` component is actually able to understand `extends`, but I'd really love to split records visually and document the composition better.

**Comment by maryiam** [comment]
+1

**Comment by maryiam** [comment]
In the same context, I'm documenting TSX UI lib as well. I have a custom button that extends ` React.ButtonHTMLAttributes<HTMLButtonElement>` props. 

Docz props table contains now all props including ButtonHTMLAttributes (263 default HTML Button props like onClick, className, onSubmit..) which is very noisy and doesn't give clear visibility of my custom button props. 

I would like to be able at least to separate props or ideally have the possibility to hide the extended props. Is this possible?
![image](https://user-images.githubusercontent.com/7223718/65774019-bb1ceb00-e13d-11e9-8f65-8a8473105e7c.png)
