### ISSUE TITLE
Run docz without starting the browser

### ISSUE THREAD

**Issue by GabrielDuarteM** [doczjs/docz#898]
## Question

**Description**
Is there a way to start docz (e.g. running `docz dev`) without it automatically opening a browser window?

My usecase is that I'm making an electron app, and because it uses system apis I have to run docz inside an electron environment, otherwise, my components would crash when calling something electron-specific. That said, its pretty annoying in my case that `docz dev` automatically opens a new browser window, as I always have to close it.

`create-react-app` provides a way to do that if you set `BROWSER=none` on a `.env` file, but this unfortunately doesn't work on docz. 

Is there any way to do that?

**Comment by danielbayerlein** [comment]
PR: #891

**Comment by wldcordeiro** [comment]
Seriously or at least actually use our `base` so you don't open a useless page!
