### ISSUE TITLE
Playground doesn't work with responsive components

### ISSUE THREAD

**Issue by pieron187** [doczjs/docz#901]
## Bug Report

Docz Playground seems doesn't recognize media queries when you switch to smaller size devices (smartphone/tablet). It stays on the default screen size media query. The only way to get the component to display correctly is by scaling down the whole browser window. 

**To Reproduce**

1. Create a responsive component that looks different based on media queries
2. Resize the playground
3. The component stays as default size. 

Thanks for creating Docz - great work so far!

**Comment by zicodeng** [comment]
This is related to issue: https://github.com/pedronauck/docz/issues/789
