### ISSUE TITLE
Failed to compile: SyntaxError: unknown: Unterminated JSX contents (21:16)

### ISSUE THREAD

**Issue by akira-cn** [doczjs/docz#912]
## Bug Report

**Describe the bug**

When I use string template as props and the multiline texts contains empty line, it will cause compile errors.

**To Reproduce**

<SomeOfComponent someProps={`
line 1
line 2

line 4
`}></SomeOfComponent>

An empty line between line 2 and line 4.

```shell
Uncaught Error: Module build failed (from ./node_modules/@mdx-js/loader/index.js):
SyntaxError: unknown: Unterminated JSX contents (21:16)
```

**Comment by trainoasis** [comment]
This error spwns for me too, when just first installing and running the 

> yarn docz dev

 ERROR #11321  PLUGIN and then some issues with HTML closing tags etc.
(SyntaxError: unknown: Expected corresponding JSX closing tag for).

Any ideas?

**Comment by btilford** [comment]
Same. Not useful message or anything I can use to figure out what is going on.
