### ISSUE TITLE
can this library highlight/emphasize certain line numbers in mdx code block?

### ISSUE THREAD

**Issue by gcloeval** [doczjs/docz#913]
Hello, really enjoying this library, it is helping us a lot.

I would like to ask - is it possible to specify certain lines in code block to be empahsized?

We are not really sure where to look - in this link:
https://www.docz.site/docs/project-configuration#build-pipeline
It describes its possible to add various plugins:
- plugins, mdPlugins, hasPlugins
But it is confusing for beginners and doesnt have any examples? Can this be accomplished with one of the plugins?

For a quick example, as in the following doc - notice how lines 9 - 12 are highlighted - we would like to use such a feature when writing a bit more detailed documentation guide for some of the components?

https://reactjs.org/docs/state-and-lifecycle.html

Cheers!

**Comment by gcloeval** [comment]
After doing some more research, it seems that in the example page I linked they use this syntax {start,end} to specify which lines to highlight:

That looks really awesome and simple, is it possible to do something like that?

```js{8-11}
function tick() {
  const element = (
    <div>
      <h1>Hello, world!</h1>
      <h2>It is {new Date().toLocaleTimeString()}.</h2>
    </div>
  );
  ReactDOM.render(
    element,
    document.getElementById('root')
  );
}

setInterval(tick, 1000);
```

**Comment by jesperorb** [comment]
ReactJS documentation uses `gatsby` with `prism` as code highlighter, the same as  `docz` in v2. So it seems feasible that we could add the same plugin that they are using to `gatsby-theme-docz` or otherwise mimic that behavior: [**gatsby-remark-prismjs**](https://www.gatsbyjs.org/packages/gatsby-remark-prismjs/)

If someone want to take a shot at it, open a PR and I'd be glad to help :)

**Comment by rakannimer** [comment]
It's possible to do that with docz and gatsby-remark-vscode, checkout this example to see how to use it in your project : https://github.com/doczjs/docz/tree/master/examples/with-gatsby-remark-vscode

And this section for lines highlighting : https://github.com/andrewbranch/gatsby-remark-vscode#line-highlighting
