### ISSUE TITLE
Props does not pick default value with typescript

### ISSUE THREAD

**Issue by thomasthiebaud** [doczjs/docz#926]
## Bug Report

I have this super tiny component that accepts an optional `theme` property. In case the property is not specified, I would like to default it to `light`.

```
export interface LogoProps {
  theme?: 'dark' | 'light';
}

const Logo: SFC<LogoProps> = ({ theme = 'light' }) => (/** some code here */);
```

Using

```
<Props of={Logo} />
```

I get

<img width="784" alt="Screenshot 2019-06-21 at 09 42 01" src="https://user-images.githubusercontent.com/3715715/59906385-eb4f4200-9408-11e9-8c18-cfeaa619fc82.png">

The same component using Proptypes give me

<img width="869" alt="Screenshot 2019-06-21 at 09 42 07" src="https://user-images.githubusercontent.com/3715715/59906413-fe621200-9408-11e9-8ae0-f453f87a6ccb.png">

Can we achieve the same behavior using typescript?

**Environment**

* OS: OSX 10.14.5
* Node/npm version: 10.15.3/6.9.0

**Comment by zicodeng** [comment]
Related: https://github.com/pedronauck/docz/issues/670

**Comment by snokier** [comment]
so is there any solution?

**Comment by papeloto** [comment]
Same issue here
