### ISSUE TITLE
External link in menu

### ISSUE THREAD

**Issue by xaviergonz** [doczjs/docz#927]
## Question

Is it possible to add external links to the side menu? (e.g to a gitub repository)

**Comment by zicodeng** [comment]
As far as I know, this is not possible with the default theme, but you can customize it. See docs here: https://www.docz.site/docs/components-api. The API is fairly straightforward and easy to work with. I used to create my own theme: http://docz-theme-ztopia.surge.sh/

**Comment by julians** [comment]
Yes, you can do it like this:

```
menu: [
    'Nav 1',
    'Nav 2',
    {name: '🔗 Github', href: 'https://github.com/'},
  ],
```

**Comment by darrenhaken** [comment]
Also having this issue, this seems to be a regression since v1. @pedronauck will this be introduced back into v2?

**Comment by bitworking** [comment]
{name: '🔗 Github', href: 'https://github.com/'}

Does not work for me. I get a non clickable menu item with an arrow down icon.

**Comment by jamesmfriedman** [comment]
Same issue for me

**Comment by jamesmfriedman** [comment]
For a little more information, it appears to render a link, it just only inserts '/'. 
![image](https://user-images.githubusercontent.com/975256/83213754-ef173880-a130-11ea-825d-57b34df77082.png)

**Comment by vilic** [comment]
Found a workaround: `{name: 'foo', route: 'https://makeflow.github.io/boring-router'}`
