### ISSUE TITLE
Playground with all library components

### ISSUE THREAD

**Issue by theo-mesnil** [doczjs/docz#929]
## Question

**How can add all my library components available on playground ?**

Hi ! 

I wan't to add access on all my library components (Button, Tabs, Tag...) on Playground to used it without import all on my doc.mdx

Thanks !

**Comment by theo-mesnil** [comment]
Up :)

**Comment by rakannimer** [comment]
Hello,

How would you like to add your library components to Playground ? Why are you looking to avoid importing them ?

**Comment by theo-mesnil** [comment]
Because i want all people testing the library to use any components :)

**Comment by rakannimer** [comment]
Will something like the below work ? 

```mdx

import { Playground, Props } from 'docz'
import Components from './'

## Playground
<Playground>
  <Components.Alert>Some message</Components.Alert>
</Playground>

```

**Comment by theo-mesnil** [comment]
Yes this can be a solution but i would like to use simply <Alert> on my Playground :)

**Comment by rakannimer** [comment]
I can't think of a way to do this without changing the docz source code. 

Happy to review any PR that would do this.
