### ISSUE TITLE
Runtime errors since v1.1.0

### ISSUE THREAD

**Issue by kirakik** [doczjs/docz#931]
## Bug Report

I'm upgrading from v0.12, and I've encountered an issue in v1.1.0 and v1.2.0.

The command compiles fine, but at runtime, I get this error:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

I know there's another issue addressing a similar issue (#109), but they seem unrelated, as this issue dates from close to a year, and on my side v1.0.0 works fine.

While trying to debug, I noticed `AsyncRoute.tsx` uses lodash's `_.get` wrong:

https://github.com/pedronauck/docz/blob/df6ffd5b435e8a6cebcf1faef94f423e02d9365d/core/docz/src/components/AsyncRoute.tsx#L18

Indeed, from the [lodash docs](https://lodash.com/docs/#get), the path should be second argument, and the object the first. I haven't been able to verify whether this is the cause of the issue I'm seeing.

**To Reproduce**

I tried reproducing the issue on a brand new CRA app, but I got other issues (maybe due to CRA 3.0.0?)

**Expected behavior**

No runtime errors

**Environment**

* OS: MacOS 10.14
* Node/npm version: Node v10.12.0, npm 6.4.1

**Comment by draperunner** [comment]
Hi! Try `rm -rf .docz` and then `docz dev` again. Worked for me!

**Comment by ddelbondio** [comment]
I had the same problem and it was caused by docz-core and docz-theme-default using different versions of docz. You can confirm this by running `yarn why docz`. 
Running `yarn upgrade docz-theme-default` fixed it for me.

**Comment by jesperorb** [comment]
Hi @kirakik have you tried following @draperunner and @ddelbondio suggestions? Is it still not working?

**Comment by canyavall** [comment]
hi there!
In our company we are having this issue.
I tried what was already mentioned here (remove docz folder, check I have the updated libraries) and I've tried reinstalling the whole node_modules (just in case some dependencies would be the issue.

Still could not fix it... It happens even if I have only the <playground> component and one simple string inside it.

Those are the curernt versions of the libraries that we are using:
    "docz": "^2.0.0-rc.66",
    "docz-theme-default": "^1.2.0",

**Comment by rakannimer** [comment]
Hey @canyavall 

`docz-theme-default` is no longer a required dependency for `docz`.

Could you try : 

```sh
yarn remove docz-theme-default && rm -rf yarn.lock .docz node_modules && yarn install
```

If that doesn't fix it could you try to make a small repro of the problem and share a repo to allow us to resolve this issue quicker ?

**Comment by canyavall** [comment]
It is fixed, thank you very much!!!
