### ISSUE TITLE
Bug paragraph inside div

### ISSUE THREAD

**Issue by adrianoresende** [doczjs/docz#932]
## Bug Report

I get an error when I put a paragraph inside `div` with the format HTML

MDX:
```
---
name: Tipografias
route: /tipografias
menu: Estilos
---

# Title
Lorem Ipsum

## Fonts

<div className="page-typograph">
  <h1>H1 Display</h1>
  <h2>H2 Display</h2>
  <h3>H3 Display</h3>

  <p>Parágrafo normal</p>
</div>
```

The error:
`SyntaxError: unknown: Expected corresponding JSX closing tag for <div> (15:0)`

**Environment**

* OS: OSX 10.14.5
* Node/npm version: v11.3.0/6.8.0

**Additional context/Screenshots**

![image](https://user-images.githubusercontent.com/798755/60311933-b888da80-992f-11e9-9780-1c2439f23a78.png)

**Comment by handfulglitter** [comment]
I encountered the same problem. If I change the @mdx-js/react package to version 1.0.21 the <p> tag inside a <div> will work. Will test if everything is ok with the version upgrade and will make a pull request for it.

**Comment by handfulglitter** [comment]
I have encountered the same problem. I changed the version of @mdx-js/react to a newer version and this seems to solve the problem. Will make a pull request for this change.
