### ISSUE TITLE
Docz is compiling entire project with webpack. when it should only compile files that are imported

### ISSUE THREAD

**Issue by hannadrehman** [doczjs/docz#933]
## Bug Report

**Describe the bug**

I have a react monorepo project powered by lerna, where there are multiple packages build by single webpack config. 

one of the package is UI-Components which is a common repo for all re usable components.
and i am using `antd` as base Ui library. and i wanted to document these components.
all of these components are independent.
 
i have noticed that docz when started is compiling all the files and packages because of which build is failing and i get some useless errors. 

is there a way to configure docz to only compile files that are imported in mdx files. since it is using webpack it should follow the dependency graph simply following the imports. but in my case it is compiling files which are no were related to the component. and i am getting useles runtime errors. 

**Environment**

* OS: OSX 10.14.4
* Node/npm version: v10.0.0/ v5.6.0

**Comment by zicodeng** [comment]
Can you provide your docz config? thanks

**Comment by rakannimer** [comment]
You can use

`files` to supply an array of file glob patterns to compile
`src` to point to a specific to compile only
`ignore` to supply an array of file glob patterns to ignore
