### ISSUE TITLE
Including global modules

### ISSUE THREAD

**Issue by DanielNetzer** [doczjs/docz#936]
I was wondering if it's possible to add a global module to the application?

The reason i'm asking is because i'm trying to add stencil components to the docz application but without success.
I want to achieve something like this
https://stenciljs.com/docs/react

**Comment by zicodeng** [comment]
Maybe try wrap all your component in a HoC in such as way that when HoC is mounted, you create side effects such as the one in Stencil? just a thought, not sure if I fully understand your situation :)
