### ISSUE TITLE
TypeScript, Default exports not working

### ISSUE THREAD

**Issue by jleck** [doczjs/docz#941]
## Question

I'm quite sure why (could it be something to do synthetic exports?), but anytime I import typescript files with a default export, I get "...does not contain a default export". My files generally end with:

```
export default Index;
```

Or something similar. Works fine through create react app, so I'm not really sure what's causing it.

**Comment by therealparmesh** [comment]
+1

I'm noticing the same exact issue.

**Comment by therealparmesh** [comment]
I wonder if https://github.com/babel/babel/pull/10019 has something to do with it.

**Comment by lbucio** [comment]
I had the same issue, looks like it should be resolved now! 🎉  https://github.com/gatsbyjs/gatsby/issues/15423

**Comment by gogoyqj** [comment]
well...just add code below to docz.js

```js
filterComponents: files => files.filter(filepath => /\/[A-Z]\w*\.(js|jsx|ts|tsx)$/.test(filepath))
```

i just do know why in 'docz-core/dist/index.js' line 1854

```js
const files = await glob(pattern, {
    cwd: root
  });
  const filtered = filterComponents ? filterComponents(files) : files;
  const metadata = await docgen(filtered, config);
```

default `filterComponents` is

```js
files => files.filter(filepath => /\/[A-Z]\w*\.(js|jsx|ts|tsx)$/.test(filepath))
```

...
