### ISSUE TITLE
the props of Components using react portal not render

### ISSUE THREAD

**Issue by zww-v5** [doczjs/docz#942]
The props of Components using react portal not render, but other componet props can render well.

Here is my component content:
![image](https://user-images.githubusercontent.com/9295948/60696798-dbac1f00-9f19-11e9-96f9-bbc70da39917.png)

If I change the component like this, it works well.
![image](https://user-images.githubusercontent.com/9295948/60696832-0c8c5400-9f1a-11e9-8b9e-86d75915f032.png)

But in this component, I have to use the react portal. Can anyone tell me how to fix this problem?

**Comment by zicodeng** [comment]
I would suggest wrap the component in a HoC and define props in the wrapped component. Then you can do

```
<Props of={InnerTest} />
```
