### ISSUE TITLE
Best way to load custom local fonts

### ISSUE THREAD

**Issue by Reklino** [doczjs/docz#944]
## What's the best way to load custom local fonts?

**Description**
I have 2 fonts that I need to load into the project that will be hosted statically with the documentation. I've tried adding it in a `style` tag that loads the fonts via `@font-face` in a custom `index.html` that's loaded in via the `indexHtml` config prop, but I can't seem to find a path that will work.

Any advice?

**Comment by zicodeng** [comment]
Have you tried something like this?

```
...rest config...
htmlContext: {
  head: {
    raw: [
      `<style>${fs.readFileSync(process.cwd() + '/src/styles/fonts.css')}</style>`
    ],
  },
},
...rest config...
```

**Comment by Reklino** [comment]
@zicodeng I couldn't find `htmlContext` as an available config property. Maybe it was in 1.0?

For anyone looking to do this in `2.0`, here's how I went about it. Would love other advice or critique on this approach!

1. In the root of your project, create a file at `src/gatsby-theme-docz/wrapper.js`. This utilizes component shadowing, and will override the existing `wrapper.js` file.
2. In the contents of `wrapper.js`, include a basic component that just passes down children:
```
import React from 'react'

export default ({ children }) => (
  <Wrapper>
    { children }
  </Wrapper>
)
```
3. Create a global css file in which load in your custom fonts, and import it in your `wrapper.js`
```
import "./styles/global.css"
import React from 'react'

...
```

I'm using `@font-face` and pointing a set of fonts inside of the project.

Hope this helps someone!

**Comment by zicodeng** [comment]
@Reklino mb, I didn't know you are working with v2. I haven't tried v2 yet, but thanks for sharing your solution here!

**Comment by sag1v** [comment]
@rakannimer Is this the idiomatic way of doing that? What about injecting scripts (like google analytics), we used to do it inside `htmlContext` but where can we do it now?
I know that gatsby uses `react-helmet` for stuff like that but where do we put it if any?
