### ISSUE TITLE
Using README.md as Root page

### ISSUE THREAD

**Issue by rfestag** [doczjs/docz#945]
## Question

Is there a recommended way to using the README.md as the root page? The best workaround I have so far is to do something like this:

```
---
route: /
---
import Readme from './README.md';

<Readme />
```

This has a few downsides though:
1. I have a separate file just to point to the root
2. It adds the README to the left side navigation, which I don't necessarily want. 

Is there some way to tell docz what to use as the root page (or to automatically route / to some specific first page)?

**Comment by bryanberger** [comment]
@rfestag We did something similar.

```
---
name: Home
route: /
layout: 'fullpage'
---
```

To create an `index` route with links on it. `layout: fullpage` essentially hides the Sidebar on that route.

**Comment by jstacoder** [comment]
@rfestag Another solution is to set your frontmatter like this:

```
—-
  route: /
  menu: 
—-
```
Setting menu to an empty value will remove the entry from your sidebar.

**Comment by rakannimer** [comment]
Hey,

Thanks @bryanberger and @jstacoder for your recommended solutions, both should work ! 

We also have in our backlog a task to automatically add first markdown file encountered as the default route if no default route is specified. That should also help the use-case when you just want docz to automatically figure out what to show.

**Comment by jesperorb** [comment]
Done @rakannimer ?
https://github.com/doczjs/docz/commit/05d7ecced4b9ccc9c1e3164080a0eddf71708846

**Comment by rakannimer** [comment]
@jesperorb Yep ! 
The first indexed `mdx?` file will be used as the root route. 
Going to close this, if someone is still facing problems please open a new issue.
