### ISSUE TITLE
Custom theme routing doesn't re-render page.

### ISSUE THREAD

**Issue by Reklino** [doczjs/docz#951]
## Bug Report

**Describe the bug**

I followed the guidance in the documentation around creating a custom theme, and the routing doesn't seem to be working as intended. When the route changes, the page doesn't re-render. Browser refreshes are the only thing that will cause a re-render.

This is the code I'm using in my custom theme.
```
import React from 'react'
import { useMenus, Link } from 'docz'

export const Menu = () => {
  const menus = useMenus()
  return (
    <ul>
      {menus.map(menu => (
        <li key={menu.id}>
          <Link to={menu.route}>{menu.name}</Link>
        </li>
      ))}
    </ul>
  )
}
```

**To Reproduce**

1. Follow the instructions here: https://www.docz.site/docs/creating-themes#using-documents-settings
2. Run project
3. Click on the links in the menu

**Expected behavior**

I expected the page to re-render when clicking on the routes.

**Environment**

* OS: 10.14.4

**Comment by zicodeng** [comment]
Interesting...I did the exact same thing, and it works as expected for my custom theme. You can see it here: https://github.com/zicodeng/docz-theme-ztopia/blob/master/src/components/Sidebar/components/MenuItem.tsx

**Comment by theo-mesnil** [comment]
I have the same issue.
