### ISSUE TITLE
`Unexpected token var` error when using @emotion/styled to style components in inlined functions

### ISSUE THREAD

**Issue by aryzing** [doczjs/docz#954]
## Bug Report
`Unexpected token var` error inside the `Playground` sandbox when using `@emotion/styled` to style components in inlined functions

At times, when I want to illustrate complex operations or maintain state, I'll define an inline function like so

```jsx
<Playground>
  <div>
    {(() => {
      // perform logic, keep state, or other complex operations
      return (
        <div>Hello World!</div>
      )
    })()}
  </div>
</Playground>
```

**To Reproduce**

When using the above pattern while using `styled` from `@emotion/styled` as below, I'll get the error.

```jsx
<Playground>
  <div>
    {(() => {
      const MyStyledDiv = styled.div`font-family: monospace;`;
      return (
        <MyStyledDiv>Hello World!</MyStyledDiv>
      )
    })()}
  </div>
</Playground>
```

When the `MyStyledDiv` component is defined in another file and then imported into the README.mdx, it works just fine

[Repro repo link](https://github.com/aryzing/docz-repro-emotion-styled)

**Expected behavior**

Should work as expected, no error thrown.

**Environment**

* OS: Ubuntu 18.04
* Node/npm version: 11.10.1 / 6.7.0

**Comment by pkrawc** [comment]
I'm getting this as well with `styled-components`

**Comment by pedronauck** [comment]
Hi guys, sorry the too late response, I was on vacation so I couldn't see any issues until now. I'll try to figure out this and fix in order to launch in the stable v2 🙏
