### ISSUE TITLE
Docz v2 build error

### ISSUE THREAD

**Issue by NexxLuo** [doczjs/docz#957]
## Bug Report

**Describe the bug**
I try to migrate 1.2.0 to 2.0 . 
But get many error ,such as the image below .
  
**Environment**

* OS:windows 10
* Node/npm version: 10.15.1/6.4.1
* Docz :  2.0.0-rc.1

**Additional context/Screenshots** 

![QQ图片20190719080348](https://user-images.githubusercontent.com/18549980/61500012-e4155700-a9fb-11e9-86fc-846bc8a8b288.png)

![2](https://user-images.githubusercontent.com/18549980/61500014-e8417480-a9fb-11e9-8054-e3350a703020.png)

```javascript
//gatsby-config.js
module.exports = {
    plugins: ['gatsby-theme-docz']
  }

//doczrc.js 
import { css } from "docz-plugin-css";
export default {
  title: "Tablex",
  port: 8888,
  typescript: false,
  plugins: [
    css({
      preprocessor: "postcss"
    }),
    css({
      preprocessor: "less",
      cssmodules: true
    })
  ],
  filterComponents: files => {
    return files.filter(
      filepath => /[w-]*.(js|jsx|ts|tsx)$/.test(filepath) 
    );
  },
  menu: ["Intro"]
};

**Comment by pedronauck** [comment]
Hi guys, sorry the too late response, I was on vacation so I couldn't see any issues until now. I'll try to figure out this and fix in order to launch in the stable v2 🙏

**Comment by rakannimer** [comment]
Hey @NexxLuo,

Is this still happening in the latest `docz` version on the `next` tag ? 

If it is, please could you provide the MDX file that is making `docz` throw ?

**Comment by NexxLuo** [comment]
It`is not happen. But get some other issues ,maybe I need to wait for DOCZ v2  stable version.
