### ISSUE TITLE
Build errors in 2.0.0-rc.1 - path aliasing and SCSS imports

### ISSUE THREAD

**Issue by sashafklein** [doczjs/docz#958]
## Bug Report

I just tried to migrate to 2.0.0-rc.1 while setting up 1.0.?, because the former version [wasn't rendering props](https://github.com/pedronauck/docz/issues/777) at all. 

*Note, my app is built using create-react-app, with limited structural changes, other than adding TypeScript support.*

On running `docs dev` I immediately bumped into a host of issues. 

The first has to do with path aliasing. I set my app source to be `src/` for absolute aliasing, so I can import `components/SomeComponent` to get to `./src/components/SomeComponent.js` directly. This is set as a `baseUrl` in `tsconfig.json` (my app uses both JS and TypeScript, and it works to set it there). 

I get these errors running `yarn docs dev`:

```
These dependencies were not found:
⠀
* redux/actions in ../src/components/ScenarioChooser/index.js
* redux/thunks in ../src/components/ScenarioChooser/index.js
* utils/cn in ../src/components/ScenarioChooser/index.js
⠀
To install them, you can run: npm install --save redux/actions redux/thunks utils/cn
```

(To clarify, these files are located in, for example `PROJECT_ROOT/src/redux/actions.js`, so it appears to be the absolute path resolution, aka path aliasing, that isn't working.)

Below that, I also see this issue, related to SCSS imports:

```
ERROR in ../src/components/ScenarioChooser/ScenarioChooser.scss 1:0
Module parse failed: Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
> @import 'styles/_sass-includes.scss';
|
| .scenario-chooser {
 @ ../src/components/ScenarioChooser/index.js 32:0-32
 @ ../src/components/ScenarioChooser/index.mdx
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi ./node_modules/event-source-polyfill/src/eventsource.js ./node_modules/webpack-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
```

(Note that the `styles/...` path is also absolute, starting from `PROJECT_ROOT/src`. I'm not sure if this absolute path will be an issue, once the loader error is resolved). 

I *did* update my `.doczrc.js` file to use `onCreateWebpackConfig` instead of `modifyBundlerConfig`. Did I have to do something other than change the key? Here's how I'm using it (this worked as `modifyBundlerConfig` in the previous docz version):

```
  onCreateWebpackConfig: bundlerConfig => {
    bundlerConfig.module.rules.push({
      test: /.s?css$/,
      use: ['style-loader', 'css-loader', 'sass-loader']
    });
    return bundlerConfig;
  },
```

**Environment**

* OS: OSX 10.14.5
* Node/npm version: v10.15.0

**Comment by pedronauck** [comment]
Hi guys, sorry the too late response, I was on vacation so I couldn't see any issues until now. I'll try to figure out this and fix in order to launch in the stable v2 🙏
