### ISSUE TITLE
v2: How to migrate indexHtml

### ISSUE THREAD

**Issue by draperunner** [doczjs/docz#960]
## Question

I am using a custom index.html in my app, and see that the `indexHtml` property has been removed. How can I still be using a custom index.html file in v2?

```
indexHtml: 'theme/index.html',
```

**Comment by cdaringe** [comment]
hey all. not sure why this was closed--the migration guide does not discuss this.  @draperunner, did you solve this?  @rakannimer, do you feel it's covered elsewhere?

**Comment by rakannimer** [comment]
Hey, the indexHtml property was mostly used to put some metadata in the page's head tag. 

You can do that using Gatsby theme shadowing as shown here : https://www.docz.site/docs/add-favicon-and-metadata

Is there something else you're trying to do with it ?

**Comment by cdaringe** [comment]
Greetings!  Ya I need to slap in a few extra Script tags globally.  I'm not clear on what yet, but there's probably a Gatsby API I need to hook into now?

**Comment by rakannimer** [comment]
Yep, you will need to shadow the wrapper component and use react-helmet-async to include your scripts as shown here : https://www.docz.site/docs/add-favicon-and-metadata

**Comment by jwdinker** [comment]
@rakannimer I have copied and pasted the example from the documentation and added an apple maps script tag and it isn't showing up in the head tag.  Any suggestions?

**Comment by jwdinker** [comment]
@rakannimer is it not possible to add scripts to the <head/>?

**Comment by jwdinker** [comment]
looks like my issue is with helmet...if you are dependent upon a global like stripe, google maps, etc and you are using helmet you have to set a listener for when the script loads...

https://github.com/nfl/react-helmet/issues/146

**Comment by rakannimer** [comment]
I guess you could also use something like [react-load-script](https://www.npmjs.com/package/react-load-script) to listen to the script loading and react when it happens.

**Comment by jwdinker** [comment]
@rakannimer i had done that originally.  Unfortunately, I'm still running into the same problem I did with Storybook - clicking on the different links in the sidebar rerenders the whole component tree including the wrapper.  

I am using a MapkitJS wrapper to authorize my mapkit token once...so the consequence of a rerender of the wrapper forces all subsequent map loads to fail.  Is the intended behavior of the wrapper to only load once?
