### ISSUE TITLE
v2: Invalid prop `css` in console

### ISSUE THREAD

**Issue by Reklino** [doczjs/docz#965]
## Bug Report

**Describe the bug**

I'm seeing some default styling missing (mainly fonts).

I'm getting the console error:
```
index.js:2177 Warning: Invalid prop `css` supplied to `React.Fragment`. React.Fragment can only have `key` and `children`
```

**To Reproduce**

1. Install 2.0 and run dev

**Environment**

* OS: [e.g. OSX 10.13.4]

**Comment by homejames203** [comment]
I'm seeing the same issue in 2.0.0-rc.1 - Don't really understand why though. The warning is complaining about [this line](https://github.com/pedronauck/docz/blob/master/core/gatsby-theme-docz/src/components/NavLink/index.js#L25) however no css prop is being supplied?

**Comment by Clarity-89** [comment]
Having the same issue with a newly setup project.

**Comment by Clarity-89** [comment]
Just installed `2.0.0-rc.40` and still see the same issue. Has the fix been included in the release?

**Comment by rakannimer** [comment]
Hey @Clarity-89,

I'm not sure what the problem is yet.

Could you provide steps to reproduce the problem or a repo ?

**Comment by Clarity-89** [comment]
@rakannimer all I'm doing is setting up a new project from scratch and add a few components to the packages. I'll try to make a sample repo later today.

**Comment by Clarity-89** [comment]
@rakannimer after spending half a weekend on it, couldn't reproduce it in a completely new project. Must have been something related to migrating old components from docz 0.x

**Comment by rakannimer** [comment]
Thanks @Clarity-89 for putting in the time.

I'll keep this issue open in case someone is able to provide a repro later.

Cheers !
