### ISSUE TITLE
gatsby-config.js is not being read

### ISSUE THREAD

**Issue by Bluesmile82** [doczjs/docz#975]
## Question

I'm trying to migrate from Docz 0.13 to 2.0.0 and I need some alias on my configuration. I'm trying to use some gatsby plugin: gatsby-plugin-alias-imports.
The gatsby config file doesn't seem to be accessed. 

in package.json:

```
  "devDependencies": {
    "docz": "latest",
    "docz-theme-default": "^1.2.0",
     ...
  }
  ...
  "dependencies": {
    "gatsby-plugin-alias-imports": "^1.0.5",
    ...
```
in gatsby-config.js: (at the root of the project in the same level as doczrc.js)

```
const path = require('path')

const srcPath = path.join(__dirname, '..', 'scripts');

module.exports = {
  siteMetadata: {
    title: 'Trase documentation',
  },
  plugins: [
    {
      resolve: `gatsby-plugin-alias-imports`,
      options: {
        alias: {
          'react-components': path.resolve(srcPath, 'react-components'),
        },
        extensions: ['js', 'jsx']
      }
    }
  ]
}
```
in doczrc.js:

```
export default {
  files: '**/*.{md,markdown,mdx}',
  dest: './docs/dist',
  title: 'Trase',
  public: './public/docs',
  themeConfig: {
    colors: {
      primary: '#34444C',
      sidebarBg: '#fff0c2'
    }
  },
};

```

**Description**

My component files cant be resolved as they are linked by webpack aliases. Before the configuration was working as I had copied the webpack config and used it for docz.

**Comment by p77u4n** [comment]
You should put your custom webpack config in gatsby-node.js in your project root folder, and export a function named 'onCreateWebpackConfig' to popularize your custom config

**Comment by Bluesmile82** [comment]
I also tried with the gatsby-node.js. Without luck: 

```
import merge from 'webpack-merge';
import webpackConfig from './config/webpack.config';

exports.onCreateWebpackConfig = ({ getConfig, actions }) => {
  actions.setWebpackConfig(
    merge(getConfig, {
      resolve: webpackConfig.resolve,
      module: webpackConfig.module
    }),
  );
}
```

**Comment by Bluesmile82** [comment]
Actually with the gatsby-node.js I get this error:

```
TypeError: Cannot read property 'originalSource' of undefined
    at getSourceById (/frontend/node_modules/react-dev-utils/evalSourceMapMiddleware.js:18:17)
```

**Comment by rakannimer** [comment]
Could you try again with latest rc ?

**Comment by rakannimer** [comment]
This should be fixed. You can see a working webpack-alias example here : (https://github.com/doczjs/docz/tree/master/examples/webpack-alias)
