### ISSUE TITLE
Can't use `useStaticQuery` or <StaticQuery>

### ISSUE THREAD

**Issue by wcastand** [doczjs/docz#976]
## Bug Report

**Describe the bug**
When i try to use `useStaticQuery` i get this error:
`Error: The result of this StaticQuery could not be fetched.`

I tried with `<StaticQuery>` and it's loading forever and never receiving the data either.

**To Reproduce**

I created a little repo that failing for me:

https://github.com/wcastand/docz-repro/tree/master

just need to yarn/npm install and then `yarn dev` and go to `http://localhost:3000`, should see the error.

**Expected behavior**

I should get the result from Gatsby Static query

**Comment by jstacoder** [comment]
I am also having mixed results when using components that internally use useStaticQuery Inside of mdx files, I have one that works, and one that doesn’t, and the second one gives this same error `the result of This static query cannot be fetched`

**Comment by jesperorb** [comment]
The limitation of `useStaticQuery` is that you can only use it once per file. [source](https://github.com/gatsbyjs/gatsby/issues/17731#issuecomment-532977522) Internally in the `Layout`-component, which is the whole wrapper for the page, the query `useDbQuery` is called which runs `useStaticQuery`. I don't know how the `.mdx` is converted and used in _docz_ but judging by the error it seems like it is being treated as being the same file as the `Layout`-component.

@jstacoder you said you had a component that worked with `useStaticQuery`, could you share it so we could try to figure out why that one works and other doesn't?

**Comment by jstacoder** [comment]
hmmm now that im looking at it more closely its even stranger, it actually works when i run gatsby develop, but when i do gatsby build the build completes that components no longer renders. 

here is the one that works, but now i see only on the dev server: 

https://github.com/jstacoder/jstacoder.github.io/blob/develop/src/components/component-props.jsx

its using gatsby-transformer-react-docgen and react-propstable to create a table of a components props, using the static query to grab the prop data. 

its used in: https://github.com/jstacoder/jstacoder.github.io/blob/develop/src/components/alert/Alert.mdx

**Comment by jstacoder** [comment]
ahhh, its the layout component, i am overriding it in that mdx file

**Comment by jesperorb** [comment]
> ahhh, its the layout component, i am overriding it in that mdx file

So the one working is the one where you are overriding and therefore not calling the static query twice because your are calling one query in your overriding component?

**Comment by jstacoder** [comment]
@jesperorb yea, the component that works (ie: the mdx page using a static query) is overridding the docz layout that uses its own static query, but now i realize that it only actually works using `gatsby develop` but if i do `gatsby build` no static queries work in mdx

**Comment by jesperorb** [comment]
Alright, it is a known limitation in gatsby so I am not sure what we can actually do about it? We should be able to override it if we want, like you were trying with your own `Layout`-component. Maybe we can look into if we can solve the conflicting queries when the page is being parsed?

Either way it should be documented somewhere in the docs.

**Comment by wcastand** [comment]
Hello thank for looking in to it :)
If I understood the conversation correctly. Since Docz is already doing a StaticQuery, we can't do one too since Gatsby is limited to one Static query by pages?

**Comment by jesperorb** [comment]
@wcastand Yes, I think that is the case.

**Comment by sh0rez** [comment]
Could docz expose an own hook that mimics the same behaviour by using the one static query it already does?
