### ISSUE TITLE
v2: Typescript example couldn't find .tsx files

### ISSUE THREAD

**Issue by matepapp** [doczjs/docz#977]
## Bug Report

**Describe the bug**
The typescript example project crashes when it tries to load `.tsx` files. Found a similar issue #422 but that solution is already provided in `doczrc.js` so it should work properly. 🤔 

**To Reproduce**

1. Copy the typescript example from the docz repository
2. Extend `tsconfig.json`
3. Install dependencies
4. run `yarn dev` or `docz dev`

```shell
...
warning  in ../src/components/Alert.mdx

"export 'Alert' was not found in './Alert'
⠀
warning  in ../src/components/Button.mdx
⠀
"export 'Button' was not found in './Button'
...
```

**Expected behavior**

The project build successfully.

**Environment**

* OS: macOS 10.14.6 Mojave
* Node/npm version: Node 10.16.0, npm 6.9.0

**Additional context/Screenshots**

My `tsconfig.json`

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es2017",
    "module": "es2015",
    "moduleResolution": "node",
    "inlineSourceMap": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "jsx": "react",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "traceResolution": false,
    "listEmittedFiles": false,
    "listFiles": false,
    "pretty": true,
    "lib": ["es2017", "dom"],
    "outDir": "dist",
    "rootDir": "src",
    "typeRoots": ["../../node_modules/@types", "node_modules/@types"]
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules/**"]
}
```

**Comment by keisans** [comment]
I'm also seeing this issue

**Comment by rakannimer** [comment]
Hey,

This issue should be fixed. Can you give another try to the typescript example (`create-docz-app my-docz-app --example typescript`) 

Feel free to re-open if it happens again
