### ISSUE TITLE
Documentation for customizing theme for v1 is missing

### ISSUE THREAD

**Issue by Okazari** [doczjs/docz#978]
## Bug Report

**Describe the bug**
There is no more doc to v1 for creating theme

**To Reproduce**

1. Go to https://www.docz.site/docs/creating-your-themes

**Expected behavior**

There is no more docs link to the v1 of docz. I'm currently using it, i can't afford to migrate right now (i have some webpack configurations that seems hard to migrate in a short time).
I juste need to intregrate a font right now, and the is no more doc for creating theme for v1.

You just CAN'T remove a whole documentation for your API like that.
You can add the depecation but you can't remove it. There is some people that will still need to see this docs.

In case someone also search for this doc. Here it is.
https://github.com/pedronauck/docz-website/blob/af65df11c83333c17d3176557522c8e6efdb3a1b/src/docs/documentation/references/creating-themes.mdx

**Comment by zicodeng** [comment]
I agree with you. I am also surprised how fast it went from v1 to v2...

**Comment by thunderBiscuit** [comment]
Yes please keep the v1 docs alive somewhere! The project I am working on is also looking for them.

**Comment by rakannimer** [comment]
I deployed the v1.2 docs to : https://docz-v1.surge.sh/

Hope that helps !

**Comment by Okazari** [comment]
Many thanks @rakannimer :) !

**Comment by rakannimer** [comment]
I also added a link to the docs in the readme [here](https://github.com/doczjs/docz#-v1-docs)

Closing this issue, feel free to open a new issue if something is missing !

**Comment by Okazari** [comment]
Perfect ! Thanks :)
