### ISSUE TITLE
Clicking menu items doesn't scroll screen back to top anymore, after v1.2.0 update

### ISSUE THREAD

**Issue by larimaza** [doczjs/docz#988]
## Bug Report

**Describe the bug**

If you're on a Docz page and scroll down, then click a menu item, the new loaded screen doesn't scroll to top; it instead loads in the same position you were at in the previous page.

**To Reproduce**

1. Go to https://astro.magnetis.com.br/
2. Scroll to the bottom of the screen
3. Click any menu item
4. See that the page loads in the same bottom position.

**Expected behavior**

Before updating the Docz version, newly opened screens always loaded on top position.

**Environment**

* Docz and Docz theme version: 1.2.0
* Last version before updating and finding this bug: 0.13.7 (yep, it was outdated)

**Comment by corysimmons** [comment]
Why was this closed?
