### ISSUE TITLE
(child.type === MyComponent) returning false 

### ISSUE THREAD

**Issue by CarlosOlave** [doczjs/docz#995]
## Question

I have a component that takes a child and does some logic if the child if of a certain type. This is working fine in my non-docz environment. However, when I run docz DEV my child component never renders.

**Description**

```
{React.Children.map(children, (child) => {
  if (React.isValidElement(child)) {
    if (child.type === MyComponent) {
      return React.cloneElement(child, {
        someProp,
      })
    }
  }
})}
```
From looking at console dev tools the line ```Child.type === MyComponent``` is returning false.

**Comment by jesperorb** [comment]
What does `child.type` return? If you log it or set a breakpoiint what is the property `type` in a _docz_environment?
