### ISSUE TITLE
How to locate`.docz` and `.doczrc.js` in a subdirectory?

### ISSUE THREAD

**Issue by Reklino** [doczjs/docz#996]
## Question

**Description**
I'd like to isolate the `docz` config in a directory other than the root directory with my `package.json`. See comparison below:

Works properly:
Run in `root` folder: `npm run docz:dev`

```
+-- doczrc.js
+-- package.json
+-- node_modules
+-- .docz
+-- sudir
|   +-- test.mdx
```

Fails miserably 😅:
Run inside of `subdir`: `npm run docz:dev`

```
+-- package.json
+-- node_modules
+-- sudir
|   +-- .docz
|   +-- doczrc.js
|   +-- test.mdx
```

☝️I get an error that states:
`Command "dev" not found.`

Has anyone found a way around this?

**Comment by jesperorb** [comment]
You should be able to specify where and how the `doczrc.js` is located, [**source**](https://www.docz.site/docs/project-configuration#config) (`yarn dev --config="whatever"`)

But I just tried it and couldn't get it to read my config when located in subdirectory. Regarding moving the actual `.docz`-folder, I don't think `docz` has support for it but I am unsure.

**Comment by rakannimer** [comment]
As @jesperorb said, you can do that by specifying the `config` flag (fixed). 

Here's a working example : https://github.com/doczjs/docz/tree/master/examples/custom-config-location

Please feel free to re-open if you encounter a problem 👍
