### ISSUE TITLE
Allow importing `<Playground>`

### ISSUE THREAD

**Issue by cdfa** [doczjs/docz#998]
## Bug Report

**Describe the bug**

Not completely sure if this should be a bug report or feature request, but I'd like to keep my `<Playground>` components in separate JSX files, because they're quite big and clutter the MDX files, but the rendered Playground is empty.

**To Reproduce**
1. Create a `.jsx` file:
```
import { Playground } from "docz";

export default () => (
  <Playground>
    Test
  </Playground>
)
```
2. Import the file from a `.mdx` file
```
import Usage from "Usage.jsx";

<Usage/>
```
3. Visit the corresponding page

**Expected behaviour**
A Playground with `Test` is rendered

**Actual behaviour**
An empty Playground is rendered.

**Environment**

* OS: `4.19.62-1-MANJARO GNU/Linux`
* Node/npm version: Node 10/~npm~[pnpm](https://pnpm.js.org/) 3.6.4]

**Comment by rakannimer** [comment]
I've looked into this and I'm not sure that it can be done. 

The code "inside" Playground is being parsed from the `mdx` file using `rehype-docz` and passed to the Playground component as a `__code` prop. 

When this code resides outside the mdx file ( like in a separate js file ) we have no way of finding and injecting it into the Playground with the right scope.

For this reason, I'm going to close this issue. If someone reads this and can think of a way to do this please comment here and I'd be happy to re-open.

PS: @S2geohem component shadowing for Playground was broken indeed and has been fixed, please update your docz version and it should work as expected 👍
